-- DESENV-9317
UPDATE tb_acesso_recurso
SET PAP_CODIGO='1', FUN_CODIGO='307', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='iniciar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO='151', ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO = '13141';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='7', FUN_CODIGO='307', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='iniciar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO='151', ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13142';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='1', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='excluir', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='S', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13145';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='7', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='excluir', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='S', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13146';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='1', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='editar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='S', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13143';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='7', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='editar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='S', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13144';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='1', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='salvar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13897';

UPDATE tb_acesso_recurso
SET PAP_CODIGO='7', FUN_CODIGO='308', ACR_RECURSO='/v3/motivoReclamacao', ACR_PARAMETRO='acao', ACR_OPERACAO='salvar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2'
WHERE ACR_CODIGO='13898';