-- DESENV-13496
INSERT INTO tb_natureza_servico (NSE_CODIGO, NSE_DESCRICAO, NSE_TRANSFERIR_ADE, NSE_IMAGEM, NSE_ORDEM_BENEFICIO, NSE_CODIGO_PAI)
SELECT '13', old.NSE_DESCRICAO, old.NSE_TRANSFERIR_ADE, old.NSE_IMAGEM, old.NSE_ORDEM_BENEFICIO, old.NSE_CODIGO_PAI 
FROM tb_natureza_servico old 
WHERE NSE_CODIGO = 'SP2';

UPDATE tb_param_nse_registro_ser SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';
UPDATE tb_natureza_editavel_nse SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';
UPDATE tb_tipo_lancamento SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';
UPDATE tb_provedor_beneficio SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';
UPDATE tb_beneficio SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';
UPDATE tb_servico SET NSE_CODIGO = '13' WHERE NSE_CODIGO = 'SP2';

DELETE FROM tb_natureza_servico WHERE NSE_CODIGO = 'SP2';
