-- DESENV-15805
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16319', '1', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');
