package com.zetra.econsig.values;

/**
 * <p>Title: ItemMenuEnum</p>
 * <p>Description: Enumeração para itens do menu.</p>
 * <p>Copyright: Copyright (c) 2012</p>
 * <p>Company: ZetraSoft</p>
 * $Author$
 * $Revision$
 * $Date$
 */
public enum ItemMenuEnum {

    SIMULAR_CONSIGNACAO(1, 1, "Simular Consignação"),
    LISTAR_SOLICITACAO(2, 1, "Listar Solicitação"),
    CONSULTAR_MARGEM(3, 1, "Consultar Margem"),
    EXTRATO_DE_DIVIDA_DO_SERVIDOR(4, 1, "Extrato de dívida do Servidor"),
    EXTRATO_CONSOLIDADO_DE_CONSIGNACAO(5, 1, "Extrato Consolidado de Consignação"),
    RESERVAR_MARGEM(6, 1, "Reservar Margem"),
    AUTORIZAR_RESERVA(7, 1, "Autorizar Reserva"),
    CONFIRMAR_RESERVA(8, 1, "Confirmar Reserva"),
    CANCELAR_RESERVA(9, 1, "Cancelar Reserva"),
    CONSULTAR_CONSIGNACAO(10, 1, "Consultar Consignação"),
    DEFERIR_CONSIGNACAO(11, 1, "Deferir Consignação"),
    INDEFERIR_CONSIGNACAO(12, 1, "Indeferir Consignação"),
    CANCELAR_CONSIGNACAO(13, 1, "Cancelar Consignação"),
    SUSPENDER_CONSIGNACAO(14, 1, "Suspender Consignação"),
    REATIVAR_CONSIGNACAO(15, 1, "Reativar Consignação"),
    TRANSFERIR_CONSIGNACAO(16, 1, "Transferir Consignação"),
    ALONGAR_CONTRATO(17, 1, "Alongar Contrato"),
    ALTERAR_CONTRATO(18, 1, "Alterar Contrato"),
    LIBERAR_ESTOQUE(19, 1, "Liberar Estoque"),
    LIQUIDAR_CONTRATO(20, 1, "Liquidar Contrato"),
    LISTAR_SOLICITACAO_DE_SALDO_DEVEDOR(21, 1, "Listar Solicitação de Saldo Devedor"),
    RENEGOCIAR_CONTRATOS(22, 1, "Renegociar Contratos"),
    REAJUSTE_DE_CONTRATOS(23, 1, "Reajuste de Contratos"),
    REGISTRAR_OCORRENCIA_DE_CONSIGNACAO(24, 1, "Registrar Ocorrência de Consignação"),
    DUPLICAR_PARCELA(25, 1, "Duplicar Parcela"),
    LIQUIDAR_PARCELA(26, 1, "Liquidar Parcela"),
    RENEGOCIAR_CONTRATOS_DE_TERCEIROS(27, 1, "Renegociar Contratos de Terceiros"),
    ACOMPANHAR_COMPRA_CONTRATOS(28, 1, "Acompanhar Compra Contratos"),
    CANCELAR_COMPRA_CONTRATO(29, 1, "Cancelar Compra Contrato"),
    CONFIRMAR_LIQUIDACAO_DE_COMPRA(30, 1, "Confirmar Liquidação de Compra"),
    RETIRAR_CONTRATO_DA_COMPRA(31, 1, "Retirar Contrato da Compra"),
    INTEGRACAO_FOLHA(32, 1, "Integração Folha"),
    UPLOAD_ARQUIVOS(33, 1, "Upload arquivos"),
    IMPORTAR_BLOQUEIO_SERVIDOR(34, 1, "Importar Bloqueio Servidor"),
    IMPORTAR_CADASTRO_MARGENS(35, 1, "Importar Cadastro Margens"),
    EXPORTAR_MOVIMENTO_FINANCEIRO(36, 1, "Exportar Movimento Financeiro"),
    IMPORTAR_RETORNO_INTEGRACAO(37, 1, "Importar Retorno Integração"),
    IMPORTAR_RETORNO_ATRASADO(38, 1, "Importar Retorno Atrasado"),
    DESFAZER_ULTIMO_RETORNO(39, 1, "Desfazer Último Retorno"),
    CADASTRAR_RETORNO_INTEGRACAO(40, 1, "Cadastrar Retorno Integração"),
    DOWNLOAD_ARQUIVOS_INTEGRACAO(41, 1, "Download Arquivos Integração"),
    PROCESSAR_LOTE(42, 1, "Processar Lote"),
    RELATORIO_CONFERENCIA_CADASTRO(44, 2, "Conferência Cadastro"),
    RELATORIO_CONSIGNATARIAS(45, 2, "Consignatárias"),
    RELATORIO_CORRESPONDENTES(46, 2, "Correspondentes"),
    RELATORIO_MARGENS(47, 2, "Margens"),
    RELATORIO_ORGAOS(48, 2, "Órgãos"),
    RELATORIO_VERBAS(49, 2, "Verbas"),
    RELATORIO_EMPRESAS_CORRESPONDENTES(50, 2, "Empresas Correspondentes"),
    RELATORIO_USUARIOS(51, 2, "Usuários"),
    RELATORIO_ACOMPANHAMENTO_COMPRA_DE_CONTRATO(52, 2, "Acompanhamento Compra de Contrato"),
    RELATORIO_ALTERACAO_VALOR_NO_RETORNO(53, 2, "Alteração Valor no Retorno"),
    RELATORIO_AUDITORIA(54, 2, "Auditoria"),
    RELATORIO_AUMENTO_DE_VALOR_ACIMA_DO_LIMITE(55, 2, "Aumento de Valor Acima do Limite"),
    RELATORIO_BLOQUEIO_DE_SERVIDORES(56, 2, "Bloqueio de Servidores"),
    RELATORIO_COMPROMETIMENTO_DE_MARGEM(57, 2, "Comprometimento de Margem"),
    RELATORIO_CONSIGNACOES(58, 2, "Consignações"),
    RELATORIO_ESTATISTICO(59, 2, "Estatístico"),
    RELATORIO_ESTATISTICO_RETORNO(60, 2, "Estatístico Retorno"),
    RELATORIO_GERENCIAL_GERAL(61, 2, "Gerencial Geral"),
    RELATORIO_GERENCIAL_PERCENTUAL_CARTEIRA(62, 2, "Gerencial Percentual Carteira"),
    RELATORIO_INTEGRACAO(63, 2, "Integração"),
    RELATORIO_INFORMACAO_BANCARIA_DIVERGENTE(64, 2, "Informação Bancária Divergente"),
    RELATORIO_LIMITE_DE_CONTRATO_POR_ENTIDADE(65, 2, "Limite de Contrato por Entidade"),
    RELATORIO_LIMITE_DE_CONTRATO_POR_GRUPO_DE_SERVICO(66, 2, "Limite de Contrato por Grupo de Serviço"),
    RELATORIO_MOVIMENTO_FINANCEIRO(67, 2, "Movimento Financeiro"),
    RELATORIO_MOVIMENTO_FINANCEIRO_SERVIDOR(282, 2, "Movimento Financeiro do Servidor"),
    RELATORIO_RANKING_DE_TAXA_DE_JUROS(68, 2, "Ranking de Taxa de Juros"),
    RELATORIO_OCORRENCIA_DE_CONSIGNACAO(69, 2, "Ocorrência de Consignação"),
    RELATORIO_OCORRENCIA_DE_CONSIGNATARIA(70, 2, "Ocorrência de Consignatária"),
    RELATORIO_OCORRENCIA_DE_USUARIO_SERVIDOR(71, 2, "Ocorrência de Usuário Servidor"),
    RELATORIO_OCORRENCIA_DE_USUARIO(72, 2, "Ocorrência de Usuário"),
    RELATORIO_PERCENTUAL_REJEITO(73, 2, "Percentual Rejeito"),
    RELATORIO_REPASSE(74, 2, "Repasse"),
    RELATORIO_SINTETICO_DE_CONSIGNACOES(75, 2, "Sintético de Consignações"),
    RELATORIO_SINTETICO_DE_MOVIMENTO_FINANCEIRO(76, 2, "Sintético de Movimento Financeiro"),
    RELATORIO_TARIFACAO(77, 2, "Tarifação"),
    RELATORIO_TAXAS_EFETIVAS(78, 2, "Taxas Efetivas"),
    RELATORIO_PROVISIONAMENTO_DE_MARGEM(79, 2, "Provisionamento de Margem"),
    CONSIGNANTE(80, 3, "Consignante"),
    ESTABELECIMENTOS(81, 3, "Estabelecimentos"),
    ORGAOS(82, 3, "Órgãos"),
    ORGAO(83, 3, "Órgão"),
    SERVIDORES(85, 3, "Servidores"),
    GRUPO_DE_CONSIGNATARIAS(86, 3, "Grupo de Consignatárias"),
    CONSIGNATARIAS(87, 3, "Consignatárias"),
    CONSIGNATARIA(88, 3, "Consignatária"),
    CORRESPONDENTES(89, 3, "Correspondentes"),
    CORRESPONDENTE(90, 3, "Correspondente"),
    GRUPO_DE_SERVICOS(91, 3, "Grupo de Serviços"),
    SERVICOS(92, 3, "Serviços"),
    EMPRESAS_CORRESPONDENTES(93, 3, "Empresas Correspondentes"),
    CALENDARIO(94, 3, "Calendário"),
    EDITAR_BANNER(95, 3, "Editar Banner"),
    COEFICIENTES_DE_CORRECAO(96, 3, "Coeficientes de Correção"),
    TIPO_DE_MOTIVO_DA_OPERACAO(97, 3, "Tipo de Motivo da Operação"),
    TIPO_DE_PENALIDADE(98, 3, "Tipo de Penalidade"),
    USUARIOS(99, 3, "Usuários"),
    USUARIOS_SERVIDORES(100, 3, "Usuários Servidores"),
    ATIVAR_SENHA_DE_SERVIDOR(101, 3, "Ativar Senha de Servidor"),
    SAIR_DO_SISTEMA(102, 4, "Sair do Sistema"),
    ALTERAR_SENHA(103, 4, "Alterar Senha"),
    AJUDA(104, 4, "Ajuda"),
    SOBRE(105, 4, "Sobre"),
    UPLOAD_GENERICO(106, 4, "Upload Genérico"),
    DOWNLOAD_GENERICO(107, 4, "Download Genérico"),
    FAQ(108, 4, "Faq"),
    EDITAR_FAQ(109, 4, "Editar Faq"),
    MENSAGENS(110, 4, "Mensagens"),
    EDITAR_MENSAGENS(111, 4, "Editar Mensagens"),
    ADMINISTRADOR(112, 4, "Administrador"),
    RECALCULA_MARGEM_PARCIAL(113, 4, "Recalcula Margem Parcial"),
    RECALCULA_MARGEM_GERAL(114, 4, "Recalcula Margem Geral"),
    TRANSFERIR_CONSIGNACAO_GERAL(115, 4, "Transferir Consignação Geral"),
    //DOWNLOAD_DE_ARQUIVOS_DE_LOG(116, 4, "Download de Arquivos de Log"),
    EDITAR_MENU(117, 4, "Editar Menu"),
    CONCILIAR_ARQUIVO(118, 1, "Conciliar Arquivo"),
    RELATORIO_INTEGRACAO_CONSIGNATARIA(119, 2, "Integração Consignatária"),
    RELATORIO_SINTETICO_ACOMPANHAMENTO_COMPRA(120, 2, "Sintético Acompanhamento de Compra"),
    RELATORIO_BUSINESS_INTELLIGENCE_BI(121, 2, "Business Intelligence (BI)"),
    COMUNICACOES(122, 4, "Comunicações"),
    LISTAR_BLOQUEIOS_DE_CONSIGNATARIA(123, 1, "Listar Bloqueios de Consignatária"),
    CANCELAR_RENEGOCIACAO(124, 1, "Cancelar Renegociação"),
    PERFIS_SUPORTE(125, 4, "Perfis Suporte"),
    USUARIOS_SUPORTE(126, 4, "Usuários Suporte"),
    RELATORIO_CONTRATO_LIQUIDADO_POS_CORTE(127, 2, "Contrato Liquidado Pós-Corte"),
    GERAR_SENHAS_DE_SERVIDORES(128, 3, "Gerar Senhas de Servidores"),
    RESTRICOES_DE_ACESSO(129, 3, "Restrições de Acesso"),
    EDITAR_RELATORIOS(130, 4, "Editar Relatórios"),
    AUDITORIA(131, 4, "Auditoria"),
    PLANOS_DE_DESCONTO(132, 3, "Planos de Desconto"),
    PERMISSIONARIO(133, 3, "Permissionário"),
    ENDERECO(134, 3, "Endereços"),
    CONSULTA_POSTO(135, 3, "Consultar Posto"),
    DESPESA_INDIVIDUAL(136, 1, "Despesa Individual"),
    CONSULTA_DESPESA_PERMISSIONARIO(137, 1, "Consulta Despesa Permissionário"),
    DESPESA_COMUM(138, 1, "Despesa Comum"),
    CONSULTA_DESPESA_COMUM(139, 1, "Consulta Despesa Comum"),
    RELATORIO_DE_DESCONTOS(140, 2, "Descontos de Prefeitura"),
    SOLICITACAO_SUPORTE(141, 4, "Solicitação ao Suporte"),
    RELATORIO_OCORRENCIA_DE_PERMISSIONARIO(142, 2, "Ocorrência de Permissionário"),
    ALTERAR_MULTIPLOS_CONTRATOS(143, 1, "Alterar Múltiplos Contratos"),
    RELATORIO_SERVICO_OPERACAO_MES(144, 2, "Serviço de Operação no Mês"),
    RELATORIO_CONFERENCIA_DE_PERMISSIONARIO(145, 2, "Ocorrência de Permissionário"),
    RELATORIO_MARKET_SHARE_CSA(146, 2, "Market Share Consignatária"),
    RELATORIO_DE_DESCONTOS_MOV_FIN(147, 2, "Descontos Efetuados e Não Efetuados"),
    RELATORIO_SINTETICO_DE_DESCONTOS(148, 2, "Sintético de Descontos"),
    ARQUIVOS_XML(149, 4, "Arquivos XML de Configuração"),
    CALENDARIO_FOLHA(150, 3, "Calendário Folha"),
    TIPO_MOTIVO_RECLAMACAO(151, 3, "Tipo Motivo de Reclamação"),
    RELATORIO_SINTETICO_RECLAMACOES(152, 2, "Sintético Reclamações"),
    RECLAMACAO(153, 4, "Reclamações"),
    RELATORIO_RECLAMACOES(154, 2, "Reclamações"),
    LISTAR_SOLICITACAO_RENEGOCIACAO(155, 1, "Listar Solicitação de Renegociação"),
    PROCESSAR_LOTE_MULTIPLO(156, 1, "Processar Lote Múltiplo"),
    ANEXAR_DOCUMENTO_ADE(157, 1, "Editar Anexo de Consignação"),
    HABILITAR_VALIDACAO_TOTP(158, 4, "Habilitar Código de Segurança"),
    RELATORIO_OCORRENCIA_DE_REGISTRO_SERVIDOR(159, 2, "Ocorrência de Registro Servidor"),
    ACOMPANHAR_FINANCIAMENTO_DIVIDA_CARTAO(160, 1, "Financiamento de Dívida de Cartão"),
    RELATORIO_INADIMPLENCIA(161, 2, "Inadimplência"),
    RELATORIO_COMUNICACOES(162, 2, "Relatório de Comunicações"),
    CANCELAR_MINHAS_RESERVAS(163, 1, "Cancelar Minhas Reservas"),
    CONFIRMAR_LIQUIDACAO(164, 1, "Confirmar Liquidação"),
    INCLUIR_CONSIGNACAO(165, 1, "Incluir Consignação"),
    IMPORTAR_ADEQUACAO_A_MARGEM(166, 1, "Importar Adequação à Margem"),
    PROCESSAR_ARQUIVO_INCONSISTENCIA(167, 1, "Processar Arquivo de Inconsistência"),
    RELATORIO_LEITURA_MENSAGENS(168, 2, "Confirmação Leitura de Mensagens"),
    ACOMPANHAR_LEILAO_DE_SOLICITACAO(169, 1, "Acompanhar Leilão de Solicitação"),
    PROCESSAR_HISTORICO(170, 1, "Processar Histórico"),
    RELATORIO_SDV_POR_CSA(171, 2, "Relatório de Saldo Devedor por Consignatária"),
    RELATORIO_INCLUSOES_POR_CSA(172, 2, "Relatório de Inclusões por Consignatária"),
    RELATORIO_PARCELAS_PAGAS_POR_CSA_PERIODO(173, 2, "Parcelas Pagas por Consignatária Período"),
    REIMPLANTAR_CAPITAL_DEVIDO(174, 1, "Reimplantar Capital Devido"),
    DESLIQUIDAR_CONTRATO(175, 1, "Desliquidar Contrato"),
    TERMO_DE_USO(176, 4, "Termo de Uso"),
    RELATORIO_SOLICITACAO_SUPORTE(177, 4, "Relatório de Solicitação de Suporte"),
    CONCILIAR_ARQUIVO_MULTIPLAS_CSA(178, 1, "Conciliar Arquivo Múltiplo"),
    RELATORIO_DESCONTOS_EXPIRAR(179, 4, "Relatório Descontos a Expirar"),
    RELATORIO_ANEXOS_CONSIGNACAO(180, 2, "Anexos de Consignação"),
    PESQUISAR_SERVIDOR(181, 1, "Pesquisar Servidor"),
    EXTRATO_DIVIDA_SERVIDOR(182, 1, "Extrato"),
    SIMULAR_RENEGOCIACAO(183, 1, "Simular renegociação"),
    CONSIGNATARIAS_SERVIDOR(184, 1, "Consignatárias"),
    DADOS_CADASTRAIS_SERVIDOR(185, 1, "Dados cadastrais"),
    BLOQUEIOS_SERVIDOR(186, 1, "Bloqueios"),
    TRANSFERIR_MARGEM(187, 1, "Transferir margem"),
    SUPORTE_ONLINE(188, 1, "Suporte online"),
    CONTRACHEQUE_SERVIDOR(189, 1, "Consultar Contracheque"),
    SOLICITAR_LEILAO_REVERSO(190, 1, "Solicitar Leilão Reverso"),
    VALIDAR_SERVIDOR(191, 1, "Validar Servidor"),
    IMP_SER_DESLIGADO_BLOQUEADO(192, 1, "Importar Servidores desligados e bloqueados"),
    LISTAR_SERVIDORES_PENDENTE_VALIDACAO(194, 1, "Listar servidores pendentes de validação"),
    DEFINIR_SENHA_APP(195, 3, "Definir Senha App"),
    RELATORIO_INCLUSAO_BENEFICIARIOS_POR_PERIODO(196, 2, "Inclusão de Beneficiários por Período"),
    RELATORIO_CONCESSAO_BENEFICIARIOS(197, 2, "Relatório de Concessão e Beneficiários"),
    RELATORIO_EXCLUSAO_BENEFICIARIO_PERIODO(198, 2, "Exclusão de Benefíciarios por Período"),
    CADASTRO_BENEFICIOS(199, 3, "Cadastro de Benefícios"),
    CALCULO_BENEFICIOS(200, 3, "Cálculo de Benefícios"),
    TEXTO_SISTEMA(201, 4, "Texto do Sistema"),
    CADASTRO_BENEFICIARIOS(202, 3, "Cadastro de Beneficiários"),
    HISTORICO_MARGEM(203, 1, "Histórico de Margem"),
    RELACAO_BENEFICIOS(204, 1, "Relação de Benefícios"),
    RELATORIO_DOCUMENTO_BENEFICIARIO_TIPO_VALIDADE(205, 2, "Documentos de Beneficiários por Tipo e Validade"),
    INTEGRAR_FOLHA(206, 1, "Integrar Folha"),
    RELATORIO_GERENCIAL_GERAL_CSA(207, 2, "Gerencial Geral de Consignatária"),
    SIMULACAO_BENEFICIOS(208, 5, "Simulação de Benefícios"),
    RELATORIO_BENEFICIARIO_DATA_NASCIMENTO(209, 2, "Beneficiário por Data Nascimento"),
    RELATORIO_CONTRATOS_BENEFICIOS(210, 2, "Contratos de Benefícios"),
    INCLUIR_BENEFICIARIO(211, 5, "Incluir Beneficiário"),
    SIMULACAO_ALTERACAO_BENEFICIOS(212, 5, "Simular Alteração Benefícios"),
    RELATORIO_MOVIMENTO_BENEFICIO_CONSOLIDADO_DIRF(213, 2, "Movimento de benefício consolidado - DIRF "),
    CONSULTAR_FATURAMENTO_BENEFICIOS(214, 3, "Faturamento de Benefícios"),
    RELATORIO_COMISSIONAMENTO_AGENCIAMENTO_ANALITICO(215, 2, "Comissionamento e Agenciamento Analítico"),
    DIRF_SERVIDOR(216, 1, "Consultar DIRF do Servidor"),
    DISTRIBUIR_CONSIGNACOES_POR_SERVICOS(217, 4, "Distribuir Consignações por Serviços"),
    RELATORIO_SINTETICO_CONSULTA_MARGEM_POR_USUARIO(218, 2, "Sintético de Consulta de Margem por Usuário"),
    UPLOAD_BOLETOS_EM_LOTE(219, 1, "Upload de Boletos em Lote"),
    CONSULTAR_BOLETO(220, 1, "Consultar Boleto"),
    BENEFICIO_SAUDE(221, 1, "Saúde"),
    RELATORIO_HISTORICO_DESCONTOS_SER(222, 2, "Histórico de Descontos do Servidor"),
    AJUDA_CONTEXTO(223, 6, "Ajuda"),
    VISUALIZAR_OCORRENCIAS(224, 6, "Visualizar Ocorrências"),
    ACESSAR_PORTAL_EUCONSIGOMAIS(225, 1, "Acessar portal euConsigoMais"),
    CONSULTAR_VARIACAO_MARGEM(226, 1, "Consultar Variação de Margem"),
    LISTAR_CONTRATOS_PENDENTES_BENEFICIO(227, 5, "Listar Contratos Pendentes"),
    POLITICA_DE_PRIVACIDADE(228, 4, "Política de Privacidade"),
    TERMO_USO_ADESAO_PRIVACIDADE(229, 2, "Termo de Uso, Adesão e Privacidade"),
    RECUPERACAO_CREDITO(230, 1, "Listar Recuperação de Crédito"),
    OPERACAO_FILA_AUTORIZACAO(231, 1, "Operações em Fila de Autorização"),
    DASHBOARD_PROCESSAMENTO(232, 1, "Dashboard Processamento Folha"),
    REATIVAR_CONTRATO_BENEFICIO(233, 5, "Reativar Contrato Benefício"),
    DECISAO_JUDICIAL(234, 1, "Decisão Judicial"),
    TERMO_DE_GARANTIA_DE_ALUGUEL(235, 1, "Termo de Garantia de Aluguel"),
    RELATORIO_RECUPERACAO_CREDITO(236, 2, "Recuperação de Crédito"),
    INFORMAR_RESCISAO(237, 7, "Informar rescisão"),
    ACESSO_BI(238, 8, "Dashboard BI"),
    CONFIRMAR_RENEGOCIACAO(239, 1, "Confirmar Renegociação"),
    RETER_VERBA_RESCISORIA(240, 7, "Reter Verba Rescisória"),
    EXPORTAR_MOVIMENTO_FINANCEIRO_COMPLEMENTAR(241, 1, "Exportar Movimento Financeiro Complementar"),
    CONSULTAR_EVENTOS_TOTEM(242, 1, "Consultar Eventos do Totem"),
    DOWNLOAD_ARQUIVOS_RESCISAO(243, 1, "Download Arquivos Rescisão"),
    CONFIGURAR_TOTEM(244, 4, "Configurar Totem"),
    EDITAR_FUNCOES(245, 4, "Editar Funções"),
    AUTORIZAR_DESCONTO_PARCIAL(246, 4, "Autorizar Desconto Parcial"),
    DOWNLOAD_ANEXOS_CONTRATO(247, 4, "Download Anexos Contrato"),
    REVER_LEILAO_NAO_CONCRETIZADO(248, 1, "Rever leilão não concretizado"),
    CANCELAR_BENEFICIO_INADIMPLENCIA(249, 5, "Cancelar benefícios por inadimplência"),
    SOLICITAR_LIQUIDACAO_CONSIGNACAO(250, 1, "Solicitar Liquidação"),
    PERFIL_SERVIDOR(251, 4, "Perfil Servidor"),
    EXTRATO_MARGEM(252, 1, "Consultar Extrato de Margem"),
    DASHBOARD_ANEXOS_CONSIGNACAO(253, 1, "Dashboard de Anexos de Consignação"),
    RELATORIO_SINTETICO_DECISAO_JUDICIAL(254, 2, "Sintético de Decisões Judiciais"),
    RELATORIO_DECISAO_JUDICIAL(255, 2, "Decisões Judiciais"),
    RELATORIO_SINTETICO_DE_OCORRENICA_CONSIGNACOES(256, 2, "Sintético de Ocorrência de Consignação"),
    DEMONSTRAR_TAXA_JUROS(257, 4, "Demonstrar Taxa de Juros"),
    RELATORIO_REGRAS_CONVENIO(258, 2, "Regras Convênio"),
    CONSULTAR_MARGEM_EXTERNA(259, 1, "Consultar Margem Externa"),
    RELATORIO_AVALIACAO_FAQ(260, 2, "Avaliação de FAQ"),
    RELATORIO_ESTATISTICO_PROCESSAMENTO(261, 2, "Estatístico do Processamento"),
    REIMPLANTAR_PARCELA_MANUAL(262, 1, "Reimplantar Parcela Manual"),
    RELATORIO_SOLICITACAO_SALDO_DEVEDOR(263, 2, "Solicitação Saldo Devedor"),
    PROCESSAR_LOTE_INF_SALDO_DEVEDOR(264, 1, "Processar Saldo Devedor"),
    AJUSTAR_CONSIGNACOES_A_MARGEM(265, 1, "Ajustar Consignações à Margem"),
    COPIA_SEGURANCA(266, 4, "Cópia de Segurança"),
    NOTIFICAR_CONSIGNACAO(267, 1, "Notificar Consignação"),
    REGISTRAR_VALOR_LIBERADO_CONSIGNACAO(268, 1, "Registrar Valor Liberado na Consignação"),
    CONFIRMAR_MARGEM_FOLHA_SERVIDOR(270, 3, "Confirmar margem folha do servidor"),
    RELATORIO_GERENCIAL_GERAL_INTERNACIONAL(271, 2, "Gerencial Geral"),
    VALIDAR_DOCUMENTOS_APROVACAO_CSE(272, 1, "Validação de Documentação"),
    DASHBOARD_CREDENCIAMENTO_CSA(273, 1, "Dashboard de Credenciamento"),
    SOLICITAR_PORTABILIDADE(274, 1, "Solicitar Portabilidade"),
    RELATORIO_CUSTOMIZACOES(275, 2, "Customizações"),
    PROCESSAR_LOTE_RECISAO(276, 1, "Processar Lote Rescisão"),
    DOWNLOAD_ARQUIVO_HISTORICO(277, 4, "Download Cópia de Segurança"),
    REIMPLANTAR_CONSIGNACAO_LOTE(280, 1, "Reimplantar Consignação em Lote"),
    MOVIMENTO_FINANCEIRO_SERVIDOR(282, 2, "Movimento financeiro servidor"),
    RELATORIO_PARCELAS_PROCESSADAS_FUTURAS(283, 2, "Parcelas Processadas e Futuras"),
    LISTAR_USUARIOS_AUTENTICADOS(284, 4, "Listar Usuários Autenticados"),
    RELATORIO_SALDO_DEVEDOR_SERVIDOR(285, 2, "Saldo Devedor do Servidor"),
    RELATORIO_SINTETICO_GERENCIAL_GERAL_CSA(286, 2, "Sintético Gerencial Geral de Consignatária"),
    AUTORIZAR_MARGEM_CONSIGNATARIA(287, 4, "Autorizar Margem para Consignatária"),
    RELATORIO_SINTETICO_AUTORIZACAO_MARGEM_SER(288, 2, "Relatório Sintético De Autorização de Margem pelo Servidor"),
    REGRA_LIMITE_DE_OPERACAO(289, 1, "Regra Limite de Operação"),
    ANALISAR_VARIACAO_MARGEM(290, 1, "Consultar Variação de Margem"),
    TERMO_DE_ADESAO(291, 4, "Termo de Adesão"),
    INTEGRAR_CREDITO_TRABALHADOR(292, 1, "Integrar Crédito Trabalhador"),
    RELATORIO_SERVIDOR_SALDO_DEVEDOR(293, 2, "Relatório Servidor Saldo Devedor"),
    EDITAR_FORMULARIO_PESQUISA(294, 3, "Formulário de Pesquisa"),
    DASHBOARD_PESQUISA_SATISFACAO(295, 8, "Pesquisa de Satisfação");

    private final int codigo;
    private final int menu;
    private final String descricao;

    private ItemMenuEnum(int codigo, int menu, String descricao) {
        this.codigo = codigo;
        this.menu = menu;
        this.descricao = descricao;
    }

    public int getCodigo() {
        return codigo;
    }

    public int getMenu() {
        return menu;
    }

    public String getDescricao() {
        return descricao;
    }
}
