-- DESENV-17446
INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_CSA_ALTERA, TPS_SUP_ALTERA, TPS_PODE_SOBREPOR_RSE)
VALUES ('315', 'Ocultar serviço no menu do servidor', 'N', 'N', 'N', NULL);

