-- DESENV-21064
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/reinicializarSenhaServidor' WHERE ACR_RECURSO = '/v3/reinicializarSenhaUsuario';
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/recuperarSenhaUsuario' WHERE ACR_RECURSO = '/v3/recuperarSenha';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16993', NULL, NULL, '/v3/autoDesbloquearUsuario', NULL, NULL, '1', 'S', 'N', NULL, 'N', 0);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16994', NULL, NULL, '/v3/recuperarSenhaServidor', NULL, NULL, '1', 'S', 'N', NULL, 'N', 0);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16995', NULL, NULL, '/v3/autoDesbloquearServidor', NULL, NULL, '1', 'S', 'N', NULL, 'N', 0);

