-- DESENV-9289

UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/cancelarCompra', ACR_PARAMETRO = 'acao' WHERE ACR_CODIGO IN ('11339','11340','11341','11342','11862','12380');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15311', '1', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15312', '2', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15313', '3', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15314', '4', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15315', '6', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15316', '7', '155', '/v3/cancelarCompra', 'acao', 'efetivarAcao', '1', 'S', 'S', NULL, 'N', '2');

DELETE FROM tb_ajuda WHERE ACR_CODIGO IN ('11335', '11336', '11337', '11338', '12379', '12853');
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO IN ('11335', '11336', '11337', '11338', '12379', '12853');
DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO IN ('11335', '11336', '11337', '11338', '12379', '12853');
