-- DESENV-17631
UPDATE tb_relatorio_filtro SET RFI_SEQUENCIA = RFI_SEQUENCIA + 1 WHERE REL_CODIGO = 'sintetico' AND RFI_SEQUENCIA >= 7;

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_CSE, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_ORG, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_EXIBE_SUP)
VALUES ('sintetico', 'campo_natureza_svc', '1', '0', '0', '0', '0', 7, '1');
