-- DESENV-9316
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/listarSolicitacaoSuporte',  ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciar'   WHERE ACR_CODIGO IN ('13016','13017','13018','13019','13020','13021');
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/listarSolicitacaoSuporte',  ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'consultar' WHERE ACR_CODIGO IN ('13022','13023','13024','13025','13026','13027');
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/inserirSolicitacaoSuporte', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciar'   WHERE ACR_CODIGO IN ('13028','13029','13030','13031','13032','13033');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15249', '1', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15250', '2', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15251', '3', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15252', '4', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15253', '6', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15254', '7', '287', '/v3/inserirSolicitacaoSuporte', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2'); 
