-- DESENV-9318
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/motivoOperacao', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciar' WHERE ACR_CODIGO IN ('10165', '11996');
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/motivoOperacao', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'editar'  WHERE ACR_CODIGO IN ('10160', '11994');
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/motivoOperacao', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'salvar'  WHERE ACR_CODIGO IN ('12905', '12906');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15255', '1', '135', '/v3/motivoOperacao', 'acao', 'excluir', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15256', '7', '135', '/v3/motivoOperacao', 'acao', 'excluir', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15257', '1', '135', '/v3/motivoOperacao', 'acao', 'alterarStatus', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15258', '7', '135', '/v3/motivoOperacao', 'acao', 'alterarStatus', 1, 'S', 'S', NULL, 'S', '2'); 

DELETE FROM tb_ajuda WHERE ACR_CODIGO IN ('10163', '11995');
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO IN ('10163', '11995');
DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO IN ('10163', '11995');
