-- DESENV-18104
INSERT INTO tb_tipo_param_sist_consignante (TPC_CODIGO, TPC_DESCRICAO, TPC_DOMINIO, TPC_VLR_DEFAULT, TPC_CSE_ALTERA, TPC_CSE_CONSULTA, TPC_SUP_ALTERA, TPC_SUP_CONSULTA, GPS_CODIGO)
VALUES ('880', 'Contratos devem ser validados pela CSE para serem exportados no movimento', 'SN', 'N', 'N', 'N', 'N', 'N', NULL);

INSERT INTO tb_param_sist_consignante (TPC_CODIGO, CSE_CODIGO, PSI_VLR)
VALUES ('880', '1', 'N');

INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD) VALUES ('57','Arquivo Anexo Autorização RG Frente','0','S','S','S','S','S','N');
INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD) VALUES ('58','Arquivo Anexo Autorização RG Verso','0','S','S','S','S','S','N');
INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD) VALUES ('59','Arquivo Anexo Autorização Mandado de Pagamento','0','S','S','S','S','S','N');
INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD) VALUES ('60','Arquivo Anexo Autorização Contracheque','0','S','S','S','S','S','N');
INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD) VALUES ('61','Arquivo Anexo Autorização Outro','0','S','S','S','S','S','N');

INSERT INTO tb_status_solicitacao (SSO_CODIGO,SSO_DESCRICAO) VALUES ('10','Validação de documentos aprovada');
INSERT INTO tb_status_solicitacao (SSO_CODIGO,SSO_DESCRICAO) VALUES ('11','Validação de documentos reprovada');
INSERT INTO tb_status_solicitacao (SSO_CODIGO,SSO_DESCRICAO) VALUES ('12','Aguardando documentação');

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR) 
VALUES ('527', '1', 'Validar Documentos', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N');

INSERT INTO tb_origem_solicitacao (OSO_CODIGO, OSO_DESCRICAO) VALUES ('1','Inclusão');
INSERT INTO tb_origem_solicitacao (OSO_CODIGO, OSO_DESCRICAO) VALUES ('2','Alteração para Maior');
INSERT INTO tb_origem_solicitacao (OSO_CODIGO, OSO_DESCRICAO) VALUES ('3','Renegociação');
INSERT INTO tb_origem_solicitacao (OSO_CODIGO, OSO_DESCRICAO) VALUES ('4','Portabilidade');
INSERT INTO tb_origem_solicitacao (OSO_CODIGO, OSO_DESCRICAO) VALUES ('5','Reimplante');

INSERT INTO tb_tipo_solicitacao (TIS_CODIGO,TIS_DESCRICAO) VALUES ('8','Solicitação de consignação que depende de aprovação');

INSERT INTO tb_tipo_motivo_nao_exportacao (MNE_CODIGO,MNE_DESCRICAO) VALUES ('7','Sem autorização do gestor');

INSERT INTO tb_item_menu (ITM_CODIGO,MNU_CODIGO,TEX_CHAVE,ITM_CODIGO_PAI,ITM_DESCRICAO,ITM_ATIVO,ITM_SEQUENCIA,ITM_SEPARADOR,ITM_CENTRALIZADOR,ITM_IMAGEM) VALUES ('272','1',NULL,NULL,'Validação de Documentos','1','99','N','S',NULL);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16588', '1', '527', '/v3/validarDocumentos', 'acao', 'iniciar', 1, 'S', 'S', '272', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16589', '2', '527', '/v3/validarDocumentos', 'acao', 'iniciar', 1, 'S', 'S', '272', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16590', '4', '527', '/v3/validarDocumentos', 'acao', 'iniciar', 1, 'S', 'S', '272', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16591', '7', '527', '/v3/validarDocumentos', 'acao', 'iniciar', 1, 'S', 'S', '272', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16592', '1', '527', '/v3/validarDocumentos', 'acao', 'aprovarReprovar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16593', '2', '527', '/v3/validarDocumentos', 'acao', 'aprovarReprovar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16594', '4', '527', '/v3/validarDocumentos', 'acao', 'aprovarReprovar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16595', '7', '527', '/v3/validarDocumentos', 'acao', 'aprovarReprovar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16596', '1', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16597', '2', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16598', '3', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16599', '4', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16600', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16601', '7', '200', '/v3/editarAnexosConsignacao', 'acao', 'uploadValidarDocumentos', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16602', '1', '527', '/v3/downloadAnexoValidarDocumentos', 'tipo', 'anexo', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16603', '2', '527', '/v3/downloadAnexoValidarDocumentos', 'tipo', 'anexo', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16604', '7', '527', '/v3/downloadAnexoValidarDocumentos', 'tipo', 'anexo', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16605', '4', '527', '/v3/downloadAnexoValidarDocumentos', 'tipo', 'anexo', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16606', NULL, NULL, '/v3/carregarStream', NULL, NULL, 1, 'S', 'S', NULL, 'N', '0');

INSERT INTO tb_campo_sistema (CAS_CHAVE,CAS_VALOR) VALUES ('detalheConsignacao_statusSolicitacao','S');