ALTER TABLE tb_termo_adesao 
MODIFY COLUMN TAD_ENVIA_API_CONSENTIMENTO VARCHAR(40);
 
ALTER TABLE tb_leitura_termo_usuario 
ADD LTU_VERSAO_TERMO INT;
 
ALTER TABLE tb_termo_adesao 
ADD TAD_VERSAO_TERMO INT;