-- DESENV-10999
INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_CSA_ALTERA, TPS_SUP_ALTERA)
VALUES ('273', 'E-mail de notificação de solicitação de consignação incluída ou cancelada pelo servidor', 'N', 'N', 'N');

INSERT INTO tb_tipo_notificacao (TNO_CODIGO, TNO_DESCRICAO, TNO_ENVIO) 
VALUES ('11', 'E-mail de notificação à CSA de nova solicitação feita por servidor', 'I');

INSERT INTO tb_tipo_notificacao (TNO_CODIGO, TNO_DESCRICAO, TNO_ENVIO) 
VALUES ('12', 'E-mail de notificação à CSA de solicitação cancelada pelo servidor', 'I');

INSERT INTO tb_modelo_email (MEM_CODIGO, MEM_TITULO, MEM_TEXTO) 
VALUES ('emailNovaSolicitacaoFeitaPeloSer', '<@nome_sistema> - <@nome_consignante>: Nova Solicitação', concat('O servidor <@ser_nome> fez uma solicitação de empréstimo e aguar retorno desta instituição financeira:<br><br><table style="border: 1px solid black', 0x3b, ' border-collapse: collapse', 0x3b, '"><tbody><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Órgão</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@org_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Matrícula:</td><td style="border: 1px solid black', 0x3b, '"><@rse_matricula></td><td style="border: 1px solid black', 0x3b, '">CPF:</td><td style="border: 1px solid black', 0x3b, '"><@ser_cpf></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Nome:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ser_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Margem antes:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@rse_margem></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Margem depois:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@rse_margem_rest></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Valor Simulado: </td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@ade_vlr_liquido></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Valor Parcela:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@ade_vlr></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Prazo:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ade_prazo></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Consignatária:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@csa_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Taxa:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@cft_vlr>%</td><tr style="border: 1px solid black', 0x3b, '"><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">E-mail:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ser_email></td></tr></tbody></table><br><br>Sistema <@nome_consignante>'));

INSERT INTO tb_modelo_email (MEM_CODIGO, MEM_TITULO, MEM_TEXTO) 
VALUES ('soliciCanceladaPorSerSemMargem', '<@nome_sistema> - <@nome_consignante>: Solicitação Cancelada', concat('O servidor <@ser_nome> cancelou a seguinte solicitação de empréstimo feita nesta instituição financeira:<br><br><table style="border: 1px solid black', 0x3b, ' border-collapse: collapse', 0x3b, '"><tbody><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Órgão</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@org_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Matrícula:</td><td style="border: 1px solid black', 0x3b, '"><@rse_matricula></td><td style="border: 1px solid black', 0x3b, '">CPF:</td><td style="border: 1px solid black', 0x3b, '"><@ser_cpf></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Nome:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ser_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Margem antes:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@rse_margem></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Margem depois:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@rse_margem_rest></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Valor Simulado: </td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@ade_vlr_liquido></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Valor Parcela:</td><td colspan="3" style="border: 1px solid black', 0x3b, '">R$ <@ade_vlr></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Prazo:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ade_prazo></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Consignatária:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@csa_nome></td></tr><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">Taxa:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@cft_vlr>%</td><tr style="border: 1px solid black', 0x3b, '"><tr style="border: 1px solid black', 0x3b, '"><td style="border: 1px solid black', 0x3b, '">E-mail:</td><td colspan="3" style="border: 1px solid black', 0x3b, '"><@ser_email></td></tr></tbody></table><br><br>Sistema <@nome_consignante>'));
