-- DESENV-22545
INSERT INTO tb_bloqueio_repasse_funcao (PAP_CODIGO_ORIGEM, PAP_CODIGO_DESTINO, FUN_CODIGO) VALUES ('2', '2', '240');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES('17034', '2', '240', '/v3/manterTaxas', 'acao', 'ativar', 1, 'S', 'S', NULL, 'N', '2');

