-- DESENV-22449
-- ORACLE
MERGE INTO tb_tipo_registro_servidor tgt
USING (SELECT '0' AS TRS_CODIGO, 'PADRÃO' AS TRS_DESCRICAO FROM dual) src ON (tgt.TRS_CODIGO = src.TRS_CODIGO)
WHEN NOT MATCHED THEN INSERT (TRS_CODIGO, TRS_DESCRICAO) VALUES (src.TRS_CODIGO, src.TRS_DESCRICAO);

MERGE INTO tb_tipo_registro_servidor tgt
USING (SELECT '1' AS TRS_CODIGO, 'EXTERIOR' AS TRS_DESCRICAO FROM dual) src ON (tgt.TRS_CODIGO = src.TRS_CODIGO)
WHEN NOT MATCHED THEN INSERT (TRS_CODIGO, TRS_DESCRICAO) VALUES (src.TRS_CODIGO, src.TRS_DESCRICAO);

MERGE INTO tb_tipo_registro_servidor tgt 
USING (SELECT '2' AS TRS_CODIGO, 'TEMPORÁRIO' AS TRS_DESCRICAO FROM dual) src ON (tgt.TRS_CODIGO = src.TRS_CODIGO)
WHEN NOT MATCHED THEN INSERT (TRS_CODIGO, TRS_DESCRICAO) VALUES (src.TRS_CODIGO, src.TRS_DESCRICAO);

MERGE INTO tb_tipo_registro_servidor tgt
USING (SELECT '3' AS TRS_CODIGO, 'PENSIONISTA' AS TRS_DESCRICAO FROM dual) src ON (tgt.TRS_CODIGO = src.TRS_CODIGO)
WHEN NOT MATCHED THEN INSERT (TRS_CODIGO, TRS_DESCRICAO) VALUES (src.TRS_CODIGO, src.TRS_DESCRICAO);

INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_SUP_ALTERA, TPS_CSA_ALTERA)
VALUES ('330', 'Prazo é limitado para os servidores temporários', 'N', 'N', 'N');

