-- DESENV-8175
UPDATE tb_tipo_entidade SET ten_campo_ent_09 = 'SER_CODIGO' WHERE ten_codigo = '19';

UPDATE tb_tipo_entidade SET TEN_CAMPO_ENT_00 = 'USU_CODIGO' WHERE ten_codigo = '60';

INSERT INTO tb_tipo_entidade (TEN_CODIGO, TEN_DESCRICAO, TEN_AUDITORIA, TEN_TITULO, TEN_CAMPO_ENT_00, TEN_CAMPO_ENT_01, TEN_CAMPO_ENT_02, TEN_CAMPO_ENT_03, TEN_CAMPO_ENT_04, TEN_CAMPO_ENT_05, TEN_CAMPO_ENT_06, TEN_CAMPO_ENT_07, TEN_CAMPO_ENT_08, TEN_CAMPO_ENT_09, TEN_CAMPO_ENT_10)
VALUES ('99', 'Notificação Dispositivo', NULL, NULL, 'NDI_CODIGO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
