-- DESENV-9669
INSERT INTO tb_funcao (FUN_CODIGO,GRF_CODIGO,FUN_DESCRICAO,FUN_PERMITE_BLOQUEIO,FUN_EXIGE_TMO,FUN_EXIGE_SEGUNDA_SENHA_CSE,FUN_AUDITAVEL,FUN_RESTRITA_NCA,FUN_EXIGE_SEGUNDA_SENHA_SUP,FUN_EXIGE_SEGUNDA_SENHA_ORG,FUN_EXIGE_SEGUNDA_SENHA_CSA,FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('431','4','Relatório Beneficiário por Data Nascimento','N','N','N','S','N','N','N','N','N');

-- INSERT INTO TB_PAPEL_FUNCAO (PAP_CODIGO, FUN_CODIGO)
-- VALUES ('7', '431');

INSERT INTO tb_relatorio (REL_CODIGO,FUN_CODIGO,TAG_CODIGO,REL_TITULO,REL_ATIVO,REL_AGENDADO,REL_CLASSE_RELATORIO,REL_CLASSE_PROCESSO,REL_CLASSE_AGENDAMENTO,REL_TEMPLATE_JASPER,REL_TEMPLATE_DINAMICO,REL_TEMPLATE_SUBRELATORIO,REL_TEMPLATE_SQL,REL_QTD_DIAS_LIMPEZA,REL_CUSTOMIZADO,REL_AGRUPAMENTO)
VALUES ('beneficiario_dt_nasc','431','3','Relatório Beneficiário por Data Nascimento',1,'N','com.zetra.report.reports.RelatorioBeneficiarioDataNascimento','com.zetra.processamento.ProcessaRelatorioBeneficiarioDataNascimento',null,'BeneficiarioDataNascimento.jasper',null,null,null,30,'N',null);

INSERT INTO tb_item_menu (ITM_CODIGO,MNU_CODIGO,ITM_CODIGO_PAI,ITM_DESCRICAO,ITM_ATIVO,ITM_SEQUENCIA,ITM_SEPARADOR)
VALUES ('209','2',null,'Beneficiário por Data Nascimento',1,80,'N');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14961', '7','431','/v3/listarRelatorio','tipo','beneficiario_dt_nasc',1,'S','S','209','N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14962', '7','431','/v3/excluirArquivo','subtipo','beneficiario_dt_nasc',1,'S','S',null,'N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14963', '7','431','/v3/downloadArquivo','subtipo','beneficiario_dt_nasc',1,'S','S',null,'N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14964', '7','431','/v3/executarRelatorio','tipoRelatorio','beneficiario_dt_nasc',1,'S','S',null,'S','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14965', '7','431','/v3/agendarRelatorio','tipo','beneficiario_dt_nasc',1,'S','S',null,'S','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14966', '7','431','/v3/cancelarAgendamentoRelatorio','tipo','beneficiario_dt_nasc',1,'S','S',null,'N','2');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_data_inicio_fim','0','0','0','0','0',1,90,'2');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_matricula','0','0','0','0','0',2,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_cpf','0','0','0','0','0',3,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_nome','0','0','0','0','0',4,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_natureza_svc','0','0','0','0','0',5,'EBENEFICIOS','1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_beneficio','0','0','0','0','0',6,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_csa_natureza_beneficio','0','0','0','0','0',7,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_status_contrato_beneficio','0','0','0','0','0',8,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_agendado','0','0','0','0','0',9,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_data_execucao','0','0','0','0','0',10,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_tipo_agendamento','0','0','0','0','0',11,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_periodicidade','0','0','0','0','0',12,null,'1');

INSERT INTO tb_relatorio_filtro (REL_CODIGO,TFR_CODIGO,RFI_EXIBE_CSE,RFI_EXIBE_CSA,RFI_EXIBE_COR,RFI_EXIBE_ORG,RFI_EXIBE_SER,RFI_SEQUENCIA,RFI_PARAMETRO,RFI_EXIBE_SUP)
VALUES ('beneficiario_dt_nasc','campo_formato_relatorio','0','0','0','0','0',13,null,'2');
