-- DESENV-9294
UPDATE tb_acesso_recurso SET PAP_CODIGO='1', FUN_CODIGO='164', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='iniciar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='10283';

UPDATE tb_acesso_recurso SET PAP_CODIGO='2', FUN_CODIGO='164', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='iniciar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='10284';

UPDATE tb_acesso_recurso SET PAP_CODIGO='7', FUN_CODIGO='164', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='iniciar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='12050';

UPDATE tb_acesso_recurso SET PAP_CODIGO='1', FUN_CODIGO='165', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='editar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='10287';

UPDATE tb_acesso_recurso SET PAP_CODIGO='2', FUN_CODIGO='165', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='editar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='10288';

UPDATE tb_acesso_recurso SET PAP_CODIGO='7', FUN_CODIGO='165', ACR_RECURSO='/v3/manterIndice', ACR_PARAMETRO='acao', ACR_OPERACAO='editar', ACR_ATIVO=1, ACR_BLOQUEIO='S', ACR_SESSAO='S', ITM_CODIGO=NULL, ACR_FIM_FLUXO='N', ACR_METODO_HTTP='2' WHERE ACR_CODIGO='12052';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16288', '1', 165 , '/v3/manterIndice', 'acao' , 'excluir' , 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16289', '2', 165 , '/v3/manterIndice', 'acao' , 'excluir' , 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16290', '7', 165 , '/v3/manterIndice', 'acao' , 'excluir' , 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16291', '1', 165 , '/v3/manterIndice', 'acao' , 'modificar' , 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16292', '2', 165 , '/v3/manterIndice', 'acao' , 'modificar' , 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16293', '7', 165 , '/v3/manterIndice', 'acao' , 'modificar' , 1, 'S', 'S', NULL, 'N', '2');