-- DESENV-15848
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('510', '9', 'Editar Bloqueio de Vínculos de Servidor', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

-- CONCEDE PERMISSÃO AOS USUÁRIOS E PAPÉIS QUE HOJE JÁ TEM PERMISSÃO PARA FUNÇÃO 85
INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) SELECT PAP_CODIGO, '510' FROM tb_papel_funcao WHERE FUN_CODIGO = '85';
INSERT INTO tb_funcao_perfil_csa (CSA_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT CSA_CODIGO, USU_CODIGO, '510' FROM tb_funcao_perfil_csa WHERE FUN_CODIGO = '85';
INSERT INTO tb_funcao_perfil (PER_CODIGO, FUN_CODIGO) SELECT PER_CODIGO, '510' FROM tb_funcao_perfil WHERE FUN_CODIGO = '85' AND PER_CODIGO IN (SELECT PER_CODIGO FROM tb_perfil WHERE PAP_CODIGO IN (SELECT PAP_CODIGO FROM tb_papel_funcao WHERE FUN_CODIGO = '510'));

UPDATE tb_acesso_recurso SET FUN_CODIGO = '510' WHERE ACR_CODIGO = '10173';
UPDATE tb_acesso_recurso SET FUN_CODIGO = '510' WHERE ACR_CODIGO = '15145';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16323', '7', '510', '/v3/manterConsignataria', 'acao', 'editarCnvVincServidor', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16324', '7', '510', '/v3/manterConsignataria', 'acao', 'salvarCnvVincServidor', 1, 'S', 'S', NULL, 'N', '2');

UPDATE tb_texto_sistema SET TEX_TEXTO = 'BLOQUEIO DE VÍNCULO POR ${upper(rotulo.servico.singular)}' WHERE TEX_CHAVE = 'rotulo.manutencao.bloqueio.vinculo.servico';
