-- DESENV-23469
INSERT INTO tb_tipo_param_sist_consignante (TPC_CODIGO, TPC_DESCRICAO, TPC_DOMINIO, TPC_VLR_DEFAULT, TPC_CSE_ALTERA, TPC_CSE_CONSULTA, TPC_SUP_ALTERA, TPC_SUP_CONSULTA, GPS_CODIGO)
VALUES ('988', 'Enviar senha por email ao se criar um novo usuário via sistema', 'SN', 'N', 'N', 'N', 'N', 'N', NULL);

INSERT INTO tb_param_sist_consignante (TPC_CODIGO, CSE_CODIGO, PSI_VLR)
VALUES ('988', '1', 'N');

INSERT INTO tb_modelo_email (MEM_CODIGO, MEM_TITULO, MEM_TEXTO) 
VALUES ('emailSenhaNovoUsuario', '<@nome_sistema>: Senha novo usuário', CONCAT('<html><head><style type="text/css">body{width:100%', cast(0x3b as char), 'font-family:Arial,Helvetica,sans-serif', cast(0x3b as char), '}.button{width:70%', cast(0x3b as char), 'height:100%', cast(0x3b as char), 'border-radius:10px', cast(0x3b as char), 'box-shadow:0px 8px 15px rgba(0,0,0,0.6) !important', cast(0x3b as char), '-moz-box-shadow:0px 8px 15px rgba(0,0,0,0.6) !important', cast(0x3b as char), '-webkit-box-shadow:0px 8px 15px rgba(0,0,0,0.6) !important', cast(0x3b as char), '}.btn-primary{color:', cast(0x23 as char), 'fff', cast(0x3b as char), 'border:none', cast(0x3b as char), 'background-color:', cast(0x23 as char), '1d4f91', cast(0x3b as char), 'padding:2.5% 4%', cast(0x3b as char), 'text-decoration:none', cast(0x3b as char), 'font-weight:bold', cast(0x3b as char), 'font-size:1.3rem', cast(0x3b as char), '}.btn-secondary{color:', cast(0x23 as char), 'fff', cast(0x3b as char), 'border:none', cast(0x3b as char), 'background-color:', cast(0x23 as char), 'e80070', cast(0x3b as char), 'padding:2.5% 4%', cast(0x3b as char), 'text-decoration:none', cast(0x3b as char), 'font-weight:bold', cast(0x3b as char), 'font-size:1.3rem', cast(0x3b as char), '} .title-h1{font-size:1.5rem', cast(0x3b as char), 'font-weight:bold', cast(0x3b as char), 'color:', cast(0x23 as char), '1d4f91', cast(0x3b as char), 'font-family:Arial,Helvetica,sans-serif', cast(0x3b as char), 'margin:0', cast(0x3b as char), '}</style></head><body><table width="50%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td align="center"><h1 class="title-h1">Olá, <@usuPrimeiroNome></h1></td></tr><tr><td align="center"><br><p>Seu usuário foi criado com sucesso. Sua senha é:</p><br><button class="button btn-primary"><@senha_inicial></button></td></tr><tr><td align="center"><br><p>Clique abaixo caso queria acessar o sistema</p><br><a href="<@link_acesso_sistema>" class="button btn-secondary">Acessar o Sistema</a></td></tr></table></body></html>'));

INSERT INTO tb_tipo_notificacao (TNO_CODIGO, TNO_DESCRICAO, TNO_ENVIO) VALUES ('49','E-mail de senha criada novo usuário','I');

