-- DESENV-23310
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('566', '4', 'Relatório Servidor Saldo Devedor', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N');

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, ITM_CODIGO_PAI, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA)
VALUES ('293', '2', NULL, 'Relatório Servidor Saldo Devedor', 1, 999);


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17104', '6', '566', '/v3/listarRelatorio', 'tipo', 'saldo_devedor_ser', 1, 'S', 'S', '293', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17105', '6', '566', '/v3/executarRelatorio', 'tipoRelatorio', 'saldo_devedor_ser', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17106', '6', '566', '/v3/excluirArquivo', 'subtipo', 'saldo_devedor_ser', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17107', '6', '566', '/v3/downloadArquivo', 'subtipo', 'saldo_devedor_ser', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17108', '6', '566', '/v3/agendarRelatorio', 'tipo', 'saldo_devedor_ser', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('17109', '6', '566', '/v3/cancelarAgendamentoRelatorio', 'tipo', 'saldo_devedor_ser', 1, 'S', 'S', NULL, 'N', '2');


INSERT INTO tb_relatorio (REL_CODIGO, FUN_CODIGO, TAG_CODIGO, REL_TITULO, REL_ATIVO, REL_AGENDADO, REL_CLASSE_RELATORIO, REL_CLASSE_PROCESSO, REL_CLASSE_AGENDAMENTO, REL_TEMPLATE_JASPER, REL_TEMPLATE_DINAMICO, REL_TEMPLATE_SUBRELATORIO, REL_TEMPLATE_SQL, REL_QTD_DIAS_LIMPEZA, REL_CUSTOMIZADO, REL_AGRUPAMENTO)
VALUES ('saldo_devedor_ser', '566', NULL, 'Relatório Servidor Saldo Devedor', 1, 'N', 'com.zetra.econsig.report.reports.RelatorioServidorSaldoDevedor', 'com.zetra.econsig.job.process.ProcessaRelatorioServidorSaldoDevedor', NULL, 'ServidorSaldoDevedor.jasper', NULL, NULL, NULL, 30, 'N', NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_csa', '0', '0', '0', '0', '0', '1', 1, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_svc', '0', '0', '0', '0', '0', '1', 2, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_data_inicio_fim', '0', '0', '0', '0', '0', '2', 3, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_ade_numero_lista', '0', '0', '0', '0', '0', '1', 4, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_tipo_saldo', '0', '0', '0', '0', '0', '1', 5, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_agendado', '0', '0', '0', '0', '0', '1', 6, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_data_execucao', '0', '0', '0', '0', '0', '1', 7, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_envio_email', '0', '0', '0', '0', '0', '1', 8, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_periodicidade', '0', '0', '0', '0', '0', '1', 9, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_tipo_agendamento', '0', '0', '0', '0', '0', '1', 10, NULL);

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('saldo_devedor_ser', 'campo_formato_relatorio', '0', '0', '0', '0', '0', '1', 11, NULL);

