-- DESENV-14592
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('493', '21', 'Configurar Totem', 'N', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N');

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA)
VALUES ('244', '4', 'Configurar Totem', 1, 84);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16004', '1', '493', '/v3/configurarTotem', 'acao', 'iniciar', 1, 'S', 'S', '244', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16005', '1', '493', '/v3/configurarTotem', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16006', '7', '493', '/v3/configurarTotem', 'acao', 'iniciar', 1, 'S', 'S', '244', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16007', '7', '493', '/v3/configurarTotem', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_tipo_param_sist_consignante (tpc_codigo,tpc_descricao,TPC_DOMINIO,TPC_VLR_DEFAULT,TPC_CSE_ALTERA,TPC_CSE_CONSULTA,TPC_SUP_ALTERA,TPC_SUP_CONSULTA,GPS_CODIGO) 
VALUES ('785','Totem - URL para limpeza do cache do sistema','ALFA',NULL,'N','N','N','N','3');

INSERT INTO tb_tipo_param_sist_consignante (tpc_codigo,tpc_descricao,TPC_DOMINIO,TPC_VLR_DEFAULT,TPC_CSE_ALTERA,TPC_CSE_CONSULTA,TPC_SUP_ALTERA,TPC_SUP_CONSULTA,GPS_CODIGO) 
VALUES ('786','Totem - Código do Consignante','ALFA',NULL,'N','N','N','N','3');