CREATE TABLE tb_dashboard_flex (
    DFL_CODIGO VARCHAR(32) NOT NULL,
    PAP_CODIGO VARCHAR(32) NOT NULL,
    FUN_CODIGO VARCHAR(32) NOT NULL DEFAULT '486',
    DFL_NOME VARCHAR(40) NOT NULL,
    DFL_COMPARTILHAMENTO CHAR(1) NOT NULL,
    DFL_ATIVO CHAR(1) NOT NULL,
    PRIMARY KEY (DFL_CODIGO)
);

CREATE TABLE tb_dashboard_flex_consulta (
    DFO_CODIGO VARCHAR(32) NOT NULL,
    DFL_CODIGO VARCHAR(32) NOT NULL,
    DFO_TITULO VARCHAR(100) NOT NULL,
    DFO_INDEX VARCHAR(100) NOT NULL,
    DFO_TIPO_INDEX CHAR(1) NOT NULL,
    DFO_USA_TOOLBAR CHAR(1) NOT NULL,
    DFO_ATIVO CHAR(1) NOT NULL,
    DFO_SLICE TEXT,
    PRIMARY KEY (DFO_CODIGO),
    CONSTRAINT FK_DFO_DFL_1 FOREIGN KEY (DFL_CODIGO) REFERENCES tb_dashboard_flex(DFL_CODIGO),
    INDEX IDX_DFO_DFL_1 (DFL_CODIGO)
);

CREATE TABLE tb_dashboard_flex_toolbar (
    DFT_CODIGO VARCHAR(32) NOT NULL,
    DFO_CODIGO VARCHAR(32) NOT NULL,
    DFT_ITEM VARCHAR(40) NOT NULL,
    PRIMARY KEY (DFT_CODIGO),
    CONSTRAINT FK_DFT_DFO_1 FOREIGN KEY (DFO_CODIGO) REFERENCES tb_dashboard_flex_consulta(DFO_CODIGO),
    INDEX IDX_DFT_DFO_1 (DFO_CODIGO)
);
