//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.31 at 09:39:45 AM BRT 
//


package com.zetra.econsig.soap.compra;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.zetra.econsig.soap.Anexo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="convenio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="adeNumero" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="valorSaldoDevedor" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="dataVencimento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="valorSaldoDevedor2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="dataVencimento2" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="valorSaldoDevedor3" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="dataVencimento3" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="numeroPrestacoes" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="banco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="agencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="conta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nomeFavorecido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cnpjFavorecido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeroContrato" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="linkBoleto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="observacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="detalheSaldoDevedor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="anexoDsdSaldoCompra" type="{Anexo}Anexo" minOccurs="0"/&gt;
 *         &lt;element name="anexoBoletoDsdSaldo" type="{Anexo}Anexo" minOccurs="0"/&gt;
 *         &lt;element name="propostaRefinanciamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cliente",
    "convenio",
    "usuario",
    "senha",
    "adeNumero",
    "valorSaldoDevedor",
    "dataVencimento",
    "valorSaldoDevedor2",
    "dataVencimento2",
    "valorSaldoDevedor3",
    "dataVencimento3",
    "numeroPrestacoes",
    "banco",
    "agencia",
    "conta",
    "nomeFavorecido",
    "cnpjFavorecido",
    "numeroContrato",
    "linkBoleto",
    "observacao",
    "detalheSaldoDevedor",
    "anexoDsdSaldoCompra",
    "anexoBoletoDsdSaldo",
    "propostaRefinanciamento"
})
@XmlRootElement(name = "informarSaldoDevedor")
public class InformarSaldoDevedor {

    @XmlElementRef(name = "cliente", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cliente;
    @XmlElementRef(name = "convenio", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> convenio;
    @XmlElement(required = true)
    protected String usuario;
    @XmlElement(required = true)
    protected String senha;
    protected long adeNumero;
    protected String valorSaldoDevedor;
    @XmlElementRef(name = "dataVencimento", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dataVencimento;
    @XmlElementRef(name = "valorSaldoDevedor2", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> valorSaldoDevedor2;
    @XmlElementRef(name = "dataVencimento2", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dataVencimento2;
    @XmlElementRef(name = "valorSaldoDevedor3", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> valorSaldoDevedor3;
    @XmlElementRef(name = "dataVencimento3", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dataVencimento3;
    @XmlElementRef(name = "numeroPrestacoes", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> numeroPrestacoes;
    @XmlElementRef(name = "banco", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> banco;
    @XmlElementRef(name = "agencia", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agencia;
    @XmlElementRef(name = "conta", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> conta;
    @XmlElementRef(name = "nomeFavorecido", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nomeFavorecido;
    @XmlElementRef(name = "cnpjFavorecido", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cnpjFavorecido;
    @XmlElementRef(name = "numeroContrato", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> numeroContrato;
    @XmlElementRef(name = "linkBoleto", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> linkBoleto;
    @XmlElementRef(name = "observacao", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> observacao;
    @XmlElementRef(name = "detalheSaldoDevedor", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> detalheSaldoDevedor;
    @XmlElementRef(name = "anexoDsdSaldoCompra", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<Anexo> anexoDsdSaldoCompra;
    @XmlElementRef(name = "anexoBoletoDsdSaldo", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<Anexo> anexoBoletoDsdSaldo;
    @XmlElementRef(name = "propostaRefinanciamento", namespace = "CompraService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> propostaRefinanciamento;

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCliente(JAXBElement<String> value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the convenio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConvenio() {
        return convenio;
    }

    /**
     * Sets the value of the convenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConvenio(JAXBElement<String> value) {
        this.convenio = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the senha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenha() {
        return senha;
    }

    /**
     * Sets the value of the senha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenha(String value) {
        this.senha = value;
    }

    /**
     * Gets the value of the adeNumero property.
     * 
     */
    public long getAdeNumero() {
        return adeNumero;
    }

    /**
     * Sets the value of the adeNumero property.
     * 
     */
    public void setAdeNumero(long value) {
        this.adeNumero = value;
    }

    /**
     * Gets the value of the valorSaldoDevedor property.
     * 
     */
    public String getValorSaldoDevedor() {
        return valorSaldoDevedor;
    }

    /**
     * Sets the value of the valorSaldoDevedor property.
     * 
     */
    public void setValorSaldoDevedor(String value) {
        this.valorSaldoDevedor = value;
    }

    /**
     * Gets the value of the dataVencimento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<String> getDataVencimento() {
        return dataVencimento;
    }

    /**
     * Sets the value of the dataVencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDataVencimento(JAXBElement<String> value) {
        this.dataVencimento = value;
    }

    /**
     * Gets the value of the valorSaldoDevedor2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<String> getValorSaldoDevedor2() {
        return valorSaldoDevedor2;
    }

    /**
     * Sets the value of the valorSaldoDevedor2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setValorSaldoDevedor2(JAXBElement<String> value) {
        this.valorSaldoDevedor2 = value;
    }

    /**
     * Gets the value of the dataVencimento2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<String> getDataVencimento2() {
        return dataVencimento2;
    }

    /**
     * Sets the value of the dataVencimento2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDataVencimento2(JAXBElement<String> value) {
        this.dataVencimento2 = value;
    }

    /**
     * Gets the value of the valorSaldoDevedor3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<String> getValorSaldoDevedor3() {
        return valorSaldoDevedor3;
    }

    /**
     * Sets the value of the valorSaldoDevedor3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setValorSaldoDevedor3(JAXBElement<String> value) {
        this.valorSaldoDevedor3 = value;
    }

    /**
     * Gets the value of the dataVencimento3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<String> getDataVencimento3() {
        return dataVencimento3;
    }

    /**
     * Sets the value of the dataVencimento3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDataVencimento3(JAXBElement<String> value) {
        this.dataVencimento3 = value;
    }

    /**
     * Gets the value of the numeroPrestacoes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Short }{@code >}
     *     
     */
    public JAXBElement<String> getNumeroPrestacoes() {
        return numeroPrestacoes;
    }

    /**
     * Sets the value of the numeroPrestacoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Short }{@code >}
     *     
     */
    public void setNumeroPrestacoes(JAXBElement<String> value) {
        this.numeroPrestacoes = value;
    }

    /**
     * Gets the value of the banco property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBanco() {
        return banco;
    }

    /**
     * Sets the value of the banco property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBanco(JAXBElement<String> value) {
        this.banco = value;
    }

    /**
     * Gets the value of the agencia property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgencia() {
        return agencia;
    }

    /**
     * Sets the value of the agencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgencia(JAXBElement<String> value) {
        this.agencia = value;
    }

    /**
     * Gets the value of the conta property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConta() {
        return conta;
    }

    /**
     * Sets the value of the conta property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConta(JAXBElement<String> value) {
        this.conta = value;
    }

    /**
     * Gets the value of the nomeFavorecido property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNomeFavorecido() {
        return nomeFavorecido;
    }

    /**
     * Sets the value of the nomeFavorecido property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNomeFavorecido(JAXBElement<String> value) {
        this.nomeFavorecido = value;
    }

    /**
     * Gets the value of the cnpjFavorecido property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCnpjFavorecido() {
        return cnpjFavorecido;
    }

    /**
     * Sets the value of the cnpjFavorecido property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCnpjFavorecido(JAXBElement<String> value) {
        this.cnpjFavorecido = value;
    }

    /**
     * Gets the value of the numeroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getNumeroContrato() {
        return numeroContrato;
    }

    /**
     * Sets the value of the numeroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setNumeroContrato(JAXBElement<Long> value) {
        this.numeroContrato = value;
    }

    /**
     * Gets the value of the linkBoleto property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkBoleto() {
        return linkBoleto;
    }

    /**
     * Sets the value of the linkBoleto property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkBoleto(JAXBElement<String> value) {
        this.linkBoleto = value;
    }

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getObservacao() {
        return observacao;
    }

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setObservacao(JAXBElement<String> value) {
        this.observacao = value;
    }

    /**
     * Gets the value of the detalheSaldoDevedor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDetalheSaldoDevedor() {
        return detalheSaldoDevedor;
    }

    /**
     * Sets the value of the detalheSaldoDevedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDetalheSaldoDevedor(JAXBElement<String> value) {
        this.detalheSaldoDevedor = value;
    }

    /**
     * Gets the value of the anexoDsdSaldoCompra property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Anexo }{@code >}
     *     
     */
    public JAXBElement<Anexo> getAnexoDsdSaldoCompra() {
        return anexoDsdSaldoCompra;
    }

    /**
     * Sets the value of the anexoDsdSaldoCompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Anexo }{@code >}
     *     
     */
    public void setAnexoDsdSaldoCompra(JAXBElement<Anexo> value) {
        this.anexoDsdSaldoCompra = value;
    }

    /**
     * Gets the value of the anexoBoletoDsdSaldo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Anexo }{@code >}
     *     
     */
    public JAXBElement<Anexo> getAnexoBoletoDsdSaldo() {
        return anexoBoletoDsdSaldo;
    }

    /**
     * Sets the value of the anexoBoletoDsdSaldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Anexo }{@code >}
     *     
     */
    public void setAnexoBoletoDsdSaldo(JAXBElement<Anexo> value) {
        this.anexoBoletoDsdSaldo = value;
    }

    /**
     * Gets the value of the propostaRefinanciamento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPropostaRefinanciamento() {
        return propostaRefinanciamento;
    }

    /**
     * Sets the value of the propostaRefinanciamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPropostaRefinanciamento(JAXBElement<String> value) {
        this.propostaRefinanciamento = value;
    }

}
