-- DESENV-16874
INSERT INTO tb_tipo_param_sist_consignante (TPC_CODIGO, TPC_DESCRICAO, TPC_DOMINIO, TPC_VLR_DEFAULT, TPC_CSE_ALTERA, TPC_CSE_CONSULTA, TPC_SUP_ALTERA, TPC_SUP_CONSULTA, GPS_CODIGO)
VALUES ('870', 'Permite reservar contrato de saúde sem utilizar fluxo do módulo de saúde', 'SN', 'N', 'N', 'N', 'N', 'N', NULL);

INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_CSA_ALTERA, TPS_SUP_ALTERA, TPS_PODE_SOBREPOR_RSE)
VALUES ('312', 'Permite desconto via boleto', 'N', 'N', 'N', NULL);

INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_DOMINIO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA,TDA_ORDENACAO)
VALUES ('54', '107', 'Código Beneficiário Dependente', 'ALFA', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N',54);

INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_DOMINIO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA, TDA_ORDENACAO)
VALUES ('55', '107', 'Forma de pagamento', 'ALFA', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N',55);

