-- DESENV-20785
INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_DOMINIO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA)
VALUES ('89', '1', 'Data para novos servidores aposentados', 'DATA', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

-- INSERT INTO tb_dados_consignante (CSE_CODIGO, TDA_CODIGO, DAC_VALOR) VALUES ('1', '89', '01/01/2023');

