-- DESENV-20922
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16864', NULL, NULL, '/v3/solicitarCertificadoDigital', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '0');

