-- DESENV-12756
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15500', '1', '469', '/v3/autorizarOperacoesFila', 'acao', 'resolverOperacoes', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15501', '2', '469', '/v3/autorizarOperacoesFila', 'acao', 'resolverOperacoes', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15502', '3', '469', '/v3/autorizarOperacoesFila', 'acao', 'resolverOperacoes', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15503', '4', '469', '/v3/autorizarOperacoesFila', 'acao', 'resolverOperacoes', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15504', '7', '469', '/v3/autorizarOperacoesFila', 'acao', 'resolverOperacoes', 1, 'S', 'S', NULL, 'S', '2');

INSERT INTO tb_tipo_entidade (TEN_CODIGO, TEN_DESCRICAO, TEN_AUDITORIA, TEN_TITULO, TEN_CAMPO_ENT_00, TEN_CAMPO_ENT_01, TEN_CAMPO_ENT_02, TEN_CAMPO_ENT_03, TEN_CAMPO_ENT_04, TEN_CAMPO_ENT_05, TEN_CAMPO_ENT_06, TEN_CAMPO_ENT_07, TEN_CAMPO_ENT_08, TEN_CAMPO_ENT_09, TEN_CAMPO_ENT_10)
VALUES ('114', 'Operação em Fila de Autorização', 1, 'Descrição', 'FUN_CODIGO', 'USU_CODIGO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
