/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "AjudaRecurso"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_ajuda_recurso")
public class AjudaRecurso implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ajr_codigo", nullable = false, length = 32)
    private String ajrCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "acr_codigo", nullable = false, length = 32)
    private String acrCodigo;

    @Column(name = "ajr_elemento", nullable = false, length = 100)
    private String ajrElemento;

    @Column(name = "ajr_sequencia", nullable = false)
    private Short ajrSequencia;

    @Column(name = "ajr_posicao", nullable = false, length = 40)
    private String ajrPosicao;

    @Column(name = "ajr_texto", nullable = false, length = 65535)
    private String ajrTexto;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acr_codigo", referencedColumnName = "acr_codigo", insertable = false, updatable = false)
    private AcessoRecurso acessoRecurso;

    /**
     * Constructor
     */
    public AjudaRecurso() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAjrCodigo(String ajrCodigo) {
        this.ajrCodigo = ajrCodigo;
    }

    public String getAjrCodigo() {
        return ajrCodigo;
    }

    public void setAcrCodigo(String acrCodigo) {
        this.acrCodigo = acrCodigo;
    }

    public String getAcrCodigo() {
        return acrCodigo;
    }

    public void setAjrElemento(String ajrElemento) {
        this.ajrElemento = ajrElemento;
    }

    public String getAjrElemento() {
        return ajrElemento;
    }

    public void setAjrSequencia(Short ajrSequencia) {
        this.ajrSequencia = ajrSequencia;
    }

    public Short getAjrSequencia() {
        return ajrSequencia;
    }

    public void setAjrPosicao(String ajrPosicao) {
        this.ajrPosicao = ajrPosicao;
    }

    public String getAjrPosicao() {
        return ajrPosicao;
    }

    public void setAjrTexto(String ajrTexto) {
        this.ajrTexto = ajrTexto;
    }

    public String getAjrTexto() {
        return ajrTexto;
    }

    //--- GETTERS FOR LINKS
    public void setAcessoRecurso(AcessoRecurso acessoRecurso) {
        this.acessoRecurso = acessoRecurso;
        setAcrCodigo(acessoRecurso != null ? acessoRecurso.getAcrCodigo() : null);
    }

    public AcessoRecurso getAcessoRecurso() {
        return acessoRecurso;
    }

}
