/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "Ajuda"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_ajuda")
public class Ajuda implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "acr_codigo", nullable = false, length = 32)
    private String acrCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "aju_titulo", nullable = false, length = 255)
    private String ajuTitulo;

    @Column(name = "aju_texto", nullable = false, length = 65535)
    private String ajuTexto;

    @Column(name = "aju_ativo", nullable = false)
    private Short ajuAtivo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "aju_data_alteracao", nullable = false)
    private Date ajuDataAlteracao;

    @Column(name = "aju_sequencia", nullable = false)
    private Short ajuSequencia;

    @Column(name = "aju_html", nullable = false, length = 1)
    private String ajuHtml;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acr_codigo", referencedColumnName = "acr_codigo", insertable = false, updatable = false)
    private AcessoRecurso acessoRecurso;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public Ajuda() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAcrCodigo(String acrCodigo) {
        this.acrCodigo = acrCodigo;
    }

    public String getAcrCodigo() {
        return acrCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setAjuTitulo(String ajuTitulo) {
        this.ajuTitulo = ajuTitulo;
    }

    public String getAjuTitulo() {
        return ajuTitulo;
    }

    public void setAjuTexto(String ajuTexto) {
        this.ajuTexto = ajuTexto;
    }

    public String getAjuTexto() {
        return ajuTexto;
    }

    public void setAjuAtivo(Short ajuAtivo) {
        this.ajuAtivo = ajuAtivo;
    }

    public Short getAjuAtivo() {
        return ajuAtivo;
    }

    public void setAjuDataAlteracao(Date ajuDataAlteracao) {
        this.ajuDataAlteracao = ajuDataAlteracao;
    }

    public Date getAjuDataAlteracao() {
        return ajuDataAlteracao;
    }

    public void setAjuSequencia(Short ajuSequencia) {
        this.ajuSequencia = ajuSequencia;
    }

    public Short getAjuSequencia() {
        return ajuSequencia;
    }

    public void setAjuHtml(String ajuHtml) {
        this.ajuHtml = ajuHtml;
    }

    public String getAjuHtml() {
        return ajuHtml;
    }

    //--- GETTERS FOR LINKS
    public void setAcessoRecurso(AcessoRecurso acessoRecurso) {
        this.acessoRecurso = acessoRecurso;
        setAcrCodigo(acessoRecurso != null ? acessoRecurso.getAcrCodigo() : null);
    }

    public AcessoRecurso getAcessoRecurso() {
        return acessoRecurso;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

}
