/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "AnexoAutorizacaoDesconto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_anexo_autorizacao_desconto")
@IdClass(AnexoAutorizacaoDescontoId.class)
public class AnexoAutorizacaoDesconto implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ade_codigo", nullable = false, length = 32)
    private String adeCodigo;

    @Id
    @Column(name = "aad_nome", nullable = false, length = 255)
    private String aadNome;

    //--- ENTITY DATA FIELDS
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "tar_codigo", nullable = false, length = 32)
    private String tarCodigo;

    @Column(name = "aad_descricao", nullable = false, length = 255)
    private String aadDescricao;

    @Column(name = "aad_ativo", nullable = false)
    private Short aadAtivo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "aad_data", nullable = false)
    private Date aadData;

    @Column(name = "aad_ip_acesso", length = 45)
    private String aadIpAcesso;

    @Temporal(TemporalType.DATE)
    @Column(name = "aad_periodo")
    private Date aadPeriodo;

    @Column(name = "aad_exibe_sup", nullable = false, length = 1)
    private String aadExibeSup;

    @Column(name = "aad_exibe_cse", nullable = false, length = 1)
    private String aadExibeCse;

    @Column(name = "aad_exibe_org", nullable = false, length = 1)
    private String aadExibeOrg;

    @Column(name = "aad_exibe_csa", nullable = false, length = 1)
    private String aadExibeCsa;

    @Column(name = "aad_exibe_cor", nullable = false, length = 1)
    private String aadExibeCor;

    @Column(name = "aad_exibe_ser", nullable = false, length = 1)
    private String aadExibeSer;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ade_codigo", referencedColumnName = "ade_codigo", insertable = false, updatable = false)
    private AutDesconto autDesconto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tar_codigo", referencedColumnName = "tar_codigo", insertable = false, updatable = false)
    private TipoArquivo tipoArquivo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public AnexoAutorizacaoDesconto() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAdeCodigo(String adeCodigo) {
        this.adeCodigo = adeCodigo;
    }

    public String getAdeCodigo() {
        return adeCodigo;
    }

    public void setAadNome(String aadNome) {
        this.aadNome = aadNome;
    }

    public String getAadNome() {
        return aadNome;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setTarCodigo(String tarCodigo) {
        this.tarCodigo = tarCodigo;
    }

    public String getTarCodigo() {
        return tarCodigo;
    }

    public void setAadDescricao(String aadDescricao) {
        this.aadDescricao = aadDescricao;
    }

    public String getAadDescricao() {
        return aadDescricao;
    }

    public void setAadAtivo(Short aadAtivo) {
        this.aadAtivo = aadAtivo;
    }

    public Short getAadAtivo() {
        return aadAtivo;
    }

    public void setAadData(Date aadData) {
        this.aadData = aadData;
    }

    public Date getAadData() {
        return aadData;
    }

    public void setAadIpAcesso(String aadIpAcesso) {
        this.aadIpAcesso = aadIpAcesso;
    }

    public String getAadIpAcesso() {
        return aadIpAcesso;
    }

    public void setAadPeriodo(Date aadPeriodo) {
        this.aadPeriodo = aadPeriodo;
    }

    public Date getAadPeriodo() {
        return aadPeriodo;
    }

    public void setAadExibeSup(String aadExibeSup) {
        this.aadExibeSup = aadExibeSup;
    }

    public String getAadExibeSup() {
        return aadExibeSup;
    }

    public void setAadExibeCse(String aadExibeCse) {
        this.aadExibeCse = aadExibeCse;
    }

    public String getAadExibeCse() {
        return aadExibeCse;
    }

    public void setAadExibeOrg(String aadExibeOrg) {
        this.aadExibeOrg = aadExibeOrg;
    }

    public String getAadExibeOrg() {
        return aadExibeOrg;
    }

    public void setAadExibeCsa(String aadExibeCsa) {
        this.aadExibeCsa = aadExibeCsa;
    }

    public String getAadExibeCsa() {
        return aadExibeCsa;
    }

    public void setAadExibeCor(String aadExibeCor) {
        this.aadExibeCor = aadExibeCor;
    }

    public String getAadExibeCor() {
        return aadExibeCor;
    }

    public void setAadExibeSer(String aadExibeSer) {
        this.aadExibeSer = aadExibeSer;
    }

    public String getAadExibeSer() {
        return aadExibeSer;
    }

    //--- GETTERS FOR LINKS
    public void setAutDesconto(AutDesconto autDesconto) {
        this.autDesconto = autDesconto;
        setAdeCodigo(autDesconto != null ? autDesconto.getAdeCodigo() : null);
    }

    public AutDesconto getAutDesconto() {
        return autDesconto;
    }

    public void setTipoArquivo(TipoArquivo tipoArquivo) {
        this.tipoArquivo = tipoArquivo;
        setTarCodigo(tipoArquivo != null ? tipoArquivo.getTarCodigo() : null);
    }

    public TipoArquivo getTipoArquivo() {
        return tipoArquivo;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setId(AnexoAutorizacaoDescontoId id) {
        setAdeCodigo(id != null ? id.getAdeCodigo() : null);
        setAadNome(id != null ? id.getAadNome() : null);
    }
}
