/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "AnexoBeneficiario" ( stored in table "tb_anexo_beneficiario" )
 *
 * @author Telosys
 *
 */
public class AnexoBeneficiarioId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String bfcCodigo;

    private String abfNome;

    /**
     * Constructor
     */
    public AnexoBeneficiarioId() {
        super();
    }

    /**
     * Constructor with values
     * @param bfcCodigo 
     * @param abfNome 
     */
    public AnexoBeneficiarioId(String bfcCodigo, String abfNome) {
        super();
        this.bfcCodigo = bfcCodigo;
        this.abfNome = abfNome;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setBfcCodigo(String value) {
        this.bfcCodigo = value;
    }

    public String getBfcCodigo() {
        return this.bfcCodigo;
    }

    public void setAbfNome(String value) {
        this.abfNome = value;
    }

    public String getAbfNome() {
        return this.abfNome;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        AnexoBeneficiarioId other = (AnexoBeneficiarioId) obj;
        //--- Attribute bfcCodigo
        if (bfcCodigo == null) {
            if (other.bfcCodigo != null)
                return false;
        } else if (!bfcCodigo.equals(other.bfcCodigo))
            return false;
        //--- Attribute abfNome
        if (abfNome == null) {
            if (other.abfNome != null)
                return false;
        } else if (!abfNome.equals(other.abfNome))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute bfcCodigo
        result = prime * result + ((bfcCodigo == null) ? 0 : bfcCodigo.hashCode());
        //--- Attribute abfNome
        result = prime * result + ((abfNome == null) ? 0 : abfNome.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(bfcCodigo);
        sb.append("|");
        sb.append(abfNome);
        return sb.toString();
    }

}
