/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ArquivoFaturamentoBen"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_arquivo_faturamento_ben")
public class ArquivoFaturamentoBen implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "afb_codigo", nullable = false)
    private Integer afbCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "fat_codigo", nullable = false, length = 32)
    private String fatCodigo;

    @Column(name = "ade_codigo", nullable = false, length = 32)
    private String adeCodigo;

    @Column(name = "tla_codigo", nullable = false, length = 32)
    private String tlaCodigo;

    @Column(name = "rse_matricula", length = 35)
    private String rseMatricula;

    @Column(name = "cbe_numero", length = 40)
    private String cbeNumero;

    @Column(name = "cbe_valor_total")
    private BigDecimal cbeValorTotal;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cbe_data_inclusao")
    private Date cbeDataInclusao;

    @Column(name = "ben_codigo_registro", length = 40)
    private String benCodigoRegistro;

    @Column(name = "ben_codigo_contrato", length = 40)
    private String benCodigoContrato;

    @Column(name = "bfc_cpf", length = 19)
    private String bfcCpf;

    @Column(name = "bfc_celular", length = 40)
    private String bfcCelular;

    @Column(name = "bfc_ordem_dependencia")
    private Short bfcOrdemDependencia;

    @Column(name = "bfc_nome", length = 255)
    private String bfcNome;

    @Column(name = "ens_logradouro", length = 100)
    private String ensLogradouro;

    @Column(name = "ens_numero", length = 15)
    private String ensNumero;

    @Column(name = "ens_complemento", length = 40)
    private String ensComplemento;

    @Column(name = "ens_bairro", length = 40)
    private String ensBairro;

    @Column(name = "ens_municipio", length = 40)
    private String ensMunicipio;

    @Column(name = "ens_uf", length = 2)
    private String ensUf;

    @Column(name = "ens_cep", length = 10)
    private String ensCep;

    @Column(name = "ens_codigo_municipio", length = 7)
    private String ensCodigoMunicipio;

    @Column(name = "prd_vlr_previsto")
    private BigDecimal prdVlrPrevisto;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_ini")
    private Date adeAnoMesIni;

    @Column(name = "cnv_cod_verba", length = 32)
    private String cnvCodVerba;

    @Column(name = "rse_matricula_inst", length = 35)
    private String rseMatriculaInst;

    @Column(name = "afb_numero_lote", length = 40)
    private String afbNumeroLote;

    @Column(name = "afb_item_lote", length = 40)
    private String afbItemLote;

    @Column(name = "afb_valor_subsidio")
    private BigDecimal afbValorSubsidio;

    @Column(name = "afb_valor_realizado")
    private BigDecimal afbValorRealizado;

    @Column(name = "afb_valor_nao_realizado")
    private BigDecimal afbValorNaoRealizado;

    @Column(name = "afb_valor_total")
    private BigDecimal afbValorTotal;

    @Column(name = "afb_codigo_fundo_repasse", length = 2)
    private String afbCodigoFundoRepasse;

    @Column(name = "afb_descricao_fundo_repasse", length = 255)
    private String afbDescricaoFundoRepasse;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tla_codigo", referencedColumnName = "tla_codigo", insertable = false, updatable = false)
    private TipoLancamento tipoLancamento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fat_codigo", referencedColumnName = "fat_codigo", insertable = false, updatable = false)
    private FaturamentoBeneficio faturamentoBeneficio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ade_codigo", referencedColumnName = "ade_codigo", insertable = false, updatable = false)
    private AutDesconto autDesconto;

    /**
     * Constructor
     */
    public ArquivoFaturamentoBen() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAfbCodigo(Integer afbCodigo) {
        this.afbCodigo = afbCodigo;
    }

    public Integer getAfbCodigo() {
        return afbCodigo;
    }

    public void setFatCodigo(String fatCodigo) {
        this.fatCodigo = fatCodigo;
    }

    public String getFatCodigo() {
        return fatCodigo;
    }

    public void setAdeCodigo(String adeCodigo) {
        this.adeCodigo = adeCodigo;
    }

    public String getAdeCodigo() {
        return adeCodigo;
    }

    public void setTlaCodigo(String tlaCodigo) {
        this.tlaCodigo = tlaCodigo;
    }

    public String getTlaCodigo() {
        return tlaCodigo;
    }

    public void setRseMatricula(String rseMatricula) {
        this.rseMatricula = rseMatricula;
    }

    public String getRseMatricula() {
        return rseMatricula;
    }

    public void setCbeNumero(String cbeNumero) {
        this.cbeNumero = cbeNumero;
    }

    public String getCbeNumero() {
        return cbeNumero;
    }

    public void setCbeValorTotal(BigDecimal cbeValorTotal) {
        this.cbeValorTotal = cbeValorTotal;
    }

    public BigDecimal getCbeValorTotal() {
        return cbeValorTotal;
    }

    public void setCbeDataInclusao(Date cbeDataInclusao) {
        this.cbeDataInclusao = cbeDataInclusao;
    }

    public Date getCbeDataInclusao() {
        return cbeDataInclusao;
    }

    public void setBenCodigoRegistro(String benCodigoRegistro) {
        this.benCodigoRegistro = benCodigoRegistro;
    }

    public String getBenCodigoRegistro() {
        return benCodigoRegistro;
    }

    public void setBenCodigoContrato(String benCodigoContrato) {
        this.benCodigoContrato = benCodigoContrato;
    }

    public String getBenCodigoContrato() {
        return benCodigoContrato;
    }

    public void setBfcCpf(String bfcCpf) {
        this.bfcCpf = bfcCpf;
    }

    public String getBfcCpf() {
        return bfcCpf;
    }

    public void setBfcCelular(String bfcCelular) {
        this.bfcCelular = bfcCelular;
    }

    public String getBfcCelular() {
        return bfcCelular;
    }

    public void setBfcOrdemDependencia(Short bfcOrdemDependencia) {
        this.bfcOrdemDependencia = bfcOrdemDependencia;
    }

    public Short getBfcOrdemDependencia() {
        return bfcOrdemDependencia;
    }

    public void setBfcNome(String bfcNome) {
        this.bfcNome = bfcNome;
    }

    public String getBfcNome() {
        return bfcNome;
    }

    public void setEnsLogradouro(String ensLogradouro) {
        this.ensLogradouro = ensLogradouro;
    }

    public String getEnsLogradouro() {
        return ensLogradouro;
    }

    public void setEnsNumero(String ensNumero) {
        this.ensNumero = ensNumero;
    }

    public String getEnsNumero() {
        return ensNumero;
    }

    public void setEnsComplemento(String ensComplemento) {
        this.ensComplemento = ensComplemento;
    }

    public String getEnsComplemento() {
        return ensComplemento;
    }

    public void setEnsBairro(String ensBairro) {
        this.ensBairro = ensBairro;
    }

    public String getEnsBairro() {
        return ensBairro;
    }

    public void setEnsMunicipio(String ensMunicipio) {
        this.ensMunicipio = ensMunicipio;
    }

    public String getEnsMunicipio() {
        return ensMunicipio;
    }

    public void setEnsUf(String ensUf) {
        this.ensUf = ensUf;
    }

    public String getEnsUf() {
        return ensUf;
    }

    public void setEnsCep(String ensCep) {
        this.ensCep = ensCep;
    }

    public String getEnsCep() {
        return ensCep;
    }

    public void setEnsCodigoMunicipio(String ensCodigoMunicipio) {
        this.ensCodigoMunicipio = ensCodigoMunicipio;
    }

    public String getEnsCodigoMunicipio() {
        return ensCodigoMunicipio;
    }

    public void setPrdVlrPrevisto(BigDecimal prdVlrPrevisto) {
        this.prdVlrPrevisto = prdVlrPrevisto;
    }

    public BigDecimal getPrdVlrPrevisto() {
        return prdVlrPrevisto;
    }

    public void setAdeAnoMesIni(Date adeAnoMesIni) {
        this.adeAnoMesIni = adeAnoMesIni;
    }

    public Date getAdeAnoMesIni() {
        return adeAnoMesIni;
    }

    public void setCnvCodVerba(String cnvCodVerba) {
        this.cnvCodVerba = cnvCodVerba;
    }

    public String getCnvCodVerba() {
        return cnvCodVerba;
    }

    public void setRseMatriculaInst(String rseMatriculaInst) {
        this.rseMatriculaInst = rseMatriculaInst;
    }

    public String getRseMatriculaInst() {
        return rseMatriculaInst;
    }

    public void setAfbNumeroLote(String afbNumeroLote) {
        this.afbNumeroLote = afbNumeroLote;
    }

    public String getAfbNumeroLote() {
        return afbNumeroLote;
    }

    public void setAfbItemLote(String afbItemLote) {
        this.afbItemLote = afbItemLote;
    }

    public String getAfbItemLote() {
        return afbItemLote;
    }

    public void setAfbValorSubsidio(BigDecimal afbValorSubsidio) {
        this.afbValorSubsidio = afbValorSubsidio;
    }

    public BigDecimal getAfbValorSubsidio() {
        return afbValorSubsidio;
    }

    public void setAfbValorRealizado(BigDecimal afbValorRealizado) {
        this.afbValorRealizado = afbValorRealizado;
    }

    public BigDecimal getAfbValorRealizado() {
        return afbValorRealizado;
    }

    public void setAfbValorNaoRealizado(BigDecimal afbValorNaoRealizado) {
        this.afbValorNaoRealizado = afbValorNaoRealizado;
    }

    public BigDecimal getAfbValorNaoRealizado() {
        return afbValorNaoRealizado;
    }

    public void setAfbValorTotal(BigDecimal afbValorTotal) {
        this.afbValorTotal = afbValorTotal;
    }

    public BigDecimal getAfbValorTotal() {
        return afbValorTotal;
    }

    public void setAfbCodigoFundoRepasse(String afbCodigoFundoRepasse) {
        this.afbCodigoFundoRepasse = afbCodigoFundoRepasse;
    }

    public String getAfbCodigoFundoRepasse() {
        return afbCodigoFundoRepasse;
    }

    public void setAfbDescricaoFundoRepasse(String afbDescricaoFundoRepasse) {
        this.afbDescricaoFundoRepasse = afbDescricaoFundoRepasse;
    }

    public String getAfbDescricaoFundoRepasse() {
        return afbDescricaoFundoRepasse;
    }

    //--- GETTERS FOR LINKS
    public void setTipoLancamento(TipoLancamento tipoLancamento) {
        this.tipoLancamento = tipoLancamento;
        setTlaCodigo(tipoLancamento != null ? tipoLancamento.getTlaCodigo() : null);
    }

    public TipoLancamento getTipoLancamento() {
        return tipoLancamento;
    }

    public void setFaturamentoBeneficio(FaturamentoBeneficio faturamentoBeneficio) {
        this.faturamentoBeneficio = faturamentoBeneficio;
        setFatCodigo(faturamentoBeneficio != null ? faturamentoBeneficio.getFatCodigo() : null);
    }

    public FaturamentoBeneficio getFaturamentoBeneficio() {
        return faturamentoBeneficio;
    }

    public void setAutDesconto(AutDesconto autDesconto) {
        this.autDesconto = autDesconto;
        setAdeCodigo(autDesconto != null ? autDesconto.getAdeCodigo() : null);
    }

    public AutDesconto getAutDesconto() {
        return autDesconto;
    }

}
