/*
 * Created on 2021-12-30 ( 18:15:55 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ArquivoPreviaOperadora"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_arquivo_previa_operadora")
public class ArquivoPreviaOperadora implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "apo_codigo", nullable = false)
    private Integer apoCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    @Column(name = "apo_nome_arquivo", nullable = false, length = 100)
    private String apoNomeArquivo;

    @Column(name = "apo_operacao", nullable = false, length = 1)
    private String apoOperacao;

    @Temporal(TemporalType.DATE)
    @Column(name = "apo_periodo_faturamento", nullable = false)
    private Date apoPeriodoFaturamento;

    @Temporal(TemporalType.DATE)
    @Column(name = "apo_data_inclusao")
    private Date apoDataInclusao;

    @Temporal(TemporalType.DATE)
    @Column(name = "apo_data_exclusao")
    private Date apoDataExclusao;

    @Column(name = "cbe_numero", nullable = false, length = 40)
    private String cbeNumero;

    @Column(name = "ben_codigo_registro", nullable = false, length = 40)
    private String benCodigoRegistro;

    @Column(name = "rse_matricula", nullable = false, length = 35)
    private String rseMatricula;

    @Column(name = "ben_codigo_contrato", nullable = false, length = 40)
    private String benCodigoContrato;

    @Column(name = "apo_valor_debito", nullable = false)
    private BigDecimal apoValorDebito;

    @Column(name = "apo_tipo_lancamento", nullable = false, length = 32)
    private String apoTipoLancamento;

    @Column(name = "apo_reajuste_faixa_etaria", length = 1)
    private String apoReajusteFaixaEtaria;

    @Column(name = "apo_reajuste_anual", length = 1)
    private String apoReajusteAnual;

    @Column(name = "apo_numero_lote", length = 40)
    private String apoNumeroLote;

    @Column(name = "apo_item_lote", length = 40)
    private String apoItemLote;

    @Column(name = "apo_valor_subsidio")
    private BigDecimal apoValorSubsidio;

    @Column(name = "apo_valor_realizado")
    private BigDecimal apoValorRealizado;

    @Column(name = "apo_valor_nao_realizado")
    private BigDecimal apoValorNaoRealizado;

    @Column(name = "apo_valor_total")
    private BigDecimal apoValorTotal;

    @Temporal(TemporalType.DATE)
    @Column(name = "apo_periodo_cobranca")
    private Date apoPeriodoCobranca;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    /**
     * Constructor
     */
    public ArquivoPreviaOperadora() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setApoCodigo(Integer apoCodigo) {
        this.apoCodigo = apoCodigo;
    }

    public Integer getApoCodigo() {
        return apoCodigo;
    }

    public void setCsaCodigo(String csaCodigo) {
        this.csaCodigo = csaCodigo;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    public void setApoNomeArquivo(String apoNomeArquivo) {
        this.apoNomeArquivo = apoNomeArquivo;
    }

    public String getApoNomeArquivo() {
        return apoNomeArquivo;
    }

    public void setApoOperacao(String apoOperacao) {
        this.apoOperacao = apoOperacao;
    }

    public String getApoOperacao() {
        return apoOperacao;
    }

    public void setApoPeriodoFaturamento(Date apoPeriodoFaturamento) {
        this.apoPeriodoFaturamento = apoPeriodoFaturamento;
    }

    public Date getApoPeriodoFaturamento() {
        return apoPeriodoFaturamento;
    }

    public void setApoDataInclusao(Date apoDataInclusao) {
        this.apoDataInclusao = apoDataInclusao;
    }

    public Date getApoDataInclusao() {
        return apoDataInclusao;
    }

    public void setApoDataExclusao(Date apoDataExclusao) {
        this.apoDataExclusao = apoDataExclusao;
    }

    public Date getApoDataExclusao() {
        return apoDataExclusao;
    }

    public void setCbeNumero(String cbeNumero) {
        this.cbeNumero = cbeNumero;
    }

    public String getCbeNumero() {
        return cbeNumero;
    }

    public void setBenCodigoRegistro(String benCodigoRegistro) {
        this.benCodigoRegistro = benCodigoRegistro;
    }

    public String getBenCodigoRegistro() {
        return benCodigoRegistro;
    }

    public void setRseMatricula(String rseMatricula) {
        this.rseMatricula = rseMatricula;
    }

    public String getRseMatricula() {
        return rseMatricula;
    }

    public void setBenCodigoContrato(String benCodigoContrato) {
        this.benCodigoContrato = benCodigoContrato;
    }

    public String getBenCodigoContrato() {
        return benCodigoContrato;
    }

    public void setApoValorDebito(BigDecimal apoValorDebito) {
        this.apoValorDebito = apoValorDebito;
    }

    public BigDecimal getApoValorDebito() {
        return apoValorDebito;
    }

    public void setApoTipoLancamento(String apoTipoLancamento) {
        this.apoTipoLancamento = apoTipoLancamento;
    }

    public String getApoTipoLancamento() {
        return apoTipoLancamento;
    }

    public void setApoReajusteFaixaEtaria(String apoReajusteFaixaEtaria) {
        this.apoReajusteFaixaEtaria = apoReajusteFaixaEtaria;
    }

    public String getApoReajusteFaixaEtaria() {
        return apoReajusteFaixaEtaria;
    }

    public void setApoReajusteAnual(String apoReajusteAnual) {
        this.apoReajusteAnual = apoReajusteAnual;
    }

    public String getApoReajusteAnual() {
        return apoReajusteAnual;
    }

    public void setApoNumeroLote(String apoNumeroLote) {
        this.apoNumeroLote = apoNumeroLote;
    }

    public String getApoNumeroLote() {
        return apoNumeroLote;
    }

    public void setApoItemLote(String apoItemLote) {
        this.apoItemLote = apoItemLote;
    }

    public String getApoItemLote() {
        return apoItemLote;
    }

    public void setApoValorSubsidio(BigDecimal apoValorSubsidio) {
        this.apoValorSubsidio = apoValorSubsidio;
    }

    public BigDecimal getApoValorSubsidio() {
        return apoValorSubsidio;
    }

    public void setApoValorRealizado(BigDecimal apoValorRealizado) {
        this.apoValorRealizado = apoValorRealizado;
    }

    public BigDecimal getApoValorRealizado() {
        return apoValorRealizado;
    }

    public void setApoValorNaoRealizado(BigDecimal apoValorNaoRealizado) {
        this.apoValorNaoRealizado = apoValorNaoRealizado;
    }

    public BigDecimal getApoValorNaoRealizado() {
        return apoValorNaoRealizado;
    }

    public void setApoValorTotal(BigDecimal apoValorTotal) {
        this.apoValorTotal = apoValorTotal;
    }

    public BigDecimal getApoValorTotal() {
        return apoValorTotal;
    }

    public void setApoPeriodoCobranca(Date apoPeriodoCobranca) {
        this.apoPeriodoCobranca = apoPeriodoCobranca;
    }

    public Date getApoPeriodoCobranca() {
        return apoPeriodoCobranca;
    }

    //--- GETTERS FOR LINKS
    public void setConsignataria(Consignataria consignataria) {
        this.consignataria = consignataria;
        setCsaCodigo(consignataria != null ? consignataria.getCsaCodigo() : null);
    }

    public Consignataria getConsignataria() {
        return consignataria;
    }

}
