/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "AtendimentoMensagem" ( stored in table "tb_atendimento_mensagem" )
 *
 * @author Telosys
 *
 */
public class AtendimentoMensagemId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String ateCodigo;

    private Integer ameSequencia;

    /**
     * Constructor
     */
    public AtendimentoMensagemId() {
        super();
    }

    /**
     * Constructor with values
     * @param ateCodigo 
     * @param ameSequencia 
     */
    public AtendimentoMensagemId(String ateCodigo, Integer ameSequencia) {
        super();
        this.ateCodigo = ateCodigo;
        this.ameSequencia = ameSequencia;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setAteCodigo(String value) {
        this.ateCodigo = value;
    }

    public String getAteCodigo() {
        return this.ateCodigo;
    }

    public void setAmeSequencia(Integer value) {
        this.ameSequencia = value;
    }

    public Integer getAmeSequencia() {
        return this.ameSequencia;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        AtendimentoMensagemId other = (AtendimentoMensagemId) obj;
        //--- Attribute ateCodigo
        if (ateCodigo == null) {
            if (other.ateCodigo != null)
                return false;
        } else if (!ateCodigo.equals(other.ateCodigo))
            return false;
        //--- Attribute ameSequencia
        if (ameSequencia == null) {
            if (other.ameSequencia != null)
                return false;
        } else if (!ameSequencia.equals(other.ameSequencia))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute ateCodigo
        result = prime * result + ((ateCodigo == null) ? 0 : ateCodigo.hashCode());
        //--- Attribute ameSequencia
        result = prime * result + ((ameSequencia == null) ? 0 : ameSequencia.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ateCodigo);
        sb.append("|");
        sb.append(ameSequencia);
        return sb.toString();
    }

}
