/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "AuditoriaOrg"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_auditoria_org")
public class AuditoriaOrg implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "aor_codigo", nullable = false)
    private Integer aorCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "org_codigo", nullable = false, length = 32)
    private String orgCodigo;

    @Column(name = "tlo_codigo", nullable = false, length = 32)
    private String tloCodigo;

    @Column(name = "usu_codigo", length = 32)
    private String usuCodigo;

    @Column(name = "fun_codigo", length = 32)
    private String funCodigo;

    @Column(name = "ten_codigo", length = 32)
    private String tenCodigo;

    @Column(name = "aor_auditado", nullable = false, length = 1)
    private String aorAuditado;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "aor_data", nullable = false)
    private Date aorData;

    @Column(name = "aor_ip", length = 45)
    private String aorIp;

    @Column(name = "aor_obs", nullable = false, length = 65535)
    private String aorObs;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "aor_data_auditoria")
    private Date aorDataAuditoria;

    @Column(name = "usu_codigo_auditor", length = 32)
    private String usuCodigoAuditor;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo_auditor", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuarioAuditor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ten_codigo", referencedColumnName = "ten_codigo", insertable = false, updatable = false)
    private TipoEntidade tipoEntidade;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tlo_codigo", referencedColumnName = "tlo_codigo", insertable = false, updatable = false)
    private TipoLog tipoLog;

    /**
     * Constructor
     */
    public AuditoriaOrg() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAorCodigo(Integer aorCodigo) {
        this.aorCodigo = aorCodigo;
    }

    public Integer getAorCodigo() {
        return aorCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setTloCodigo(String tloCodigo) {
        this.tloCodigo = tloCodigo;
    }

    public String getTloCodigo() {
        return tloCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setTenCodigo(String tenCodigo) {
        this.tenCodigo = tenCodigo;
    }

    public String getTenCodigo() {
        return tenCodigo;
    }

    public void setAorAuditado(String aorAuditado) {
        this.aorAuditado = aorAuditado;
    }

    public String getAorAuditado() {
        return aorAuditado;
    }

    public void setAorData(Date aorData) {
        this.aorData = aorData;
    }

    public Date getAorData() {
        return aorData;
    }

    public void setAorIp(String aorIp) {
        this.aorIp = aorIp;
    }

    public String getAorIp() {
        return aorIp;
    }

    public void setAorObs(String aorObs) {
        this.aorObs = aorObs;
    }

    public String getAorObs() {
        return aorObs;
    }

    public void setAorDataAuditoria(Date aorDataAuditoria) {
        this.aorDataAuditoria = aorDataAuditoria;
    }

    public Date getAorDataAuditoria() {
        return aorDataAuditoria;
    }

    public void setUsuCodigoAuditor(String usuCodigoAuditor) {
        this.usuCodigoAuditor = usuCodigoAuditor;
    }

    public String getUsuCodigoAuditor() {
        return usuCodigoAuditor;
    }

    //--- GETTERS FOR LINKS
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuarioAuditor(Usuario usuario) {
        usuarioAuditor = usuario;
        setUsuCodigoAuditor(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuarioAuditor() {
        return usuarioAuditor;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
    }

    public Orgao getOrgao() {
        return orgao;
    }

    public void setTipoEntidade(TipoEntidade tipoEntidade) {
        this.tipoEntidade = tipoEntidade;
        setTenCodigo(tipoEntidade != null ? tipoEntidade.getTenCodigo() : null);
    }

    public TipoEntidade getTipoEntidade() {
        return tipoEntidade;
    }

    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setTipoLog(TipoLog tipoLog) {
        this.tipoLog = tipoLog;
        setTloCodigo(tipoLog != null ? tipoLog.getTloCodigo() : null);
    }

    public TipoLog getTipoLog() {
        return tipoLog;
    }
}
