/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

/**
 * JPA entity class for "AutDesconto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_aut_desconto")
public class AutDesconto implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ade_codigo", nullable = false, length = 32)
    private String adeCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "sad_codigo", nullable = false, length = 32)
    private String sadCodigo;

    @Column(name = "mne_codigo", length = 32)
    private String mneCodigo;

    @Column(name = "vco_codigo", nullable = false, length = 32)
    private String vcoCodigo;

    @Column(name = "cor_codigo", length = 32)
    private String corCodigo;

    @Column(name = "rse_codigo", nullable = false, length = 32)
    private String rseCodigo;

    @Column(name = "cid_codigo", length = 32)
    private String cidCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data", nullable = false)
    private Date adeData;

    @Column(name = "ade_vlr", nullable = false)
    private BigDecimal adeVlr;

    @Column(name = "ade_prazo")
    private Integer adePrazo;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_ini", nullable = false)
    private Date adeAnoMesIni;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_fim")
    private Date adeAnoMesFim;

    @Column(name = "ade_identificador", nullable = false, length = 40)
    private String adeIdentificador;

    @Column(name = "ade_numero", nullable = false)
    private Long adeNumero;

    @Column(name = "ade_tipo_vlr", length = 1)
    private String adeTipoVlr;

    @Column(name = "ade_int_folha")
    private Short adeIntFolha;

    @Column(name = "ade_inc_margem")
    private Short adeIncMargem;

    @Column(name = "ade_prd_pagas")
    private Integer adePrdPagas;

    @Column(name = "ade_indice", length = 32)
    private String adeIndice;

    @Column(name = "ade_vlr_tac")
    private BigDecimal adeVlrTac;

    @Column(name = "ade_vlr_iof")
    private BigDecimal adeVlrIof;

    @Column(name = "ade_vlr_liquido")
    private BigDecimal adeVlrLiquido;

    @Column(name = "ade_vlr_mens_vinc")
    private BigDecimal adeVlrMensVinc;

    @Column(name = "ade_vlr_folha")
    private BigDecimal adeVlrFolha;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_ini_folha")
    private Date adeAnoMesIniFolha;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_fim_folha")
    private Date adeAnoMesFimFolha;

    @Column(name = "ade_indice_exp", length = 32)
    private String adeIndiceExp;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_ini_ref")
    private Date adeAnoMesIniRef;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ano_mes_fim_ref")
    private Date adeAnoMesFimRef;

    @Column(name = "ade_cod_reg", length = 1)
    private String adeCodReg;

    @Column(name = "ade_carencia_final")
    private Short adeCarenciaFinal;

    @Column(name = "ade_taxa_juros")
    private BigDecimal adeTaxaJuros;

    @Column(name = "ade_pode_confirmar", length = 1)
    private String adePodeConfirmar;

    @Column(name = "ade_paga", nullable = false, length = 1)
    private String adePaga;

    @Column(name = "ade_banco", length = 3)
    private String adeBanco;

    @Column(name = "ade_agencia", length = 30)
    private String adeAgencia;

    @Column(name = "ade_conta", length = 40)
    private String adeConta;

    @Column(name = "ade_agencia_dv", length = 2)
    private String adeAgenciaDv;

    @Column(name = "ade_conta_dv", length = 2)
    private String adeContaDv;

    @Column(name = "ade_vlr_devido")
    private BigDecimal adeVlrDevido;

    @Column(name = "ade_vlr_seg_prestamista")
    private BigDecimal adeVlrSegPrestamista;

    @Column(name = "ade_vlr_sdo_mov")
    private BigDecimal adeVlrSdoMov;

    @Column(name = "ade_vlr_sdo_ret")
    private BigDecimal adeVlrSdoRet;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_ref")
    private Date adeDataRef;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_hora_ocorrencia")
    private Date adeDataHoraOcorrencia;

    @Column(name = "ade_vlr_ref")
    private BigDecimal adeVlrRef;

    // Deveria ser Short, porém por compatibilidade, mantive em Integer
    @Column(name = "ade_carencia")
    private Integer adeCarencia;

    @Column(name = "ade_prazo_ref")
    private Integer adePrazoRef;

    @Column(name = "ade_prd_pagas_total")
    private Integer adePrdPagasTotal;

    @Column(name = "ade_tipo_taxa", length = 1)
    private String adeTipoTaxa;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_ult_conciliacao")
    private Date adeDataUltConciliacao;

    @Column(name = "ade_vlr_percentual")
    private BigDecimal adeVlrPercentual;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_confirmacao")
    private Date adeDataConfirmacao;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_deferimento")
    private Date adeDataDeferimento;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_exclusao")
    private Date adeDataExclusao;

    @Column(name = "ade_periodicidade", nullable = false, length = 1)
    private String adePeriodicidade;

    @Column(name = "ade_prazo_folha")
    private Integer adePrazoFolha;

    @Column(name = "ade_vlr_parcela_folha")
    private BigDecimal adeVlrParcelaFolha;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_status")
    private Date adeDataStatus;

    @Column(name = "ade_exportacao", nullable = false, length = 1)
    private String adeExportacao;

    @Column(name = "cbe_codigo", length = 32)
    private String cbeCodigo;

    @Column(name = "tla_codigo", length = 32)
    private String tlaCodigo;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_data_reativacao_automatica")
    private Date adeDataReativacaoAutomatica;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_notificacao_cse")
    private Date adeDataNotificacaoCse;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ade_data_liberacao_valor")
    private Date adeDataLiberacaoValor;

    @Temporal(TemporalType.DATE)
    @Column(name = "ade_ult_periodo_exportacao")
    private Date adeUltPeriodoExportacao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vco_codigo", referencedColumnName = "vco_codigo", insertable = false, updatable = false)
    private VerbaConvenio verbaConvenio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cbe_codigo", referencedColumnName = "cbe_codigo", insertable = false, updatable = false)
    private ContratoBeneficio contratoBeneficio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cid_codigo", referencedColumnName = "cid_codigo", insertable = false, updatable = false)
    private Cidade cidade;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tla_codigo", referencedColumnName = "tla_codigo", insertable = false, updatable = false)
    private TipoLancamento tipoLancamento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mne_codigo", referencedColumnName = "mne_codigo", insertable = false, updatable = false)
    private TipoMotivoNaoExportacao tipoMotivoNaoExportacao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sad_codigo", referencedColumnName = "sad_codigo", insertable = false, updatable = false)
    private StatusAutorizacaoDesconto statusAutorizacaoDesconto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cor_codigo", referencedColumnName = "cor_codigo", insertable = false, updatable = false)
    private Correspondente correspondente;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rse_codigo", referencedColumnName = "rse_codigo", insertable = false, updatable = false)
    private RegistroServidor registroServidor;


    @OneToMany(mappedBy = "autDesconto", targetEntity = DespesaIndividual.class)
    private Set<DespesaIndividual> despesaIndividualSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = OcorrenciaAutorizacao.class)
    private Set<OcorrenciaAutorizacao> ocorrenciaAutorizacaoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = SaldoDevedor.class)
    private Set<SaldoDevedor> saldoDevedorSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = IgnoraInconsistenciaAde.class)
    private Set<IgnoraInconsistenciaAde> ignoraInconsistenciaAdeSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = PropostaPagamentoDivida.class)
    private Set<PropostaPagamentoDivida> propostaPagamentoDividaSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = PropostaLeilaoSolicitacao.class)
    private Set<PropostaLeilaoSolicitacao> propostaLeilaoSolicitacaoSet;

    @OneToMany(mappedBy = "autDescontoByAdeCodigoOrigem", targetEntity = RelacionamentoAutorizacao.class)
    private Set<RelacionamentoAutorizacao> relacionamentoAutorizacaoByAdeCodigoOrigemSet;

    @OneToMany(mappedBy = "autDescontoByAdeCodigoDestino", targetEntity = RelacionamentoAutorizacao.class)
    private Set<RelacionamentoAutorizacao> relacionamentoAutorizacaoByAdeCodigoDestinoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = ParcelaDescontoPeriodo.class)
    private Set<ParcelaDescontoPeriodo> parcelaDescontoPeriodoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = ArquivoFaturamentoBen.class)
    private Set<ArquivoFaturamentoBen> arquivoFaturamentoBenSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = AnexoAutorizacaoDesconto.class)
    private Set<AnexoAutorizacaoDesconto> anexoAutorizacaoDescontoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = SolicitacaoAutorizacao.class)
    private Set<SolicitacaoAutorizacao> solicitacaoAutorizacaoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = CoeficienteDesconto.class)
    private Set<CoeficienteDesconto> coeficienteDescontoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = ParcelaDesconto.class)
    private Set<ParcelaDesconto> parcelaDescontoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = HistoricoStatusAde.class)
    private Set<HistoricoStatusAde> historicoStatusAdeSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = DadosAutorizacaoDesconto.class)
    private Set<DadosAutorizacaoDesconto> dadosAutorizacaoDescontoSet;

    @OneToMany(mappedBy = "autDesconto", targetEntity = OcorrenciaDadosAde.class)
    private Set<OcorrenciaDadosAde> ocorrenciaDadosAdeSet;

    @ManyToMany
    @JoinTable(name = "tb_param_servico_autorizacao", joinColumns = @JoinColumn(name = "ade_codigo"), inverseJoinColumns = @JoinColumn(name = "psc_codigo"))
    private Set<ParamSvcConsignataria> paramSvcConsignatariaSet;


    /**
     * Constructor
     */
    public AutDesconto() {
        super();
    }

    public AutDesconto(HtAutDesconto ade) {
        this();
        BeanUtils.copyProperties(ade, this);
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setAdeCodigo(String adeCodigo) {
        this.adeCodigo = adeCodigo;
    }

    public String getAdeCodigo() {
        return adeCodigo;
    }

    public void setSadCodigo(String sadCodigo) {
        this.sadCodigo = sadCodigo;
    }

    public String getSadCodigo() {
        return sadCodigo;
    }

    public void setMneCodigo(String mneCodigo) {
        this.mneCodigo = mneCodigo;
    }

    public String getMneCodigo() {
        return mneCodigo;
    }

    public void setVcoCodigo(String vcoCodigo) {
        this.vcoCodigo = vcoCodigo;
    }

    public String getVcoCodigo() {
        return vcoCodigo;
    }

    public void setCorCodigo(String corCodigo) {
        this.corCodigo = corCodigo;
    }

    public String getCorCodigo() {
        return corCodigo;
    }

    public void setRseCodigo(String rseCodigo) {
        this.rseCodigo = rseCodigo;
    }

    public String getRseCodigo() {
        return rseCodigo;
    }

    public void setCidCodigo(String cidCodigo) {
        this.cidCodigo = cidCodigo;
    }

    public String getCidCodigo() {
        return cidCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setAdeData(Date adeData) {
        this.adeData = adeData;
    }

    public Date getAdeData() {
        return adeData;
    }

    public void setAdeVlr(BigDecimal adeVlr) {
        this.adeVlr = adeVlr;
    }

    public BigDecimal getAdeVlr() {
        return adeVlr;
    }

    public void setAdePrazo(Integer adePrazo) {
        this.adePrazo = adePrazo;
    }

    public Integer getAdePrazo() {
        return adePrazo;
    }

    public void setAdeAnoMesIni(Date adeAnoMesIni) {
        this.adeAnoMesIni = adeAnoMesIni;
    }

    public Date getAdeAnoMesIni() {
        return adeAnoMesIni;
    }

    public void setAdeAnoMesFim(Date adeAnoMesFim) {
        this.adeAnoMesFim = adeAnoMesFim;
    }

    public Date getAdeAnoMesFim() {
        return adeAnoMesFim;
    }

    public void setAdeIdentificador(String adeIdentificador) {
        this.adeIdentificador = adeIdentificador;
    }

    public String getAdeIdentificador() {
        return adeIdentificador;
    }

    public void setAdeNumero(Long adeNumero) {
        this.adeNumero = adeNumero;
    }

    public Long getAdeNumero() {
        return adeNumero;
    }

    public void setAdeTipoVlr(String adeTipoVlr) {
        this.adeTipoVlr = adeTipoVlr;
    }

    public String getAdeTipoVlr() {
        return adeTipoVlr;
    }

    public void setAdeIntFolha(Short adeIntFolha) {
        this.adeIntFolha = adeIntFolha;
    }

    public Short getAdeIntFolha() {
        return adeIntFolha;
    }

    public void setAdeIncMargem(Short adeIncMargem) {
        this.adeIncMargem = adeIncMargem;
    }

    public Short getAdeIncMargem() {
        return adeIncMargem;
    }

    public void setAdePrdPagas(Integer adePrdPagas) {
        this.adePrdPagas = adePrdPagas;
    }

    public Integer getAdePrdPagas() {
        return adePrdPagas;
    }

    public void setAdeIndice(String adeIndice) {
        this.adeIndice = adeIndice;
    }

    public String getAdeIndice() {
        return adeIndice;
    }

    public void setAdeVlrTac(BigDecimal adeVlrTac) {
        this.adeVlrTac = adeVlrTac;
    }

    public BigDecimal getAdeVlrTac() {
        return adeVlrTac;
    }

    public void setAdeVlrIof(BigDecimal adeVlrIof) {
        this.adeVlrIof = adeVlrIof;
    }

    public BigDecimal getAdeVlrIof() {
        return adeVlrIof;
    }

    public void setAdeVlrLiquido(BigDecimal adeVlrLiquido) {
        this.adeVlrLiquido = adeVlrLiquido;
    }

    public BigDecimal getAdeVlrLiquido() {
        return adeVlrLiquido;
    }

    public void setAdeVlrMensVinc(BigDecimal adeVlrMensVinc) {
        this.adeVlrMensVinc = adeVlrMensVinc;
    }

    public BigDecimal getAdeVlrMensVinc() {
        return adeVlrMensVinc;
    }

    public void setAdeVlrFolha(BigDecimal adeVlrFolha) {
        this.adeVlrFolha = adeVlrFolha;
    }

    public BigDecimal getAdeVlrFolha() {
        return adeVlrFolha;
    }

    public void setAdeAnoMesIniFolha(Date adeAnoMesIniFolha) {
        this.adeAnoMesIniFolha = adeAnoMesIniFolha;
    }

    public Date getAdeAnoMesIniFolha() {
        return adeAnoMesIniFolha;
    }

    public void setAdeAnoMesFimFolha(Date adeAnoMesFimFolha) {
        this.adeAnoMesFimFolha = adeAnoMesFimFolha;
    }

    public Date getAdeAnoMesFimFolha() {
        return adeAnoMesFimFolha;
    }

    public void setAdeIndiceExp(String adeIndiceExp) {
        this.adeIndiceExp = adeIndiceExp;
    }

    public String getAdeIndiceExp() {
        return adeIndiceExp;
    }

    public void setAdeAnoMesIniRef(Date adeAnoMesIniRef) {
        this.adeAnoMesIniRef = adeAnoMesIniRef;
    }

    public Date getAdeAnoMesIniRef() {
        return adeAnoMesIniRef;
    }

    public void setAdeAnoMesFimRef(Date adeAnoMesFimRef) {
        this.adeAnoMesFimRef = adeAnoMesFimRef;
    }

    public Date getAdeAnoMesFimRef() {
        return adeAnoMesFimRef;
    }

    public void setAdeCodReg(String adeCodReg) {
        this.adeCodReg = adeCodReg;
    }

    public String getAdeCodReg() {
        return adeCodReg;
    }

    public void setAdeCarenciaFinal(Short adeCarenciaFinal) {
        this.adeCarenciaFinal = adeCarenciaFinal;
    }

    public Short getAdeCarenciaFinal() {
        return adeCarenciaFinal;
    }

    public void setAdeTaxaJuros(BigDecimal adeTaxaJuros) {
        this.adeTaxaJuros = adeTaxaJuros;
    }

    public BigDecimal getAdeTaxaJuros() {
        return adeTaxaJuros;
    }

    public void setAdePodeConfirmar(String adePodeConfirmar) {
        this.adePodeConfirmar = adePodeConfirmar;
    }

    public String getAdePodeConfirmar() {
        return adePodeConfirmar;
    }

    public void setAdePaga(String adePaga) {
        this.adePaga = adePaga;
    }

    public String getAdePaga() {
        return adePaga;
    }

    public void setAdeBanco(String adeBanco) {
        this.adeBanco = adeBanco;
    }

    public String getAdeBanco() {
        return adeBanco;
    }

    public void setAdeAgencia(String adeAgencia) {
        this.adeAgencia = adeAgencia;
    }

    public String getAdeAgencia() {
        return adeAgencia;
    }

    public void setAdeConta(String adeConta) {
        this.adeConta = adeConta;
    }

    public String getAdeConta() {
        return adeConta;
    }

    public void setAdeAgenciaDv(String adeAgenciaDv) {
        this.adeAgenciaDv = adeAgenciaDv;
    }

    public String getAdeAgenciaDv() {
        return adeAgenciaDv;
    }

    public void setAdeContaDv(String adeContaDv) {
        this.adeContaDv = adeContaDv;
    }

    public String getAdeContaDv() {
        return adeContaDv;
    }

    public void setAdeVlrDevido(BigDecimal adeVlrDevido) {
        this.adeVlrDevido = adeVlrDevido;
    }

    public BigDecimal getAdeVlrDevido() {
        return adeVlrDevido;
    }

    public void setAdeVlrSegPrestamista(BigDecimal adeVlrSegPrestamista) {
        this.adeVlrSegPrestamista = adeVlrSegPrestamista;
    }

    public BigDecimal getAdeVlrSegPrestamista() {
        return adeVlrSegPrestamista;
    }

    public void setAdeVlrSdoMov(BigDecimal adeVlrSdoMov) {
        this.adeVlrSdoMov = adeVlrSdoMov;
    }

    public BigDecimal getAdeVlrSdoMov() {
        return adeVlrSdoMov;
    }

    public void setAdeVlrSdoRet(BigDecimal adeVlrSdoRet) {
        this.adeVlrSdoRet = adeVlrSdoRet;
    }

    public BigDecimal getAdeVlrSdoRet() {
        return adeVlrSdoRet;
    }

    public void setAdeDataRef(Date adeDataRef) {
        this.adeDataRef = adeDataRef;
    }

    public Date getAdeDataRef() {
        return adeDataRef;
    }

    public void setAdeDataHoraOcorrencia(Date adeDataHoraOcorrencia) {
        this.adeDataHoraOcorrencia = adeDataHoraOcorrencia;
    }

    public Date getAdeDataHoraOcorrencia() {
        return adeDataHoraOcorrencia;
    }

    public void setAdeVlrRef(BigDecimal adeVlrRef) {
        this.adeVlrRef = adeVlrRef;
    }

    public BigDecimal getAdeVlrRef() {
        return adeVlrRef;
    }

    public void setAdeCarencia(Integer adeCarencia) {
        this.adeCarencia = adeCarencia;
    }

    public Integer getAdeCarencia() {
        return adeCarencia;
    }

    public void setAdePrazoRef(Integer adePrazoRef) {
        this.adePrazoRef = adePrazoRef;
    }

    public Integer getAdePrazoRef() {
        return adePrazoRef;
    }

    public void setAdePrdPagasTotal(Integer adePrdPagasTotal) {
        this.adePrdPagasTotal = adePrdPagasTotal;
    }

    public Integer getAdePrdPagasTotal() {
        return adePrdPagasTotal;
    }

    public void setAdeTipoTaxa(String adeTipoTaxa) {
        this.adeTipoTaxa = adeTipoTaxa;
    }

    public String getAdeTipoTaxa() {
        return adeTipoTaxa;
    }

    public void setAdeDataUltConciliacao(Date adeDataUltConciliacao) {
        this.adeDataUltConciliacao = adeDataUltConciliacao;
    }

    public Date getAdeDataUltConciliacao() {
        return adeDataUltConciliacao;
    }

    public void setAdeVlrPercentual(BigDecimal adeVlrPercentual) {
        this.adeVlrPercentual = adeVlrPercentual;
    }

    public BigDecimal getAdeVlrPercentual() {
        return adeVlrPercentual;
    }

    public void setAdeDataConfirmacao(Date adeDataConfirmacao) {
        this.adeDataConfirmacao = adeDataConfirmacao;
    }

    public Date getAdeDataConfirmacao() {
        return adeDataConfirmacao;
    }

    public void setAdeDataDeferimento(Date adeDataDeferimento) {
        this.adeDataDeferimento = adeDataDeferimento;
    }

    public Date getAdeDataDeferimento() {
        return adeDataDeferimento;
    }

    public void setAdeDataExclusao(Date adeDataExclusao) {
        this.adeDataExclusao = adeDataExclusao;
    }

    public Date getAdeDataExclusao() {
        return adeDataExclusao;
    }

    public void setAdePeriodicidade(String adePeriodicidade) {
        this.adePeriodicidade = adePeriodicidade;
    }

    public String getAdePeriodicidade() {
        return adePeriodicidade;
    }

    public void setAdePrazoFolha(Integer adePrazoFolha) {
        this.adePrazoFolha = adePrazoFolha;
    }

    public Integer getAdePrazoFolha() {
        return adePrazoFolha;
    }

    public void setAdeVlrParcelaFolha(BigDecimal adeVlrParcelaFolha) {
        this.adeVlrParcelaFolha = adeVlrParcelaFolha;
    }

    public BigDecimal getAdeVlrParcelaFolha() {
        return adeVlrParcelaFolha;
    }

    public void setAdeDataStatus(Date adeDataStatus) {
        this.adeDataStatus = adeDataStatus;
    }

    public Date getAdeDataStatus() {
        return adeDataStatus;
    }

    public void setAdeExportacao(String adeExportacao) {
        this.adeExportacao = adeExportacao;
    }

    public String getAdeExportacao() {
        return adeExportacao;
    }

    public void setCbeCodigo(String cbeCodigo) {
        this.cbeCodigo = cbeCodigo;
    }

    public String getCbeCodigo() {
        return cbeCodigo;
    }

    public void setTlaCodigo(String tlaCodigo) {
        this.tlaCodigo = tlaCodigo;
    }

    public String getTlaCodigo() {
        return tlaCodigo;
    }

    public void setAdeDataReativacaoAutomatica(Date adeDataReativacaoAutomatica) {
        this.adeDataReativacaoAutomatica = adeDataReativacaoAutomatica;
    }

    public Date getAdeDataReativacaoAutomatica() {
        return adeDataReativacaoAutomatica;
    }

    public Date getAdeDataNotificacaoCse() {
        return adeDataNotificacaoCse;
    }

    public void setAdeDataNotificacaoCse(Date adeDataNotificacaoCse) {
        this.adeDataNotificacaoCse = adeDataNotificacaoCse;
    }

    public Date getAdeDataLiberacaoValor() {
        return adeDataLiberacaoValor;
    }

    public void setAdeDataLiberacaoValor(Date adeDataLiberacaoValor) {
        this.adeDataLiberacaoValor = adeDataLiberacaoValor;
    }

    public Date getAdeUltPeriodoExportacao() {
        return adeUltPeriodoExportacao;
    }

    public void setAdeUltPeriodoExportacao(Date adeUltPeriodoExportacao) {
        this.adeUltPeriodoExportacao = adeUltPeriodoExportacao;
    }

    //--- GETTERS FOR LINKS
    public Set<DespesaIndividual> getDespesaIndividualSet() {
        return despesaIndividualSet;
    }

    public void setVerbaConvenio(VerbaConvenio verbaConvenio) {
        this.verbaConvenio = verbaConvenio;
        setVcoCodigo(verbaConvenio != null ? verbaConvenio.getVcoCodigo() : null);
    }

    public VerbaConvenio getVerbaConvenio() {
        return verbaConvenio;
    }

    public Set<OcorrenciaAutorizacao> getOcorrenciaAutorizacaoSet() {
        return ocorrenciaAutorizacaoSet;
    }

    public void setContratoBeneficio(ContratoBeneficio contratoBeneficio) {
        this.contratoBeneficio = contratoBeneficio;
        setCbeCodigo(contratoBeneficio != null ? contratoBeneficio.getCbeCodigo() : null);
    }

    public ContratoBeneficio getContratoBeneficio() {
        return contratoBeneficio;
    }

    public Set<SaldoDevedor> getSaldoDevedorSet() {
        return saldoDevedorSet;
    }

    public Set<IgnoraInconsistenciaAde> getIgnoraInconsistenciaAdeSet() {
        return ignoraInconsistenciaAdeSet;
    }

    public Set<RelacionamentoAutorizacao> getRelacionamentoAutorizacaoByAdeCodigoOrigemSet() {
        return relacionamentoAutorizacaoByAdeCodigoDestinoSet;
    }

    public Set<RelacionamentoAutorizacao> getRelacionamentoAutorizacaoByAdeCodigoDestinoSet() {
        return relacionamentoAutorizacaoByAdeCodigoDestinoSet;
    }

    public Set<PropostaPagamentoDivida> getPropostaPagamentoDividaSet() {
        return propostaPagamentoDividaSet;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
        setCidCodigo(cidade != null ? cidade.getCidCodigo() : null);
    }

    public Cidade getCidade() {
        return cidade;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public Set<PropostaLeilaoSolicitacao> getPropostaLeilaoSolicitacaoSet() {
        return propostaLeilaoSolicitacaoSet;
    }

    public Set<ParcelaDescontoPeriodo> getParcelaDescontoPeriodoSet() {
        return parcelaDescontoPeriodoSet;
    }

    public Set<ArquivoFaturamentoBen> getArquivoFaturamentoBenSet() {
        return arquivoFaturamentoBenSet;
    }

    public Set<AnexoAutorizacaoDesconto> getAnexoAutorizacaoDescontoSet() {
        return anexoAutorizacaoDescontoSet;
    }

    public void setTipoLancamento(TipoLancamento tipoLancamento) {
        this.tipoLancamento = tipoLancamento;
        setTlaCodigo(tipoLancamento != null ? tipoLancamento.getTlaCodigo() : null);
    }

    public TipoLancamento getTipoLancamento() {
        return tipoLancamento;
    }

    public Set<SolicitacaoAutorizacao> getSolicitacaoAutorizacaoSet() {
        return solicitacaoAutorizacaoSet;
    }

    public Set<CoeficienteDesconto> getCoeficienteDescontoSet() {
        return coeficienteDescontoSet;
    }

    public void setTipoMotivoNaoExportacao(TipoMotivoNaoExportacao tipoMotivoNaoExportacao) {
        this.tipoMotivoNaoExportacao = tipoMotivoNaoExportacao;
        setMneCodigo(tipoMotivoNaoExportacao != null ? tipoMotivoNaoExportacao.getMneCodigo() : null);
    }

    public TipoMotivoNaoExportacao getTipoMotivoNaoExportacao() {
        return tipoMotivoNaoExportacao;
    }

    public Set<ParcelaDesconto> getParcelaDescontoSet() {
        return parcelaDescontoSet;
    }

    public Set<HistoricoStatusAde> getHistoricoStatusAdeSet() {
        return historicoStatusAdeSet;
    }

    public void setStatusAutorizacaoDesconto(StatusAutorizacaoDesconto statusAutorizacaoDesconto) {
        this.statusAutorizacaoDesconto = statusAutorizacaoDesconto;
        setSadCodigo(statusAutorizacaoDesconto != null ? statusAutorizacaoDesconto.getSadCodigo() : null);
    }

    public StatusAutorizacaoDesconto getStatusAutorizacaoDesconto() {
        return statusAutorizacaoDesconto;
    }

    public Set<DadosAutorizacaoDesconto> getDadosAutorizacaoDescontoSet() {
        return dadosAutorizacaoDescontoSet;
    }

    public Set<OcorrenciaDadosAde> getOcorrenciaDadosAdeSet() {
        return ocorrenciaDadosAdeSet;
    }

    public void setCorrespondente(Correspondente correspondente) {
        this.correspondente = correspondente;
        setCorCodigo(correspondente != null ? correspondente.getCorCodigo() : null);
    }

    public Correspondente getCorrespondente() {
        return correspondente;
    }

    public void setRegistroServidor(RegistroServidor registroServidor) {
        this.registroServidor = registroServidor;
        setRseCodigo(registroServidor != null ? registroServidor.getRseCodigo() : null);
    }

    public RegistroServidor getRegistroServidor() {
        return registroServidor;
    }

    public Set<ParamSvcConsignataria> getParamSvcConsignatariaSet() {
        return paramSvcConsignatariaSet;
    }
}
