/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "BaseCalcRegistroServidor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_base_calc_registro_servidor")
@IdClass(BaseCalcRegistroServidorId.class)
public class BaseCalcRegistroServidor implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tbc_codigo", nullable = false, length = 32)
    private String tbcCodigo;

    @Id
    @Column(name = "rse_codigo", nullable = false, length = 32)
    private String rseCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "bcs_valor", nullable = false)
    private BigDecimal bcsValor;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tbc_codigo", referencedColumnName = "tbc_codigo", insertable = false, updatable = false)
    private TipoBaseCalculo tipoBaseCalculo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rse_codigo", referencedColumnName = "rse_codigo", insertable = false, updatable = false)
    private RegistroServidor registroServidor;

    /**
     * Constructor
     */
    public BaseCalcRegistroServidor() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTbcCodigo(String tbcCodigo) {
        this.tbcCodigo = tbcCodigo;
    }

    public String getTbcCodigo() {
        return tbcCodigo;
    }

    public void setRseCodigo(String rseCodigo) {
        this.rseCodigo = rseCodigo;
    }

    public String getRseCodigo() {
        return rseCodigo;
    }

    public void setBcsValor(BigDecimal bcsValor) {
        this.bcsValor = bcsValor;
    }

    public BigDecimal getBcsValor() {
        return bcsValor;
    }

    //--- GETTERS FOR LINKS
    public void setTipoBaseCalculo(TipoBaseCalculo tipoBaseCalculo) {
        this.tipoBaseCalculo = tipoBaseCalculo;
        setTbcCodigo(tipoBaseCalculo != null ? tipoBaseCalculo.getTbcCodigo() : null);
    }

    public TipoBaseCalculo getTipoBaseCalculo() {
        return tipoBaseCalculo;
    }

    public void setRegistroServidor(RegistroServidor registroServidor) {
        this.registroServidor = registroServidor;
        setRseCodigo(registroServidor != null ? registroServidor.getRseCodigo() : null);
    }

    public RegistroServidor getRegistroServidor() {
        return registroServidor;
    }

    public void setId(BaseCalcRegistroServidorId id) {
        setRseCodigo(id != null ? id.getRseCodigo() : null);
        setTbcCodigo(id != null ? id.getTbcCodigo() : null);
    }
}
