/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "BloqueioRepasseFuncao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_bloqueio_repasse_funcao")
@IdClass(BloqueioRepasseFuncaoId.class)
public class BloqueioRepasseFuncao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "pap_codigo_origem", nullable = false, length = 32)
    private String papCodigoOrigem;

    @Id
    @Column(name = "pap_codigo_destino", nullable = false, length = 32)
    private String papCodigoDestino;

    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pap_codigo_origem", referencedColumnName = "pap_codigo", insertable = false, updatable = false)
    private Papel papelOrigem;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pap_codigo_destino", referencedColumnName = "pap_codigo", insertable = false, updatable = false)
    private Papel papelDestino;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    /**
     * Constructor
     */
    public BloqueioRepasseFuncao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setPapCodigoOrigem(String papCodigoOrigem) {
        this.papCodigoOrigem = papCodigoOrigem;
    }

    public String getPapCodigoOrigem() {
        return papCodigoOrigem;
    }

    public void setPapCodigoDestino(String papCodigoDestino) {
        this.papCodigoDestino = papCodigoDestino;
    }

    public String getPapCodigoDestino() {
        return papCodigoDestino;
    }

    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setPapelOrigem(Papel papel) {
        papelOrigem = papel;
        setPapCodigoOrigem(papel != null ? papel.getPapCodigo() : null);
    }

    public Papel getPapelOrigem() {
        return papelOrigem;
    }

    public void setPapelDestino(Papel papel) {
        papelDestino = papel;
        setPapCodigoDestino(papel != null ? papel.getPapCodigo() : null);
    }

    public Papel getPapelDestino() {
        return papelDestino;
    }

    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

}
