/*
 * Created on 2021-12-30 ( 18:15:56 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "CalculoBeneficio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_calculo_beneficio")
public class CalculoBeneficio implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "clb_codigo", nullable = false, length = 32)
    private String clbCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tib_codigo", length = 32)
    private String tibCodigo;

    @Column(name = "org_codigo", length = 32)
    private String orgCodigo;

    @Column(name = "ben_codigo", nullable = false, length = 32)
    private String benCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "clb_vigencia_ini")
    private Date clbVigenciaIni;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "clb_vigencia_fim")
    private Date clbVigenciaFim;

    @Column(name = "clb_valor_mensalidade", nullable = false)
    private BigDecimal clbValorMensalidade;

    @Column(name = "clb_valor_subsidio")
    private BigDecimal clbValorSubsidio;

    @Column(name = "clb_faixa_etaria_ini")
    private Short clbFaixaEtariaIni;

    @Column(name = "clb_faixa_etaria_fim")
    private Short clbFaixaEtariaFim;

    @Column(name = "clb_faixa_salarial_ini")
    private BigDecimal clbFaixaSalarialIni;

    @Column(name = "clb_faixa_salarial_fim")
    private BigDecimal clbFaixaSalarialFim;

    @Column(name = "grp_codigo", length = 32)
    private String grpCodigo;

    @Column(name = "mde_codigo", length = 32)
    private String mdeCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mde_codigo", referencedColumnName = "mde_codigo", insertable = false, updatable = false)
    private MotivoDependencia motivoDependencia;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ben_codigo", referencedColumnName = "ben_codigo", insertable = false, updatable = false)
    private Beneficio beneficio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tib_codigo", referencedColumnName = "tib_codigo", insertable = false, updatable = false)
    private TipoBeneficiario tipoBeneficiario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "grp_codigo", referencedColumnName = "grp_codigo", insertable = false, updatable = false)
    private GrauParentesco grauParentesco;

    /**
     * Constructor
     */
    public CalculoBeneficio() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setClbCodigo(String clbCodigo) {
        this.clbCodigo = clbCodigo;
    }

    public String getClbCodigo() {
        return clbCodigo;
    }

    public void setTibCodigo(String tibCodigo) {
        this.tibCodigo = tibCodigo;
    }

    public String getTibCodigo() {
        return tibCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setBenCodigo(String benCodigo) {
        this.benCodigo = benCodigo;
    }

    public String getBenCodigo() {
        return benCodigo;
    }

    public void setClbVigenciaIni(Date clbVigenciaIni) {
        this.clbVigenciaIni = clbVigenciaIni;
    }

    public Date getClbVigenciaIni() {
        return clbVigenciaIni;
    }

    public void setClbVigenciaFim(Date clbVigenciaFim) {
        this.clbVigenciaFim = clbVigenciaFim;
    }

    public Date getClbVigenciaFim() {
        return clbVigenciaFim;
    }

    public void setClbValorMensalidade(BigDecimal clbValorMensalidade) {
        this.clbValorMensalidade = clbValorMensalidade;
    }

    public BigDecimal getClbValorMensalidade() {
        return clbValorMensalidade;
    }

    public void setClbValorSubsidio(BigDecimal clbValorSubsidio) {
        this.clbValorSubsidio = clbValorSubsidio;
    }

    public BigDecimal getClbValorSubsidio() {
        return clbValorSubsidio;
    }

    public void setClbFaixaEtariaIni(Short clbFaixaEtariaIni) {
        this.clbFaixaEtariaIni = clbFaixaEtariaIni;
    }

    public Short getClbFaixaEtariaIni() {
        return clbFaixaEtariaIni;
    }

    public void setClbFaixaEtariaFim(Short clbFaixaEtariaFim) {
        this.clbFaixaEtariaFim = clbFaixaEtariaFim;
    }

    public Short getClbFaixaEtariaFim() {
        return clbFaixaEtariaFim;
    }

    public void setClbFaixaSalarialIni(BigDecimal clbFaixaSalarialIni) {
        this.clbFaixaSalarialIni = clbFaixaSalarialIni;
    }

    public BigDecimal getClbFaixaSalarialIni() {
        return clbFaixaSalarialIni;
    }

    public void setClbFaixaSalarialFim(BigDecimal clbFaixaSalarialFim) {
        this.clbFaixaSalarialFim = clbFaixaSalarialFim;
    }

    public BigDecimal getClbFaixaSalarialFim() {
        return clbFaixaSalarialFim;
    }

    public void setGrpCodigo(String grpCodigo) {
        this.grpCodigo = grpCodigo;
    }

    public String getGrpCodigo() {
        return grpCodigo;
    }

    public void setMdeCodigo(String mdeCodigo) {
        this.mdeCodigo = mdeCodigo;
    }

    public String getMdeCodigo() {
        return mdeCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setMotivoDependencia(MotivoDependencia motivoDependencia) {
        this.motivoDependencia = motivoDependencia;
        if (motivoDependencia != null) {
            setMdeCodigo(motivoDependencia != null ? motivoDependencia.getMdeCodigo() : null);
        }
    }

    public MotivoDependencia getMotivoDependencia() {
        return motivoDependencia;
    }

    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
        if (beneficio != null) {
            setBenCodigo(beneficio != null ? beneficio.getBenCodigo() : null);
        }
    }

    public Beneficio getBeneficio() {
        return beneficio;
    }

    public void setTipoBeneficiario(TipoBeneficiario tipoBeneficiario) {
        this.tipoBeneficiario = tipoBeneficiario;
        if (tipoBeneficiario != null) {
            setTibCodigo(tipoBeneficiario != null ? tipoBeneficiario.getTibCodigo() : null);
        }
    }

    public TipoBeneficiario getTipoBeneficiario() {
        return tipoBeneficiario;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        if (orgao != null) {
            setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
        }
    }

    public Orgao getOrgao() {
        return orgao;
    }

    public void setGrauParentesco(GrauParentesco grauParentesco) {
        this.grauParentesco = grauParentesco;
        if (grauParentesco != null) {
            setGrpCodigo(grauParentesco != null ? grauParentesco.getGrpCodigo() : null);
        }
    }

    public GrauParentesco getGrauParentesco() {
        return grauParentesco;
    }
}
