/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Cep"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_cep")
public class Cep implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "cep_codigo", nullable = false, length = 8)
    private String cepCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "cep_logradouro", nullable = false, length = 255)
    private String cepLogradouro;

    @Column(name = "cep_bairro", nullable = false, length = 100)
    private String cepBairro;

    @Column(name = "cep_cidade", nullable = false, length = 100)
    private String cepCidade;

    @Column(name = "cep_estado", nullable = false, length = 100)
    private String cepEstado;

    @Column(name = "cep_estado_sigla", nullable = false, length = 5)
    private String cepEstadoSigla;

    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Cep() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setCepCodigo(String cepCodigo) {
        this.cepCodigo = cepCodigo;
    }

    public String getCepCodigo() {
        return this.cepCodigo;
    }

    public void setCepLogradouro(String cepLogradouro) {
        this.cepLogradouro = cepLogradouro;
    }

    public String getCepLogradouro() {
        return this.cepLogradouro;
    }

    public void setCepBairro(String cepBairro) {
        this.cepBairro = cepBairro;
    }

    public String getCepBairro() {
        return this.cepBairro;
    }

    public void setCepCidade(String cepCidade) {
        this.cepCidade = cepCidade;
    }

    public String getCepCidade() {
        return this.cepCidade;
    }

    public void setCepEstado(String cepEstado) {
        this.cepEstado = cepEstado;
    }

    public String getCepEstado() {
        return this.cepEstado;
    }

    public void setCepEstadoSigla(String cepEstadoSigla) {
        this.cepEstadoSigla = cepEstadoSigla;
    }

    public String getCepEstadoSigla() {
        return this.cepEstadoSigla;
    }

    //--- GETTERS FOR LINKS
}
