/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "ComunicacaoOrg"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_comunicacao_org")
@IdClass(ComunicacaoOrgId.class)
public class ComunicacaoOrg implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "cmn_codigo", nullable = false, length = 32)
    private String cmnCodigo;

    @Id
    @Column(name = "org_codigo", nullable = false, length = 32)
    private String orgCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "cmo_destinatario", nullable = false, length = 1)
    private String cmoDestinatario;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cmn_codigo", referencedColumnName = "cmn_codigo", insertable = false, updatable = false)
    private Comunicacao comunicacao;

    /**
     * Constructor
     */
    public ComunicacaoOrg() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setCmnCodigo(String cmnCodigo) {
        this.cmnCodigo = cmnCodigo;
    }

    public String getCmnCodigo() {
        return cmnCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setCmoDestinatario(String cmoDestinatario) {
        this.cmoDestinatario = cmoDestinatario;
    }

    public String getCmoDestinatario() {
        return cmoDestinatario;
    }

    //--- GETTERS FOR LINKS
    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
    }

    public Orgao getOrgao() {
        return orgao;
    }

    public void setComunicacao(Comunicacao comunicacao) {
        this.comunicacao = comunicacao;
        setCmnCodigo(comunicacao != null ? comunicacao.getCmnCodigo() : null);
    }

    public Comunicacao getComunicacao() {
        return comunicacao;
    }

    public void setId(ComunicacaoOrgId id) {
        setCmnCodigo(id != null ? id.getCmnCodigo() : null);
        setOrgCodigo(id != null ? id.getOrgCodigo() : null);
    }
}
