/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import com.zetra.econsig.values.CodedValues;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "Consignante"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_consignante")
public class Consignante implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "cse_identificador", nullable = false, length = 40)
    private String cseIdentificador;

    @Column(name = "cse_nome", nullable = false, length = 100)
    private String cseNome;

    @Column(name = "cse_cnpj", length = 19)
    private String cseCnpj;

    @Column(name = "cse_email", length = 65535)
    private String cseEmail;

    @Column(name = "cse_responsavel", length = 100)
    private String cseResponsavel;

    @Column(name = "cse_resp_cargo", length = 100)
    private String cseRespCargo;

    @Column(name = "cse_resp_telefone", length = 100)
    private String cseRespTelefone;

    @Column(name = "cse_responsavel_2", length = 100)
    private String cseResponsavel2;

    @Column(name = "cse_resp_cargo_2", length = 100)
    private String cseRespCargo2;

    @Column(name = "cse_resp_telefone_2", length = 100)
    private String cseRespTelefone2;

    @Column(name = "cse_responsavel_3", length = 100)
    private String cseResponsavel3;

    @Column(name = "cse_resp_cargo_3", length = 100)
    private String cseRespCargo3;

    @Column(name = "cse_resp_telefone_3", length = 100)
    private String cseRespTelefone3;

    @Column(name = "cse_logradouro", length = 100)
    private String cseLogradouro;

    @Column(name = "cse_nro")
    private Integer cseNro;

    @Column(name = "cse_compl", length = 40)
    private String cseCompl;

    @Column(name = "cse_bairro", length = 40)
    private String cseBairro;

    @Column(name = "cse_cidade", length = 40)
    private String cseCidade;

    @Column(name = "cse_uf", length = 5)
    private String cseUf;

    @Column(name = "cse_cep", length = 10)
    private String cseCep;

    @Column(name = "cse_tel", length = 100)
    private String cseTel;

    @Column(name = "cse_fax", length = 100)
    private String cseFax;

    @Column(name = "cse_ativo")
    private Short cseAtivo;

    @Column(name = "cse_licenca", length = 65535)
    private String cseLicenca;

    @Column(name = "cse_ip_acesso", length = 65535)
    private String cseIpAcesso;

    @Column(name = "cse_ddns_acesso", length = 65535)
    private String cseDdnsAcesso;

    @Column(name = "cse_identificador_interno", length = 8)
    private String cseIdentificadorInterno;

    @Column(name = "cse_email_folha", length = 65535)
    private String cseEmailFolha;

    @Column(name = "cse_certificado_centralizador", length = 65535)
    private String cseCertificadoCentralizador;

    @Temporal(TemporalType.DATE)
    @Column(name = "cse_data_cobranca")
    private Date cseDataCobranca;

    @Column(name = "cse_folha", length = 40)
    private String cseFolha;

    @Column(name = "cse_email_validar_servidor", length = 65535)
    private String cseEmailValidarServidor;

    @Column(name = "cse_projeto_inadimplencia", length = 1)
    private String cseProjetoInadimplencia;

    @Column(name = "tce_codigo", length = 32)
    private String tceCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cse_data_atualizacao_cadastral")
    private Date cseDataAtualizacaoCadastral;

    @Column(name = "cse_certificado_central_mobile", length = 65535)
    private String cseCertificadoCentralMobile;

    @Column(name = "cse_sistema_folha", length = 100)
    private String cseSistemaFolha;

    @Column(name = "bco_codigo")
    private Short bcoCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "consignante", targetEntity = OcorrenciaParamSistCse.class)
    private Set<OcorrenciaParamSistCse> ocorrenciaParamSistCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = PerfilSup.class)
    private Set<PerfilSup> perfilSupSet;

    @OneToMany(mappedBy = "consignante", targetEntity = Estabelecimento.class)
    private Set<Estabelecimento> estabelecimentoSet;

    @OneToMany(mappedBy = "consignante", targetEntity = CalendarioBeneficioCse.class)
    private Set<CalendarioBeneficioCse> calendarioBeneficioCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = ParamSistConsignante.class)
    private Set<ParamSistConsignante> paramSistConsignanteSet;

    @OneToMany(mappedBy = "consignante", targetEntity = ParamTarifConsignante.class)
    private Set<ParamTarifConsignante> paramTarifConsignanteSet;

    @OneToMany(mappedBy = "consignante", targetEntity = ComunicacaoCse.class)
    private Set<ComunicacaoCse> comunicacaoCseSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tce_codigo", referencedColumnName = "tce_codigo", insertable = false, updatable = false)
    private TipoConsignante tipoConsignante;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bco_codigo", referencedColumnName = "bco_codigo", insertable = false, updatable = false)
    private Banco banco;

    @OneToMany(mappedBy = "consignante", targetEntity = OcorrenciaConsignante.class)
    private Set<OcorrenciaConsignante> ocorrenciaConsignanteSet;

    @OneToMany(mappedBy = "consignante", targetEntity = ParamValidacaoArqCse.class)
    private Set<ParamValidacaoArqCse> paramValidacaoArqCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = CalendarioFolhaCse.class)
    private Set<CalendarioFolhaCse> calendarioFolhaCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = ParamSvcConsignante.class)
    private Set<ParamSvcConsignante> paramSvcConsignanteSet;

    @OneToMany(mappedBy = "consignante", targetEntity = PerfilCse.class)
    private Set<PerfilCse> perfilCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = UsuarioCse.class)
    private Set<UsuarioCse> usuarioCseSet;

    @OneToMany(mappedBy = "consignante", targetEntity = UsuarioSup.class)
    private Set<UsuarioSup> usuarioSupSet;

    @OneToMany(mappedBy = "consignante", targetEntity = DestinatarioEmailCse.class)
    private Set<DestinatarioEmailCse> destinatarioEmailCseSet;

    /**
     * Constructor
     */
    public Consignante() {
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    public void setCseIdentificador(String cseIdentificador) {
        this.cseIdentificador = cseIdentificador;
    }

    public String getCseIdentificador() {
        return cseIdentificador;
    }

    public void setCseNome(String cseNome) {
        this.cseNome = cseNome;
    }

    public String getCseNome() {
        return cseNome;
    }

    public void setCseCnpj(String cseCnpj) {
        this.cseCnpj = cseCnpj;
    }

    public String getCseCnpj() {
        return cseCnpj;
    }

    public void setCseEmail(String cseEmail) {
        this.cseEmail = cseEmail;
    }

    public String getCseEmail() {
        return cseEmail;
    }

    public void setCseResponsavel(String cseResponsavel) {
        this.cseResponsavel = cseResponsavel;
    }

    public String getCseResponsavel() {
        return cseResponsavel;
    }

    public void setCseRespCargo(String cseRespCargo) {
        this.cseRespCargo = cseRespCargo;
    }

    public String getCseRespCargo() {
        return cseRespCargo;
    }

    public void setCseRespTelefone(String cseRespTelefone) {
        this.cseRespTelefone = cseRespTelefone;
    }

    public String getCseRespTelefone() {
        return cseRespTelefone;
    }

    public void setCseResponsavel2(String cseResponsavel2) {
        this.cseResponsavel2 = cseResponsavel2;
    }

    public String getCseResponsavel2() {
        return cseResponsavel2;
    }

    public void setCseRespCargo2(String cseRespCargo2) {
        this.cseRespCargo2 = cseRespCargo2;
    }

    public String getCseRespCargo2() {
        return cseRespCargo2;
    }

    public void setCseRespTelefone2(String cseRespTelefone2) {
        this.cseRespTelefone2 = cseRespTelefone2;
    }

    public String getCseRespTelefone2() {
        return cseRespTelefone2;
    }

    public void setCseResponsavel3(String cseResponsavel3) {
        this.cseResponsavel3 = cseResponsavel3;
    }

    public String getCseResponsavel3() {
        return cseResponsavel3;
    }

    public void setCseRespCargo3(String cseRespCargo3) {
        this.cseRespCargo3 = cseRespCargo3;
    }

    public String getCseRespCargo3() {
        return cseRespCargo3;
    }

    public void setCseRespTelefone3(String cseRespTelefone3) {
        this.cseRespTelefone3 = cseRespTelefone3;
    }

    public String getCseRespTelefone3() {
        return cseRespTelefone3;
    }

    public void setCseLogradouro(String cseLogradouro) {
        this.cseLogradouro = cseLogradouro;
    }

    public String getCseLogradouro() {
        return cseLogradouro;
    }

    public void setCseNro(Integer cseNro) {
        this.cseNro = cseNro;
    }

    public Integer getCseNro() {
        return cseNro;
    }

    public void setCseCompl(String cseCompl) {
        this.cseCompl = cseCompl;
    }

    public String getCseCompl() {
        return cseCompl;
    }

    public void setCseBairro(String cseBairro) {
        this.cseBairro = cseBairro;
    }

    public String getCseBairro() {
        return cseBairro;
    }

    public void setCseCidade(String cseCidade) {
        this.cseCidade = cseCidade;
    }

    public String getCseCidade() {
        return cseCidade;
    }

    public void setCseUf(String cseUf) {
        this.cseUf = cseUf;
    }

    public String getCseUf() {
        return cseUf;
    }

    public void setCseCep(String cseCep) {
        this.cseCep = cseCep;
    }

    public String getCseCep() {
        return cseCep;
    }

    public void setCseTel(String cseTel) {
        this.cseTel = cseTel;
    }

    public String getCseTel() {
        return cseTel;
    }

    public void setCseFax(String cseFax) {
        this.cseFax = cseFax;
    }

    public String getCseFax() {
        return cseFax;
    }

    public void setCseAtivo(Short cseAtivo) {
        this.cseAtivo = cseAtivo;
    }

    public Short getCseAtivo() {
        return cseAtivo;
    }

    public void setCseLicenca(String cseLicenca) {
        this.cseLicenca = cseLicenca;
    }

    public String getCseLicenca() {
        return cseLicenca;
    }

    public void setCseIpAcesso(String cseIpAcesso) {
        this.cseIpAcesso = cseIpAcesso;
    }

    public String getCseIpAcesso() {
        return cseIpAcesso;
    }

    public void setCseDdnsAcesso(String cseDdnsAcesso) {
        this.cseDdnsAcesso = cseDdnsAcesso;
    }

    public String getCseDdnsAcesso() {
        return cseDdnsAcesso;
    }

    public void setCseIdentificadorInterno(String cseIdentificadorInterno) {
        this.cseIdentificadorInterno = cseIdentificadorInterno;
    }

    public String getCseIdentificadorInterno() {
        return cseIdentificadorInterno;
    }

    public void setCseEmailFolha(String cseEmailFolha) {
        this.cseEmailFolha = cseEmailFolha;
    }

    public String getCseEmailFolha() {
        return cseEmailFolha;
    }

    public void setCseCertificadoCentralizador(String cseCertificadoCentralizador) {
        this.cseCertificadoCentralizador = cseCertificadoCentralizador;
    }

    public String getCseCertificadoCentralizador() {
        return cseCertificadoCentralizador;
    }

    public void setCseDataCobranca(Date cseDataCobranca) {
        this.cseDataCobranca = cseDataCobranca;
    }

    public Date getCseDataCobranca() {
        return cseDataCobranca;
    }

    public void setCseFolha(String cseFolha) {
        this.cseFolha = cseFolha;
    }

    public String getCseFolha() {
        return cseFolha;
    }

    public void setCseEmailValidarServidor(String cseEmailValidarServidor) {
        this.cseEmailValidarServidor = cseEmailValidarServidor;
    }

    public String getCseEmailValidarServidor() {
        return cseEmailValidarServidor;
    }

    public void setCseProjetoInadimplencia(String cseProjetoInadimplencia) {
        this.cseProjetoInadimplencia = cseProjetoInadimplencia;
    }

    public String getCseProjetoInadimplencia() {
        return cseProjetoInadimplencia;
    }

    public void setTceCodigo(String tceCodigo) {
        this.tceCodigo = tceCodigo;
    }

    public String getTceCodigo() {
        return tceCodigo;
    }

    public void setCseDataAtualizacaoCadastral(Date cseDataAtualizacaoCadastral) {
        this.cseDataAtualizacaoCadastral = cseDataAtualizacaoCadastral;
    }

    public Date getCseDataAtualizacaoCadastral() {
        return cseDataAtualizacaoCadastral;
    }

    public void setCseCertificadoCentralMobile(String cseCertificadoCentralMobile) {
        this.cseCertificadoCentralMobile = cseCertificadoCentralMobile;
    }

    public String getCseCertificadoCentralMobile() {
        return cseCertificadoCentralMobile;
    }

    public void setCseSistemaFolha(String cseSistemaFolha) {
        this.cseSistemaFolha = cseSistemaFolha;
    }

    public String getCseSistemaFolha() {
        return cseSistemaFolha;
    }

    public void setBcoCodigo(Short bcoCodigo) {
        this.bcoCodigo = bcoCodigo;
    }

    public Short getBcoCodigo() {
        return bcoCodigo;
    }

    //--- GETTERS FOR LINKS
    public Set<OcorrenciaParamSistCse> getOcorrenciaParamSistCseSet() {
        return ocorrenciaParamSistCseSet;
    }

    public Set<PerfilSup> getPerfilSupSet() {
        return perfilSupSet;
    }

    public Set<Estabelecimento> getEstabelecimentoSet() {
        return estabelecimentoSet;
    }

    public Set<CalendarioBeneficioCse> getCalendarioBeneficioCseSet() {
        return calendarioBeneficioCseSet;
    }

    public Set<ParamSistConsignante> getParamSistConsignanteSet() {
        return paramSistConsignanteSet;
    }

    public Set<ParamTarifConsignante> getParamTarifConsignanteSet() {
        return paramTarifConsignanteSet;
    }

    public Set<ComunicacaoCse> getComunicacaoCseSet() {
        return comunicacaoCseSet;
    }

    public Set<DestinatarioEmailCse> getDestinatarioEmailCseSet() {
        return destinatarioEmailCseSet;
    }

    public void setTipoConsignante(TipoConsignante tipoConsignante) {
        this.tipoConsignante = tipoConsignante;
        setTceCodigo(tipoConsignante != null ? tipoConsignante.getTceCodigo() : null);
    }

    public TipoConsignante getTipoConsignante() {
        return tipoConsignante;
    }

    public void setBanco(Banco banco) {
        this.banco = banco;
        setBcoCodigo(banco != null ? banco.getBcoCodigo() : null);
    }

    public Banco getBanco() {
        return banco;
    }

    public Set<OcorrenciaConsignante> getOcorrenciaConsignanteSet() {
        return ocorrenciaConsignanteSet;
    }

    public Set<ParamValidacaoArqCse> getParamValidacaoArqCseSet() {
        return paramValidacaoArqCseSet;
    }

    public Set<CalendarioFolhaCse> getCalendarioFolhaCseSet() {
        return calendarioFolhaCseSet;
    }

    public Set<ParamSvcConsignante> getParamSvcConsignanteSet() {
        return paramSvcConsignanteSet;
    }

    public Set<PerfilCse> getPerfilCseSet() {
        return perfilCseSet;
    }

    public Set<UsuarioCse> getUsuarioCseSet() {
        return usuarioCseSet;
    }

    public Set<UsuarioSup> getUsuarioSupSet() {
        return usuarioSupSet;
    }

    public String getCseRsaPublicKeyCentralizador() {
        return CodedValues.RSA_PUBLIC_KEY_CENTRALIZADOR;
    }

    public String getCseRsaModulusCentralizador() {
        return CodedValues.RSA_MODULUS_CENTRALIZADOR;
    }

}
