/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "ConsignatariaPermiteTda" ( stored in table "tb_consignataria_permite_tda" )
 *
 * @author Telosys
 *
 */
public class ConsignatariaPermiteTdaId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES
    private String tdaCodigo;

    private String csaCodigo;

    /**
     * Constructor
     */
    public ConsignatariaPermiteTdaId() {
        super();
    }

    /**
     * Constructor with values
     * @param tdaCodigo
     * @param csaCodigo
     */
    public ConsignatariaPermiteTdaId(String csaCodigo, String tdaCodigo) {
        super();
        this.tdaCodigo = tdaCodigo;
        this.csaCodigo = csaCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setTdaCodigo(String value) {
        tdaCodigo = value;
    }

    public String getTdaCodigo() {
        return tdaCodigo;
    }

    public void setCsaCodigo(String value) {
        csaCodigo = value;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        ConsignatariaPermiteTdaId other = (ConsignatariaPermiteTdaId) obj;
        //--- Attribute tdaCodigo
        if (tdaCodigo == null) {
            if (other.tdaCodigo != null) {
                return false;
            }
        } else if (!tdaCodigo.equals(other.tdaCodigo)) {
            return false;
        }
        //--- Attribute csaCodigo
        if (csaCodigo == null) {
            if (other.csaCodigo != null) {
                return false;
            }
        } else if (!csaCodigo.equals(other.csaCodigo)) {
            return false;
        }
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute tdaCodigo
        result = prime * result + ((tdaCodigo == null) ? 0 : tdaCodigo.hashCode());
        //--- Attribute csaCodigo
        result = prime * result + ((csaCodigo == null) ? 0 : csaCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(tdaCodigo);
        sb.append("|");
        sb.append(csaCodigo);
        return sb.toString();
    }

}
