/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * JPA entity class for "ContratoBeneficio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_contrato_beneficio")
@Audited
@AuditTable(value = "ta_contrato_beneficio")
public class ContratoBeneficio implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "cbe_codigo", nullable = false, length = 32)
    private String cbeCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "scb_codigo", nullable = false, length = 32)
    private String scbCodigo;

    @Column(name = "bfc_codigo", nullable = false, length = 32)
    private String bfcCodigo;

    @Column(name = "ben_codigo", nullable = false, length = 32)
    private String benCodigo;

    @Column(name = "cbe_numero", nullable = false, length = 40)
    private String cbeNumero;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cbe_data_inclusao", nullable = false)
    private Date cbeDataInclusao;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cbe_data_inicio_vigencia", nullable = false)
    private Date cbeDataInicioVigencia;

    @Column(name = "cbe_item_lote", nullable = false, length = 40)
    private String cbeItemLote;

    @Column(name = "cbe_numero_lote", nullable = false, length = 40)
    private String cbeNumeroLote;

    @Column(name = "cbe_valor_total", nullable = false)
    private BigDecimal cbeValorTotal;

    @Column(name = "cbe_valor_subsidio", nullable = false)
    private BigDecimal cbeValorSubsidio;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cbe_data_fim_vigencia")
    private Date cbeDataFimVigencia;

    @Temporal(TemporalType.DATE)
    @Column(name = "cbe_data_cancelamento")
    private Date cbeDataCancelamento;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @NotAudited
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "scb_codigo", referencedColumnName = "scb_codigo", insertable = false, updatable = false)
    private StatusContratoBeneficio statusContratoBeneficio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bfc_codigo", referencedColumnName = "bfc_codigo", insertable = false, updatable = false)
    private Beneficiario beneficiario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ben_codigo", referencedColumnName = "ben_codigo", insertable = false, updatable = false)
    private Beneficio beneficio;

    @NotAudited
    @OneToMany(mappedBy = "contratoBeneficio", targetEntity = MemoriaCalculoSubsidio.class)
    private Set<MemoriaCalculoSubsidio> memoriaCalculoSubsidioSet;

    @NotAudited
    @OneToMany(mappedBy = "contratoBeneficio", targetEntity = AutDesconto.class)
    private Set<AutDesconto> autDescontoSet;

    @NotAudited
    @OneToMany(mappedBy = "contratoBeneficio", targetEntity = OcorrenciaCttBeneficio.class)
    private Set<OcorrenciaCttBeneficio> ocorrenciaCttBeneficioSet;

    /**
     * Constructor
     */
    public ContratoBeneficio() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setCbeCodigo(String cbeCodigo) {
        this.cbeCodigo = cbeCodigo;
    }

    public String getCbeCodigo() {
        return cbeCodigo;
    }

    public void setScbCodigo(String scbCodigo) {
        this.scbCodigo = scbCodigo;
    }

    public String getScbCodigo() {
        return scbCodigo;
    }

    public void setBfcCodigo(String bfcCodigo) {
        this.bfcCodigo = bfcCodigo;
    }

    public String getBfcCodigo() {
        return bfcCodigo;
    }

    public void setBenCodigo(String benCodigo) {
        this.benCodigo = benCodigo;
    }

    public String getBenCodigo() {
        return benCodigo;
    }

    public void setCbeNumero(String cbeNumero) {
        this.cbeNumero = cbeNumero;
    }

    public String getCbeNumero() {
        return cbeNumero;
    }

    public void setCbeDataInclusao(Date cbeDataInclusao) {
        this.cbeDataInclusao = cbeDataInclusao;
    }

    public Date getCbeDataInclusao() {
        return cbeDataInclusao;
    }

    public void setCbeDataInicioVigencia(Date cbeDataInicioVigencia) {
        this.cbeDataInicioVigencia = cbeDataInicioVigencia;
    }

    public Date getCbeDataInicioVigencia() {
        return cbeDataInicioVigencia;
    }

    public void setCbeItemLote(String cbeItemLote) {
        this.cbeItemLote = cbeItemLote;
    }

    public String getCbeItemLote() {
        return cbeItemLote;
    }

    public void setCbeNumeroLote(String cbeNumeroLote) {
        this.cbeNumeroLote = cbeNumeroLote;
    }

    public String getCbeNumeroLote() {
        return cbeNumeroLote;
    }

    public void setCbeValorTotal(BigDecimal cbeValorTotal) {
        this.cbeValorTotal = cbeValorTotal;
    }

    public BigDecimal getCbeValorTotal() {
        return cbeValorTotal;
    }

    public void setCbeValorSubsidio(BigDecimal cbeValorSubsidio) {
        this.cbeValorSubsidio = cbeValorSubsidio;
    }

    public BigDecimal getCbeValorSubsidio() {
        return cbeValorSubsidio;
    }

    public void setCbeDataFimVigencia(Date cbeDataFimVigencia) {
        this.cbeDataFimVigencia = cbeDataFimVigencia;
    }

    public Date getCbeDataFimVigencia() {
        return cbeDataFimVigencia;
    }

    public void setCbeDataCancelamento(Date cbeDataCancelamento) {
        this.cbeDataCancelamento = cbeDataCancelamento;
    }

    public Date getCbeDataCancelamento() {
        return cbeDataCancelamento;
    }

    //--- GETTERS FOR LINKS
    public void setStatusContratoBeneficio(StatusContratoBeneficio statusContratoBeneficio) {
        this.statusContratoBeneficio = statusContratoBeneficio;
        setScbCodigo(statusContratoBeneficio != null ? statusContratoBeneficio.getScbCodigo() : null);
    }

    public StatusContratoBeneficio getStatusContratoBeneficio() {
        return statusContratoBeneficio;
    }

    public Set<MemoriaCalculoSubsidio> getMemoriaCalculoSubsidioSet() {
        return memoriaCalculoSubsidioSet;
    }

    public void setBeneficiario(Beneficiario beneficiario) {
        this.beneficiario = beneficiario;
        setBfcCodigo(beneficiario != null ? beneficiario.getBfcCodigo() : null);
    }

    public Beneficiario getBeneficiario() {
        return beneficiario;
    }

    public Set<AutDesconto> getAutDescontoSet() {
        return autDescontoSet;
    }

    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
        setBenCodigo(beneficio != null ? beneficio.getBenCodigo() : null);
    }

    public Beneficio getBeneficio() {
        return beneficio;
    }

    public Set<OcorrenciaCttBeneficio> getOcorrenciaCttBeneficioSet() {
        return ocorrenciaCttBeneficioSet;
    }

    // Não estamos usando o equal porque não podemos comparar o ID
    // Mas totalmente baseado no equals
    public boolean comparacaoModuloBeneficio(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ContratoBeneficio other = (ContratoBeneficio) obj;
        if (beneficiario == null) {
            if (other.beneficiario != null) {
                return false;
            }
        } else if (!beneficiario.getBfcCodigo().equals(other.beneficiario.getBfcCodigo())) {
            return false;
        }
        if (beneficio == null) {
            if (other.beneficio != null) {
                return false;
            }
        } else if (!beneficio.getBenCodigo().equals(other.beneficio.getBenCodigo())) {
            return false;
        }
        if (statusContratoBeneficio == null) {
            if (other.statusContratoBeneficio != null) {
                return false;
            }
        } else if (!statusContratoBeneficio.getScbCodigo().equals(other.statusContratoBeneficio.getScbCodigo())) {
            return false;
        }
        if (cbeDataInclusao == null) {
            if (other.cbeDataInclusao != null) {
                return false;
            }
        } else if (cbeDataInclusao.compareTo(other.cbeDataInclusao) != 0) { //Cuidado se for mudar esse if, quando o objeto volta do banco de dados ele vem como TimeStamp.
            return false;
        }
        if (cbeDataInicioVigencia == null) {
            if (other.cbeDataInicioVigencia != null) {
                return false;
            }
        } else if (cbeDataInicioVigencia.compareTo(other.cbeDataInicioVigencia) != 0) { //Cuidado se for mudar esse if, quando o objeto volta do banco de dados ele vem como TimeStamp.
            return false;
        }
        if (cbeDataFimVigencia == null) {
            if (other.cbeDataFimVigencia != null) {
                return false;
            }
        } else if (cbeDataFimVigencia.compareTo(other.cbeDataFimVigencia) != 0) { //Cuidado se for mudar esse if, quando o objeto volta do banco de dados ele vem como TimeStamp.
            return false;
        }
        if (cbeItemLote == null) {
            if (other.cbeItemLote != null) {
                return false;
            }
        } else if (!cbeItemLote.equals(other.cbeItemLote)) {
            return false;
        }
        if (cbeNumero == null) {
            if (other.cbeNumero != null) {
                return false;
            }
        } else if (!cbeNumero.equals(other.cbeNumero)) {
            return false;
        }
        if (cbeNumeroLote == null) {
            if (other.cbeNumeroLote != null) {
                return false;
            }
        } else if (!cbeNumeroLote.equals(other.cbeNumeroLote)) {
            return false;
        }
        if (cbeValorSubsidio == null) {
            if (other.cbeValorSubsidio != null) {
                return false;
            }
        } else if (cbeValorSubsidio.compareTo(other.cbeValorSubsidio) != 0) {
            return false;
        }
        if (cbeValorTotal == null) {
            if (other.cbeValorTotal != null) {
                return false;
            }
        } else if (cbeValorTotal.compareTo(other.cbeValorTotal) != 0) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("ContratoBeneficio [");
        if (cbeCodigo != null) {
            builder.append("cbeCodigo=");
            builder.append(cbeCodigo);
            builder.append(", ");
        }
        if (beneficiario != null) {
            builder.append("beneficiario=");
            builder.append(beneficiario.getBfcCodigo());
            builder.append(", ");
        }
        if (beneficio != null) {
            builder.append("beneficio=");
            builder.append(beneficio.getBenCodigo());
            builder.append(", ");
        }
        if (cbeNumero != null) {
            builder.append("cbeNumero=");
            builder.append(cbeNumero);
            builder.append(", ");
        }
        if (cbeDataInclusao != null) {
            builder.append("cbeDataInclusao=");
            builder.append(cbeDataInclusao);
            builder.append(", ");
        }
        if (cbeDataInicioVigencia != null) {
            builder.append("cbeDataInicioVigencia=");
            builder.append(cbeDataInicioVigencia);
            builder.append(", ");
        }
        if (cbeItemLote != null) {
            builder.append("cbeItemLote=");
            builder.append(cbeItemLote);
            builder.append(", ");
        }
        if (cbeNumeroLote != null) {
            builder.append("cbeNumeroLote=");
            builder.append(cbeNumeroLote);
            builder.append(", ");
        }
        if (cbeValorTotal != null) {
            builder.append("cbeValorTotal=");
            builder.append(cbeValorTotal);
            builder.append(", ");
        }
        if (cbeValorSubsidio != null) {
            builder.append("cbeValorSubsidio=");
            builder.append(cbeValorSubsidio);
            builder.append(", ");
        }
        if (cbeDataFimVigencia != null) {
            builder.append("cbeDataFimVigencia=");
            builder.append(cbeDataFimVigencia);
            builder.append(", ");
        }
        if (statusContratoBeneficio != null) {
            builder.append("statusContratoBeneficio=");
            builder.append(statusContratoBeneficio.getScbCodigo());
        }
        builder.append("]");
        return builder.toString();
    }
}
