/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "tb_convenio_vinculo_registro")
@IdClass(ConvenioVinculoRegistroId.class)
@Getter
@Setter
public class ConvenioVinculoRegistro implements Serializable {

    private static final long serialVersionUID = 2L;

    @Id
    @Column(name = "vrs_codigo", nullable = false, length = 32)
    private String vrsCodigo;

    @Id
    @Column(name = "svc_codigo", nullable = false, length = 32)
    private String svcCodigo;

    @Id
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "svc_codigo", referencedColumnName = "svc_codigo", insertable = false, updatable = false)
    private Servico servico;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vrs_codigo", referencedColumnName = "vrs_codigo", insertable = false, updatable = false)
    private VinculoRegistroServidor vinculoRegistroServidor;

    public void setId(ConvenioVinculoRegistroId id) {
        setVrsCodigo(id != null ? id.getVrsCodigo() : null);
        setSvcCodigo(id != null ? id.getSvcCodigo() : null);
        setCsaCodigo(id != null ? id.getCsaCodigo() : null);
    }
}
