/*
 * Created on 2021-12-30 ( 18:15:57 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "DadosServidor" ( stored in table "tb_dados_servidor" )
 *
 * @author Telosys
 *
 */
public class DadosServidorId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String serCodigo;

    private String tdaCodigo;

    /**
     * Constructor
     */
    public DadosServidorId() {
        super();
    }

    /**
     * Constructor with values
     * @param serCodigo 
     * @param tdaCodigo 
     */
    public DadosServidorId(String serCodigo, String tdaCodigo) {
        super();
        this.serCodigo = serCodigo;
        this.tdaCodigo = tdaCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setSerCodigo(String value) {
        this.serCodigo = value;
    }

    public String getSerCodigo() {
        return this.serCodigo;
    }

    public void setTdaCodigo(String value) {
        this.tdaCodigo = value;
    }

    public String getTdaCodigo() {
        return this.tdaCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        DadosServidorId other = (DadosServidorId) obj;
        //--- Attribute serCodigo
        if (serCodigo == null) {
            if (other.serCodigo != null)
                return false;
        } else if (!serCodigo.equals(other.serCodigo))
            return false;
        //--- Attribute tdaCodigo
        if (tdaCodigo == null) {
            if (other.tdaCodigo != null)
                return false;
        } else if (!tdaCodigo.equals(other.tdaCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute serCodigo
        result = prime * result + ((serCodigo == null) ? 0 : serCodigo.hashCode());
        //--- Attribute tdaCodigo
        result = prime * result + ((tdaCodigo == null) ? 0 : tdaCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(serCodigo);
        sb.append("|");
        sb.append(tdaCodigo);
        return sb.toString();
    }

}
