/*
 * Created on 2021-12-30 ( 18:15:58 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "DefinicaoTaxaJuros"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_definicao_taxa_juros")
public class DefinicaoTaxaJuros implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "dtj_codigo", nullable = false, length = 32)
    private String dtjCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    @Column(name = "org_codigo", length = 32)
    private String orgCodigo;

    @Column(name = "svc_codigo", nullable = false, length = 32)
    private String svcCodigo;

    @Column(name = "fun_codigo", length = 32)
    private String funCodigo;

    @Column(name = "dtj_faixa_etaria_ini")
    private Short dtjFaixaEtariaIni;

    @Column(name = "dtj_faixa_etaria_fim")
    private Short dtjFaixaEtariaFim;

    @Column(name = "dtj_faixa_temp_servico_ini")
    private Short dtjFaixaTempServicoIni;

    @Column(name = "dtj_faixa_temp_servico_fim")
    private Short dtjFaixaTempServicoFim;

    @Column(name = "dtj_faixa_salario_ini")
    private BigDecimal dtjFaixaSalarioIni;

    @Column(name = "dtj_faixa_salario_fim")
    private BigDecimal dtjFaixaSalarioFim;

    @Column(name = "dtj_faixa_margem_ini")
    private BigDecimal dtjFaixaMargemIni;

    @Column(name = "dtj_faixa_margem_fim")
    private BigDecimal dtjFaixaMargemFim;

    @Column(name = "dtj_faixa_valor_total_ini")
    private BigDecimal dtjFaixaValorTotalIni;

    @Column(name = "dtj_faixa_valor_total_fim")
    private BigDecimal dtjFaixaValorTotalFim;

    @Column(name = "dtj_faixa_valor_contrato_ini")
    private BigDecimal dtjFaixaValorContratoIni;

    @Column(name = "dtj_faixa_valor_contrato_fim")
    private BigDecimal dtjFaixaValorContratoFim;

    @Column(name = "dtj_faixa_prazo_ini", nullable = false)
    private Short dtjFaixaPrazoIni;

    @Column(name = "dtj_faixa_prazo_fim", nullable = false)
    private Short dtjFaixaPrazoFim;

    @Column(name = "dtj_taxa_juros", nullable = false)
    private BigDecimal dtjTaxaJuros;
    
    @Column(name = "dtj_taxa_juros_minima")
    private BigDecimal dtjTaxaJurosMinima;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtj_data_vigencia_ini")
    private Date dtjDataVigenciaIni;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtj_data_vigencia_fim")
    private Date dtjDataVigenciaFim;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtj_data_cadastro", nullable = false)
    private Date dtjDataCadastro;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "svc_codigo", referencedColumnName = "svc_codigo", insertable = false, updatable = false)
    private Servico servico;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo" , referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    /**
     * Constructor
     */
    public DefinicaoTaxaJuros() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setDtjCodigo(String dtjCodigo) {
        this.dtjCodigo = dtjCodigo;
    }

    public String getDtjCodigo() {
        return dtjCodigo;
    }

    public void setCsaCodigo(String csaCodigo) {
        this.csaCodigo = csaCodigo;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setSvcCodigo(String svcCodigo) {
        this.svcCodigo = svcCodigo;
    }

    public String getSvcCodigo() {
        return svcCodigo;
    }

    public void setDtjFaixaEtariaIni(Short dtjFaixaEtariaIni) {
        this.dtjFaixaEtariaIni = dtjFaixaEtariaIni;
    }

    public Short getDtjFaixaEtariaIni() {
        return dtjFaixaEtariaIni;
    }

    public void setDtjFaixaEtariaFim(Short dtjFaixaEtariaFim) {
        this.dtjFaixaEtariaFim = dtjFaixaEtariaFim;
    }

    public Short getDtjFaixaEtariaFim() {
        return dtjFaixaEtariaFim;
    }

    public void setDtjFaixaTempServicoIni(Short dtjFaixaTempServicoIni) {
        this.dtjFaixaTempServicoIni = dtjFaixaTempServicoIni;
    }

    public Short getDtjFaixaTempServicoIni() {
        return dtjFaixaTempServicoIni;
    }

    public void setDtjFaixaTempServicoFim(Short dtjFaixaTempServicoFim) {
        this.dtjFaixaTempServicoFim = dtjFaixaTempServicoFim;
    }

    public Short getDtjFaixaTempServicoFim() {
        return dtjFaixaTempServicoFim;
    }

    public void setDtjFaixaSalarioIni(BigDecimal dtjFaixaSalarioIni) {
        this.dtjFaixaSalarioIni = dtjFaixaSalarioIni;
    }

    public BigDecimal getDtjFaixaSalarioIni() {
        return dtjFaixaSalarioIni;
    }

    public void setDtjFaixaSalarioFim(BigDecimal dtjFaixaSalarioFim) {
        this.dtjFaixaSalarioFim = dtjFaixaSalarioFim;
    }

    public BigDecimal getDtjFaixaSalarioFim() {
        return dtjFaixaSalarioFim;
    }

    public void setDtjFaixaMargemIni(BigDecimal dtjFaixaMargemIni) {
        this.dtjFaixaMargemIni = dtjFaixaMargemIni;
    }

    public BigDecimal getDtjFaixaMargemIni() {
        return dtjFaixaMargemIni;
    }

    public void setDtjFaixaMargemFim(BigDecimal dtjFaixaMargemFim) {
        this.dtjFaixaMargemFim = dtjFaixaMargemFim;
    }

    public BigDecimal getDtjFaixaMargemFim() {
        return dtjFaixaMargemFim;
    }

    public void setDtjFaixaValorTotalIni(BigDecimal dtjFaixaValorTotalIni) {
        this.dtjFaixaValorTotalIni = dtjFaixaValorTotalIni;
    }

    public BigDecimal getDtjFaixaValorTotalIni() {
        return dtjFaixaValorTotalIni;
    }

    public void setDtjFaixaValorTotalFim(BigDecimal dtjFaixaValorTotalFim) {
        this.dtjFaixaValorTotalFim = dtjFaixaValorTotalFim;
    }

    public BigDecimal getDtjFaixaValorTotalFim() {
        return dtjFaixaValorTotalFim;
    }

    public void setDtjFaixaValorContratoIni(BigDecimal dtjFaixaValorContratoIni) {
        this.dtjFaixaValorContratoIni = dtjFaixaValorContratoIni;
    }

    public BigDecimal getDtjFaixaValorContratoIni() {
        return dtjFaixaValorContratoIni;
    }

    public void setDtjFaixaValorContratoFim(BigDecimal dtjFaixaValorContratoFim) {
        this.dtjFaixaValorContratoFim = dtjFaixaValorContratoFim;
    }

    public BigDecimal getDtjFaixaValorContratoFim() {
        return dtjFaixaValorContratoFim;
    }

    public void setDtjFaixaPrazoIni(Short dtjFaixaPrazoIni) {
        this.dtjFaixaPrazoIni = dtjFaixaPrazoIni;
    }

    public Short getDtjFaixaPrazoIni() {
        return dtjFaixaPrazoIni;
    }

    public void setDtjFaixaPrazoFim(Short dtjFaixaPrazoFim) {
        this.dtjFaixaPrazoFim = dtjFaixaPrazoFim;
    }

    public Short getDtjFaixaPrazoFim() {
        return dtjFaixaPrazoFim;
    }

    public void setDtjTaxaJuros(BigDecimal dtjTaxaJuros) {
        this.dtjTaxaJuros = dtjTaxaJuros;
    }

    public BigDecimal getDtjTaxaJuros() {
        return dtjTaxaJuros;
    }

    public BigDecimal getDtjTaxaJurosMinima() {
		return dtjTaxaJurosMinima;
	}

	public void setDtjTaxaJurosMinima(BigDecimal dtjTaxaJurosMinima) {
		this.dtjTaxaJurosMinima = dtjTaxaJurosMinima;
	}

	public void setDtjDataVigenciaIni(Date dtjDataVigenciaIni) {
        this.dtjDataVigenciaIni = dtjDataVigenciaIni;
    }

    public Date getDtjDataVigenciaIni() {
        return dtjDataVigenciaIni;
    }

    public void setDtjDataVigenciaFim(Date dtjDataVigenciaFim) {
        this.dtjDataVigenciaFim = dtjDataVigenciaFim;
    }

    public Date getDtjDataVigenciaFim() {
        return dtjDataVigenciaFim;
    }

    public void setDtjDataCadastro(Date dtjDataCadastro) {
        this.dtjDataCadastro = dtjDataCadastro;
    }

    public Date getDtjDataCadastro() {
        return dtjDataCadastro;
    }

    //--- GETTERS FOR LINKS
    public void setServico(Servico servico) {
        this.servico = servico;
        setSvcCodigo(servico != null ? servico.getSvcCodigo() : null);
    }

    public Servico getServico() {
        return servico;
    }


    public void setFunCodigo(String funCodigo){
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo(){
        return funCodigo;
    }
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao(){
        return funcao;
    }

    public void setConsignataria(Consignataria consignataria) {
        this.consignataria = consignataria;
        setCsaCodigo(consignataria != null ? consignataria.getCsaCodigo() : null);
    }

    public Consignataria getConsignataria() {
        return consignataria;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
    }

    public Orgao getOrgao() {
        return orgao;
    }

}
