/*
 * Created on 2021-12-30 ( 18:15:58 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * <p>Title: DestinatarioEmailCse</p>
 * <p>Description: Entidade da tabela tb_destinatario_email_cse
 * <p>Copyright: Copyright (c) 2023</p>
 * <p>Company: ZetraSoft</p>
 * @author Eduardo Fortes
 */
@Entity
@Table(name = "tb_destinatario_email_cse")
@IdClass(DestinatarioEmailCseId.class)
public class DestinatarioEmailCse implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    @Id
    @Column(name = "pap_codigo", nullable = false, length = 32)
    private String papCodigo;

    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "dee_receber", nullable = false, length = 1)
    private String deeReceber;

    @Column(name = "dee_email", length = 100)
    private String deeEmail;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pap_codigo", referencedColumnName = "pap_codigo", insertable = false, updatable = false)
    private Papel papel;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false)
    private Consignante consignante;

    /**
     * Constructor
     */
    public DestinatarioEmailCse() {
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setPapCodigo(String papCodigo) {
        this.papCodigo = papCodigo;
    }

    public String getPapCodigo() {
        return papCodigo;
    }

    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    public void setDeeReceber(String deeReceber) {
        this.deeReceber = deeReceber;
    }

    public String getDeeReceber() {
        return deeReceber;
    }

    public void setDeeEmail(String deeEmail) {
        this.deeEmail = deeEmail;
    }

    public String getDeeEmail() {
        return deeEmail;
    }

    //--- GETTERS FOR LINKS
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setPapel(Papel papel) {
        this.papel = papel;
        setPapCodigo(papel != null ? papel.getPapCodigo() : null);
    }

    public Papel getPapel() {
        return papel;
    }

    public void setConsignante(Consignante consignante) {
        this.consignante = consignante;
        setCseCodigo(consignante != null ? consignante.getCseCodigo() : null);
    }

    public Consignante getConsignante() {
        return consignante;
    }

    public void setId(DestinatarioEmailCseId id) {
        setFunCodigo(id != null ? id.getFunCodigo() : null);
        setPapCodigo(id != null ? id.getPapCodigo() : null);
        setCseCodigo(id != null ? id.getCseCodigo() : null);
    }
}
