/*
 * Created on 2021-12-30 ( 18:15:58 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "DirfServidor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_dirf_servidor")
@IdClass(DirfServidorId.class)
public class DirfServidor implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ser_codigo", nullable = false, length = 32)
    private String serCodigo;

    @Id
    @Column(name = "dis_ano_calendario", nullable = false)
    private Short disAnoCalendario;

    //--- ENTITY DATA FIELDS
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dis_data_carga", nullable = false)
    private Date disDataCarga;

    @Column(name = "arq_codigo", nullable = false, length = 32)
    private String arqCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "arq_codigo", referencedColumnName = "arq_codigo", insertable = false, updatable = false)
    private Arquivo arquivo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ser_codigo", referencedColumnName = "ser_codigo", insertable = false, updatable = false)
    private Servidor servidor;

    /**
     * Constructor
     */
    public DirfServidor() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setSerCodigo(String serCodigo) {
        this.serCodigo = serCodigo;
    }

    public String getSerCodigo() {
        return serCodigo;
    }

    public void setDisAnoCalendario(Short disAnoCalendario) {
        this.disAnoCalendario = disAnoCalendario;
    }

    public Short getDisAnoCalendario() {
        return disAnoCalendario;
    }

    public void setDisDataCarga(Date disDataCarga) {
        this.disDataCarga = disDataCarga;
    }

    public Date getDisDataCarga() {
        return disDataCarga;
    }

    public void setArqCodigo(String arqCodigo) {
        this.arqCodigo = arqCodigo;
    }

    public String getArqCodigo() {
        return arqCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setArquivo(Arquivo arquivo) {
        this.arquivo = arquivo;
        setArqCodigo(arquivo != null ? arquivo.getArqCodigo() : null);
    }

    public Arquivo getArquivo() {
        return arquivo;
    }

    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
        setSerCodigo(servidor != null ? servidor.getSerCodigo() : null);
    }

    public Servidor getServidor() {
        return servidor;
    }

    public void setId(DirfServidorId id) {
        setSerCodigo(id != null ? id.getSerCodigo() : null);
        setDisAnoCalendario(id != null ? id.getDisAnoCalendario() : null);
    }
}
