/*
 * Created on 2021-12-30 ( 18:15:58 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "EnderecoAcessoFuncao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_endereco_acesso_funcao")
@IdClass(EnderecoAcessoFuncaoId.class)
public class EnderecoAcessoFuncao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "eaf_ip_acesso", length = 65535)
    private String eafIpAcesso;

    @Column(name = "eaf_ddns_acesso", length = 65535)
    private String eafDdnsAcesso;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    /**
     * Constructor
     */
    public EnderecoAcessoFuncao() {
        super();
    }

    public EnderecoAcessoFuncao(String usuCodigo, String funCodigo, String eafIpAcesso, String eafDdnsAcesso) {
        this();
        this.usuCodigo = usuCodigo;
        this.funCodigo = funCodigo;
        this.eafIpAcesso = eafIpAcesso;
        this.eafDdnsAcesso = eafDdnsAcesso;
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setEafIpAcesso(String eafIpAcesso) {
        this.eafIpAcesso = eafIpAcesso;
    }

    public String getEafIpAcesso() {
        return eafIpAcesso;
    }

    public void setEafDdnsAcesso(String eafDdnsAcesso) {
        this.eafDdnsAcesso = eafDdnsAcesso;
    }

    public String getEafDdnsAcesso() {
        return eafDdnsAcesso;
    }

    //--- GETTERS FOR LINKS
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

}
