/*
 * Created on 2021-12-30 ( 18:15:58 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * JPA entity class for "EnderecoServidor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_endereco_servidor")
@Audited
@AuditTable(value="ta_endereco_servidor")
public class EnderecoServidor implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ens_codigo", nullable = false, length = 32)
    private String ensCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "ser_codigo", nullable = false, length = 32)
    private String serCodigo;

    @Column(name = "tie_codigo", nullable = false, length = 32)
    private String tieCodigo;

    @Column(name = "ens_logradouro", nullable = false, length = 100)
    private String ensLogradouro;

    @Column(name = "ens_numero", nullable = false, length = 15)
    private String ensNumero;

    @Column(name = "ens_complemento", nullable = false, length = 40)
    private String ensComplemento;

    @Column(name = "ens_bairro", nullable = false, length = 40)
    private String ensBairro;

    @Column(name = "ens_municipio", nullable = false, length = 40)
    private String ensMunicipio;

    @Column(name = "ens_uf", nullable = false, length = 2)
    private String ensUf;

    @Column(name = "ens_cep", nullable = false, length = 10)
    private String ensCep;

    @Column(name = "ens_codigo_municipio", length = 7)
    private String ensCodigoMunicipio;

    @Column(name = "ens_ativo", nullable = false)
    private Short ensAtivo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @NotAudited
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ser_codigo", referencedColumnName = "ser_codigo", insertable = false, updatable = false)
    private Servidor servidor;

    @NotAudited
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tie_codigo", referencedColumnName = "tie_codigo", insertable = false, updatable = false)
    private TipoEndereco tipoEndereco;

    @NotAudited
    @OneToMany(mappedBy = "enderecoServidor", targetEntity = OcorrenciaEnderecoSer.class)
    private Set<OcorrenciaEnderecoSer> ocorrenciaEnderecoSerSet;

    /**
     * Constructor
     */
    public EnderecoServidor() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setEnsCodigo(String ensCodigo) {
        this.ensCodigo = ensCodigo;
    }

    public String getEnsCodigo() {
        return ensCodigo;
    }

    public void setSerCodigo(String serCodigo) {
        this.serCodigo = serCodigo;
    }

    public String getSerCodigo() {
        return serCodigo;
    }

    public void setTieCodigo(String tieCodigo) {
        this.tieCodigo = tieCodigo;
    }

    public String getTieCodigo() {
        return tieCodigo;
    }

    public void setEnsLogradouro(String ensLogradouro) {
        this.ensLogradouro = ensLogradouro;
    }

    public String getEnsLogradouro() {
        return ensLogradouro;
    }

    public void setEnsNumero(String ensNumero) {
        this.ensNumero = ensNumero;
    }

    public String getEnsNumero() {
        return ensNumero;
    }

    public void setEnsComplemento(String ensComplemento) {
        this.ensComplemento = ensComplemento;
    }

    public String getEnsComplemento() {
        return ensComplemento;
    }

    public void setEnsBairro(String ensBairro) {
        this.ensBairro = ensBairro;
    }

    public String getEnsBairro() {
        return ensBairro;
    }

    public void setEnsMunicipio(String ensMunicipio) {
        this.ensMunicipio = ensMunicipio;
    }

    public String getEnsMunicipio() {
        return ensMunicipio;
    }

    public void setEnsUf(String ensUf) {
        this.ensUf = ensUf;
    }

    public String getEnsUf() {
        return ensUf;
    }

    public void setEnsCep(String ensCep) {
        this.ensCep = ensCep;
    }

    public String getEnsCep() {
        return ensCep;
    }

    public void setEnsCodigoMunicipio(String ensCodigoMunicipio) {
        this.ensCodigoMunicipio = ensCodigoMunicipio;
    }

    public String getEnsCodigoMunicipio() {
        return ensCodigoMunicipio;
    }

    public void setEnsAtivo(Short ensAtivo) {
        this.ensAtivo = ensAtivo;
    }

    public Short getEnsAtivo() {
        return ensAtivo;
    }

    //--- GETTERS FOR LINKS
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
        setSerCodigo(servidor != null ? servidor.getSerCodigo() : null);
    }

    public Servidor getServidor() {
        return servidor;
    }

    public void setTipoEndereco(TipoEndereco tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
        setTieCodigo(tipoEndereco != null ? tipoEndereco.getTieCodigo() : null);
    }

    public TipoEndereco getTipoEndereco() {
        return tipoEndereco;
    }

    public Set<OcorrenciaEnderecoSer> getOcorrenciaEnderecoSerSet() {
        return ocorrenciaEnderecoSerSet;
    }

    // Não estamos usando o equal porque não podemos comprar o ID
    // Mas totalmente baseado no equals
    public boolean comparacaoModuloBeneficio(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        EnderecoServidor other = (EnderecoServidor) obj;
        if (ensBairro == null) {
            if (other.ensBairro != null) {
                return false;
            }
        } else if (!ensBairro.equals(other.ensBairro)) {
            return false;
        }
        if (ensCep == null) {
            if (other.ensCep != null) {
                return false;
            }
        } else if (!ensCep.equals(other.ensCep)) {
            return false;
        }
        if (ensCodigoMunicipio == null) {
            if (other.ensCodigoMunicipio != null) {
                return false;
            }
        } else if (!ensCodigoMunicipio.equals(other.ensCodigoMunicipio)) {
            return false;
        }
        if (ensComplemento == null) {
            if (other.ensComplemento != null) {
                return false;
            }
        } else if (!ensComplemento.equals(other.ensComplemento)) {
            return false;
        }
        if (ensLogradouro == null) {
            if (other.ensLogradouro != null) {
                return false;
            }
        } else if (!ensLogradouro.equals(other.ensLogradouro)) {
            return false;
        }
        if (ensMunicipio == null) {
            if (other.ensMunicipio != null) {
                return false;
            }
        } else if (!ensMunicipio.equals(other.ensMunicipio)) {
            return false;
        }
        if (ensNumero == null) {
            if (other.ensNumero != null) {
                return false;
            }
        } else if (!ensNumero.equals(other.ensNumero)) {
            return false;
        }
        if (servidor == null) {
            if (other.servidor != null) {
                return false;
            }
        } else if (!servidor.getSerCodigo().equals(other.servidor.getSerCodigo())) {
            return false;
        }
//        if (tipoEndereco == null) {
//            if (other.tipoEndereco != null) {
//                return false;
//            }
//        } else if (!tipoEndereco.equals(other.tipoEndereco)) {
//            return false;
//        }
        if (ensUf == null) {
            if (other.ensUf != null) {
                return false;
            }
        } else if (!ensUf.equals(other.ensUf)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("EnderecoServidor [");
        if (ensCodigo != null) {
            builder.append("ensCodigo=");
            builder.append(ensCodigo);
            builder.append(", ");
        }
        if (servidor != null) {
            builder.append("servidor=");
            builder.append(servidor.getSerCodigo());
            builder.append(", ");
        }
        if (tipoEndereco != null) {
            builder.append("tipoEndereco=");
            builder.append(tipoEndereco.getTieCodigo());
            builder.append(", ");
        }
        if (ensLogradouro != null) {
            builder.append("ensLogradouro=");
            builder.append(ensLogradouro);
            builder.append(", ");
        }
        if (ensNumero != null) {
            builder.append("ensNumero=");
            builder.append(ensNumero);
            builder.append(", ");
        }
        if (ensComplemento != null) {
            builder.append("ensComplemento=");
            builder.append(ensComplemento);
            builder.append(", ");
        }
        if (ensBairro != null) {
            builder.append("ensBairro=");
            builder.append(ensBairro);
            builder.append(", ");
        }
        if (ensMunicipio != null) {
            builder.append("ensMunicipio=");
            builder.append(ensMunicipio);
            builder.append(", ");
        }
        if (ensCodigoMunicipio != null) {
            builder.append("ensCodigoMunicipio=");
            builder.append(ensCodigoMunicipio);
            builder.append(", ");
        }
        if (ensUf != null) {
            builder.append("ensUf=");
            builder.append(ensUf);
            builder.append(", ");
        }
        if (ensCep != null) {
            builder.append("ensCep=");
            builder.append(ensCep);
            builder.append(", ");
        }
        if (ensAtivo != null) {
            builder.append("ensAtivo=");
            builder.append(ensAtivo);
        }
        builder.append("]");
        return builder.toString();
    }
}
