/*
 * Created on 2021-12-30 ( 18:16:03 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "FiltroLeilaoSolicitacao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_filtro_leilao_solicitacao")
public class FiltroLeilaoSolicitacao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "fls_codigo", nullable = false, length = 32)
    private String flsCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "pos_codigo", length = 32)
    private String posCodigo;

    @Column(name = "cid_codigo", length = 32)
    private String cidCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "fls_descricao", nullable = false, length = 100)
    private String flsDescricao;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fls_data", nullable = false)
    private Date flsData;

    @Column(name = "fls_email_notificacao", length = 100)
    private String flsEmailNotificacao;

    @Temporal(TemporalType.DATE)
    @Column(name = "fls_data_abertura_ini")
    private Date flsDataAberturaIni;

    @Temporal(TemporalType.DATE)
    @Column(name = "fls_data_abertura_fim")
    private Date flsDataAberturaFim;

    @Column(name = "fls_horas_encerramento")
    private Short flsHorasEncerramento;

    @Column(name = "fls_pontuacao_min")
    private Integer flsPontuacaoMin;

    @Column(name = "fls_margem_livre_max")
    private Integer flsMargemLivreMax;

    @Column(name = "fls_tipo_pesquisa", length = 1)
    private String flsTipoPesquisa;

    @Column(name = "fls_matricula", length = 20)
    private String flsMatricula;

    @Column(name = "fls_cpf", length = 19)
    private String flsCpf;

    @Column(name = "fls_analise_risco", length = 1)
    private String flsAnaliseRisco;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pos_codigo", referencedColumnName = "pos_codigo", insertable = false, updatable = false)
    private PostoRegistroServidor postoRegistroServidor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cid_codigo", referencedColumnName = "cid_codigo", insertable = false, updatable = false)
    private Cidade cidade;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public FiltroLeilaoSolicitacao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setFlsCodigo(String flsCodigo) {
        this.flsCodigo = flsCodigo;
    }

    public String getFlsCodigo() {
        return flsCodigo;
    }

    public void setPosCodigo(String posCodigo) {
        this.posCodigo = posCodigo;
    }

    public String getPosCodigo() {
        return posCodigo;
    }

    public void setCidCodigo(String cidCodigo) {
        this.cidCodigo = cidCodigo;
    }

    public String getCidCodigo() {
        return cidCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setFlsDescricao(String flsDescricao) {
        this.flsDescricao = flsDescricao;
    }

    public String getFlsDescricao() {
        return flsDescricao;
    }

    public void setFlsData(Date flsData) {
        this.flsData = flsData;
    }

    public Date getFlsData() {
        return flsData;
    }

    public void setFlsEmailNotificacao(String flsEmailNotificacao) {
        this.flsEmailNotificacao = flsEmailNotificacao;
    }

    public String getFlsEmailNotificacao() {
        return flsEmailNotificacao;
    }

    public void setFlsDataAberturaIni(Date flsDataAberturaIni) {
        this.flsDataAberturaIni = flsDataAberturaIni;
    }

    public Date getFlsDataAberturaIni() {
        return flsDataAberturaIni;
    }

    public void setFlsDataAberturaFim(Date flsDataAberturaFim) {
        this.flsDataAberturaFim = flsDataAberturaFim;
    }

    public Date getFlsDataAberturaFim() {
        return flsDataAberturaFim;
    }

    public void setFlsHorasEncerramento(Short flsHorasEncerramento) {
        this.flsHorasEncerramento = flsHorasEncerramento;
    }

    public Short getFlsHorasEncerramento() {
        return flsHorasEncerramento;
    }

    public void setFlsPontuacaoMin(Integer flsPontuacaoMin) {
        this.flsPontuacaoMin = flsPontuacaoMin;
    }

    public Integer getFlsPontuacaoMin() {
        return flsPontuacaoMin;
    }

    public void setFlsMargemLivreMax(Integer flsMargemLivreMax) {
        this.flsMargemLivreMax = flsMargemLivreMax;
    }

    public Integer getFlsMargemLivreMax() {
        return flsMargemLivreMax;
    }

    public void setFlsTipoPesquisa(String flsTipoPesquisa) {
        this.flsTipoPesquisa = flsTipoPesquisa;
    }

    public String getFlsTipoPesquisa() {
        return flsTipoPesquisa;
    }

    public void setFlsMatricula(String flsMatricula) {
        this.flsMatricula = flsMatricula;
    }

    public String getFlsMatricula() {
        return flsMatricula;
    }

    public void setFlsCpf(String flsCpf) {
        this.flsCpf = flsCpf;
    }

    public String getFlsCpf() {
        return flsCpf;
    }

    public void setFlsAnaliseRisco(String flsAnaliseRisco) {
        this.flsAnaliseRisco = flsAnaliseRisco;
    }

    public String getFlsAnaliseRisco() {
        return flsAnaliseRisco;
    }

    //--- GETTERS FOR LINKS
    public void setPostoRegistroServidor(PostoRegistroServidor postoRegistroServidor) {
        this.postoRegistroServidor = postoRegistroServidor;
        setPosCodigo(postoRegistroServidor != null ? postoRegistroServidor.getPosCodigo() : null);
    }

    public PostoRegistroServidor getPostoRegistroServidor() {
        return postoRegistroServidor;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
        setCidCodigo(cidade != null ? cidade.getCidCodigo() : null);
    }

    public Cidade getCidade() {
        return cidade;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

}
