/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "FuncaoPerfilCse" ( stored in table "tb_funcao_perfil_cse" )
 *
 * @author Telosys
 *
 */
public class FuncaoPerfilCseId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String cseCodigo;

    private String usuCodigo;

    private String funCodigo;

    /**
     * Constructor
     */
    public FuncaoPerfilCseId() {
        super();
    }

    /**
     * Constructor with values
     * @param cseCodigo 
     * @param usuCodigo 
     * @param funCodigo 
     */
    public FuncaoPerfilCseId(String cseCodigo, String usuCodigo, String funCodigo) {
        super();
        this.cseCodigo = cseCodigo;
        this.usuCodigo = usuCodigo;
        this.funCodigo = funCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setCseCodigo(String value) {
        this.cseCodigo = value;
    }

    public String getCseCodigo() {
        return this.cseCodigo;
    }

    public void setUsuCodigo(String value) {
        this.usuCodigo = value;
    }

    public String getUsuCodigo() {
        return this.usuCodigo;
    }

    public void setFunCodigo(String value) {
        this.funCodigo = value;
    }

    public String getFunCodigo() {
        return this.funCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        FuncaoPerfilCseId other = (FuncaoPerfilCseId) obj;
        //--- Attribute cseCodigo
        if (cseCodigo == null) {
            if (other.cseCodigo != null)
                return false;
        } else if (!cseCodigo.equals(other.cseCodigo))
            return false;
        //--- Attribute usuCodigo
        if (usuCodigo == null) {
            if (other.usuCodigo != null)
                return false;
        } else if (!usuCodigo.equals(other.usuCodigo))
            return false;
        //--- Attribute funCodigo
        if (funCodigo == null) {
            if (other.funCodigo != null)
                return false;
        } else if (!funCodigo.equals(other.funCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute cseCodigo
        result = prime * result + ((cseCodigo == null) ? 0 : cseCodigo.hashCode());
        //--- Attribute usuCodigo
        result = prime * result + ((usuCodigo == null) ? 0 : usuCodigo.hashCode());
        //--- Attribute funCodigo
        result = prime * result + ((funCodigo == null) ? 0 : funCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(cseCodigo);
        sb.append("|");
        sb.append(usuCodigo);
        sb.append("|");
        sb.append(funCodigo);
        return sb.toString();
    }

}
