/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinColumns;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "FuncaoPerfilCse"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_funcao_perfil_cse")
@IdClass(FuncaoPerfilCseId.class)
public class FuncaoPerfilCse implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false)
    private Consignante consignante;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false),
        @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false),
    })
    private UsuarioCse usuarioCse;

    /**
     * Constructor
     */
    public FuncaoPerfilCse() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setConsignante(Consignante consignante) {
        this.consignante = consignante;
        setCseCodigo(consignante != null ? consignante.getCseCodigo() : null);
    }

    public Consignante getConsignante() {
        return consignante;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public UsuarioCse getUsuarioCse() {
        return usuarioCse;
    }

    public void setId(FuncaoPerfilCseId id) {
        setUsuCodigo(id != null ? id.getUsuCodigo() : null);
        setFunCodigo(id != null ? id.getFunCodigo() : null);
        setCseCodigo(id != null ? id.getCseCodigo() : null);
    }
}
