/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "FuncaoSensivelCsa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_funcao_sensivel_csa")
@IdClass(FuncaoSensivelCsaId.class)
public class FuncaoSensivelCsa implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    @Id
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "fsc_valor", nullable = false, length = 1)
    private String fscValor;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    /**
     * Constructor
     */
    public FuncaoSensivelCsa() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setCsaCodigo(String csaCodigo) {
        this.csaCodigo = csaCodigo;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    public void setFscValor(String fscValor) {
        this.fscValor = fscValor;
    }

    public String getFscValor() {
        return fscValor;
    }

    //--- GETTERS FOR LINKS
    public void setConsignataria(Consignataria consignataria) {
        this.consignataria = consignataria;
        setCsaCodigo(consignataria != null ? consignataria.getCsaCodigo() : null);
    }

    public Consignataria getConsignataria() {
        return consignataria;
    }

    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setId(FuncaoSensivelCsaId id) {
        setFunCodigo(id != null ? id.getFunCodigo() : null);
        setCsaCodigo(id != null ? id.getCsaCodigo() : null);
    }
}
