/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "FuncaoAuditavelSup"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_funcao_auditavel_sup")
@IdClass(FuncaoAuditavelSupId.class)
public class FuncaoAuditavelSup implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false)
    private Consignante consignante;

    /**
     * Constructor
     */
    public FuncaoAuditavelSup() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setConsignante(Consignante consignante) {
        this.consignante = consignante;
        setCseCodigo(consignante != null ? consignante.getCseCodigo() : null);
    }

    public Consignante getConsignante() {
        return consignante;
    }

    public void setId(FuncaoAuditavelSupId id) {
        setFunCodigo(id != null ? id.getFunCodigo() : null);
        setCseCodigo(id != null ? id.getCseCodigo() : null);
    }
}
