/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "FuncaoPerfilMasterNca"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_funcao_perfil_master_nca")
@IdClass(FuncaoPerfilMasterNcaId.class)
public class FuncaoPerfilMasterNca implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    @Id
    @Column(name = "nca_codigo", nullable = false, length = 32)
    private String ncaCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nca_codigo", referencedColumnName = "nca_codigo", insertable = false, updatable = false)
    private NaturezaConsignataria naturezaConsignataria;

    /**
     * Constructor
     */
    public FuncaoPerfilMasterNca() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    public void setNcaCodigo(String ncaCodigo) {
        this.ncaCodigo = ncaCodigo;
    }

    public String getNcaCodigo() {
        return ncaCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setNaturezaConsignataria(NaturezaConsignataria naturezaConsignataria) {
        this.naturezaConsignataria = naturezaConsignataria;
        setNcaCodigo(naturezaConsignataria != null ? naturezaConsignataria.getNcaCodigo() : null);
    }

    public NaturezaConsignataria getNaturezaConsignataria() {
        return naturezaConsignataria;
    }
}
