/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "FuncaoPermitidaNca" ( stored in table "tb_funcao_permitida_nca" )
 *
 * @author Telosys
 *
 */
public class FuncaoPermitidaNcaId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String ncaCodigo;

    private String funCodigo;

    /**
     * Constructor
     */
    public FuncaoPermitidaNcaId() {
        super();
    }

    /**
     * Constructor with values
     * @param ncaCodigo 
     * @param funCodigo 
     */
    public FuncaoPermitidaNcaId(String ncaCodigo, String funCodigo) {
        super();
        this.ncaCodigo = ncaCodigo;
        this.funCodigo = funCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setNcaCodigo(String value) {
        this.ncaCodigo = value;
    }

    public String getNcaCodigo() {
        return this.ncaCodigo;
    }

    public void setFunCodigo(String value) {
        this.funCodigo = value;
    }

    public String getFunCodigo() {
        return this.funCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        FuncaoPermitidaNcaId other = (FuncaoPermitidaNcaId) obj;
        //--- Attribute ncaCodigo
        if (ncaCodigo == null) {
            if (other.ncaCodigo != null)
                return false;
        } else if (!ncaCodigo.equals(other.ncaCodigo))
            return false;
        //--- Attribute funCodigo
        if (funCodigo == null) {
            if (other.funCodigo != null)
                return false;
        } else if (!funCodigo.equals(other.funCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute ncaCodigo
        result = prime * result + ((ncaCodigo == null) ? 0 : ncaCodigo.hashCode());
        //--- Attribute funCodigo
        result = prime * result + ((funCodigo == null) ? 0 : funCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ncaCodigo);
        sb.append("|");
        sb.append(funCodigo);
        return sb.toString();
    }

}
