/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "GrauParentesco"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_grau_parentesco")
public class GrauParentesco implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "grp_codigo", nullable = false, length = 32)
    private String grpCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "grp_descricao", nullable = false, length = 40)
    private String grpDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "grauParentesco", targetEntity = CalculoBeneficio.class)
    private Set<CalculoBeneficio> calculoBeneficioSet;

    @OneToMany(mappedBy = "grauParentesco", targetEntity = Beneficiario.class)
    private Set<Beneficiario> beneficiarioSet;

    /**
     * Constructor
     */
    public GrauParentesco() {
        super();
    }

    public GrauParentesco(String grpCodigo) {
        this();
        this.grpCodigo = grpCodigo;
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setGrpCodigo(String grpCodigo) {
        this.grpCodigo = grpCodigo;
    }

    public String getGrpCodigo() {
        return grpCodigo;
    }

    public void setGrpDescricao(String grpDescricao) {
        this.grpDescricao = grpDescricao;
    }

    public String getGrpDescricao() {
        return grpDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<CalculoBeneficio> getCalculoBeneficioSet() {
        return calculoBeneficioSet;
    }

    public Set<Beneficiario> getBeneficiarioSet() {
        return beneficiarioSet;
    }

}
