/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "HistoricoArquivoCse"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_historico_arquivo_cse")
@IdClass(HistoricoArquivoCseId.class)
public class HistoricoArquivoCse implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "har_codigo", nullable = false)
    private Long harCodigo;

    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "har_codigo", referencedColumnName = "har_codigo", insertable = false, updatable = false)
    private HistoricoArquivo historicoArquivo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false)
    private Consignante consignante;

    /**
     * Constructor
     */
    public HistoricoArquivoCse() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setHarCodigo(Long harCodigo) {
        this.harCodigo = harCodigo;
    }

    public Long getHarCodigo() {
        return harCodigo;
    }

    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    //--- GETTERS FOR LINKS
    public HistoricoArquivo getHistoricoArquivo() {
        return historicoArquivo;
    }

    public void setHistoricoArquivo(HistoricoArquivo historicoArquivo) {
        this.historicoArquivo = historicoArquivo;
        setHarCodigo(historicoArquivo != null ? historicoArquivo.getHarCodigo() : null);
    }

    public Consignante getConsignante() {
        return consignante;
    }

    public void setConsignante(Consignante consignante) {
        this.consignante = consignante;
        setCseCodigo(consignante != null ? consignante.getCseCodigo() : null);
    }

    public void setId(HistoricoArquivoCseId id) {
        setCseCodigo(id != null ? id.getCseCodigo() : null);
        setHarCodigo(id != null ? id.getHarCodigo() : null);
    }
}
