/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "HistoricoArquivoEst" ( stored in table "tb_historico_arquivo_est" )
 *
 * @author Telosys
 *
 */
public class HistoricoArquivoEstId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES
    private Long harCodigo;

    private String estCodigo;

    /**
     * Constructor
     */
    public HistoricoArquivoEstId() {
        super();
    }

    /**
     * Constructor with values
     * @param harCodigo
     * @param estCodigo
     */
    public HistoricoArquivoEstId(String estCodigo, Long harCodigo) {
        super();
        this.harCodigo = harCodigo;
        this.estCodigo = estCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setHarCodigo(Long value) {
        harCodigo = value;
    }

    public Long getHarCodigo() {
        return harCodigo;
    }

    public void setEstCodigo(String value) {
        estCodigo = value;
    }

    public String getEstCodigo() {
        return estCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        HistoricoArquivoEstId other = (HistoricoArquivoEstId) obj;
        //--- Attribute harCodigo
        if (harCodigo == null) {
            if (other.harCodigo != null) {
                return false;
            }
        } else if (!harCodigo.equals(other.harCodigo)) {
            return false;
        }
        //--- Attribute estCodigo
        if (estCodigo == null) {
            if (other.estCodigo != null) {
                return false;
            }
        } else if (!estCodigo.equals(other.estCodigo)) {
            return false;
        }
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute harCodigo
        result = prime * result + ((harCodigo == null) ? 0 : harCodigo.hashCode());
        //--- Attribute estCodigo
        result = prime * result + ((estCodigo == null) ? 0 : estCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(harCodigo);
        sb.append("|");
        sb.append(estCodigo);
        return sb.toString();
    }

}
