/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Composite primary key for entity "HistoricoConclusaoRetorno" ( stored in table "tb_historico_conclusao_retorno" )
 *
 * @author Telosys
 *
 */
public class HistoricoConclusaoRetornoId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String orgCodigo;

    private Date hcrDataInicio;

    /**
     * Constructor
     */
    public HistoricoConclusaoRetornoId() {
        super();
    }

    /**
     * Constructor with values
     * @param orgCodigo 
     * @param hcrDataInicio 
     */
    public HistoricoConclusaoRetornoId(String orgCodigo, Date hcrDataInicio) {
        super();
        this.orgCodigo = orgCodigo;
        this.hcrDataInicio = hcrDataInicio;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setOrgCodigo(String value) {
        this.orgCodigo = value;
    }

    public String getOrgCodigo() {
        return this.orgCodigo;
    }

    public void setHcrDataInicio(Date value) {
        this.hcrDataInicio = value;
    }

    public Date getHcrDataInicio() {
        return this.hcrDataInicio;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        HistoricoConclusaoRetornoId other = (HistoricoConclusaoRetornoId) obj;
        //--- Attribute orgCodigo
        if (orgCodigo == null) {
            if (other.orgCodigo != null)
                return false;
        } else if (!orgCodigo.equals(other.orgCodigo))
            return false;
        //--- Attribute hcrDataInicio
        if (hcrDataInicio == null) {
            if (other.hcrDataInicio != null)
                return false;
        } else if (!hcrDataInicio.equals(other.hcrDataInicio))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute orgCodigo
        result = prime * result + ((orgCodigo == null) ? 0 : orgCodigo.hashCode());
        //--- Attribute hcrDataInicio
        result = prime * result + ((hcrDataInicio == null) ? 0 : hcrDataInicio.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(orgCodigo);
        sb.append("|");
        sb.append(hcrDataInicio);
        return sb.toString();
    }

}
