/*
 * Created on 2021-12-30 ( 18:16:04 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "HistoricoArquivo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_historico_arquivo")
public class HistoricoArquivo implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "har_codigo", nullable = false)
    private Long harCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "tar_codigo", nullable = false, length = 32)
    private String tarCodigo;

    @Column(name = "har_nome_arquivo", nullable = false, length = 255)
    private String harNomeArquivo;

    @Column(name = "har_qtd_linhas", nullable = false)
    private Integer harQtdLinhas;

    @Column(name = "har_resultado_proc", nullable = false, length = 1)
    private String harResultadoProc;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "har_data_proc", nullable = false)
    private Date harDataProc;

    @Temporal(TemporalType.DATE)
    @Column(name = "har_periodo")
    private Date harPeriodo;

    @Column(name = "har_obs", length = 65535)
    private String harObs;

    @Column(name = "fun_codigo", length = 32)
    private String funCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tar_codigo", referencedColumnName = "tar_codigo", insertable = false, updatable = false)
    private TipoArquivo tipoArquivo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @OneToMany(mappedBy = "historicoArquivo", targetEntity = HistoricoArquivoCse.class)
    private Set<HistoricoArquivoCse> historicoArquivoCseSet;

    @OneToMany(mappedBy = "historicoArquivo", targetEntity = HistoricoArquivoEst.class)
    private Set<HistoricoArquivoEst> historicoArquivoEstSet;

    @OneToMany(mappedBy = "historicoArquivo", targetEntity = HistoricoArquivoOrg.class)
    private Set<HistoricoArquivoOrg> historicoArquivoOrgSet;

    @OneToMany(mappedBy = "historicoArquivo", targetEntity = HistoricoArquivoCsa.class)
    private Set<HistoricoArquivoCsa> historicoArquivoCsaSet;

    /**
     * Constructor
     */
    public HistoricoArquivo() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setHarCodigo(Long harCodigo) {
        this.harCodigo = harCodigo;
    }

    public Long getHarCodigo() {
        return harCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setTarCodigo(String tarCodigo) {
        this.tarCodigo = tarCodigo;
    }

    public String getTarCodigo() {
        return tarCodigo;
    }

    public void setHarNomeArquivo(String harNomeArquivo) {
        this.harNomeArquivo = harNomeArquivo;
    }

    public String getHarNomeArquivo() {
        return harNomeArquivo;
    }

    public void setHarQtdLinhas(Integer harQtdLinhas) {
        this.harQtdLinhas = harQtdLinhas;
    }

    public Integer getHarQtdLinhas() {
        return harQtdLinhas;
    }

    public void setHarResultadoProc(String harResultadoProc) {
        this.harResultadoProc = harResultadoProc;
    }

    public String getHarResultadoProc() {
        return harResultadoProc;
    }

    public void setHarDataProc(Date harDataProc) {
        this.harDataProc = harDataProc;
    }

    public Date getHarDataProc() {
        return harDataProc;
    }

    public void setHarPeriodo(Date harPeriodo) {
        this.harPeriodo = harPeriodo;
    }

    public Date getHarPeriodo() {
        return harPeriodo;
    }

    public void setHarObs(String harObs) {
        this.harObs = harObs;
    }

    public String getHarObs() {
        return harObs;
    }

    public void setFunCodigo(String funCodigo) {
        this.funCodigo = funCodigo;
    }

    public String getFunCodigo() {
        return funCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setTipoArquivo(TipoArquivo tipoArquivo) {
        this.tipoArquivo = tipoArquivo;
        setTarCodigo(tipoArquivo != null ? tipoArquivo.getTarCodigo() : null);
    }

    public TipoArquivo getTipoArquivo() {
        return tipoArquivo;
    }

    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
        setFunCodigo(funcao != null ? funcao.getFunCodigo() : null);
    }

    public Funcao getFuncao() {
        return funcao;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public Set<HistoricoArquivoCse> getHistoricoArquivoCseSet() {
        return historicoArquivoCseSet;
    }

    public Set<HistoricoArquivoEst> getHistoricoArquivoEstSet() {
        return historicoArquivoEstSet;
    }

    public Set<HistoricoArquivoOrg> getHistoricoArquivoOrgSet() {
        return historicoArquivoOrgSet;
    }

    public Set<HistoricoArquivoCsa> getHistoricoArquivoCsaSet() {
        return historicoArquivoCsaSet;
    }

}
