/*
 * Created on 2021-12-30 ( 18:16:05 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "HistoricoProcMargemOrg" ( stored in table "tb_historico_proc_margem_org" )
 *
 * @author Telosys
 *
 */
public class HistoricoProcMargemOrgId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES
    private Long hpmCodigo;

    private String orgCodigo;

    /**
     * Constructor
     */
    public HistoricoProcMargemOrgId() {
        super();
    }

    /**
     * Constructor with values
     * @param hpmCodigo
     * @param orgCodigo
     */
    public HistoricoProcMargemOrgId(String orgCodigo, Long hpmCodigo) {
        super();
        this.hpmCodigo = hpmCodigo;
        this.orgCodigo = orgCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setHpmCodigo(Long value) {
        hpmCodigo = value;
    }

    public Long getHpmCodigo() {
        return hpmCodigo;
    }

    public void setOrgCodigo(String value) {
        orgCodigo = value;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        HistoricoProcMargemOrgId other = (HistoricoProcMargemOrgId) obj;
        //--- Attribute hpmCodigo
        if (hpmCodigo == null) {
            if (other.hpmCodigo != null) {
                return false;
            }
        } else if (!hpmCodigo.equals(other.hpmCodigo)) {
            return false;
        }
        //--- Attribute orgCodigo
        if (orgCodigo == null) {
            if (other.orgCodigo != null) {
                return false;
            }
        } else if (!orgCodigo.equals(other.orgCodigo)) {
            return false;
        }
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute hpmCodigo
        result = prime * result + ((hpmCodigo == null) ? 0 : hpmCodigo.hashCode());
        //--- Attribute orgCodigo
        result = prime * result + ((orgCodigo == null) ? 0 : orgCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(hpmCodigo);
        sb.append("|");
        sb.append(orgCodigo);
        return sb.toString();
    }

}
