/*
 * Created on 2021-12-30 ( 18:16:05 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "HistoricoProcMargemOrg"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_historico_proc_margem_org")
@IdClass(HistoricoProcMargemOrgId.class)
public class HistoricoProcMargemOrg implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "hpm_codigo", nullable = false)
    private Long hpmCodigo;

    @Id
    @Column(name = "org_codigo", nullable = false, length = 32)
    private String orgCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hpm_codigo", referencedColumnName = "hpm_codigo", insertable = false, updatable = false)
    private HistoricoProcMargem historicoProcMargem;

    /**
     * Constructor
     */
    public HistoricoProcMargemOrg() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setHpmCodigo(Long hpmCodigo) {
        this.hpmCodigo = hpmCodigo;
    }

    public Long getHpmCodigo() {
        return hpmCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
    }

    public Orgao getOrgao() {
        return orgao;
    }

    public void setHistoricoProcMargem(HistoricoProcMargem historicoProcMargem) {
        this.historicoProcMargem = historicoProcMargem;
        setHpmCodigo(historicoProcMargem != null ? historicoProcMargem.getHpmCodigo() : null);
    }

    public HistoricoProcMargem getHistoricoProcMargem() {
        return historicoProcMargem;
    }

    public void setId(HistoricoProcMargemOrgId id) {
        setOrgCodigo(id != null ? id.getOrgCodigo() : null);
        setHpmCodigo(id != null ? id.getHpmCodigo() : null);
    }
}
