/*
 * Created on 2021-12-30 ( 18:16:05 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "HistoricoProcMargemCse"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_historico_proc_margem_cse")
@IdClass(HistoricoProcMargemCseId.class)
public class HistoricoProcMargemCse implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "hpm_codigo", nullable = false)
    private Long hpmCodigo;

    @Id
    @Column(name = "cse_codigo", nullable = false, length = 32)
    private String cseCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cse_codigo", referencedColumnName = "cse_codigo", insertable = false, updatable = false)
    private Consignante consignante;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hpm_codigo", referencedColumnName = "hpm_codigo", insertable = false, updatable = false)
    private HistoricoProcMargem historicoProcMargem;

    /**
     * Constructor
     */
    public HistoricoProcMargemCse() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setHpmCodigo(Long hpmCodigo) {
        this.hpmCodigo = hpmCodigo;
    }

    public Long getHpmCodigo() {
        return hpmCodigo;
    }

    public void setCseCodigo(String cseCodigo) {
        this.cseCodigo = cseCodigo;
    }

    public String getCseCodigo() {
        return cseCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setConsignante(Consignante consignante) {
        this.consignante = consignante;
        setCseCodigo(consignante != null ? consignante.getCseCodigo() : null);
    }

    public Consignante getConsignante() {
        return consignante;
    }

    public void setHistoricoProcMargem(HistoricoProcMargem historicoProcMargem) {
        this.historicoProcMargem = historicoProcMargem;
        setHpmCodigo(historicoProcMargem != null ? historicoProcMargem.getHpmCodigo() : null);
    }

    public HistoricoProcMargem getHistoricoProcMargem() {
        return historicoProcMargem;
    }

    public void setId(HistoricoProcMargemCseId id) {
        setCseCodigo(id != null ? id.getCseCodigo() : null);
        setHpmCodigo(id != null ? id.getHpmCodigo() : null);
    }
}
