/*
 * Created on 2021-12-30 ( 18:16:05 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "HistoricoExportacao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_historico_exportacao")
public class HistoricoExportacao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "hie_codigo", nullable = false, length = 32)
    private String hieCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "org_codigo", nullable = false, length = 32)
    private String orgCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hie_data_ini", nullable = false)
    private Date hieDataIni;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hie_data_fim", nullable = false)
    private Date hieDataFim;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hie_data", nullable = false)
    private Date hieData;

    @Temporal(TemporalType.DATE)
    @Column(name = "hie_periodo", nullable = false)
    private Date hiePeriodo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hie_data_inicio_exp", nullable = false)
    private Date hieDataInicioExp;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hie_data_fim_exp", nullable = false)
    private Date hieDataFimExp;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_codigo", referencedColumnName = "org_codigo", insertable = false, updatable = false)
    private Orgao orgao;

    /**
     * Constructor
     */
    public HistoricoExportacao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setHieCodigo(String hieCodigo) {
        this.hieCodigo = hieCodigo;
    }

    public String getHieCodigo() {
        return hieCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setHieDataIni(Date hieDataIni) {
        this.hieDataIni = hieDataIni;
    }

    public Date getHieDataIni() {
        return hieDataIni;
    }

    public void setHieDataFim(Date hieDataFim) {
        this.hieDataFim = hieDataFim;
    }

    public Date getHieDataFim() {
        return hieDataFim;
    }

    public void setHieData(Date hieData) {
        this.hieData = hieData;
    }

    public Date getHieData() {
        return hieData;
    }

    public void setHiePeriodo(Date hiePeriodo) {
        this.hiePeriodo = hiePeriodo;
    }

    public Date getHiePeriodo() {
        return hiePeriodo;
    }

    public void setHieDataInicioExp(Date hieDataInicioExp) {
        this.hieDataInicioExp = hieDataInicioExp;
    }

    public Date getHieDataInicioExp() {
        return hieDataInicioExp;
    }

    public void setHieDataFimExp(Date hieDataFimExp) {
        this.hieDataFimExp = hieDataFimExp;
    }

    public Date getHieDataFimExp() {
        return hieDataFimExp;
    }

    //--- GETTERS FOR LINKS
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
        setOrgCodigo(orgao != null ? orgao.getOrgCodigo() : null);
    }

    public Orgao getOrgao() {
        return orgao;
    }

}
