/*
 * Created on 2021-12-30 ( 18:16:05 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "HtOcorrenciaParcela"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "ht_ocorrencia_parcela")
public class HtOcorrenciaParcela implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ocp_codigo", nullable = false, length = 32)
    private String ocpCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "prd_codigo", nullable = false)
    private Integer prdCodigo;

    @Column(name = "toc_codigo", nullable = false, length = 32)
    private String tocCodigo;

    @Column(name = "usu_codigo", length = 32)
    private String usuCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ocp_data", nullable = false)
    private Date ocpData;

    @Column(name = "ocp_obs", length = 65535)
    private String ocpObs;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prd_codigo", referencedColumnName = "prd_codigo", insertable = false, updatable = false)
    private HtParcelaDesconto parcelaDesconto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "toc_codigo", referencedColumnName = "toc_codigo", insertable = false, updatable = false)
    private TipoOcorrencia tipoOcorrencia;

    /**
     * Constructor
     */
    public HtOcorrenciaParcela() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setOcpCodigo(String ocpCodigo) {
        this.ocpCodigo = ocpCodigo;
    }

    public String getOcpCodigo() {
        return ocpCodigo;
    }

    public void setPrdCodigo(Integer prdCodigo) {
        this.prdCodigo = prdCodigo;
    }

    public Integer getPrdCodigo() {
        return prdCodigo;
    }

    public void setTocCodigo(String tocCodigo) {
        this.tocCodigo = tocCodigo;
    }

    public String getTocCodigo() {
        return tocCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setOcpData(Date ocpData) {
        this.ocpData = ocpData;
    }

    public Date getOcpData() {
        return ocpData;
    }

    public void setOcpObs(String ocpObs) {
        this.ocpObs = ocpObs;
    }

    public String getOcpObs() {
        return ocpObs;
    }

    //--- GETTERS FOR LINKS
    public void setParcelaDesconto(HtParcelaDesconto htParcelaDesconto) {
        parcelaDesconto = htParcelaDesconto;
        setPrdCodigo(htParcelaDesconto != null ? htParcelaDesconto.getPrdCodigo() : null);
    }

    public HtParcelaDesconto getParcelaDesconto() {
        return parcelaDesconto;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setTipoOcorrencia(TipoOcorrencia tipoOcorrencia) {
        this.tipoOcorrencia = tipoOcorrencia;
        setTocCodigo(tipoOcorrencia != null ? tipoOcorrencia.getTocCodigo() : null);
    }

    public TipoOcorrencia getTipoOcorrencia() {
        return tipoOcorrencia;
    }

}
