/*
 * Created on 2021-12-30 ( 18:16:08 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "NaturezaServico"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_natureza_servico")
public class NaturezaServico implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "nse_codigo", nullable = false, length = 32)
    private String nseCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "nse_descricao", nullable = false, length = 40)
    private String nseDescricao;

    @Column(name = "nse_transferir_ade", nullable = false, length = 1)
    private String nseTransferirAde;

    @Column(name = "nse_ordem_beneficio", nullable = false)
    private Short nseOrdemBeneficio;

    @Lob
    @Column(name = "nse_imagem")
    private byte[] nseImagem;

    @Column(name = "nse_codigo_pai", length = 32)
    private String nseCodigoPai;

    @Column(name = "nse_descricao_portal", length = 40)
    private String nseDescricaoPortal;

    @Column(name = "nse_titulo_detalhe_topo", length = 255)
    private String nseTituloDetalheTopo;

    @Column(name = "nse_texto_detalhe_topo", length = 65535)
    private String nseTextoDetalheTopo;

    @Column(name = "nse_titulo_detalhe_rodape", length = 255)
    private String nseTituloDetalheRodape;

    @Column(name = "nse_texto_detalhe_rodape", length = 65535)
    private String nseTextoDetalheRodape;

    @Column(name = "nse_titulo_carousel_provedor", length = 255)
    private String nseTituloCarouselProvedor;

    @Column(name = "nse_retem_verba", nullable = false, length = 1)
    private String nseRetemVerba;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "naturezaServico", targetEntity = Beneficio.class)
    private Set<Beneficio> beneficioSet;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = TipoLancamento.class)
    private Set<TipoLancamento> tipoLancamentoSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nse_codigo_pai", referencedColumnName = "nse_codigo", insertable = false, updatable = false)
    private NaturezaServico naturezaServicoPai;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = ProvedorBeneficio.class)
    private Set<ProvedorBeneficio> provedorBeneficioSet;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = Servico.class)
    private Set<Servico> servicoSet;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = ParamNseRegistroSer.class)
    private Set<ParamNseRegistroSer> paramNseRegistroSerSet;

    @OneToMany(mappedBy = "naturezaServicoPai", targetEntity = NaturezaServico.class)
    private Set<NaturezaServico> naturezaServicoFilhoSet;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = BannerPublicidade.class)
    private Set<BannerPublicidade> bannerPublicidadeSet;

    @OneToMany(mappedBy = "naturezaServico", targetEntity = ParamPontuacaoRseCsa.class)
    private Set<ParamPontuacaoRseCsa> paramPontuacaoRseCsaSet;

    /**
     * Constructor
     */
    public NaturezaServico() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setNseCodigo(String nseCodigo) {
        this.nseCodigo = nseCodigo;
    }

    public String getNseCodigo() {
        return nseCodigo;
    }

    public void setNseDescricao(String nseDescricao) {
        this.nseDescricao = nseDescricao;
    }

    public String getNseDescricao() {
        return nseDescricao;
    }

    public void setNseTransferirAde(String nseTransferirAde) {
        this.nseTransferirAde = nseTransferirAde;
    }

    public String getNseTransferirAde() {
        return nseTransferirAde;
    }

    public void setNseOrdemBeneficio(Short nseOrdemBeneficio) {
        this.nseOrdemBeneficio = nseOrdemBeneficio;
    }

    public Short getNseOrdemBeneficio() {
        return nseOrdemBeneficio;
    }

    public void setNseImagem(byte[] nseImagem) {
        this.nseImagem = nseImagem;
    }

    public byte[] getNseImagem() {
        return nseImagem;
    }

    public void setNseCodigoPai(String nseCodigoPai) {
        this.nseCodigoPai = nseCodigoPai;
    }

    public String getNseCodigoPai() {
        return nseCodigoPai;
    }

    public void setNseDescricaoPortal(String nseDescricaoPortal) {
        this.nseDescricaoPortal = nseDescricaoPortal;
    }

    public String getNseDescricaoPortal() {
        return nseDescricaoPortal;
    }

    public void setNseTituloDetalheTopo(String nseTituloDetalheTopo) {
        this.nseTituloDetalheTopo = nseTituloDetalheTopo;
    }

    public String getNseTituloDetalheTopo() {
        return nseTituloDetalheTopo;
    }

    public void setNseTextoDetalheTopo(String nseTextoDetalheTopo) {
        this.nseTextoDetalheTopo = nseTextoDetalheTopo;
    }

    public String getNseTextoDetalheTopo() {
        return nseTextoDetalheTopo;
    }

    public void setNseTituloDetalheRodape(String nseTituloDetalheRodape) {
        this.nseTituloDetalheRodape = nseTituloDetalheRodape;
    }

    public String getNseTituloDetalheRodape() {
        return nseTituloDetalheRodape;
    }

    public void setNseTextoDetalheRodape(String nseTextoDetalheRodape) {
        this.nseTextoDetalheRodape = nseTextoDetalheRodape;
    }

    public String getNseTextoDetalheRodape() {
        return nseTextoDetalheRodape;
    }

    public void setNseTituloCarouselProvedor(String nseTituloCarouselProvedor) {
        this.nseTituloCarouselProvedor = nseTituloCarouselProvedor;
    }

    public String getNseTituloCarouselProvedor() {
        return nseTituloCarouselProvedor;
    }

    public String getNseRetemVerba() {
        return nseRetemVerba;
    }

    public void setNseRetemVerba(String nseRetemVerba) {
        this.nseRetemVerba = nseRetemVerba;
    }

    //--- GETTERS FOR LINKS
    public Set<Beneficio> getBeneficioSet() {
        return beneficioSet;
    }

    public Set<TipoLancamento> getTipoLancamentoSet() {
        return tipoLancamentoSet;
    }

    public void setNaturezaServicoPai(NaturezaServico naturezaServico) {
        naturezaServicoPai = naturezaServico;
        setNseCodigoPai(naturezaServico != null ? naturezaServico.getNseCodigo() : null);
    }

    public NaturezaServico getNaturezaServicoPai() {
        return naturezaServicoPai;
    }

    public Set<ProvedorBeneficio> getProvedorBeneficioSet() {
        return provedorBeneficioSet;
    }

    public Set<Servico> getServicoSet() {
        return servicoSet;
    }

    public Set<ParamNseRegistroSer> getParamNseRegistroSerSet() {
        return paramNseRegistroSerSet;
    }

    public Set<NaturezaServico> getNaturezaServicoFilhoSet() {
        return naturezaServicoFilhoSet;
    }

    public Set<BannerPublicidade> getBannerPublicidadeSet() {
        return bannerPublicidadeSet;
    }

    public Set<ParamPontuacaoRseCsa> getParamPontuacaoRseCsaSet() {
        return paramPontuacaoRseCsaSet;
    }
}
