/*
 * Created on 2021-12-30 ( 18:16:08 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "NotificacaoUsuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_notificacao_usuario")
@IdClass(NotificacaoUsuarioId.class)
public class NotificacaoUsuario implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tno_codigo", nullable = false, length = 32)
    private String tnoCodigo;

    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "nus_ativo", nullable = false)
    private Short nusAtivo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tno_codigo", referencedColumnName = "tno_codigo", insertable = false, updatable = false)
    private TipoNotificacao tipoNotificacao;

    /**
     * Constructor
     */
    public NotificacaoUsuario() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTnoCodigo(String tnoCodigo) {
        this.tnoCodigo = tnoCodigo;
    }

    public String getTnoCodigo() {
        return tnoCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setNusAtivo(Short nusAtivo) {
        this.nusAtivo = nusAtivo;
    }

    public Short getNusAtivo() {
        return nusAtivo;
    }

    //--- GETTERS FOR LINKS
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setTipoNotificacao(TipoNotificacao tipoNotificacao) {
        this.tipoNotificacao = tipoNotificacao;
        setTnoCodigo(tipoNotificacao != null ? tipoNotificacao.getTnoCodigo() : null);
    }

    public TipoNotificacao getTipoNotificacao() {
        return tipoNotificacao;
    }

    public void setId(NotificacaoUsuarioId id) {
        setUsuCodigo(id != null ? id.getUsuCodigo() : null);
        setTnoCodigo(id != null ? id.getTnoCodigo() : null);
    }
}
