/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "OcorrenciaDespIndividual"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_ocorrencia_desp_individual")
public class OcorrenciaDespIndividual implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "odi_codigo", nullable = false, length = 32)
    private String odiCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "ade_codigo", nullable = false, length = 32)
    private String adeCodigo;

    @Column(name = "toc_codigo", nullable = false, length = 32)
    private String tocCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "odi_data", nullable = false)
    private Date odiData;

    @Column(name = "odi_ip_acesso", length = 45)
    private String odiIpAcesso;

    @Column(name = "odi_obs", nullable = false, length = 65535)
    private String odiObs;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ade_codigo", referencedColumnName = "ade_codigo", insertable = false, updatable = false)
    private DespesaIndividual despesaIndividual;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "toc_codigo", referencedColumnName = "toc_codigo", insertable = false, updatable = false)
    private TipoOcorrencia tipoOcorrencia;

    /**
     * Constructor
     */
    public OcorrenciaDespIndividual() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setOdiCodigo(String odiCodigo) {
        this.odiCodigo = odiCodigo;
    }

    public String getOdiCodigo() {
        return odiCodigo;
    }

    public void setAdeCodigo(String adeCodigo) {
        this.adeCodigo = adeCodigo;
    }

    public String getAdeCodigo() {
        return adeCodigo;
    }

    public void setTocCodigo(String tocCodigo) {
        this.tocCodigo = tocCodigo;
    }

    public String getTocCodigo() {
        return tocCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setOdiData(Date odiData) {
        this.odiData = odiData;
    }

    public Date getOdiData() {
        return odiData;
    }

    public void setOdiIpAcesso(String odiIpAcesso) {
        this.odiIpAcesso = odiIpAcesso;
    }

    public String getOdiIpAcesso() {
        return odiIpAcesso;
    }

    public void setOdiObs(String odiObs) {
        this.odiObs = odiObs;
    }

    public String getOdiObs() {
        return odiObs;
    }

    //--- GETTERS FOR LINKS
    public void setDespesaIndividual(DespesaIndividual despesaIndividual) {
        this.despesaIndividual = despesaIndividual;
        setAdeCodigo(despesaIndividual != null ? despesaIndividual.getAdeCodigo() : null);
    }

    public DespesaIndividual getDespesaIndividual() {
        return despesaIndividual;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setTipoOcorrencia(TipoOcorrencia tipoOcorrencia) {
        this.tipoOcorrencia = tipoOcorrencia;
        setTocCodigo(tipoOcorrencia != null ? tipoOcorrencia.getTocCodigo() : null);
    }

    public TipoOcorrencia getTipoOcorrencia() {
        return tipoOcorrencia;
    }

}
