/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "OcorrenciaRegistroSer"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_ocorrencia_registro_ser")
public class OcorrenciaRegistroSer implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ors_codigo", nullable = false, length = 32)
    private String orsCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "toc_codigo", nullable = false, length = 32)
    private String tocCodigo;

    @Column(name = "rse_codigo", nullable = false, length = 32)
    private String rseCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ors_data", nullable = false)
    private Date orsData;

    @Column(name = "ors_obs", nullable = false, length = 65535)
    private String orsObs;

    @Column(name = "ors_ip_acesso", length = 45)
    private String orsIpAcesso;

    @Column(name = "tmo_codigo", length = 32)
    private String tmoCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "toc_codigo", referencedColumnName = "toc_codigo", insertable = false, updatable = false)
    private TipoOcorrencia tipoOcorrencia;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tmo_codigo", referencedColumnName = "tmo_codigo", insertable = false, updatable = false)
    private TipoMotivoOperacao tipoMotivoOperacao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rse_codigo", referencedColumnName = "rse_codigo", insertable = false, updatable = false)
    private RegistroServidor registroServidor;

    /**
     * Constructor
     */
    public OcorrenciaRegistroSer() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrsCodigo(String orsCodigo) {
        this.orsCodigo = orsCodigo;
    }

    public String getOrsCodigo() {
        return orsCodigo;
    }

    public void setTocCodigo(String tocCodigo) {
        this.tocCodigo = tocCodigo;
    }

    public String getTocCodigo() {
        return tocCodigo;
    }

    public void setRseCodigo(String rseCodigo) {
        this.rseCodigo = rseCodigo;
    }

    public String getRseCodigo() {
        return rseCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setOrsData(Date orsData) {
        this.orsData = orsData;
    }

    public Date getOrsData() {
        return orsData;
    }

    public void setOrsObs(String orsObs) {
        this.orsObs = orsObs;
    }

    public String getOrsObs() {
        return orsObs;
    }

    public void setOrsIpAcesso(String orsIpAcesso) {
        this.orsIpAcesso = orsIpAcesso;
    }

    public String getOrsIpAcesso() {
        return orsIpAcesso;
    }

    public void setTmoCodigo(String tmoCodigo) {
        this.tmoCodigo = tmoCodigo;
    }

    public String getTmoCodigo() {
        return tmoCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setTipoOcorrencia(TipoOcorrencia tipoOcorrencia) {
        this.tipoOcorrencia = tipoOcorrencia;
        setTocCodigo(tipoOcorrencia != null ? tipoOcorrencia.getTocCodigo() : null);
    }

    public TipoOcorrencia getTipoOcorrencia() {
        return tipoOcorrencia;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setTipoMotivoOperacao(TipoMotivoOperacao tipoMotivoOperacao) {
        this.tipoMotivoOperacao = tipoMotivoOperacao;
        setTmoCodigo(tipoMotivoOperacao != null ? tipoMotivoOperacao.getTmoCodigo() : null);
    }

    public TipoMotivoOperacao getTipoMotivoOperacao() {
        return tipoMotivoOperacao;
    }

    public void setRegistroServidor(RegistroServidor registroServidor) {
        this.registroServidor = registroServidor;
        setRseCodigo(registroServidor != null ? registroServidor.getRseCodigo() : null);
    }

    public RegistroServidor getRegistroServidor() {
        return registroServidor;
    }

}
