/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "OperacaoNaoConfirmada"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_operacao_nao_confirmada")
public class OperacaoNaoConfirmada implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "onc_codigo", nullable = false, length = 32)
    private String oncCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "acr_codigo", nullable = false, length = 32)
    private String acrCodigo;

    @Column(name = "onc_ip_acesso", nullable = false, length = 45)
    private String oncIpAcesso;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "onc_data", nullable = false)
    private Date oncData;

    @Column(name = "onc_detalhe", nullable = false, length = 2147483647)
    private String oncDetalhe;

    @Column(name = "onc_parametros", nullable = false, length = 65535)
    private String oncParametros;
    
    @Column(name = "rse_codigo", length = 32)
    private String rseCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acr_codigo", referencedColumnName = "acr_codigo", insertable = false, updatable = false)
    private AcessoRecurso acessoRecurso;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rse_codigo", referencedColumnName = "rse_codigo", insertable = false, updatable = false)
    private RegistroServidor registroServidor;

    @OneToMany(mappedBy = "operacaoNaoConfirmada", targetEntity = ArquivoOpeNaoConfirmadas.class)
    private Set<ArquivoOpeNaoConfirmadas> arquivoOpeNaoConfirmadasSet;

    /**
     * Constructor
     */
    public OperacaoNaoConfirmada() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setOncCodigo(String oncCodigo) {
        this.oncCodigo = oncCodigo;
    }

    public String getOncCodigo() {
        return oncCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setAcrCodigo(String acrCodigo) {
        this.acrCodigo = acrCodigo;
    }

    public String getAcrCodigo() {
        return acrCodigo;
    }

    public void setOncIpAcesso(String oncIpAcesso) {
        this.oncIpAcesso = oncIpAcesso;
    }

    public String getOncIpAcesso() {
        return oncIpAcesso;
    }

    public void setOncData(Date oncData) {
        this.oncData = oncData;
    }

    public Date getOncData() {
        return oncData;
    }

    public void setOncDetalhe(String oncDetalhe) {
        this.oncDetalhe = oncDetalhe;
    }

    public String getOncDetalhe() {
        return oncDetalhe;
    }

    public void setOncParametros(String oncParametros) {
        this.oncParametros = oncParametros;
    }

    public String getOncParametros() {
        return oncParametros;
    }

    //--- GETTERS FOR LINKS
    public void setAcessoRecurso(AcessoRecurso acessoRecurso) {
        this.acessoRecurso = acessoRecurso;
        setAcrCodigo(acessoRecurso != null ? acessoRecurso.getAcrCodigo() : null);
    }

    public AcessoRecurso getAcessoRecurso() {
        return acessoRecurso;
    }

    public Set<ArquivoOpeNaoConfirmadas> getArquivoOpeNaoConfirmadasSet() {
        return arquivoOpeNaoConfirmadasSet;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public String getRseCodigo() {
        return rseCodigo;
    }

    public void setRseCodigo(String rseCodigo) {
        this.rseCodigo = rseCodigo;
    }

}
