/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Orgao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_orgao")
public class Orgao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "org_codigo", nullable = false, length = 32)
    private String orgCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "est_codigo", nullable = false, length = 32)
    private String estCodigo;

    @Column(name = "org_identificador", nullable = false, length = 40)
    private String orgIdentificador;

    @Column(name = "org_nome", nullable = false, length = 100)
    private String orgNome;

    @Column(name = "org_email", length = 65535)
    private String orgEmail;

    @Column(name = "org_responsavel", length = 100)
    private String orgResponsavel;

    @Column(name = "org_resp_cargo", length = 100)
    private String orgRespCargo;

    @Column(name = "org_resp_telefone", length = 100)
    private String orgRespTelefone;

    @Column(name = "org_responsavel_2", length = 100)
    private String orgResponsavel2;

    @Column(name = "org_resp_cargo_2", length = 100)
    private String orgRespCargo2;

    @Column(name = "org_resp_telefone_2", length = 100)
    private String orgRespTelefone2;

    @Column(name = "org_responsavel_3", length = 100)
    private String orgResponsavel3;

    @Column(name = "org_resp_cargo_3", length = 100)
    private String orgRespCargo3;

    @Column(name = "org_resp_telefone_3", length = 100)
    private String orgRespTelefone3;

    @Column(name = "org_logradouro", length = 100)
    private String orgLogradouro;

    @Column(name = "org_nro")
    private Integer orgNro;

    @Column(name = "org_compl", length = 40)
    private String orgCompl;

    @Column(name = "org_bairro", length = 40)
    private String orgBairro;

    @Column(name = "org_cidade", length = 40)
    private String orgCidade;

    @Column(name = "org_uf", length = 5)
    private String orgUf;

    @Column(name = "org_cep", length = 10)
    private String orgCep;

    @Column(name = "org_tel", length = 100)
    private String orgTel;

    @Column(name = "org_fax", length = 100)
    private String orgFax;

    @Column(name = "org_ativo")
    private Short orgAtivo;

    @Column(name = "org_cnpj", length = 19)
    private String orgCnpj;

    @Column(name = "org_nome_abrev", length = 40)
    private String orgNomeAbrev;

    @Column(name = "org_dia_repasse")
    private Integer orgDiaRepasse;

    @Column(name = "org_ip_acesso", length = 65535)
    private String orgIpAcesso;

    @Column(name = "org_ddns_acesso", length = 65535)
    private String orgDdnsAcesso;

    @Column(name = "org_email_folha", length = 65535)
    private String orgEmailFolha;

    @Column(name = "org_folha", length = 40)
    private String orgFolha;

    @Column(name = "org_email_validar_servidor", length = 65535)
    private String orgEmailValidarServidor;

    @Column(name = "org_identificador_beneficio", length = 40)
    private String orgIdentificadorBeneficio;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "orgao", targetEntity = PeriodoBeneficio.class)
    private Set<PeriodoBeneficio> periodoBeneficioSet;

    @OneToMany(mappedBy = "orgao", targetEntity = ComunicacaoOrg.class)
    private Set<ComunicacaoOrg> comunicacaoOrgSet;

    @OneToMany(mappedBy = "orgao", targetEntity = CalculoBeneficio.class)
    private Set<CalculoBeneficio> calculoBeneficioSet;

    @OneToMany(mappedBy = "orgao", targetEntity = HistoricoConclusaoRetorno.class)
    private Set<HistoricoConclusaoRetorno> historicoConclusaoRetornoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = HistoricoExportacao.class)
    private Set<HistoricoExportacao> historicoExportacaoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = ParamOrgao.class)
    private Set<ParamOrgao> paramOrgaoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = DefinicaoTaxaJuros.class)
    private Set<DefinicaoTaxaJuros> definicaoTaxaJurosSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "est_codigo", referencedColumnName = "est_codigo", insertable = false, updatable = false)
    private Estabelecimento estabelecimento;

    @OneToMany(mappedBy = "orgao", targetEntity = SubOrgao.class)
    private Set<SubOrgao> subOrgaoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = ParamValidacaoArqOrg.class)
    private Set<ParamValidacaoArqOrg> paramValidacaoArqOrgSet;

    @OneToMany(mappedBy = "orgao", targetEntity = HistoricoProcessamento.class)
    private Set<HistoricoProcessamento> historicoProcessamentoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = PerfilOrg.class)
    private Set<PerfilOrg> perfilOrgSet;

    @OneToMany(mappedBy = "orgao", targetEntity = BlocoProcessamento.class)
    private Set<BlocoProcessamento> blocoProcessamentoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = OcorrenciaOrgao.class)
    private Set<OcorrenciaOrgao> ocorrenciaOrgaoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = Convenio.class)
    private Set<Convenio> convenioSet;

    @OneToMany(mappedBy = "orgao", targetEntity = CalendarioFolhaOrg.class)
    private Set<CalendarioFolhaOrg> calendarioFolhaOrgSet;

    @OneToMany(mappedBy = "orgao", targetEntity = PeriodoExportacao.class)
    private Set<PeriodoExportacao> periodoExportacaoSet;

    @OneToMany(mappedBy = "orgao", targetEntity = RegistroServidor.class)
    private Set<RegistroServidor> registroServidorSet;

    @OneToMany(mappedBy = "orgao", targetEntity = UsuarioOrg.class)
    private Set<UsuarioOrg> usuarioOrgSet;

    @OneToMany(mappedBy = "orgao", targetEntity = LimiteMargemCsaOrg.class)
    private Set<LimiteMargemCsaOrg> limiteMargemCsaOrgSet;
    /**
     * Constructor
     */
    public Orgao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }

    public String getOrgCodigo() {
        return orgCodigo;
    }

    public void setEstCodigo(String estCodigo) {
        this.estCodigo = estCodigo;
    }

    public String getEstCodigo() {
        return estCodigo;
    }

    public void setOrgIdentificador(String orgIdentificador) {
        this.orgIdentificador = orgIdentificador;
    }

    public String getOrgIdentificador() {
        return orgIdentificador;
    }

    public void setOrgNome(String orgNome) {
        this.orgNome = orgNome;
    }

    public String getOrgNome() {
        return orgNome;
    }

    public void setOrgEmail(String orgEmail) {
        this.orgEmail = orgEmail;
    }

    public String getOrgEmail() {
        return orgEmail;
    }

    public void setOrgResponsavel(String orgResponsavel) {
        this.orgResponsavel = orgResponsavel;
    }

    public String getOrgResponsavel() {
        return orgResponsavel;
    }

    public void setOrgRespCargo(String orgRespCargo) {
        this.orgRespCargo = orgRespCargo;
    }

    public String getOrgRespCargo() {
        return orgRespCargo;
    }

    public void setOrgRespTelefone(String orgRespTelefone) {
        this.orgRespTelefone = orgRespTelefone;
    }

    public String getOrgRespTelefone() {
        return orgRespTelefone;
    }

    public void setOrgResponsavel2(String orgResponsavel2) {
        this.orgResponsavel2 = orgResponsavel2;
    }

    public String getOrgResponsavel2() {
        return orgResponsavel2;
    }

    public void setOrgRespCargo2(String orgRespCargo2) {
        this.orgRespCargo2 = orgRespCargo2;
    }

    public String getOrgRespCargo2() {
        return orgRespCargo2;
    }

    public void setOrgRespTelefone2(String orgRespTelefone2) {
        this.orgRespTelefone2 = orgRespTelefone2;
    }

    public String getOrgRespTelefone2() {
        return orgRespTelefone2;
    }

    public void setOrgResponsavel3(String orgResponsavel3) {
        this.orgResponsavel3 = orgResponsavel3;
    }

    public String getOrgResponsavel3() {
        return orgResponsavel3;
    }

    public void setOrgRespCargo3(String orgRespCargo3) {
        this.orgRespCargo3 = orgRespCargo3;
    }

    public String getOrgRespCargo3() {
        return orgRespCargo3;
    }

    public void setOrgRespTelefone3(String orgRespTelefone3) {
        this.orgRespTelefone3 = orgRespTelefone3;
    }

    public String getOrgRespTelefone3() {
        return orgRespTelefone3;
    }

    public void setOrgLogradouro(String orgLogradouro) {
        this.orgLogradouro = orgLogradouro;
    }

    public String getOrgLogradouro() {
        return orgLogradouro;
    }

    public void setOrgNro(Integer orgNro) {
        this.orgNro = orgNro;
    }

    public Integer getOrgNro() {
        return orgNro;
    }

    public void setOrgCompl(String orgCompl) {
        this.orgCompl = orgCompl;
    }

    public String getOrgCompl() {
        return orgCompl;
    }

    public void setOrgBairro(String orgBairro) {
        this.orgBairro = orgBairro;
    }

    public String getOrgBairro() {
        return orgBairro;
    }

    public void setOrgCidade(String orgCidade) {
        this.orgCidade = orgCidade;
    }

    public String getOrgCidade() {
        return orgCidade;
    }

    public void setOrgUf(String orgUf) {
        this.orgUf = orgUf;
    }

    public String getOrgUf() {
        return orgUf;
    }

    public void setOrgCep(String orgCep) {
        this.orgCep = orgCep;
    }

    public String getOrgCep() {
        return orgCep;
    }

    public void setOrgTel(String orgTel) {
        this.orgTel = orgTel;
    }

    public String getOrgTel() {
        return orgTel;
    }

    public void setOrgFax(String orgFax) {
        this.orgFax = orgFax;
    }

    public String getOrgFax() {
        return orgFax;
    }

    public void setOrgAtivo(Short orgAtivo) {
        this.orgAtivo = orgAtivo;
    }

    public Short getOrgAtivo() {
        return orgAtivo;
    }

    public void setOrgCnpj(String orgCnpj) {
        this.orgCnpj = orgCnpj;
    }

    public String getOrgCnpj() {
        return orgCnpj;
    }

    public void setOrgNomeAbrev(String orgNomeAbrev) {
        this.orgNomeAbrev = orgNomeAbrev;
    }

    public String getOrgNomeAbrev() {
        return orgNomeAbrev;
    }

    public void setOrgDiaRepasse(Integer orgDiaRepasse) {
        this.orgDiaRepasse = orgDiaRepasse;
    }

    public Integer getOrgDiaRepasse() {
        return orgDiaRepasse;
    }

    public void setOrgIpAcesso(String orgIpAcesso) {
        this.orgIpAcesso = orgIpAcesso;
    }

    public String getOrgIpAcesso() {
        return orgIpAcesso;
    }

    public void setOrgDdnsAcesso(String orgDdnsAcesso) {
        this.orgDdnsAcesso = orgDdnsAcesso;
    }

    public String getOrgDdnsAcesso() {
        return orgDdnsAcesso;
    }

    public void setOrgEmailFolha(String orgEmailFolha) {
        this.orgEmailFolha = orgEmailFolha;
    }

    public String getOrgEmailFolha() {
        return orgEmailFolha;
    }

    public void setOrgFolha(String orgFolha) {
        this.orgFolha = orgFolha;
    }

    public String getOrgFolha() {
        return orgFolha;
    }

    public void setOrgEmailValidarServidor(String orgEmailValidarServidor) {
        this.orgEmailValidarServidor = orgEmailValidarServidor;
    }

    public String getOrgEmailValidarServidor() {
        return orgEmailValidarServidor;
    }

    public void setOrgIdentificadorBeneficio(String orgIdentificadorBeneficio) {
        this.orgIdentificadorBeneficio = orgIdentificadorBeneficio;
    }

    public String getOrgIdentificadorBeneficio() {
        return orgIdentificadorBeneficio;
    }

    //--- GETTERS FOR LINKS
    public Set<PeriodoBeneficio> getPeriodoBeneficioSet() {
        return periodoBeneficioSet;
    }

    public Set<ComunicacaoOrg> getComunicacaoOrgSet() {
        return comunicacaoOrgSet;
    }

    public Set<CalculoBeneficio> getCalculoBeneficioSet() {
        return calculoBeneficioSet;
    }

    public Set<HistoricoConclusaoRetorno> getHistoricoConclusaoRetornoSet() {
        return historicoConclusaoRetornoSet;
    }

    public Set<HistoricoExportacao> getHistoricoExportacaoSet() {
        return historicoExportacaoSet;
    }

    public Set<ParamOrgao> getParamOrgaoSet() {
        return paramOrgaoSet;
    }

    public Set<DefinicaoTaxaJuros> getDefinicaoTaxaJurosSet() {
        return definicaoTaxaJurosSet;
    }

    public void setEstabelecimento(Estabelecimento estabelecimento) {
        this.estabelecimento = estabelecimento;
        setEstCodigo(estabelecimento != null ? estabelecimento.getEstCodigo() : null);
    }

    public Estabelecimento getEstabelecimento() {
        return estabelecimento;
    }

    public Set<SubOrgao> getSubOrgaoSet() {
        return subOrgaoSet;
    }

    public Set<ParamValidacaoArqOrg> getParamValidacaoArqOrgSet() {
        return paramValidacaoArqOrgSet;
    }

    public Set<HistoricoProcessamento> getHistoricoProcessamentoSet() {
        return historicoProcessamentoSet;
    }

    public Set<PerfilOrg> getPerfilOrgSet() {
        return perfilOrgSet;
    }

    public Set<BlocoProcessamento> getBlocoProcessamentoSet() {
        return blocoProcessamentoSet;
    }

    public Set<OcorrenciaOrgao> getOcorrenciaOrgaoSet() {
        return ocorrenciaOrgaoSet;
    }

    public Set<Convenio> getConvenioSet() {
        return convenioSet;
    }

    public Set<CalendarioFolhaOrg> getCalendarioFolhaOrgSet() {
        return calendarioFolhaOrgSet;
    }

    public Set<PeriodoExportacao> getPeriodoExportacaoSet() {
        return periodoExportacaoSet;
    }

    public Set<RegistroServidor> getRegistroServidorSet() {
        return registroServidorSet;
    }

    public Set<UsuarioOrg> getUsuarioOrgSet() {
        return usuarioOrgSet;
    }

    public Set<LimiteMargemCsaOrg> getLimiteMargemCsaOrgSet() {
        return limiteMargemCsaOrgSet;
    }
}
