/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "PalavraChaveBeneficio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_palavra_chave_beneficio")
@IdClass(PalavraChaveBeneficioId.class)
public class PalavraChaveBeneficio implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ben_codigo", nullable = false, length = 32)
    private String benCodigo;

    @Id
    @Column(name = "pch_codigo", nullable = false)
    private Integer pchCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ben_codigo", referencedColumnName = "ben_codigo", insertable = false, updatable = false)
    private Beneficio beneficio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pch_codigo", referencedColumnName = "pch_codigo", insertable = false, updatable = false)
    private PalavraChave palavraChave;

    /**
     * Constructor
     */
    public PalavraChaveBeneficio() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setBenCodigo(String benCodigo) {
        this.benCodigo = benCodigo;
    }

    public String getBenCodigo() {
        return benCodigo;
    }

    public void setPchCodigo(Integer pchCodigo) {
        this.pchCodigo = pchCodigo;
    }

    public Integer getPchCodigo() {
        return pchCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
        setBenCodigo(beneficio != null ? beneficio.getBenCodigo() : null);
    }

    public Beneficio getBeneficio() {
        return beneficio;
    }

    public void setPalavraChave(PalavraChave palavraChave) {
        this.palavraChave = palavraChave;
        setPchCodigo(palavraChave != null ? palavraChave.getPchCodigo() : null);
    }

    public PalavraChave getPalavraChave() {
        return palavraChave;
    }

    public void setId(PalavraChaveBeneficioId id) {
        setBenCodigo(id != null ? id.getBenCodigo() : null);
        setPchCodigo(id != null ? id.getPchCodigo() : null);
    }
}
