/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ParamServicoRegistroSer"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_param_servico_registro_ser")
@IdClass(ParamServicoRegistroSerId.class)
public class ParamServicoRegistroSer implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tps_codigo", nullable = false, length = 32)
    private String tpsCodigo;

    @Id
    @Column(name = "svc_codigo", nullable = false, length = 32)
    private String svcCodigo;

    @Id
    @Column(name = "rse_codigo", nullable = false, length = 32)
    private String rseCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "psr_vlr", nullable = false, length = 255)
    private String psrVlr;

    @Column(name = "psr_obs", length = 65535)
    private String psrObs;

    @Column(name = "psr_alterado_pelo_servidor", length = 1)
    private String psrAlteradoPeloServidor;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "psr_data_cadastro")
    private Date psrDataCadastro;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tps_codigo", referencedColumnName = "tps_codigo", insertable = false, updatable = false)
    private TipoParamSvc tipoParamSvc;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "svc_codigo", referencedColumnName = "svc_codigo", insertable = false, updatable = false)
    private Servico servico;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rse_codigo", referencedColumnName = "rse_codigo", insertable = false, updatable = false)
    private RegistroServidor registroServidor;

    /**
     * Constructor
     */
    public ParamServicoRegistroSer() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTpsCodigo(String tpsCodigo) {
        this.tpsCodigo = tpsCodigo;
    }

    public String getTpsCodigo() {
        return tpsCodigo;
    }

    public void setSvcCodigo(String svcCodigo) {
        this.svcCodigo = svcCodigo;
    }

    public String getSvcCodigo() {
        return svcCodigo;
    }

    public void setRseCodigo(String rseCodigo) {
        this.rseCodigo = rseCodigo;
    }

    public String getRseCodigo() {
        return rseCodigo;
    }

    public void setPsrVlr(String psrVlr) {
        this.psrVlr = psrVlr;
    }

    public String getPsrVlr() {
        return psrVlr;
    }

    public void setPsrObs(String psrObs) {
        this.psrObs = psrObs;
    }

    public String getPsrObs() {
        return psrObs;
    }

    public void setPsrAlteradoPeloServidor(String psrAlteradoPeloServidor) {
        this.psrAlteradoPeloServidor = psrAlteradoPeloServidor;
    }

    public String getPsrAlteradoPeloServidor() {
        return psrAlteradoPeloServidor;
    }

    public void setPsrDataCadastro(Date psrDataCadastro) {
        this.psrDataCadastro = psrDataCadastro;
    }

    public Date getPsrDataCadastro() {
        return psrDataCadastro;
    }

    //--- GETTERS FOR LINKS
    public void setTipoParamSvc(TipoParamSvc tipoParamSvc) {
        this.tipoParamSvc = tipoParamSvc;
        setTpsCodigo(tipoParamSvc != null ? tipoParamSvc.getTpsCodigo() : null);
    }

    public TipoParamSvc getTipoParamSvc() {
        return tipoParamSvc;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
        setSvcCodigo(servico != null ? servico.getSvcCodigo() : null);
    }

    public Servico getServico() {
        return servico;
    }

    public void setRegistroServidor(RegistroServidor registroServidor) {
        this.registroServidor = registroServidor;
        setRseCodigo(registroServidor != null ? registroServidor.getRseCodigo() : null);
    }

    public RegistroServidor getRegistroServidor() {
        return registroServidor;
    }

    public void setId(ParamServicoRegistroSerId id) {
        setRseCodigo(id != null ? id.getRseCodigo() : null);
        setSvcCodigo(id != null ? id.getSvcCodigo() : null);
        setTpsCodigo(id != null ? id.getTpsCodigo() : null);
    }
}
