/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ParamSvcCorrespondente"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_param_svc_correspondente")
public class ParamSvcCorrespondente implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "pso_codigo", nullable = false, length = 32)
    private String psoCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tps_codigo", nullable = false, length = 32)
    private String tpsCodigo;

    @Column(name = "cor_codigo", nullable = false, length = 32)
    private String corCodigo;

    @Column(name = "svc_codigo", nullable = false, length = 32)
    private String svcCodigo;

    @Temporal(TemporalType.DATE)
    @Column(name = "pso_data_ini_vig")
    private Date psoDataIniVig;

    @Temporal(TemporalType.DATE)
    @Column(name = "pso_data_fim_vig")
    private Date psoDataFimVig;

    @Column(name = "pso_ativo")
    private Short psoAtivo;

    @Column(name = "pso_vlr", length = 255)
    private String psoVlr;

    @Column(name = "pso_vlr_ref", length = 255)
    private String psoVlrRef;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cor_codigo", referencedColumnName = "cor_codigo", insertable = false, updatable = false)
    private Correspondente correspondente;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "svc_codigo", referencedColumnName = "svc_codigo", insertable = false, updatable = false)
    private Servico servico;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tps_codigo", referencedColumnName = "tps_codigo", insertable = false, updatable = false)
    private TipoParamSvc tipoParamSvc;

    /**
     * Constructor
     */
    public ParamSvcCorrespondente() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setPsoCodigo(String psoCodigo) {
        this.psoCodigo = psoCodigo;
    }

    public String getPsoCodigo() {
        return psoCodigo;
    }

    public void setTpsCodigo(String tpsCodigo) {
        this.tpsCodigo = tpsCodigo;
    }

    public String getTpsCodigo() {
        return tpsCodigo;
    }

    public void setCorCodigo(String corCodigo) {
        this.corCodigo = corCodigo;
    }

    public String getCorCodigo() {
        return corCodigo;
    }

    public void setSvcCodigo(String svcCodigo) {
        this.svcCodigo = svcCodigo;
    }

    public String getSvcCodigo() {
        return svcCodigo;
    }

    public void setPsoDataIniVig(Date psoDataIniVig) {
        this.psoDataIniVig = psoDataIniVig;
    }

    public Date getPsoDataIniVig() {
        return psoDataIniVig;
    }

    public void setPsoDataFimVig(Date psoDataFimVig) {
        this.psoDataFimVig = psoDataFimVig;
    }

    public Date getPsoDataFimVig() {
        return psoDataFimVig;
    }

    public void setPsoAtivo(Short psoAtivo) {
        this.psoAtivo = psoAtivo;
    }

    public Short getPsoAtivo() {
        return psoAtivo;
    }

    public void setPsoVlr(String psoVlr) {
        this.psoVlr = psoVlr;
    }

    public String getPsoVlr() {
        return psoVlr;
    }

    public void setPsoVlrRef(String psoVlrRef) {
        this.psoVlrRef = psoVlrRef;
    }

    public String getPsoVlrRef() {
        return psoVlrRef;
    }

    //--- GETTERS FOR LINKS
    public void setCorrespondente(Correspondente correspondente) {
        this.correspondente = correspondente;
        setCorCodigo(correspondente != null ? correspondente.getCorCodigo() : null);
    }

    public Correspondente getCorrespondente() {
        return correspondente;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
        setSvcCodigo(servico != null ? servico.getSvcCodigo() : null);
    }

    public Servico getServico() {
        return servico;
    }

    public void setTipoParamSvc(TipoParamSvc tipoParamSvc) {
        this.tipoParamSvc = tipoParamSvc;
        setTpsCodigo(tipoParamSvc != null ? tipoParamSvc.getTpsCodigo() : null);
    }

    public TipoParamSvc getTipoParamSvc() {
        return tipoParamSvc;
    }

}
