/*
 * Created on 2021-12-30 ( 18:16:09 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "ParamSenhaExterna"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_param_senha_externa")
public class ParamSenhaExterna implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "psx_chave", nullable = false, length = 200)
    private String psxChave;

    //--- ENTITY DATA FIELDS 
    @Column(name = "psx_valor", nullable = false, length = 65535)
    private String psxValor;

    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public ParamSenhaExterna() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setPsxChave(String psxChave) {
        this.psxChave = psxChave;
    }

    public String getPsxChave() {
        return this.psxChave;
    }

    public void setPsxValor(String psxValor) {
        this.psxValor = psxValor;
    }

    public String getPsxValor() {
        return this.psxValor;
    }

    //--- GETTERS FOR LINKS
}
