/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "PerfilCse" ( stored in table "tb_perfil_cse" )
 *
 * @author Telosys
 *
 */
public class PerfilCseId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String cseCodigo;

    private String perCodigo;

    /**
     * Constructor
     */
    public PerfilCseId() {
        super();
    }

    /**
     * Constructor with values
     * @param cseCodigo 
     * @param perCodigo 
     */
    public PerfilCseId(String cseCodigo, String perCodigo) {
        super();
        this.cseCodigo = cseCodigo;
        this.perCodigo = perCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setCseCodigo(String value) {
        this.cseCodigo = value;
    }

    public String getCseCodigo() {
        return this.cseCodigo;
    }

    public void setPerCodigo(String value) {
        this.perCodigo = value;
    }

    public String getPerCodigo() {
        return this.perCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        PerfilCseId other = (PerfilCseId) obj;
        //--- Attribute cseCodigo
        if (cseCodigo == null) {
            if (other.cseCodigo != null)
                return false;
        } else if (!cseCodigo.equals(other.cseCodigo))
            return false;
        //--- Attribute perCodigo
        if (perCodigo == null) {
            if (other.perCodigo != null)
                return false;
        } else if (!perCodigo.equals(other.perCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute cseCodigo
        result = prime * result + ((cseCodigo == null) ? 0 : cseCodigo.hashCode());
        //--- Attribute perCodigo
        result = prime * result + ((perCodigo == null) ? 0 : perCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(cseCodigo);
        sb.append("|");
        sb.append(perCodigo);
        return sb.toString();
    }

}
