/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "PerfilUsuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_perfil_usuario")
public class PerfilUsuario implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "per_codigo", nullable = false, length = 32)
    private String perCodigo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "per_codigo", referencedColumnName = "per_codigo", insertable = false, updatable = false)
    private Perfil perfil;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public PerfilUsuario() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setPerCodigo(String perCodigo) {
        this.perCodigo = perCodigo;
    }

    public String getPerCodigo() {
        return perCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
        setPerCodigo(perfil != null ? perfil.getPerCodigo() : null);
    }

    public Perfil getPerfil() {
        return perfil;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

}
