/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;

/**
 * JPA entity class for "PerguntaDadosCadastrais"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_pergunta_dados_cadastrais")
@IdClass(PerguntaDadosCadastraisId.class)
public class PerguntaDadosCadastrais implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "pdc_grupo", nullable = false)
    private Short pdcGrupo;

    @Id
    @Column(name = "pdc_numero", nullable = false)
    private Short pdcNumero;

    //--- ENTITY DATA FIELDS
    @Column(name = "pdc_status", nullable = false)
    private Short pdcStatus;

    @Column(name = "pdc_texto", nullable = false, length = 100)
    private String pdcTexto;

    @Column(name = "pdc_campo", nullable = false, length = 255)
    private String pdcCampo;

    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public PerguntaDadosCadastrais() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setPdcGrupo(Short pdcGrupo) {
        this.pdcGrupo = pdcGrupo;
    }

    public Short getPdcGrupo() {
        return pdcGrupo;
    }

    public void setPdcNumero(Short pdcNumero) {
        this.pdcNumero = pdcNumero;
    }

    public Short getPdcNumero() {
        return pdcNumero;
    }

    public void setPdcStatus(Short pdcStatus) {
        this.pdcStatus = pdcStatus;
    }

    public Short getPdcStatus() {
        return pdcStatus;
    }

    public void setPdcTexto(String pdcTexto) {
        this.pdcTexto = pdcTexto;
    }

    public String getPdcTexto() {
        return pdcTexto;
    }

    public void setPdcCampo(String pdcCampo) {
        this.pdcCampo = pdcCampo;
    }

    public String getPdcCampo() {
        return pdcCampo;
    }

    //--- GETTERS FOR LINKS

    public void setId(PerguntaDadosCadastraisId id) {
        setPdcGrupo(id != null ? id.getPdcGrupo() : null);
        setPdcNumero(id != null ? id.getPdcNumero() : null);
    }

}
