/*
 * Created on 2021-12-30 ( 18:16:10 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Composite primary key for entity "PeriodoExportacao" ( stored in table "tb_periodo_exportacao" )
 *
 * @author Telosys
 *
 */
public class PeriodoExportacaoId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String orgCodigo;

    private Date pexPeriodo;

    /**
     * Constructor
     */
    public PeriodoExportacaoId() {
        super();
    }

    /**
     * Constructor with values
     * @param orgCodigo 
     * @param pexPeriodo 
     */
    public PeriodoExportacaoId(String orgCodigo, Date pexPeriodo) {
        super();
        this.orgCodigo = orgCodigo;
        this.pexPeriodo = pexPeriodo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setOrgCodigo(String value) {
        this.orgCodigo = value;
    }

    public String getOrgCodigo() {
        return this.orgCodigo;
    }

    public void setPexPeriodo(Date value) {
        this.pexPeriodo = value;
    }

    public Date getPexPeriodo() {
        return this.pexPeriodo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        PeriodoExportacaoId other = (PeriodoExportacaoId) obj;
        //--- Attribute orgCodigo
        if (orgCodigo == null) {
            if (other.orgCodigo != null)
                return false;
        } else if (!orgCodigo.equals(other.orgCodigo))
            return false;
        //--- Attribute pexPeriodo
        if (pexPeriodo == null) {
            if (other.pexPeriodo != null)
                return false;
        } else if (!pexPeriodo.equals(other.pexPeriodo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute orgCodigo
        result = prime * result + ((orgCodigo == null) ? 0 : orgCodigo.hashCode());
        //--- Attribute pexPeriodo
        result = prime * result + ((pexPeriodo == null) ? 0 : pexPeriodo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(orgCodigo);
        sb.append("|");
        sb.append(pexPeriodo);
        return sb.toString();
    }

}
