/*
 * Created on 2021-12-30 ( 18:16:11 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "PrazoConsignataria"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_prazo_consignataria")
public class PrazoConsignataria implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "prz_csa_codigo", nullable = false, length = 32)
    private String przCsaCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    @Column(name = "prz_codigo", nullable = false, length = 32)
    private String przCodigo;

    @Column(name = "prz_csa_ativo")
    private Short przCsaAtivo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    @OneToMany(mappedBy = "prazoConsignataria", targetEntity = Coeficiente.class)
    private Set<Coeficiente> coeficienteSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prz_codigo", referencedColumnName = "prz_codigo", insertable = false, updatable = false)
    private Prazo prazo;

    @OneToMany(mappedBy = "prazoConsignataria", targetEntity = CoeficienteAtivo.class)
    private Set<CoeficienteAtivo> coeficienteAtivoSet;

    /**
     * Constructor
     */
    public PrazoConsignataria() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setPrzCsaCodigo(String przCsaCodigo) {
        this.przCsaCodigo = przCsaCodigo;
    }

    public String getPrzCsaCodigo() {
        return przCsaCodigo;
    }

    public void setCsaCodigo(String csaCodigo) {
        this.csaCodigo = csaCodigo;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    public void setPrzCodigo(String przCodigo) {
        this.przCodigo = przCodigo;
    }

    public String getPrzCodigo() {
        return przCodigo;
    }

    public void setPrzCsaAtivo(Short przCsaAtivo) {
        this.przCsaAtivo = przCsaAtivo;
    }

    public Short getPrzCsaAtivo() {
        return przCsaAtivo;
    }

    //--- GETTERS FOR LINKS
    public void setConsignataria(Consignataria consignataria) {
        this.consignataria = consignataria;
        setCsaCodigo(consignataria != null ? consignataria.getCsaCodigo() : null);
    }

    public Consignataria getConsignataria() {
        return consignataria;
    }

    public Set<Coeficiente> getCoeficienteSet() {
        return coeficienteSet;
    }

    public void setPrazo(Prazo prazo) {
        this.prazo = prazo;
        setPrzCodigo(prazo != null ? prazo.getPrzCodigo() : null);
    }

    public Prazo getPrazo() {
        return prazo;
    }

    public Set<CoeficienteAtivo> getCoeficienteAtivoSet() {
        return coeficienteAtivoSet;
    }

}
