/*
 * Created on 2021-12-30 ( 18:16:11 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "ProvedorBeneficio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_provedor_beneficio")
public class ProvedorBeneficio implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "pro_codigo", nullable = false, length = 32)
    private String proCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "csa_codigo", nullable = false, length = 32)
    private String csaCodigo;

    @Column(name = "nse_codigo", nullable = false, length = 32)
    private String nseCodigo;

    @Column(name = "pro_titulo_detalhe_topo", nullable = false, length = 255)
    private String proTituloDetalheTopo;

    @Column(name = "pro_texto_detalhe_topo", nullable = false, length = 65535)
    private String proTextoDetalheTopo;

    @Column(name = "pro_titulo_detalhe_rodape", nullable = false, length = 255)
    private String proTituloDetalheRodape;

    @Column(name = "pro_texto_detalhe_rodape", nullable = false, length = 65535)
    private String proTextoDetalheRodape;

    @Column(name = "pro_titulo_lista_beneficio", nullable = false, length = 255)
    private String proTituloListaBeneficio;

    @Column(name = "pro_texto_card_beneficio", nullable = false, length = 65535)
    private String proTextoCardBeneficio;

    @Column(name = "pro_link_beneficio", length = 255)
    private String proLinkBeneficio;

    @Lob
    @Column(name = "pro_imagem_beneficio")
    private byte[] proImagemBeneficio;

    @Column(name = "cor_codigo", length = 32)
    private String corCodigo;

    @Column(name = "pro_agrupa", nullable = false, length = 1)
    private String proAgrupa;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nse_codigo", referencedColumnName = "nse_codigo", insertable = false, updatable = false)
    private NaturezaServico naturezaServico;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cor_codigo", referencedColumnName = "cor_codigo", insertable = false, updatable = false)
    private Correspondente correspondente;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "csa_codigo", referencedColumnName = "csa_codigo", insertable = false, updatable = false)
    private Consignataria consignataria;

    /**
     * Constructor
     */
    public ProvedorBeneficio() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setProCodigo(String proCodigo) {
        this.proCodigo = proCodigo;
    }

    public String getProCodigo() {
        return proCodigo;
    }

    public void setCsaCodigo(String csaCodigo) {
        this.csaCodigo = csaCodigo;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    public void setNseCodigo(String nseCodigo) {
        this.nseCodigo = nseCodigo;
    }

    public String getNseCodigo() {
        return nseCodigo;
    }

    public void setProTituloDetalheTopo(String proTituloDetalheTopo) {
        this.proTituloDetalheTopo = proTituloDetalheTopo;
    }

    public String getProTituloDetalheTopo() {
        return proTituloDetalheTopo;
    }

    public void setProTextoDetalheTopo(String proTextoDetalheTopo) {
        this.proTextoDetalheTopo = proTextoDetalheTopo;
    }

    public String getProTextoDetalheTopo() {
        return proTextoDetalheTopo;
    }

    public void setProTituloDetalheRodape(String proTituloDetalheRodape) {
        this.proTituloDetalheRodape = proTituloDetalheRodape;
    }

    public String getProTituloDetalheRodape() {
        return proTituloDetalheRodape;
    }

    public void setProTextoDetalheRodape(String proTextoDetalheRodape) {
        this.proTextoDetalheRodape = proTextoDetalheRodape;
    }

    public String getProTextoDetalheRodape() {
        return proTextoDetalheRodape;
    }

    public void setProTituloListaBeneficio(String proTituloListaBeneficio) {
        this.proTituloListaBeneficio = proTituloListaBeneficio;
    }

    public String getProTituloListaBeneficio() {
        return proTituloListaBeneficio;
    }

    public void setProTextoCardBeneficio(String proTextoCardBeneficio) {
        this.proTextoCardBeneficio = proTextoCardBeneficio;
    }

    public String getProTextoCardBeneficio() {
        return proTextoCardBeneficio;
    }

    public void setProLinkBeneficio(String proLinkBeneficio) {
        this.proLinkBeneficio = proLinkBeneficio;
    }

    public String getProLinkBeneficio() {
        return proLinkBeneficio;
    }

    public void setProImagemBeneficio(byte[] proImagemBeneficio) {
        this.proImagemBeneficio = proImagemBeneficio;
    }

    public byte[] getProImagemBeneficio() {
        return proImagemBeneficio;
    }

    public void setCorCodigo(String corCodigo) {
        this.corCodigo = corCodigo;
    }

    public String getCorCodigo() {
        return corCodigo;
    }

    public void setProAgrupa(String proAgrupa) {
        this.proAgrupa = proAgrupa;
    }

    public String getProAgrupa() {
        return proAgrupa;
    }

    //--- GETTERS FOR LINKS
    public void setNaturezaServico(NaturezaServico naturezaServico) {
        this.naturezaServico = naturezaServico;
        setNseCodigo(naturezaServico != null ? naturezaServico.getNseCodigo() : null);
    }

    public NaturezaServico getNaturezaServico() {
        return naturezaServico;
    }

    public void setCorrespondente(Correspondente correspondente) {
        this.correspondente = correspondente;
        setCorCodigo(correspondente != null ? correspondente.getCorCodigo() : null);
    }

    public Correspondente getCorrespondente() {
        return correspondente;
    }

    public void setConsignataria(Consignataria consignataria) {
        this.consignataria = consignataria;
        setCsaCodigo(consignataria != null ? consignataria.getCsaCodigo() : null);
    }

    public Consignataria getConsignataria() {
        return consignataria;
    }

}
