/*
 * Created on 2021-12-30 ( 18:16:11 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "ReclamacaoMotivo" ( stored in table "tb_reclamacao_motivo" )
 *
 * @author Telosys
 *
 */
public class ReclamacaoMotivoId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String tmrCodigo;

    private String rrsCodigo;

    /**
     * Constructor
     */
    public ReclamacaoMotivoId() {
        super();
    }

    /**
     * Constructor with values
     * @param tmrCodigo 
     * @param rrsCodigo 
     */
    public ReclamacaoMotivoId(String tmrCodigo, String rrsCodigo) {
        super();
        this.tmrCodigo = tmrCodigo;
        this.rrsCodigo = rrsCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setTmrCodigo(String value) {
        this.tmrCodigo = value;
    }

    public String getTmrCodigo() {
        return this.tmrCodigo;
    }

    public void setRrsCodigo(String value) {
        this.rrsCodigo = value;
    }

    public String getRrsCodigo() {
        return this.rrsCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        ReclamacaoMotivoId other = (ReclamacaoMotivoId) obj;
        //--- Attribute tmrCodigo
        if (tmrCodigo == null) {
            if (other.tmrCodigo != null)
                return false;
        } else if (!tmrCodigo.equals(other.tmrCodigo))
            return false;
        //--- Attribute rrsCodigo
        if (rrsCodigo == null) {
            if (other.rrsCodigo != null)
                return false;
        } else if (!rrsCodigo.equals(other.rrsCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute tmrCodigo
        result = prime * result + ((tmrCodigo == null) ? 0 : tmrCodigo.hashCode());
        //--- Attribute rrsCodigo
        result = prime * result + ((rrsCodigo == null) ? 0 : rrsCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(tmrCodigo);
        sb.append("|");
        sb.append(rrsCodigo);
        return sb.toString();
    }

}
