/*
 * Created on 2021-12-30 ( 18:16:11 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "RegraRestricaoAcessoCsa" ( stored in table "tb_regra_restricao_acesso_csa" )
 *
 * @author Telosys
 *
 */
public class RegraRestricaoAcessoCsaId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES
    private String rraCodigo;

    private String csaCodigo;

    /**
     * Constructor
     */
    public RegraRestricaoAcessoCsaId() {
        super();
    }

    /**
     * Constructor with values
     * @param rraCodigo
     * @param csaCodigo
     */
    public RegraRestricaoAcessoCsaId(String csaCodigo, String rraCodigo) {
        super();
        this.rraCodigo = rraCodigo;
        this.csaCodigo = csaCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setRraCodigo(String value) {
        rraCodigo = value;
    }

    public String getRraCodigo() {
        return rraCodigo;
    }

    public void setCsaCodigo(String value) {
        csaCodigo = value;
    }

    public String getCsaCodigo() {
        return csaCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        RegraRestricaoAcessoCsaId other = (RegraRestricaoAcessoCsaId) obj;
        //--- Attribute rraCodigo
        if (rraCodigo == null) {
            if (other.rraCodigo != null) {
                return false;
            }
        } else if (!rraCodigo.equals(other.rraCodigo)) {
            return false;
        }
        //--- Attribute csaCodigo
        if (csaCodigo == null) {
            if (other.csaCodigo != null) {
                return false;
            }
        } else if (!csaCodigo.equals(other.csaCodigo)) {
            return false;
        }
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute rraCodigo
        result = prime * result + ((rraCodigo == null) ? 0 : rraCodigo.hashCode());
        //--- Attribute csaCodigo
        result = prime * result + ((csaCodigo == null) ? 0 : csaCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(rraCodigo);
        sb.append("|");
        sb.append(csaCodigo);
        return sb.toString();
    }

}
