/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "RelatorioFiltro"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_relatorio_filtro")
@IdClass(RelatorioFiltroId.class)
public class RelatorioFiltro implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "rel_codigo", nullable = false, length = 32)
    private String relCodigo;

    @Id
    @Column(name = "tfr_codigo", nullable = false, length = 32)
    private String tfrCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "rfi_exibe_cse", nullable = false, length = 1)
    private String rfiExibeCse;

    @Column(name = "rfi_exibe_csa", nullable = false, length = 1)
    private String rfiExibeCsa;

    @Column(name = "rfi_exibe_cor", nullable = false, length = 1)
    private String rfiExibeCor;

    @Column(name = "rfi_exibe_org", nullable = false, length = 1)
    private String rfiExibeOrg;

    @Column(name = "rfi_exibe_ser", nullable = false, length = 1)
    private String rfiExibeSer;

    @Column(name = "rfi_sequencia", nullable = false)
    private Short rfiSequencia;

    @Column(name = "rfi_parametro", length = 255)
    private String rfiParametro;

    @Column(name = "rfi_exibe_sup", nullable = false, length = 1)
    private String rfiExibeSup;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tfr_codigo", referencedColumnName = "tfr_codigo", insertable = false, updatable = false)
    private TipoFiltroRelatorio tipoFiltroRelatorio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rel_codigo", referencedColumnName = "rel_codigo", insertable = false, updatable = false)
    private Relatorio relatorio;

    /**
     * Constructor
     */
    public RelatorioFiltro() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setRelCodigo(String relCodigo) {
        this.relCodigo = relCodigo;
    }

    public String getRelCodigo() {
        return relCodigo;
    }

    public void setTfrCodigo(String tfrCodigo) {
        this.tfrCodigo = tfrCodigo;
    }

    public String getTfrCodigo() {
        return tfrCodigo;
    }

    public void setRfiExibeCse(String rfiExibeCse) {
        this.rfiExibeCse = rfiExibeCse;
    }

    public String getRfiExibeCse() {
        return rfiExibeCse;
    }

    public void setRfiExibeCsa(String rfiExibeCsa) {
        this.rfiExibeCsa = rfiExibeCsa;
    }

    public String getRfiExibeCsa() {
        return rfiExibeCsa;
    }

    public void setRfiExibeCor(String rfiExibeCor) {
        this.rfiExibeCor = rfiExibeCor;
    }

    public String getRfiExibeCor() {
        return rfiExibeCor;
    }

    public void setRfiExibeOrg(String rfiExibeOrg) {
        this.rfiExibeOrg = rfiExibeOrg;
    }

    public String getRfiExibeOrg() {
        return rfiExibeOrg;
    }

    public void setRfiExibeSer(String rfiExibeSer) {
        this.rfiExibeSer = rfiExibeSer;
    }

    public String getRfiExibeSer() {
        return rfiExibeSer;
    }

    public void setRfiSequencia(Short rfiSequencia) {
        this.rfiSequencia = rfiSequencia;
    }

    public Short getRfiSequencia() {
        return rfiSequencia;
    }

    public void setRfiParametro(String rfiParametro) {
        this.rfiParametro = rfiParametro;
    }

    public String getRfiParametro() {
        return rfiParametro;
    }

    public void setRfiExibeSup(String rfiExibeSup) {
        this.rfiExibeSup = rfiExibeSup;
    }

    public String getRfiExibeSup() {
        return rfiExibeSup;
    }

    //--- GETTERS FOR LINKS
    public void setTipoFiltroRelatorio(TipoFiltroRelatorio tipoFiltroRelatorio) {
        this.tipoFiltroRelatorio = tipoFiltroRelatorio;
        setTfrCodigo(tipoFiltroRelatorio != null ? tipoFiltroRelatorio.getTfrCodigo() : null);
    }

    public TipoFiltroRelatorio getTipoFiltroRelatorio() {
        return tipoFiltroRelatorio;
    }

    public void setRelatorio(Relatorio relatorio) {
        this.relatorio = relatorio;
        setRelCodigo(relatorio != null ? relatorio.getRelCodigo() : null);
    }

    public Relatorio getRelatorio() {
        return relatorio;
    }

    public void setId(RelatorioFiltroId id) {
        setRelCodigo(id != null ? id.getRelCodigo() : null);
        setTfrCodigo(id != null ? id.getTfrCodigo() : null);
    }
}
