/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "ResultadoValidacaoMov"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_resultado_validacao_mov")
public class ResultadoValidacaoMov implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "rva_codigo", nullable = false, length = 32)
    private String rvaCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "rva_nome_arquivo", nullable = false, length = 255)
    private String rvaNomeArquivo;

    @Temporal(TemporalType.DATE)
    @Column(name = "rva_periodo", nullable = false)
    private Date rvaPeriodo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rva_data_processo", nullable = false)
    private Date rvaDataProcesso;

    @Column(name = "rva_resultado", length = 1)
    private String rvaResultado;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "rva_aceite")
    private Boolean rvaAceite;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rva_data_aceite")
    private Date rvaDataAceite;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "resultadoValidacaoMov", targetEntity = ResultadoRegraValidMov.class)
    private Set<ResultadoRegraValidMov> resultadoRegraValidMovSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public ResultadoValidacaoMov() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setRvaCodigo(String rvaCodigo) {
        this.rvaCodigo = rvaCodigo;
    }

    public String getRvaCodigo() {
        return rvaCodigo;
    }

    public void setRvaNomeArquivo(String rvaNomeArquivo) {
        this.rvaNomeArquivo = rvaNomeArquivo;
    }

    public String getRvaNomeArquivo() {
        return rvaNomeArquivo;
    }

    public void setRvaPeriodo(Date rvaPeriodo) {
        this.rvaPeriodo = rvaPeriodo;
    }

    public Date getRvaPeriodo() {
        return rvaPeriodo;
    }

    public void setRvaDataProcesso(Date rvaDataProcesso) {
        this.rvaDataProcesso = rvaDataProcesso;
    }

    public Date getRvaDataProcesso() {
        return rvaDataProcesso;
    }

    public void setRvaResultado(String rvaResultado) {
        this.rvaResultado = rvaResultado;
    }

    public String getRvaResultado() {
        return rvaResultado;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setRvaAceite(Boolean rvaAceite) {
        this.rvaAceite = rvaAceite;
    }

    public Boolean getRvaAceite() {
        return rvaAceite;
    }

    public void setRvaDataAceite(Date rvaDataAceite) {
        this.rvaDataAceite = rvaDataAceite;
    }

    public Date getRvaDataAceite() {
        return rvaDataAceite;
    }

    //--- GETTERS FOR LINKS
    public Set<ResultadoRegraValidMov> getResultadoRegraValidMovSet() {
        return resultadoRegraValidMovSet;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

}
