/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "SenhaAutorizacaoServidor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_senha_autorizacao_servidor")
@IdClass(SenhaAutorizacaoServidorId.class)
public class SenhaAutorizacaoServidor implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "sas_data_criacao", nullable = false)
    private Date sasDataCriacao;

    //--- ENTITY DATA FIELDS
    @Temporal(TemporalType.DATE)
    @Column(name = "sas_data_expiracao", nullable = false)
    private Date sasDataExpiracao;

    @Column(name = "sas_senha", nullable = false, length = 264)
    private String sasSenha;

    @Column(name = "sas_qtd_operacoes", nullable = false)
    private Short sasQtdOperacoes;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public SenhaAutorizacaoServidor() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setSasDataCriacao(Date sasDataCriacao) {
        this.sasDataCriacao = sasDataCriacao;
    }

    public Date getSasDataCriacao() {
        return sasDataCriacao;
    }

    public void setSasDataExpiracao(Date sasDataExpiracao) {
        this.sasDataExpiracao = sasDataExpiracao;
    }

    public Date getSasDataExpiracao() {
        return sasDataExpiracao;
    }

    public void setSasSenha(String sasSenha) {
        this.sasSenha = sasSenha;
    }

    public String getSasSenha() {
        return sasSenha;
    }

    public void setSasQtdOperacoes(Short sasQtdOperacoes) {
        this.sasQtdOperacoes = sasQtdOperacoes;
    }

    public Short getSasQtdOperacoes() {
        return sasQtdOperacoes;
    }

    //--- GETTERS FOR LINKS
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setId(SenhaAutorizacaoServidorId id) {
        setUsuCodigo(id != null ? id.getUsuCodigo() : null);
        setSasDataCriacao(id != null ? id.getSasDataCriacao() : null);
    }
}
