/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Composite primary key for entity "SenhaAutorizacaoServidor" ( stored in table "tb_senha_autorizacao_servidor" )
 *
 * @author Telosys
 *
 */
public class SenhaAutorizacaoServidorId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String usuCodigo;

    private Date sasDataCriacao;

    /**
     * Constructor
     */
    public SenhaAutorizacaoServidorId() {
        super();
    }

    /**
     * Constructor with values
     * @param usuCodigo 
     * @param sasDataCriacao 
     */
    public SenhaAutorizacaoServidorId(String usuCodigo, Date sasDataCriacao) {
        super();
        this.usuCodigo = usuCodigo;
        this.sasDataCriacao = sasDataCriacao;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setUsuCodigo(String value) {
        this.usuCodigo = value;
    }

    public String getUsuCodigo() {
        return this.usuCodigo;
    }

    public void setSasDataCriacao(Date value) {
        this.sasDataCriacao = value;
    }

    public Date getSasDataCriacao() {
        return this.sasDataCriacao;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        SenhaAutorizacaoServidorId other = (SenhaAutorizacaoServidorId) obj;
        //--- Attribute usuCodigo
        if (usuCodigo == null) {
            if (other.usuCodigo != null)
                return false;
        } else if (!usuCodigo.equals(other.usuCodigo))
            return false;
        //--- Attribute sasDataCriacao
        if (sasDataCriacao == null) {
            if (other.sasDataCriacao != null)
                return false;
        } else if (!sasDataCriacao.equals(other.sasDataCriacao))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute usuCodigo
        result = prime * result + ((usuCodigo == null) ? 0 : usuCodigo.hashCode());
        //--- Attribute sasDataCriacao
        result = prime * result + ((sasDataCriacao == null) ? 0 : sasDataCriacao.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(usuCodigo);
        sb.append("|");
        sb.append(sasDataCriacao);
        return sb.toString();
    }

}
