/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "SenhaAnterior" ( stored in table "tb_senha_anterior" )
 *
 * @author Telosys
 *
 */
public class SenhaAnteriorId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private String usuCodigo;

    private String seaSenha;

    /**
     * Constructor
     */
    public SenhaAnteriorId() {
        super();
    }

    /**
     * Constructor with values
     * @param usuCodigo 
     * @param seaSenha 
     */
    public SenhaAnteriorId(String usuCodigo, String seaSenha) {
        super();
        this.usuCodigo = usuCodigo;
        this.seaSenha = seaSenha;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setUsuCodigo(String value) {
        this.usuCodigo = value;
    }

    public String getUsuCodigo() {
        return this.usuCodigo;
    }

    public void setSeaSenha(String value) {
        this.seaSenha = value;
    }

    public String getSeaSenha() {
        return this.seaSenha;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        SenhaAnteriorId other = (SenhaAnteriorId) obj;
        //--- Attribute usuCodigo
        if (usuCodigo == null) {
            if (other.usuCodigo != null)
                return false;
        } else if (!usuCodigo.equals(other.usuCodigo))
            return false;
        //--- Attribute seaSenha
        if (seaSenha == null) {
            if (other.seaSenha != null)
                return false;
        } else if (!seaSenha.equals(other.seaSenha))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute usuCodigo
        result = prime * result + ((usuCodigo == null) ? 0 : usuCodigo.hashCode());
        //--- Attribute seaSenha
        result = prime * result + ((seaSenha == null) ? 0 : seaSenha.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(usuCodigo);
        sb.append("|");
        sb.append(seaSenha);
        return sb.toString();
    }

}
