/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "ServicoPermiteTda" ( stored in table "tb_servico_permite_tda" )
 *
 * @author Telosys
 *
 */
public class ServicoPermiteTdaId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES
    private String tdaCodigo;

    private String svcCodigo;

    /**
     * Constructor
     */
    public ServicoPermiteTdaId() {
        super();
    }

    /**
     * Constructor with values
     * @param tdaCodigo
     * @param svcCodigo
     */
    public ServicoPermiteTdaId(String svcCodigo, String tdaCodigo) {
        super();
        this.tdaCodigo = tdaCodigo;
        this.svcCodigo = svcCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setTdaCodigo(String value) {
        tdaCodigo = value;
    }

    public String getTdaCodigo() {
        return tdaCodigo;
    }

    public void setSvcCodigo(String value) {
        svcCodigo = value;
    }

    public String getSvcCodigo() {
        return svcCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        ServicoPermiteTdaId other = (ServicoPermiteTdaId) obj;
        //--- Attribute tdaCodigo
        if (tdaCodigo == null) {
            if (other.tdaCodigo != null) {
                return false;
            }
        } else if (!tdaCodigo.equals(other.tdaCodigo)) {
            return false;
        }
        //--- Attribute svcCodigo
        if (svcCodigo == null) {
            if (other.svcCodigo != null) {
                return false;
            }
        } else if (!svcCodigo.equals(other.svcCodigo)) {
            return false;
        }
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute tdaCodigo
        result = prime * result + ((tdaCodigo == null) ? 0 : tdaCodigo.hashCode());
        //--- Attribute svcCodigo
        result = prime * result + ((svcCodigo == null) ? 0 : svcCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(tdaCodigo);
        sb.append("|");
        sb.append(svcCodigo);
        return sb.toString();
    }

}
