/*
 * Created on 2021-12-30 ( 18:16:12 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "SolicitacaoAutorizacao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_solicitacao_autorizacao")
public class SolicitacaoAutorizacao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "soa_codigo", nullable = false, length = 32)
    private String soaCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "ade_codigo", nullable = false, length = 32)
    private String adeCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "tis_codigo", nullable = false, length = 32)
    private String tisCodigo;

    @Column(name = "sso_codigo", nullable = false, length = 32)
    private String ssoCodigo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "soa_data", nullable = false)
    private Date soaData;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "soa_data_validade")
    private Date soaDataValidade;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "soa_data_resposta")
    private Date soaDataResposta;

    @Column(name = "soa_obs", length = 65535)
    private String soaObs;

    //--- ENTITY DATA FIELDS
    @Column(name = "oso_codigo", length = 32)
    private String osoCodigo;

    @Temporal(TemporalType.DATE)
    @Column(name = "soa_periodo")
    private Date soaPeriodo;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ade_codigo", referencedColumnName = "ade_codigo", insertable = false, updatable = false)
    private AutDesconto autDesconto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sso_codigo", referencedColumnName = "sso_codigo", insertable = false, updatable = false)
    private StatusSolicitacao statusSolicitacao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tis_codigo", referencedColumnName = "tis_codigo", insertable = false, updatable = false)
    private TipoSolicitacao tipoSolicitacao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oso_codigo", referencedColumnName = "oso_codigo", insertable = false, updatable = false)
    private OrigemSolicitacao origemSolicitacao;

    /**
     * Constructor
     */
    public SolicitacaoAutorizacao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setSoaCodigo(String soaCodigo) {
        this.soaCodigo = soaCodigo;
    }

    public String getSoaCodigo() {
        return soaCodigo;
    }

    public void setAdeCodigo(String adeCodigo) {
        this.adeCodigo = adeCodigo;
    }

    public String getAdeCodigo() {
        return adeCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    public void setTisCodigo(String tisCodigo) {
        this.tisCodigo = tisCodigo;
    }

    public String getTisCodigo() {
        return tisCodigo;
    }

    public void setSsoCodigo(String ssoCodigo) {
        this.ssoCodigo = ssoCodigo;
    }

    public String getSsoCodigo() {
        return ssoCodigo;
    }

    public void setSoaData(Date soaData) {
        this.soaData = soaData;
    }

    public Date getSoaData() {
        return soaData;
    }

    public void setSoaDataValidade(Date soaDataValidade) {
        this.soaDataValidade = soaDataValidade;
    }

    public Date getSoaDataValidade() {
        return soaDataValidade;
    }

    //--- GETTERS FOR LINKS
    public void setAutDesconto(AutDesconto autDesconto) {
        this.autDesconto = autDesconto;
        setAdeCodigo(autDesconto != null ? autDesconto.getAdeCodigo() : null);
    }

    public AutDesconto getAutDesconto() {
        return autDesconto;
    }

    public void setStatusSolicitacao(StatusSolicitacao statusSolicitacao) {
        this.statusSolicitacao = statusSolicitacao;
        setSsoCodigo(statusSolicitacao != null ? statusSolicitacao.getSsoCodigo() : null);
    }

    public StatusSolicitacao getStatusSolicitacao() {
        return statusSolicitacao;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setTipoSolicitacao(TipoSolicitacao tipoSolicitacao) {
        this.tipoSolicitacao = tipoSolicitacao;
        setTisCodigo(tipoSolicitacao != null ? tipoSolicitacao.getTisCodigo() : null);
    }

    public TipoSolicitacao getTipoSolicitacao() {
        return tipoSolicitacao;
    }

    public Date getSoaDataResposta() {
        return soaDataResposta;
    }

    public void setSoaDataResposta(Date soaDataResposta) {
        this.soaDataResposta = soaDataResposta;
    }

    public String getSoaObs() {
        return soaObs;
    }

    public void setSoaObs(String soaObs) {
        this.soaObs = soaObs;
    }

    public String getOsoCodigo() {
        return osoCodigo;
    }

    public void setOsoCodigo(String osoCodigo) {
        this.osoCodigo = osoCodigo;
    }

    public OrigemSolicitacao getOrigemSolicitacao() {
        return origemSolicitacao;
    }

    public void setOrigemSolicitacao(OrigemSolicitacao origemSolicitacao) {
        this.origemSolicitacao = origemSolicitacao;
        setOsoCodigo(origemSolicitacao != null ? origemSolicitacao.getOsoCodigo() : null);
    }

	public Date getSoaPeriodo() {
		return soaPeriodo;
	}

	public void setSoaPeriodo(Date soaPeriodo) {
		this.soaPeriodo = soaPeriodo;
	}
}
