/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "StatusVerbaRescisoria"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_status_verba_rescisoria")
public class StatusVerbaRescisoria implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "svr_codigo", nullable = false, length = 32)
    private String svrCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "svr_descricao", nullable = false, length = 100)
    private String svrDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "statusVerbaRescisoria", targetEntity = VerbaRescisoriaRse.class)
    private Set<VerbaRescisoriaRse> verbaRescisoriaRseSet;

    /**
     * Constructor
     */
    public StatusVerbaRescisoria() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setSvrCodigo(String svrCodigo) {
        this.svrCodigo = svrCodigo;
    }

    public String getSvrCodigo() {
        return this.svrCodigo;
    }

    public void setSvrDescricao(String svrDescricao) {
        this.svrDescricao = svrDescricao;
    }

    public String getSvrDescricao() {
        return this.svrDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<VerbaRescisoriaRse> getVerbaRescisoriaRseSet() {
        return this.verbaRescisoriaRseSet;
    }

}
