/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "StatusAutorizacaoDesconto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_status_autorizacao_desconto")
public class StatusAutorizacaoDesconto implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "sad_codigo", nullable = false, length = 32)
    private String sadCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "sad_descricao", nullable = false, length = 40)
    private String sadDescricao;

    @Column(name = "sad_sequencia")
    private Short sadSequencia;

    @Column(name = "sad_exibe", nullable = false, length = 1)
    private String sadExibe;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "statusAutorizacaoDesconto", targetEntity = AutDesconto.class)
    private Set<AutDesconto> autDescontoSet;

    @OneToMany(mappedBy = "statusAutorizacaoDescontoBySadCodigoAnterior", targetEntity = HistoricoStatusAde.class)
    private Set<HistoricoStatusAde> historicoStatusAdeBySadCodigoAnteriorSet;

    @OneToMany(mappedBy = "statusAutorizacaoDescontoBySadCodigoNovo", targetEntity = HistoricoStatusAde.class)
    private Set<HistoricoStatusAde> historicoStatusAdeBySadCodigoNovoSet;

    /**
     * Constructor
     */
    public StatusAutorizacaoDesconto() {
        super();
    }

    public StatusAutorizacaoDesconto(String sadCodigo) {
        this();
        this.sadCodigo = sadCodigo;
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setSadCodigo(String sadCodigo) {
        this.sadCodigo = sadCodigo;
    }

    public String getSadCodigo() {
        return sadCodigo;
    }

    public void setSadDescricao(String sadDescricao) {
        this.sadDescricao = sadDescricao;
    }

    public String getSadDescricao() {
        return sadDescricao;
    }

    public void setSadSequencia(Short sadSequencia) {
        this.sadSequencia = sadSequencia;
    }

    public Short getSadSequencia() {
        return sadSequencia;
    }

    public void setSadExibe(String sadExibe) {
        this.sadExibe = sadExibe;
    }

    public String getSadExibe() {
        return sadExibe;
    }

    //--- GETTERS FOR LINKS
    public Set<AutDesconto> getAutDescontoSet() {
        return autDescontoSet;
    }

    public Set<HistoricoStatusAde> getHistoricoStatusAdeBySadCodigoAnteriorSet() {
        return historicoStatusAdeBySadCodigoAnteriorSet;
    }

    public Set<HistoricoStatusAde> getHistoricoStatusAdeBySadCodigoNovoSet() {
        return historicoStatusAdeBySadCodigoNovoSet;
    }
}
