/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "StatusCompra"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_status_compra")
public class StatusCompra implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "stc_codigo", nullable = false, length = 32)
    private String stcCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "stc_descricao", nullable = false, length = 40)
    private String stcDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "statusCompra", targetEntity = RelacionamentoAutorizacao.class)
    private Set<RelacionamentoAutorizacao> relacionamentoAutorizacaoSet;

    /**
     * Constructor
     */
    public StatusCompra() {
        super();
    }

    public StatusCompra(String stcCodigo) {
        this();
        this.stcCodigo = stcCodigo;
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setStcCodigo(String stcCodigo) {
        this.stcCodigo = stcCodigo;
    }

    public String getStcCodigo() {
        return stcCodigo;
    }

    public void setStcDescricao(String stcDescricao) {
        this.stcDescricao = stcDescricao;
    }

    public String getStcDescricao() {
        return stcDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<RelacionamentoAutorizacao> getRelacionamentoAutorizacaoSet() {
        return relacionamentoAutorizacaoSet;
    }

}
