/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * JPA entity class for "TermoAdesao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_termo_adesao")
public class TermoAdesao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tad_codigo", nullable = false, length = 32)
    private String tadCodigo;

    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    @Column(name = "fun_codigo", nullable = false, length = 32)
    private String funCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tad_titulo", nullable = false, length = 100)
    private String tadTitulo;

    @Column(name = "tad_texto", nullable = false, length = 65535)
    private String tadTexto;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tad_data", nullable = false)
    private Date tadData;

    @Column(name = "tad_sequencia", nullable = false)
    private Integer tadSequencia;

    @Column(name = "tad_exibe_cse", nullable = false, length = 1)
    private String tadExibeCse;

    @Column(name = "tad_exibe_org", nullable = false, length = 1)
    private String tadExibeOrg;

    @Column(name = "tad_exibe_csa", nullable = false, length = 1)
    private String tadExibeCsa;

    @Column(name = "tad_exibe_cor", nullable = false, length = 1)
    private String tadExibeCor;

    @Column(name = "tad_exibe_ser", nullable = false, length = 1)
    private String tadExibeSer;

    @Column(name = "tad_exibe_sup", nullable = false, length = 1)
    private String tadExibeSup;

    @Column(name = "tad_html", nullable = false, length = 1)
    private String tadHtml;

    @Column(name = "tad_permite_recusar", nullable = false, length = 1)
    private String tadPermiteRecusar;

    @Column(name = "tad_permite_ler_depois", nullable = false, length = 1)
    private String tadPermiteLerDepois;

	@Column(name = "tad_envia_api_consentimento", length = 40)
    private String tadEnviaApiConsentimento;

	@Column(name = "tad_versao_termo")
    private Integer tadVersaoTermo;

	@Column(name = "tad_classe_acao", length = 100)
    private String tadClasseAcao;

	@Column(name = "tad_exibe_apos_leitura", length = 1)
    private String tadExibeAposLeitura;

	//--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fun_codigo", referencedColumnName = "fun_codigo", insertable = false, updatable = false)
    private Funcao funcao;

    @OneToMany(mappedBy = "termoAdesao", targetEntity = LeituraTermoUsuario.class)
    private Set<LeituraTermoUsuario> leituraTermoUsuarioSet;

    /**
     * Constructor
     */
    public TermoAdesao() {
    }

    //--- GETTERS & SETTERS FOR FIELDS
	public String getTadCodigo() {
		return tadCodigo;
	}

	public void setTadCodigo(String tadCodigo) {
		this.tadCodigo = tadCodigo;
	}

	public String getUsuCodigo() {
		return usuCodigo;
	}

	public void setUsuCodigo(String usuCodigo) {
		this.usuCodigo = usuCodigo;
	}

	public String getFunCodigo() {
		return funCodigo;
	}

	public void setFunCodigo(String funCodigo) {
		this.funCodigo = funCodigo;
	}

	public String getTadTitulo() {
		return tadTitulo;
	}

	public void setTadTitulo(String tadTitulo) {
		this.tadTitulo = tadTitulo;
	}

	public String getTadTexto() {
		return tadTexto;
	}

	public void setTadTexto(String tadTexto) {
		this.tadTexto = tadTexto;
	}

	public Date getTadData() {
		return tadData;
	}

	public void setTadData(Date tadData) {
		this.tadData = tadData;
	}

	public Integer getTadSequencia() {
		return tadSequencia;
	}

	public void setTadSequencia(Integer tadSequencia) {
		this.tadSequencia = tadSequencia;
	}

	public String getTadExibeCse() {
		return tadExibeCse;
	}

	public void setTadExibeCse(String tadExibeCse) {
		this.tadExibeCse = tadExibeCse;
	}

	public String getTadExibeOrg() {
		return tadExibeOrg;
	}

	public void setTadExibeOrg(String tadExibeOrg) {
		this.tadExibeOrg = tadExibeOrg;
	}

	public String getTadExibeCsa() {
		return tadExibeCsa;
	}

	public void setTadExibeCsa(String tadExibeCsa) {
		this.tadExibeCsa = tadExibeCsa;
	}

	public String getTadExibeCor() {
		return tadExibeCor;
	}

	public void setTadExibeCor(String tadExibeCor) {
		this.tadExibeCor = tadExibeCor;
	}

	public String getTadExibeSer() {
		return tadExibeSer;
	}

	public void setTadExibeSer(String tadExibeSer) {
		this.tadExibeSer = tadExibeSer;
	}

	public String getTadExibeSup() {
		return tadExibeSup;
	}

	public void setTadExibeSup(String tadExibeSup) {
		this.tadExibeSup = tadExibeSup;
	}

	public String getTadHtml() {
		return tadHtml;
	}

	public void setTadHtml(String tadHtml) {
		this.tadHtml = tadHtml;
	}

	public String getTadPermiteRecusar() {
		return tadPermiteRecusar;
	}

	public void setTadPermiteRecusar(String tadPermiteRecusar) {
		this.tadPermiteRecusar = tadPermiteRecusar;
	}

	public String getTadPermiteLerDepois() {
		return tadPermiteLerDepois;
	}

	public void setTadPermiteLerDepois(String tadPermiteLerDepois) {
		this.tadPermiteLerDepois = tadPermiteLerDepois;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Funcao getFuncao() {
		return funcao;
	}

	public void setFuncao(Funcao funcao) {
		this.funcao = funcao;
	}

	 public Integer getTadVersaoTermo() {
		return tadVersaoTermo;
	}

	public void setTadVersaoTermo(Integer tadVersaoTermo) {
		this.tadVersaoTermo = tadVersaoTermo;
	}

	public String getTadEnviaApiConsentimento() {
		return tadEnviaApiConsentimento;
	}

	public void setTadEnviaApiConsentimento(String tadEnviaApiConsentimento) {
		this.tadEnviaApiConsentimento = tadEnviaApiConsentimento;
	}

	public Set<LeituraTermoUsuario> getLeituraTermoUsuario() {
		return leituraTermoUsuarioSet;
	}

	public void setLeituraTermoUsuario(Set<LeituraTermoUsuario> leituraTermoUsuarioSet) {
		this.leituraTermoUsuarioSet = leituraTermoUsuarioSet;
	}

	public String getTadClasseAcao() {
		return tadClasseAcao;
	}

	public void setTadClasseAcao(String tadClasseAcao) {
		this.tadClasseAcao = tadClasseAcao;
	}

	public String getTadExibeAposLeitura() {
		return tadExibeAposLeitura;
	}

	public void setTadExibeAposLeitura(String tadExibeAposLeitura) {
		this.tadExibeAposLeitura = tadExibeAposLeitura;
	}
}
