/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoDesconto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_desconto")
public class TipoDesconto implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tde_codigo", nullable = false, length = 32)
    private String tdeCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "aca_codigo", length = 32)
    private String acaCodigo;

    @Column(name = "tde_descricao", nullable = false, length = 100)
    private String tdeDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoDesconto", targetEntity = ParcelaDesconto.class)
    private Set<ParcelaDesconto> parcelaDescontoSet;

    @OneToMany(mappedBy = "tipoDesconto", targetEntity = ParcelaDescontoPeriodo.class)
    private Set<ParcelaDescontoPeriodo> parcelaDescontoPeriodoSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "aca_codigo", referencedColumnName = "aca_codigo", insertable = false, updatable = false)
    private Acao acao;

    /**
     * Constructor
     */
    public TipoDesconto() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTdeCodigo(String tdeCodigo) {
        this.tdeCodigo = tdeCodigo;
    }

    public String getTdeCodigo() {
        return tdeCodigo;
    }

    public void setAcaCodigo(String acaCodigo) {
        this.acaCodigo = acaCodigo;
    }

    public String getAcaCodigo() {
        return acaCodigo;
    }

    public void setTdeDescricao(String tdeDescricao) {
        this.tdeDescricao = tdeDescricao;
    }

    public String getTdeDescricao() {
        return tdeDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<ParcelaDesconto> getParcelaDescontoSet() {
        return parcelaDescontoSet;
    }

    public Set<ParcelaDescontoPeriodo> getParcelaDescontoPeriodoSet() {
        return parcelaDescontoPeriodoSet;
    }

    public void setAcao(Acao acao) {
        this.acao = acao;
        setAcaCodigo(acao != null ? acao.getAcaCodigo() : null);
    }

    public Acao getAcao() {
        return acao;
    }

}
