/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoNotificacao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_notificacao")
public class TipoNotificacao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "tno_codigo", nullable = false, length = 32)
    private String tnoCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "tno_descricao", nullable = false, length = 100)
    private String tnoDescricao;

    @Column(name = "tno_envio", nullable = false, length = 1)
    private String tnoEnvio;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoNotificacao", targetEntity = NotificacaoEmail.class)
    private Set<NotificacaoEmail> notificacaoEmailSet;

    @OneToMany(mappedBy = "tipoNotificacao", targetEntity = NotificacaoUsuario.class)
    private Set<NotificacaoUsuario> notificacaoUsuarioSet;

    @OneToMany(mappedBy = "tipoNotificacao", targetEntity = NotificacaoDispositivo.class)
    private Set<NotificacaoDispositivo> notificacaoDispositivoSet;

    /**
     * Constructor
     */
    public TipoNotificacao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTnoCodigo(String tnoCodigo) {
        this.tnoCodigo = tnoCodigo;
    }

    public String getTnoCodigo() {
        return this.tnoCodigo;
    }

    public void setTnoDescricao(String tnoDescricao) {
        this.tnoDescricao = tnoDescricao;
    }

    public String getTnoDescricao() {
        return this.tnoDescricao;
    }

    public void setTnoEnvio(String tnoEnvio) {
        this.tnoEnvio = tnoEnvio;
    }

    public String getTnoEnvio() {
        return this.tnoEnvio;
    }

    //--- GETTERS FOR LINKS
    public Set<NotificacaoEmail> getNotificacaoEmailSet() {
        return this.notificacaoEmailSet;
    }

    public Set<NotificacaoUsuario> getNotificacaoUsuarioSet() {
        return this.notificacaoUsuarioSet;
    }

    public Set<NotificacaoDispositivo> getNotificacaoDispositivoSet() {
        return this.notificacaoDispositivoSet;
    }

}
