/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoMotivoReclamacao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_motivo_reclamacao")
public class TipoMotivoReclamacao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tmr_codigo", nullable = false, length = 32)
    private String tmrCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tmr_descricao", nullable = false, length = 100)
    private String tmrDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )

    @OneToMany(mappedBy = "tipoMotivoReclamacao", targetEntity = ReclamacaoMotivo.class)
    private Set<ReclamacaoMotivo> reclamacaoMotivoSet;

    /**
     * Constructor
     */
    public TipoMotivoReclamacao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTmrCodigo(String tmrCodigo) {
        this.tmrCodigo = tmrCodigo;
    }

    public String getTmrCodigo() {
        return tmrCodigo;
    }

    public void setTmrDescricao(String tmrDescricao) {
        this.tmrDescricao = tmrDescricao;
    }

    public String getTmrDescricao() {
        return tmrDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<ReclamacaoMotivo> getReclamacaoMotivoSet() {
        return reclamacaoMotivoSet;
    }
}
