/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoBeneficiario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_beneficiario")
public class TipoBeneficiario implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tib_codigo", nullable = false, length = 32)
    private String tibCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tib_descricao", nullable = false, length = 40)
    private String tibDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoBeneficiario", targetEntity = CalculoBeneficio.class)
    private Set<CalculoBeneficio> calculoBeneficioSet;

    @OneToMany(mappedBy = "tipoBeneficiario", targetEntity = BeneficioServico.class)
    private Set<BeneficioServico> beneficioServicoSet;

    @OneToMany(mappedBy = "tipoBeneficiario", targetEntity = Beneficiario.class)
    private Set<Beneficiario> beneficiarioSet;

    /**
     * Constructor
     */
    public TipoBeneficiario() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTibCodigo(String tibCodigo) {
        this.tibCodigo = tibCodigo;
    }

    public String getTibCodigo() {
        return tibCodigo;
    }

    public void setTibDescricao(String tibDescricao) {
        this.tibDescricao = tibDescricao;
    }

    public String getTibDescricao() {
        return tibDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<CalculoBeneficio> getCalculoBeneficioSet() {
        return calculoBeneficioSet;
    }

    public Set<BeneficioServico> getBeneficioServicoSet() {
        return beneficioServicoSet;
    }

    public Set<Beneficiario> getBeneficiarioSet() {
        return beneficiarioSet;
    }

}
