/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoCoeficienteCorrecao"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_coeficiente_correcao")
public class TipoCoeficienteCorrecao implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "tcc_codigo", nullable = false, length = 32)
    private String tccCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "tcc_descricao", nullable = false, length = 100)
    private String tccDescricao;

    @Column(name = "tcc_forma_calc", nullable = false, length = 1)
    private String tccFormaCalc;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoCoeficienteCorrecao", targetEntity = CoeficienteCorrecao.class)
    private Set<CoeficienteCorrecao> coeficienteCorrecaoSet;

    /**
     * Constructor
     */
    public TipoCoeficienteCorrecao() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTccCodigo(String tccCodigo) {
        this.tccCodigo = tccCodigo;
    }

    public String getTccCodigo() {
        return this.tccCodigo;
    }

    public void setTccDescricao(String tccDescricao) {
        this.tccDescricao = tccDescricao;
    }

    public String getTccDescricao() {
        return this.tccDescricao;
    }

    public void setTccFormaCalc(String tccFormaCalc) {
        this.tccFormaCalc = tccFormaCalc;
    }

    public String getTccFormaCalc() {
        return this.tccFormaCalc;
    }

    //--- GETTERS FOR LINKS
    public Set<CoeficienteCorrecao> getCoeficienteCorrecaoSet() {
        return this.coeficienteCorrecaoSet;
    }

}
