/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoDadoAdicional"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_dado_adicional")
public class TipoDadoAdicional implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tda_codigo", nullable = false, length = 32)
    private String tdaCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "ten_codigo", nullable = false, length = 32)
    private String tenCodigo;

    @Column(name = "tda_descricao", nullable = false, length = 100)
    private String tdaDescricao;

    @Column(name = "tda_exporta", nullable = false, length = 1)
    private String tdaExporta;

    @Column(name = "tda_sup_consulta", nullable = false, length = 1)
    private String tdaSupConsulta;

    @Column(name = "tda_cse_consulta", nullable = false, length = 1)
    private String tdaCseConsulta;

    @Column(name = "tda_csa_consulta", nullable = false, length = 1)
    private String tdaCsaConsulta;

    @Column(name = "tda_ser_consulta", nullable = false, length = 1)
    private String tdaSerConsulta;

    @Column(name = "tda_sup_altera", nullable = false, length = 1)
    private String tdaSupAltera;

    @Column(name = "tda_cse_altera", nullable = false, length = 1)
    private String tdaCseAltera;

    @Column(name = "tda_csa_altera", nullable = false, length = 1)
    private String tdaCsaAltera;

    @Column(name = "tda_ser_altera", nullable = false, length = 1)
    private String tdaSerAltera;

    @Column(name = "tda_dominio", nullable = false, length = 50)
    private String tdaDominio;

    @Column(name = "tda_ordenacao", nullable = false)
    private Integer tdaOrdenacao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = ServicoPermiteTda.class)
    private Set<ServicoPermiteTda> servicoPermiteTdaSet;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = OcorrenciaDadosServidor.class)
    private Set<OcorrenciaDadosServidor> ocorrenciaDadosServidorSet;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = DadosAutorizacaoDesconto.class)
    private Set<DadosAutorizacaoDesconto> dadosAutorizacaoDescontoSet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ten_codigo", referencedColumnName = "ten_codigo", insertable = false, updatable = false)
    private TipoEntidade tipoEntidade;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = OcorrenciaDadosAde.class)
    private Set<OcorrenciaDadosAde> ocorrenciaDadosAdeSet;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = ConsignatariaPermiteTda.class)
    private Set<ConsignatariaPermiteTda> consignatariaPermiteTdaSet;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = DadosServidor.class)
    private Set<DadosServidor> dadosServidorSet;

    @OneToMany(mappedBy = "tipoDadoAdicional", targetEntity = FuncaoEditavelTda.class)
    private Set<FuncaoEditavelTda> funcaoEditavelTdaSet;

    /**
     * Constructor
     */
    public TipoDadoAdicional() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTdaCodigo(String tdaCodigo) {
        this.tdaCodigo = tdaCodigo;
    }

    public String getTdaCodigo() {
        return tdaCodigo;
    }

    public void setTenCodigo(String tenCodigo) {
        this.tenCodigo = tenCodigo;
    }

    public String getTenCodigo() {
        return tenCodigo;
    }

    public void setTdaDescricao(String tdaDescricao) {
        this.tdaDescricao = tdaDescricao;
    }

    public String getTdaDescricao() {
        return tdaDescricao;
    }

    public void setTdaExporta(String tdaExporta) {
        this.tdaExporta = tdaExporta;
    }

    public String getTdaExporta() {
        return tdaExporta;
    }

    public void setTdaSupConsulta(String tdaSupConsulta) {
        this.tdaSupConsulta = tdaSupConsulta;
    }

    public String getTdaSupConsulta() {
        return tdaSupConsulta;
    }

    public void setTdaCseConsulta(String tdaCseConsulta) {
        this.tdaCseConsulta = tdaCseConsulta;
    }

    public String getTdaCseConsulta() {
        return tdaCseConsulta;
    }

    public void setTdaCsaConsulta(String tdaCsaConsulta) {
        this.tdaCsaConsulta = tdaCsaConsulta;
    }

    public String getTdaCsaConsulta() {
        return tdaCsaConsulta;
    }

    public void setTdaSerConsulta(String tdaSerConsulta) {
        this.tdaSerConsulta = tdaSerConsulta;
    }

    public String getTdaSerConsulta() {
        return tdaSerConsulta;
    }

    public void setTdaSupAltera(String tdaSupAltera) {
        this.tdaSupAltera = tdaSupAltera;
    }

    public String getTdaSupAltera() {
        return tdaSupAltera;
    }

    public void setTdaCseAltera(String tdaCseAltera) {
        this.tdaCseAltera = tdaCseAltera;
    }

    public String getTdaCseAltera() {
        return tdaCseAltera;
    }

    public void setTdaCsaAltera(String tdaCsaAltera) {
        this.tdaCsaAltera = tdaCsaAltera;
    }

    public String getTdaCsaAltera() {
        return tdaCsaAltera;
    }

    public void setTdaSerAltera(String tdaSerAltera) {
        this.tdaSerAltera = tdaSerAltera;
    }

    public String getTdaSerAltera() {
        return tdaSerAltera;
    }

    public void setTdaDominio(String tdaDominio) {
        this.tdaDominio = tdaDominio;
    }

    public String getTdaDominio() {
        return tdaDominio;
    }

    public void setTdaOrdenacao(Integer tdaOrdenacao) {
        this.tdaOrdenacao = tdaOrdenacao;
    }

    public Integer getTdaOrdenacao() {
        return tdaOrdenacao;
    }

    //--- GETTERS FOR LINKS
    public Set<ServicoPermiteTda> getServicoPermiteTdaSet() {
        return servicoPermiteTdaSet;
    }

    public Set<OcorrenciaDadosServidor> getOcorrenciaDadosServidorSet() {
        return ocorrenciaDadosServidorSet;
    }

    public Set<DadosAutorizacaoDesconto> getDadosAutorizacaoDescontoSet() {
        return dadosAutorizacaoDescontoSet;
    }

    public void setTipoEntidade(TipoEntidade tipoEntidade) {
        this.tipoEntidade = tipoEntidade;
        setTenCodigo(tipoEntidade != null ? tipoEntidade.getTenCodigo() : null);
    }

    public TipoEntidade getTipoEntidade() {
        return tipoEntidade;
    }

    public Set<OcorrenciaDadosAde> getOcorrenciaDadosAdeSet() {
        return ocorrenciaDadosAdeSet;
    }

    public Set<ConsignatariaPermiteTda> getConsignatariaPermiteTdaSet() {
        return consignatariaPermiteTdaSet;
    }

    public Set<DadosServidor> getDadosServidorSet() {
        return dadosServidorSet;
    }

    public Set<FuncaoEditavelTda> getFuncaoEditavelTdaSet() {
        return funcaoEditavelTdaSet;
    }

}
