/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoParametroPlano"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_parametro_plano")
public class TipoParametroPlano implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "tpp_codigo", nullable = false, length = 32)
    private String tppCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "tpp_descricao", nullable = false, length = 100)
    private String tppDescricao;

    @Column(name = "tpp_dominio", nullable = false, length = 255)
    private String tppDominio;

    @Column(name = "tpp_vlr_default", nullable = false, length = 255)
    private String tppVlrDefault;

    @Column(name = "tpp_csa_altera", nullable = false, length = 1)
    private String tppCsaAltera;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoParametroPlano", targetEntity = ParametroPlano.class)
    private Set<ParametroPlano> parametroPlanoSet;

    /**
     * Constructor
     */
    public TipoParametroPlano() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTppCodigo(String tppCodigo) {
        this.tppCodigo = tppCodigo;
    }

    public String getTppCodigo() {
        return this.tppCodigo;
    }

    public void setTppDescricao(String tppDescricao) {
        this.tppDescricao = tppDescricao;
    }

    public String getTppDescricao() {
        return this.tppDescricao;
    }

    public void setTppDominio(String tppDominio) {
        this.tppDominio = tppDominio;
    }

    public String getTppDominio() {
        return this.tppDominio;
    }

    public void setTppVlrDefault(String tppVlrDefault) {
        this.tppVlrDefault = tppVlrDefault;
    }

    public String getTppVlrDefault() {
        return this.tppVlrDefault;
    }

    public void setTppCsaAltera(String tppCsaAltera) {
        this.tppCsaAltera = tppCsaAltera;
    }

    public String getTppCsaAltera() {
        return this.tppCsaAltera;
    }

    //--- GETTERS FOR LINKS
    public Set<ParametroPlano> getParametroPlanoSet() {
        return this.parametroPlanoSet;
    }

}
