/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoNatureza"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_natureza")
public class TipoNatureza implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "tnt_codigo", nullable = false, length = 32)
    private String tntCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "tnt_descricao", nullable = false, length = 100)
    private String tntDescricao;

    @Column(name = "tnt_cse_altera", length = 1)
    private String tntCseAltera;

    @Column(name = "tnt_sup_altera", length = 1)
    private String tntSupAltera;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoNatureza", targetEntity = RelacionamentoAutorizacao.class)
    private Set<RelacionamentoAutorizacao> relacionamentoAutorizacaoSet;

    @OneToMany(mappedBy = "tipoNatureza", targetEntity = TipoLancamento.class)
    private Set<TipoLancamento> tipoLancamentoSet;

    @OneToMany(mappedBy = "tipoNatureza", targetEntity = RelacionamentoServico.class)
    private Set<RelacionamentoServico> relacionamentoServicoSet;

    @OneToMany(mappedBy = "tipoNatureza", targetEntity = RelacionamentoRegistroSer.class)
    private Set<RelacionamentoRegistroSer> relacionamentoRegistroSerSet;

    /**
     * Constructor
     */
    public TipoNatureza() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTntCodigo(String tntCodigo) {
        this.tntCodigo = tntCodigo;
    }

    public String getTntCodigo() {
        return tntCodigo;
    }

    public void setTntDescricao(String tntDescricao) {
        this.tntDescricao = tntDescricao;
    }

    public String getTntDescricao() {
        return tntDescricao;
    }

    public void setTntCseAltera(String tntCseAltera) {
        this.tntCseAltera = tntCseAltera;
    }

    public String getTntCseAltera() {
        return tntCseAltera;
    }

    public void setTntSupAltera(String tntSupAltera) {
        this.tntSupAltera = tntSupAltera;
    }

    public String getTntSupAltera() {
        return tntSupAltera;
    }

    //--- GETTERS FOR LINKS
    public Set<RelacionamentoAutorizacao> getRelacionamentoAutorizacaoSet() {
        return relacionamentoAutorizacaoSet;
    }

    public Set<TipoLancamento> getTipoLancamentoSet() {
        return tipoLancamentoSet;
    }

    public Set<RelacionamentoServico> getRelacionamentoServicoSet() {
        return relacionamentoServicoSet;
    }

    public Set<RelacionamentoRegistroSer> getRelacionamentoRegistroSerSet() {
        return relacionamentoRegistroSerSet;
    }

}
