/*
 * Created on 2021-12-30 ( 18:16:13 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoDispositivo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_dispositivo")
public class TipoDispositivo implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "tdi_codigo", nullable = false, length = 32)
    private String tdiCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "tdi_descricao", nullable = false, length = 40)
    private String tdiDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoDispositivo", targetEntity = UsuarioChaveDispositivo.class)
    private Set<UsuarioChaveDispositivo> usuarioChaveDispositivoSet;

    /**
     * Constructor
     */
    public TipoDispositivo() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTdiCodigo(String tdiCodigo) {
        this.tdiCodigo = tdiCodigo;
    }

    public String getTdiCodigo() {
        return this.tdiCodigo;
    }

    public void setTdiDescricao(String tdiDescricao) {
        this.tdiDescricao = tdiDescricao;
    }

    public String getTdiDescricao() {
        return this.tdiDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<UsuarioChaveDispositivo> getUsuarioChaveDispositivoSet() {
        return this.usuarioChaveDispositivoSet;
    }

}
