/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TipoParamConsignataria"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_tipo_param_consignataria")
public class TipoParamConsignataria implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "tpa_codigo", nullable = false, length = 32)
    private String tpaCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "tpa_descricao", length = 200)
    private String tpaDescricao;

    @Column(name = "tpa_dominio", length = 255)
    private String tpaDominio;

    @Column(name = "tpa_cse_altera", length = 1)
    private String tpaCseAltera;

    @Column(name = "tpa_csa_altera", length = 1)
    private String tpaCsaAltera;

    @Column(name = "tpa_sup_altera", length = 1)
    private String tpaSupAltera;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoParamConsignataria", targetEntity = ParamConsignataria.class)
    private Set<ParamConsignataria> paramConsignatariaSet;
    
    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "tipoParamConsignataria", targetEntity = ParamConsignatariaRegistroSer.class)
    private Set<ParamConsignatariaRegistroSer> paramConsignatariaRegistroSerSet;

    /**
     * Constructor
     */
    public TipoParamConsignataria() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setTpaCodigo(String tpaCodigo) {
        this.tpaCodigo = tpaCodigo;
    }

    public String getTpaCodigo() {
        return this.tpaCodigo;
    }

    public void setTpaDescricao(String tpaDescricao) {
        this.tpaDescricao = tpaDescricao;
    }

    public String getTpaDescricao() {
        return this.tpaDescricao;
    }

    public void setTpaDominio(String tpaDominio) {
        this.tpaDominio = tpaDominio;
    }

    public String getTpaDominio() {
        return this.tpaDominio;
    }

    public void setTpaCseAltera(String tpaCseAltera) {
        this.tpaCseAltera = tpaCseAltera;
    }

    public String getTpaCseAltera() {
        return this.tpaCseAltera;
    }

    public void setTpaCsaAltera(String tpaCsaAltera) {
        this.tpaCsaAltera = tpaCsaAltera;
    }

    public String getTpaCsaAltera() {
        return this.tpaCsaAltera;
    }

    public void setTpaSupAltera(String tpaSupAltera) {
        this.tpaSupAltera = tpaSupAltera;
    }

    public String getTpaSupAltera() {
        return this.tpaSupAltera;
    }

    //--- GETTERS FOR LINKS
    public Set<ParamConsignataria> getParamConsignatariaSet() {
        return this.paramConsignatariaSet;
    }
    
    public Set<ParamConsignatariaRegistroSer> getParamConsignatariaRegistroSerSet() {
		return paramConsignatariaRegistroSerSet;
	}

}
