/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

/**
 * Composite primary key for entity "TransferenciaMargem" ( stored in table "tb_transferencia_margem" )
 *
 * @author Telosys
 *
 */
public class TransferenciaMargemId implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY KEY ATTRIBUTES 
    private Short marCodigoOrigem;

    private Short marCodigoDestino;

    private String papCodigo;

    /**
     * Constructor
     */
    public TransferenciaMargemId() {
        super();
    }

    /**
     * Constructor with values
     * @param marCodigoOrigem 
     * @param marCodigoDestino 
     * @param papCodigo 
     */
    public TransferenciaMargemId(Short marCodigoOrigem, Short marCodigoDestino, String papCodigo) {
        super();
        this.marCodigoOrigem = marCodigoOrigem;
        this.marCodigoDestino = marCodigoDestino;
        this.papCodigo = papCodigo;
    }

    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setMarCodigoOrigem(Short value) {
        this.marCodigoOrigem = value;
    }

    public Short getMarCodigoOrigem() {
        return this.marCodigoOrigem;
    }

    public void setMarCodigoDestino(Short value) {
        this.marCodigoDestino = value;
    }

    public Short getMarCodigoDestino() {
        return this.marCodigoDestino;
    }

    public void setPapCodigo(String value) {
        this.papCodigo = value;
    }

    public String getPapCodigo() {
        return this.papCodigo;
    }

    //--- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        TransferenciaMargemId other = (TransferenciaMargemId) obj;
        //--- Attribute marCodigoOrigem
        if (marCodigoOrigem == null) {
            if (other.marCodigoOrigem != null)
                return false;
        } else if (!marCodigoOrigem.equals(other.marCodigoOrigem))
            return false;
        //--- Attribute marCodigoDestino
        if (marCodigoDestino == null) {
            if (other.marCodigoDestino != null)
                return false;
        } else if (!marCodigoDestino.equals(other.marCodigoDestino))
            return false;
        //--- Attribute papCodigo
        if (papCodigo == null) {
            if (other.papCodigo != null)
                return false;
        } else if (!papCodigo.equals(other.papCodigo))
            return false;
        return true;
    }

    //--- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        //--- Attribute marCodigoOrigem
        result = prime * result + ((marCodigoOrigem == null) ? 0 : marCodigoOrigem.hashCode());
        //--- Attribute marCodigoDestino
        result = prime * result + ((marCodigoDestino == null) ? 0 : marCodigoDestino.hashCode());
        //--- Attribute papCodigo
        result = prime * result + ((papCodigo == null) ? 0 : papCodigo.hashCode());

        return result;
    }

    //--- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(marCodigoOrigem);
        sb.append("|");
        sb.append(marCodigoDestino);
        sb.append("|");
        sb.append(papCodigo);
        return sb.toString();
    }

}
