/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "TransferenciaMargem"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_transferencia_margem")
@IdClass(TransferenciaMargemId.class)
public class TransferenciaMargem implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "mar_codigo_origem", nullable = false)
    private Short marCodigoOrigem;

    @Id
    @Column(name = "mar_codigo_destino", nullable = false)
    private Short marCodigoDestino;

    @Id
    @Column(name = "pap_codigo", nullable = false, length = 32)
    private String papCodigo;

    //--- ENTITY DATA FIELDS
    @Column(name = "trm_apenas_total", nullable = false, length = 1)
    private String trmApenasTotal;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pap_codigo", referencedColumnName = "pap_codigo", insertable = false, updatable = false)
    private Papel papel;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mar_codigo_origem", referencedColumnName = "mar_codigo", insertable = false, updatable = false)
    private Margem margemByMarCodigoOrigem;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mar_codigo_destino", referencedColumnName = "mar_codigo", insertable = false, updatable = false)
    private Margem margemByMarCodigoDestino;

    /**
     * Constructor
     */
    public TransferenciaMargem() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setMarCodigoOrigem(Short marCodigoOrigem) {
        this.marCodigoOrigem = marCodigoOrigem;
    }

    public Short getMarCodigoOrigem() {
        return marCodigoOrigem;
    }

    public void setMarCodigoDestino(Short marCodigoDestino) {
        this.marCodigoDestino = marCodigoDestino;
    }

    public Short getMarCodigoDestino() {
        return marCodigoDestino;
    }

    public void setPapCodigo(String papCodigo) {
        this.papCodigo = papCodigo;
    }

    public String getPapCodigo() {
        return papCodigo;
    }

    public void setTrmApenasTotal(String trmApenasTotal) {
        this.trmApenasTotal = trmApenasTotal;
    }

    public String getTrmApenasTotal() {
        return trmApenasTotal;
    }

    //--- GETTERS FOR LINKS
    public void setPapel(Papel papel) {
        this.papel = papel;
        setPapCodigo(papel != null ? papel.getPapCodigo() : null);
    }

    public Papel getPapel() {
        return papel;
    }

    public void setMargemByMarCodigoOrigem(Margem margem) {
        margemByMarCodigoOrigem = margem;
        setMarCodigoOrigem(margem != null ? margem.getMarCodigo() : null);
    }

    public Margem getMargemByMarCodigoOrigem() {
        return margemByMarCodigoOrigem;
    }

    public void setMargemByMarCodigoDestino(Margem margem) {
        margemByMarCodigoDestino = margem;
        setMarCodigoDestino(margem != null ? margem.getMarCodigo() : null);
    }

    public Margem getMargemByMarCodigoDestino() {
        return margemByMarCodigoDestino;
    }

    public void setId(TransferenciaMargemId id) {
        setMarCodigoOrigem(id != null ? id.getMarCodigoOrigem() : null);
        setMarCodigoDestino(id != null ? id.getMarCodigoDestino() : null);
        setPapCodigo(id != null ? id.getPapCodigo() : null);
    }
}
