/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity class for "UsuarioSer"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_usuario_ser")
@IdClass(UsuarioSerId.class)
public class UsuarioSer implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ser_codigo", nullable = false, length = 32)
    private String serCodigo;

    @Id
    @Column(name = "usu_codigo", nullable = false, length = 32)
    private String usuCodigo;

    //--- ENTITY DATA FIELDS

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ser_codigo", referencedColumnName = "ser_codigo", insertable = false, updatable = false)
    private Servidor servidor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_codigo", referencedColumnName = "usu_codigo", insertable = false, updatable = false)
    private Usuario usuario;

    /**
     * Constructor
     */
    public UsuarioSer() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setSerCodigo(String serCodigo) {
        this.serCodigo = serCodigo;
    }

    public String getSerCodigo() {
        return serCodigo;
    }

    public void setUsuCodigo(String usuCodigo) {
        this.usuCodigo = usuCodigo;
    }

    public String getUsuCodigo() {
        return usuCodigo;
    }

    //--- GETTERS FOR LINKS
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
        setSerCodigo(servidor != null ? servidor.getSerCodigo() : null);
    }

    public Servidor getServidor() {
        return servidor;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        setUsuCodigo(usuario != null ? usuario.getUsuCodigo() : null);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setId(UsuarioSerId id) {
        setSerCodigo(id != null ? id.getSerCodigo() : null);
        setUsuCodigo(id != null ? id.getUsuCodigo() : null);
    }
}
