/*
 * Created on 2021-12-30 ( 18:16:14 ) Generated by Telosys (
 * http://www.telosys.org/ ) version 3.3.0
 */
package com.zetra.econsig.persistence.entity;

import java.io.Serializable;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Vencimento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tb_vencimento")
public class Vencimento implements Serializable {

    private static final long serialVersionUID = 2L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name = "vct_codigo", nullable = false, length = 32)
    private String vctCodigo;

    //--- ENTITY DATA FIELDS 
    @Column(name = "vct_identificador", length = 40)
    private String vctIdentificador;

    @Column(name = "vct_descricao", length = 100)
    private String vctDescricao;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "vencimento", targetEntity = CompMargem.class)
    private Set<CompMargem> compMargemSet;

    /**
     * Constructor
     */
    public Vencimento() {
        super();
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setVctCodigo(String vctCodigo) {
        this.vctCodigo = vctCodigo;
    }

    public String getVctCodigo() {
        return this.vctCodigo;
    }

    public void setVctIdentificador(String vctIdentificador) {
        this.vctIdentificador = vctIdentificador;
    }

    public String getVctIdentificador() {
        return this.vctIdentificador;
    }

    public void setVctDescricao(String vctDescricao) {
        this.vctDescricao = vctDescricao;
    }

    public String getVctDescricao() {
        return this.vctDescricao;
    }

    //--- GETTERS FOR LINKS
    public Set<CompMargem> getCompMargemSet() {
        return this.compMargemSet;
    }

}
