ALTER TABLE TB_REGISTRO_SERVIDOR MODIFY RSE_MATRICULA varchar(35) NOT NULL DEFAULT '';
ALTER TABLE TB_ARQUIVO_RETORNO MODIFY RSE_MATRICULA varchar(35) NOT NULL;
ALTER TABLE TB_ARQUIVO_PREVIA_OPERADORA MODIFY RSE_MATRICULA varchar(35) NOT NULL;
ALTER TABLE TB_ARQUIVO_FATURAMENTO_BEN MODIFY RSE_MATRICULA varchar(35) NULL;
ALTER TABLE TB_BLOCO_PROCESSAMENTO MODIFY RSE_MATRICULA varchar(35) NULL;
ALTER TABLE HT_REGISTRO_SERVIDOR MODIFY RSE_MATRICULA varchar(35) NOT NULL;
ALTER TABLE TB_REGISTRO_SERVIDOR MODIFY RSE_MATRICULA_INST varchar(35) NULL;
ALTER TABLE TB_ARQUIVO_FATURAMENTO_BEN MODIFY RSE_MATRICULA_INST varchar(35) NULL;
ALTER TABLE HT_REGISTRO_SERVIDOR MODIFY RSE_MATRICULA_INST varchar(35) NULL;