-- DESENV-10471
INSERT INTO tb_tipo_dados_autorizacao (TDA_CODIGO, TDA_DESCRICAO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA, TDA_DOMINIO) 
VALUES ('38', 'Data da recusa do servidor em fornecer informações de contato para leilão.', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'DATETIME');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15067', '6', NULL, '/v3/informarContatoLeilaoFinalizado', NULL, NULL, 1, 'S', 'S', NULL, 'N', '0');
