-- DESENV-16331
INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA, TDA_DOMINIO, TDA_ORDENACAO)
VALUES ('51', '19', 'Numero da proposta de seguro MAG', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'ALFA', 38);

INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA, TDA_DOMINIO, TDA_ORDENACAO)
VALUES ('52', '19', 'Data/hora da leitura do termo de condição do seguro MAG', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'DATETIME', 39);  
    
INSERT INTO tb_tipo_dado_adicional (TDA_CODIGO, TEN_CODIGO, TDA_DESCRICAO, TDA_EXPORTA, TDA_SUP_CONSULTA, TDA_CSE_CONSULTA, TDA_CSA_CONSULTA, TDA_SER_CONSULTA, TDA_SUP_ALTERA, TDA_CSE_ALTERA, TDA_CSA_ALTERA, TDA_SER_ALTERA, TDA_DOMINIO, TDA_ORDENACAO)
VALUES ('53', '19', 'IP de leitura do termo de condição do seguro MAG', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'DATETIME', 40);
