-- DESENV-14555
INSERT INTO tb_acao (ACA_CODIGO, ACA_DESCRICAO) VALUES ('7', 'Cancelamento Beneficio por óbito');

UPDATE tb_tipo_motivo_operacao SET ACA_CODIGO = '7' WHERE TMO_IDENTIFICADOR IN ('PS05','PS06','PS18');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16062', '7', '424', '/v3/aprovarSolicitacao/exibeObito', NULL, NULL, 1, 'S', 'S', NULL, 'S', 2);
