-- DESENV-14590
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16063', '1', '204', '/v3/transferirConsignacaoGeral', 'acao', 'pesquisar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16064', '7', '204', '/v3/transferirConsignacaoGeral', 'acao', 'pesquisar', 1, 'S', 'S', NULL, 'N', '2');

UPDATE tb_acesso_recurso SET ACR_OPERACAO = 'gerarRelatorio' WHERE ACR_CODIGO IN ('15215', '15216');
