-- DESENV-15621
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16321', NULL, NULL, '/v3/autenticarUsuarioJwt', 'acao', 'iniciar', 1, 'N', 'N', NULL, 'N', 0);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('16322', NULL, NULL, '/v3/autenticarUsuarioJwt', 'acao', 'validar', 1, 'N', 'N', NULL, 'N', 0);

-- INSERT INTO tb_param_senha_externa (PSX_CHAVE, PSX_VALOR) VALUES ('jwt.token', '849bf2018e31b0b3c5b60c41a6aacb8b');
