-- DESENV-15660
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16294', '1', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16295', '2', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16296', '3', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16297', '4', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16298', '7', NULL, '/v3/listarCadastroTaxas', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16299', '1', NULL, '/v3/listarServicosCancelamentoAutomatico', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16300', '2', NULL, '/v3/listarServicosCancelamentoAutomatico', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16301', '3', NULL, '/v3/listarServicosCancelamentoAutomatico', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16302', '4', NULL, '/v3/listarServicosCancelamentoAutomatico', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16303', '7', NULL, '/v3/listarServicosCancelamentoAutomatico', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16304', '1', NULL, '/v3/listarServicosModuloAvancadoCompra', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16305', '2', NULL, '/v3/listarServicosModuloAvancadoCompra', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16306', '3', NULL, '/v3/listarServicosModuloAvancadoCompra', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16307', '4', NULL, '/v3/listarServicosModuloAvancadoCompra', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16308', '7', NULL, '/v3/listarServicosModuloAvancadoCompra', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16309', '1', NULL, '/v3/listarServicosCompraContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16310', '2', NULL, '/v3/listarServicosCompraContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16311', '3', NULL, '/v3/listarServicosCompraContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16312', '4', NULL, '/v3/listarServicosCompraContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16313', '7', NULL, '/v3/listarServicosCompraContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16314', '1', NULL, '/v3/listarServicosRenegociacaoContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16315', '2', NULL, '/v3/listarServicosRenegociacaoContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16316', '3', NULL, '/v3/listarServicosRenegociacaoContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16317', '4', NULL, '/v3/listarServicosRenegociacaoContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16318', '7', NULL, '/v3/listarServicosRenegociacaoContrato', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');
