-- DESENV-13016
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15342', '6', '26', '/v3/autorizarConsignacaoPorVerba', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '0'); 
