-- DESENV-20127
INSERT INTO tb_natureza_servico (NSE_CODIGO, NSE_DESCRICAO, NSE_TRANSFERIR_ADE, NSE_IMAGEM, NSE_ORDEM_BENEFICIO, NSE_CODIGO_PAI, NSE_DESCRICAO_PORTAL, NSE_TITULO_DETALHE_TOPO, NSE_TEXTO_DETALHE_TOPO, NSE_TITULO_DETALHE_RODAPE, NSE_TEXTO_DETALHE_RODAPE, NSE_TITULO_CAROUSEL_PROVEDOR)
VALUES ('14', 'SalaryPay PIX Manual', 'S', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

UPDATE tb_servico SET NSE_CODIGO = '14' WHERE SVC_IDENTIFICADOR = 'SPPIX';

