-- DESENV-10939

DELETE FROM tb_ajuda WHERE ACR_CODIGO IN (SELECT ACR_CODIGO FROM tb_acesso_recurso WHERE FUN_CODIGO = '292');
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO IN (SELECT ACR_CODIGO FROM tb_acesso_recurso WHERE FUN_CODIGO = '292');
DELETE FROM tb_acesso_recurso WHERE FUN_CODIGO = '292';
DELETE FROM tb_funcao_perfil_ser WHERE FUN_CODIGO = '292';
DELETE FROM tb_papel_funcao WHERE FUN_CODIGO = '292';
