-- DESENV-10476

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR) 
SELECT '451', GRF_CODIGO, 'Excluir anexos da consignação', FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR
FROM tb_funcao WHERE FUN_CODIGO = '200';

UPDATE tb_acesso_recurso set FUN_CODIGO = '451' WHERE ACR_RECURSO = '/v3/editarAnexosConsignacao' and ACR_OPERACAO = 'excluir' and FUN_CODIGO = '200';

INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO)
SELECT pap.PAP_CODIGO, '451' FROM tb_papel_funcao pap WHERE pap.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil (FUN_CODIGO, PER_CODIGO)
SELECT '451', per.PER_CODIGO FROM tb_funcao_perfil per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil_sup (CSE_CODIGO, USU_CODIGO, FUN_CODIGO)
SELECT per.CSE_CODIGO, per.USU_CODIGO, '451' FROM tb_funcao_perfil_sup per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil_cse (CSE_CODIGO, USU_CODIGO, FUN_CODIGO)
SELECT per.CSE_CODIGO, per.USU_CODIGO, '451' FROM tb_funcao_perfil_cse per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil_org (ORG_CODIGO, USU_CODIGO, FUN_CODIGO)
SELECT per.ORG_CODIGO, per.USU_CODIGO, '451' FROM tb_funcao_perfil_org per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil_csa (CSA_CODIGO, USU_CODIGO, FUN_CODIGO)
SELECT per.CSA_CODIGO, per.USU_CODIGO, '451' FROM tb_funcao_perfil_csa per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_perfil_cor (COR_CODIGO, USU_CODIGO, FUN_CODIGO)
SELECT per.COR_CODIGO, per.USU_CODIGO, '451' FROM tb_funcao_perfil_cor per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_auditavel_sup (FUN_CODIGO, CSE_CODIGO)
SELECT '451', per.CSE_CODIGO FROM tb_funcao_auditavel_sup per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_auditavel_cse (FUN_CODIGO, CSE_CODIGO)
SELECT '451', per.CSE_CODIGO FROM tb_funcao_auditavel_cse per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_auditavel_org (FUN_CODIGO, ORG_CODIGO)
SELECT '451', per.ORG_CODIGO FROM tb_funcao_auditavel_org per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_auditavel_csa (FUN_CODIGO, CSA_CODIGO)
SELECT '451', per.CSA_CODIGO FROM tb_funcao_auditavel_csa per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_auditavel_cor (FUN_CODIGO, COR_CODIGO)
SELECT '451', per.COR_CODIGO FROM tb_funcao_auditavel_cor per WHERE per.FUN_CODIGO = '200';

INSERT INTO tb_funcao_permitida_nca (NCA_CODIGO, FUN_CODIGO)
SELECT nca.NCA_CODIGO, '451' FROM tb_funcao_permitida_nca nca WHERE nca.FUN_CODIGO = '200';

INSERT INTO tb_bloqueio_repasse_funcao (PAP_CODIGO_ORIGEM, PAP_CODIGO_DESTINO, FUN_CODIGO)
SELECT blo.PAP_CODIGO_ORIGEM, blo.PAP_CODIGO_DESTINO, '451' FROM tb_bloqueio_repasse_funcao blo WHERE blo.FUN_CODIGO = '200';
