-- DESENV-15096
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('500', '19', 'Consultar Perfil de Servidor', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('501', '19', 'Editar Perfil de Servidor', 'N', 'S', 'S', 'P', 'P', 'N', 'N', 'N', 'N');

INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO)
VALUES ('7', '500');

INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO)
VALUES ('7', '501');

UPDATE tb_item_menu SET ITM_SEQUENCIA = ITM_SEQUENCIA + 1 WHERE MNU_CODIGO = '4' AND ITM_SEQUENCIA >= 23 AND ITM_CODIGO <> '251';

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, TEX_CHAVE, ITM_CODIGO_PAI, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA, ITM_SEPARADOR, ITM_CENTRALIZADOR, ITM_IMAGEM)
VALUES ('251', '4', NULL, '112', 'Perfil Servidor', 1, 23, 'N', 'S', NULL);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16103', '7', '500', '/v3/consultarPerfilSer', 'acao', 'iniciar', '1', 'S', 'S', '251', 'S', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16104', '7', '501', '/v3/manterPerfilSer', 'acao', 'editar', '1', 'S', 'S', NULL, 'S', '2');

DELETE FROM tb_texto_sistema WHERE TEX_CHAVE LIKE 'tb_funcao_perfil_ser%';
