-- DESENV-12395
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15487', '7', '442', '/v3/alterarContratoBeneficio', 'acao', 'salvarInclusaoManual', 1, 'S', 'S', NULL, 'N', '2'); 
