-- DESENV-21158
UPDATE tb_acesso_recurso SET FUN_CODIGO = '452' WHERE ACR_CODIGO = '16863';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16905', '7', '452', '/v3/editarRegraTaxaJuros/getTaxaLimite', NULL, NULL, 1, 'S', 'S', NULL, 'N', '2');

