-- DESENV-17250
INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_CSA_ALTERA, TPS_SUP_ALTERA, TPS_PODE_SOBREPOR_RSE) 
VALUES ('314', 'Dias de vingência para o CET', 'N', 'N', 'N', NULL);
