-- DESENV-20509
UPDATE tb_funcao SET FUN_DESCRICAO = 'Editar Saldo Devedor de Portabilidade' WHERE FUN_CODIGO = '138';

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR) 
VALUES ('551', '2', 'Editar Saldo Devedor de Solicitação do Servidor', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N');

-- INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) VALUES ('1', '551');
-- INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) VALUES ('2', '551');
-- INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) VALUES ('3', '551');
-- INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) VALUES ('4', '551');
-- INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) VALUES ('7', '551');


-- INCLUI PERMISSÃO PARA USUÁRIOS E PERFIS QUE POSSUEM PERMISSÃO PARA FUNÇÃO 138
INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) SELECT PAP_CODIGO, '551' FROM tb_papel_funcao WHERE FUN_CODIGO = '138';

INSERT INTO tb_funcao_perfil_cse (CSE_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT CSE_CODIGO, USU_CODIGO, '551' FROM tb_funcao_perfil_cse WHERE FUN_CODIGO = '138';
INSERT INTO tb_funcao_perfil_org (ORG_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT ORG_CODIGO, USU_CODIGO, '551' FROM tb_funcao_perfil_org WHERE FUN_CODIGO = '138';
INSERT INTO tb_funcao_perfil_sup (CSE_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT CSE_CODIGO, USU_CODIGO, '551' FROM tb_funcao_perfil_sup WHERE FUN_CODIGO = '138';
INSERT INTO tb_funcao_perfil_csa (CSA_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT CSA_CODIGO, USU_CODIGO, '551' FROM tb_funcao_perfil_csa WHERE FUN_CODIGO = '138';
INSERT INTO tb_funcao_perfil_cor (COR_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT COR_CODIGO, USU_CODIGO, '551' FROM tb_funcao_perfil_cor WHERE FUN_CODIGO = '138';

INSERT INTO tb_funcao_perfil (PER_CODIGO, FUN_CODIGO) SELECT PER_CODIGO, '551' FROM tb_funcao_perfil WHERE FUN_CODIGO = '138' AND PER_CODIGO IN (SELECT PER_CODIGO FROM tb_perfil WHERE PAP_CODIGO IN (SELECT PAP_CODIGO FROM tb_papel_funcao WHERE FUN_CODIGO = '551'));


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16848', '1', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16849', '1', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16850', '2', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16851', '2', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16852', '3', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16853', '3', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16854', '4', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16855', '4', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');


INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16856', '7', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16857', '7', '551', '/v3/editarSaldoDevedorSolicitacao', 'acao', 'salvar', 1, 'S', 'S', NULL, 'S', '2');

