CREATE TABLE tb_form_pesquisa (
   FPE_CODIGO VARCHAR2(32 CHAR) NOT NULL,
   FPE_NOME VARCHAR2(100 CHAR),
   FPE_BLOQUEIA_SISTEMA NUMBER(1) DEFAULT 1 NOT NULL,
   FPE_DT_CRIACAO DATE NOT NULL,
   FPE_DT_FIM DATE,
   FPE_PUBLICADO NUMBER(1) DEFAULT 0 NOT NULL,
   FPE_JSON CLOB NOT NULL,
   CONSTRAINT PK_FPE PRIMARY KEY (FPE_CODIGO)
);

CREATE TABLE tb_form_pesquisa_resposta (
   FPR_CODIGO VARCHAR2(32 CHAR) NOT NULL,
   FPE_CODIGO VARCHAR2(32 CHAR) NOT NULL,
   USU_CODIGO VARCHAR2(32 CHAR) NOT NULL,
   FPR_DT_CRIACAO DATE NOT NULL,
   FPR_JSON CLOB NOT NULL,
   CONSTRAINT PK_FPR PRIMARY KEY (FPR_CODIGO)
);

ALTER TABLE tb_form_pesquisa_resposta ADD CONSTRAINT FK_FPR_FPE_1
   FOREIGN KEY (FPE_CODIGO)
   REFERENCES tb_form_pesquisa (FPE_CODIGO);

ALTER TABLE tb_form_pesquisa_resposta ADD CONSTRAINT FK_FPR_USU_1
   FOREIGN KEY (USU_CODIGO)
   REFERENCES tb_usuario (USU_CODIGO);