-- DESENV-23170
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR, FUN_EXIGE_SEGUNDA_SENHA_SER, FUN_LIBERA_MARGEM)
VALUES ('564', '1', 'Consultar o salário do servidor via REST', 'N', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

