-- DESENV-13858
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15797', '3', '36', '/v3/listarArquivosDownloadIntegracao', 'acao', 'downloadManual', '1', 'S', 'S', NULL, 'N', '2');
