-- DESENV-21745
INSERT INTO tb_tipo_entidade (TEN_CODIGO, TEN_DESCRICAO, TEN_AUDITORIA, TEN_CAMPO_ENT_00, TEN_CAMPO_ENT_01, TEN_CAMPO_ENT_02, TEN_CAMPO_ENT_03, TEN_CAMPO_ENT_04)
VALUES ('111', 'Regra de definição de taxa de juros', 1, 'DTJ_CODIGO', 'CSA_CODIGO', 'SVC_CODIGO', 'ORG_CODIGO', 'FUN_CODIGO');

