const eConsigTheme = {
        "themeName": "eConsig",
        "colorPalette": "light",
        "isPanelless": false,
        "backgroundImage": "",
        "backgroundImageFit": "cover",
        "backgroundImageAttachment": "scroll",
        "backgroundOpacity": 1,
   "cssVariables": {
      "--sjs-layer-1-background-500": "#FFFFFFFF",
      "--sjs-layer-1-background-400": "#E6EBF9FF",
      "--sjs-layer-1-foreground-100": "#122243FF",
      "--sjs-layer-1-foreground-50": "#0E205580",
      "--sjs-layer-3-background-500": "#EAF0FBFF",
      "--sjs-layer-3-foreground-100": "#273859FF",
      "--sjs-layer-3-foreground-50": "#26335880",
      "--sjs-layer-2-background-500": "#F2F6FDFF",
      "--sjs-layer-2-background-400": "#DAE2F7FF",
      "--sjs-special-haze": "#0930A040",
      "--sjs-border-25": "#C2CEE6FF",
      "--sjs-border-10": "#CDD7EAFF",
      "--sjs-primary-background-500": "#1D4F91",
      "--sjs-primary-background-10": "#0435C41A",
      "--sjs-primary-background-400": "#042480FF",
      "--sjs-primary-foreground-100": "#FFFFFFFF",
      "--sjs-primary-foreground-25": "#FFFFFF40",
      "--sjs-secondary-background-500": "#E80070",
      "--sjs-secondary-background-25": "#D6378A40",
      "--sjs-secondary-background-10": "#D6378A1A",
      "--sjs-secondary-foreground-100": "#FFFFFFFF",
      "--sjs-secondary-forecolor-25": "#FFFFFF40",
      "--sjs-semantic-red-background-500": "#E80070",
      "--sjs-semantic-red-background-10": "#D6378A1A",
      "--sjs-semantic-red-foreground-100": "#FFFFFFFF",
      "--sjs-semantic-green-background-500": "#E80070",
      "--sjs-semantic-green-background-10": "#19B3941A",
      "--sjs-semantic-green-foreground-100": "#FFFFFFFF",
      "--sjs-semantic-blue-background-500": "#437FD9FF",
      "--sjs-semantic-blue-background-10": "#437FD91A",
      "--sjs-semantic-blue-foreground-100": "#FFFFFFFF",
      "--sjs-semantic-yellow-background-500": "#FF9814FF",
      "--sjs-semantic-yellow-background-10": "#FF98141A",
      "--sjs-semantic-yellow-foreground-100": "#FFFFFFFF",
      "--sjs-semantic-white-background-500": "#FFFFFFFF",
      "--sjs-code-gray-700": "#B6B6B6FF",
      "--sjs-code-blue-500": "#326FCAFF",
      "--sjs-code-gray-300": "#505050FF",
      "--sjs-code-green-500": "#E80070",
      "--sjs-code-red-500": "#F41B50FF",
      "--sjs-code-purple-500": "#C22FA2FF",
      "--sjs-code-yellow-500": "#F58D06FF",
      "--sjs-code-gray-500": "#8A8A8AFF",
      "--sjs-special-background": "#EAF0FBFF",
      "--sjs-layer-1-foreground-75": "#1D4F91",
      "--sjs-layer-3-background-400": "#D3DDF5FF",
      "--sjs-special-glow": "#27385933",
      "--sjs-special-shadow": "#27385940",
      "--sjs-layer-3-foreground-75": "#1D4F91",
      "--sjs-layer-2-foreground-100": "#273859FF",
      "--sjs-layer-2-foreground-75": "#1D4F91",
      "--sjs-layer-2-foreground-50": "#26335880",
      "--sjs-border-25-overlay": "#00000026",
      "--sjs-secondary-background-400": "#C62076FF",
      "--sjs-font-family": "Open Sans",
      "--sjs-font-family": "Open Sans",
      "--sjs-font-size": "16px",
      "--sjs-corner-radius": "4px",
      "--sjs-base-unit": "8px",
      "--sjs-shadow-small": "0px 0px 0px 2px rgba(0, 0, 0, 0.07)",
      "--sjs-shadow-inner": "0px 0px 0px 2px rgba(0, 0, 0, 0.1)",
      "--sjs-border-default": "rgba(0, 0, 0, 0.1)",
      "--sjs-border-light": "rgba(0, 0, 0, 0.1)",
      "--sjs-general-backcolor": "rgba(255, 255, 255, 1)",
      "--sjs-general-backcolor-dark": "rgba(239, 239, 239, 1)",
      "--sjs-general-backcolor-dim-light": "rgba(255, 255, 255, 1)",
      "--sjs-general-backcolor-dim-dark": "rgba(237, 237, 237, 1)",
      "--sjs-general-forecolor": "rgba(0, 0, 0, 0.91)",
      "--sjs-general-forecolor-light": "rgba(0, 0, 0, 0.45)",
      "--sjs-general-dim-forecolor": "rgba(0, 0, 0, 0.91)",
      "--sjs-general-dim-forecolor-light": "rgba(0, 0, 0, 0.45)",
      "--sjs-secondary-backcolor": "rgba(255, 152, 20, 1)",
      "--sjs-secondary-backcolor-light": "rgba(255, 152, 20, 0.1)",
      "--sjs-secondary-backcolor-semi-light": "rgba(255, 152, 20, 0.25)",
      "--sjs-secondary-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-secondary-forecolor-light": "rgba(255, 255, 255, 0.25)",
      "--sjs-shadow-small-reset": "0px 0px 0px 0px rgba(0, 0, 0, 0.07)",
      "--sjs-shadow-medium": "0px 0px 0px 2px rgba(0, 0, 0, 0.08),0px 2px 6px 0px rgba(0, 0, 0, 0.04)",
      "--sjs-shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.08)",
      "--sjs-shadow-inner-reset": "0px 0px 0px 0px rgba(0, 0, 0, 0.1)",
      "--sjs-border-inside": "rgba(0, 0, 0, 0.16)",
      "--sjs-special-red-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-special-green": "rgba(25, 179, 148, 1)",
      "--sjs-special-green-light": "rgba(25, 179, 148, 0.1)",
      "--sjs-special-green-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-special-blue": "rgba(67, 127, 217, 1)",
      "--sjs-special-blue-light": "rgba(67, 127, 217, 0.1)",
      "--sjs-special-blue-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
      "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
      "--sjs-special-yellow-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-article-font-xx-large-textDecoration": "none",
      "--sjs-article-font-xx-large-fontWeight": "700",
      "--sjs-article-font-xx-large-fontStyle": "normal",
      "--sjs-article-font-xx-large-fontStretch": "normal",
      "--sjs-article-font-xx-large-letterSpacing": "0",
      "--sjs-article-font-xx-large-lineHeight": "64px",
      "--sjs-article-font-xx-large-paragraphIndent": "0px",
      "--sjs-article-font-xx-large-textCase": "none",
      "--sjs-article-font-x-large-textDecoration": "none",
      "--sjs-article-font-x-large-fontWeight": "700",
      "--sjs-article-font-x-large-fontStyle": "normal",
      "--sjs-article-font-x-large-fontStretch": "normal",
      "--sjs-article-font-x-large-letterSpacing": "0",
      "--sjs-article-font-x-large-lineHeight": "56px",
      "--sjs-article-font-x-large-paragraphIndent": "0px",
      "--sjs-article-font-x-large-textCase": "none",
      "--sjs-article-font-large-textDecoration": "none",
      "--sjs-article-font-large-fontWeight": "700",
      "--sjs-article-font-large-fontStyle": "normal",
      "--sjs-article-font-large-fontStretch": "normal",
      "--sjs-article-font-large-letterSpacing": "0",
      "--sjs-article-font-large-lineHeight": "40px",
      "--sjs-article-font-large-paragraphIndent": "0px",
      "--sjs-article-font-large-textCase": "none",
      "--sjs-article-font-medium-textDecoration": "none",
      "--sjs-article-font-medium-fontWeight": "700",
      "--sjs-article-font-medium-fontStyle": "normal",
      "--sjs-article-font-medium-fontStretch": "normal",
      "--sjs-article-font-medium-letterSpacing": "0",
      "--sjs-article-font-medium-lineHeight": "32px",
      "--sjs-article-font-medium-paragraphIndent": "0px",
      "--sjs-article-font-medium-textCase": "none",
      "--sjs-article-font-default-textDecoration": "none",
      "--sjs-article-font-default-fontWeight": "400",
      "--sjs-article-font-default-fontStyle": "normal",
      "--sjs-article-font-default-fontStretch": "normal",
      "--sjs-article-font-default-letterSpacing": "0",
      "--sjs-article-font-default-lineHeight": "28px",
      "--sjs-article-font-default-paragraphIndent": "0px",
      "--sjs-article-font-default-textCase": "none",
      "--sjs-general-backcolor-dim": "rgba(245, 245, 245, 1)",
      "--sjs-primary-backcolor": "#E80070",
      "--sjs-primary-backcolor-dark": "rgba(62, 83, 115, 1)",
      "--sjs-primary-backcolor-light": "rgba(76, 100, 137, 0.1)",
      "--sjs-primary-forecolor": "rgba(255, 255, 255, 1)",
      "--sjs-primary-forecolor-light": "rgba(255, 255, 255, 0.25)",
      "--sjs-special-red": "rgba(229, 10, 62, 1)",
      "--sjs-special-red-light": "rgba(229, 10, 62, 0.1)"
    },
   "header": {
        "height": 0,
        "mobileHeight": 0,
        "inheritWidthFrom": "survey",
        "textAreaWidth": 0,
        "backgroundImageFit": "cover",
        "backgroundImageOpacity": 100,
        "overlapEnabled": false,
        "logoPositionX": "left",
        "logoPositionY": "top",
        "titlePositionX": "left",
        "titlePositionY": "bottom",
        "descriptionPositionX": "left",
        "descriptionPositionY": "bottom"
     },
        "headerView": "advanced"
};