-- DESENV-15497
UPDATE tb_acesso_recurso
SET PAP_CODIGO = NULL, FUN_CODIGO = NULL, ACR_RECURSO = '/v3/visualizarFaq', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'pesquisarAvaliacaoFaq', ACR_ATIVO = '1', ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = '108', ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2'
WHERE ACR_CODIGO='11414';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES('16361', NULL, NULL, '/v3/visualizarFaq', 'acao', 'salvarAvaliacaoFaq', 1, 'S', 'S', NULL, 'N', '2');

