-- DESENV-14162
INSERT INTO tb_tipo_param_svc (TPS_CODIGO, TPS_DESCRICAO, TPS_CSE_ALTERA, TPS_CSA_ALTERA, TPS_SUP_ALTERA) VALUES ('287', 'Exige Confirmação de Renegociação/Portabilidade', 'S', 'S', 'S');

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR) 
SELECT '484', GRF_CODIGO, 'Confirmar Renegociação', FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR FROM tb_funcao WHERE FUN_CODIGO = '58';

INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) SELECT PAP_CODIGO, '484' FROM tb_papel_funcao WHERE FUN_CODIGO = '58';

UPDATE tb_item_menu SET ITM_SEQUENCIA = ITM_SEQUENCIA + 1 WHERE MNU_CODIGO = '1' AND ITM_SEQUENCIA > 14;

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, TEX_CHAVE, ITM_CODIGO_PAI, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA, ITM_SEPARADOR, ITM_CENTRALIZADOR, ITM_IMAGEM) VALUES ('239', '1', null, null, 'Confirmar Renegociação', 1, 15, 'N', 'S', 'i-margem');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15869', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'iniciar', 1, 'S', 'S', '239', 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15870', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'iniciar', 1, 'S', 'S', '239', 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15871', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'iniciar', 1, 'S', 'S', '239', 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15872', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'iniciar', 1, 'S', 'S', '239', 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15873', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'iniciar', 1, 'S', 'S', '239', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15874', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarServidor', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15875', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarServidor', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15876', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarServidor', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15877', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarServidor', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15878', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarServidor', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15879', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15880', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15881', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15882', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15883', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'pesquisarConsignacao', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15884', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'detalharConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15885', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'detalharConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15886', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'detalharConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15887', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'detalharConsignacao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15888', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'detalharConsignacao', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15889', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoleto', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15890', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoleto', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15891', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoleto', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15892', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoleto', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15893', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoleto', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15894', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoletoExterno', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15895', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoletoExterno', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15896', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoletoExterno', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15897', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoletoExterno', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15898', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'emitirBoletoExterno', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15899', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'efetivarAcao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15901', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'efetivarAcao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15902', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'efetivarAcao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15903', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'efetivarAcao', 1, 'S', 'S', null, 'N', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15904', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'efetivarAcao', 1, 'S', 'S', null, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15905', '1', '484', '/v3/confirmarRenegociacao', 'acao', 'confirmar', 1, 'S', 'S', null, 'S', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15906', '2', '484', '/v3/confirmarRenegociacao', 'acao', 'confirmar', 1, 'S', 'S', null, 'S', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15907', '3', '484', '/v3/confirmarRenegociacao', 'acao', 'confirmar', 1, 'S', 'S', null, 'S', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15908', '4', '484', '/v3/confirmarRenegociacao', 'acao', 'confirmar', 1, 'S', 'S', null, 'S', '2');
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) VALUES ('15909', '7', '484', '/v3/confirmarRenegociacao', 'acao', 'confirmar', 1, 'S', 'S', null, 'S', '2');

INSERT INTO tb_funcao_perfil (FUN_CODIGO, PER_CODIGO)
SELECT '484', fp.PER_CODIGO FROM tb_funcao_perfil fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_cor (FUN_CODIGO, COR_CODIGO, USU_CODIGO)
SELECT '484', fp.COR_CODIGO, fp.USU_CODIGO FROM tb_funcao_perfil_cor fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_csa (FUN_CODIGO, CSA_CODIGO, USU_CODIGO)
SELECT '484', fp.CSA_CODIGO, fp.USU_CODIGO FROM tb_funcao_perfil_csa fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_cse (FUN_CODIGO, CSE_CODIGO, USU_CODIGO)
SELECT '484', fp.CSE_CODIGO, fp.USU_CODIGO FROM tb_funcao_perfil_cse fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_org (FUN_CODIGO, ORG_CODIGO, USU_CODIGO)
SELECT '484', fp.ORG_CODIGO, fp.USU_CODIGO FROM tb_funcao_perfil_org fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_sup (FUN_CODIGO, CSE_CODIGO, USU_CODIGO)
SELECT '484', fp.CSE_CODIGO, fp.USU_CODIGO FROM tb_funcao_perfil_sup fp WHERE fp.FUN_CODIGO = '58';

INSERT INTO tb_funcao_perfil_master_nca (FUN_CODIGO, NCA_CODIGO)
SELECT '484', fp.NCA_CODIGO FROM tb_funcao_perfil_master_nca fp WHERE fp.FUN_CODIGO = '58';

-- Correção de acesso recurso do caso de uso processar Lote
UPDATE tb_acesso_recurso SET FUN_CODIGO = '105' WHERE ACR_RECURSO = '/v3/processarLote' AND ACR_OPERACAO = 'importar';
UPDATE tb_acesso_recurso SET FUN_CODIGO = '206' WHERE ACR_RECURSO = '/v3/processarLote' AND ACR_OPERACAO = 'validar';
