-- DESENV-11164
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/editarManualAjuda', PAP_CODIGO = '1', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'editar' WHERE ACR_CODIGO = '11650';
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/editarManualAjuda', PAP_CODIGO = '1', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'listar' WHERE ACR_CODIGO = '11651';

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15763', '7', '241', '/v3/editarManualAjuda', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15764', '7', '241', '/v3/editarManualAjuda', 'acao', 'listar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15765', '7', '241', '/v3/editarManualAjuda', 'acao', 'editar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15766', '1', '241', '/v3/editarManualAjuda', 'acao', 'salvar', 1, 'S', 'S', NULL, 'N', '2');
