-- DESENV-10110
INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('475', '1', 'Nota fiscal para faturamento de benefício', 'N', 'S', 'N', 'S', 'N', 'N', 'N', 'N', 'N');

INSERT INTO tb_tipo_nota_fiscal (TNF_CODIGO, TNF_DESCRICAO) VALUES ('S','Subsídio');
INSERT INTO tb_tipo_nota_fiscal (TNF_CODIGO, TNF_DESCRICAO) VALUES ('M','MC e MNC');
INSERT INTO tb_tipo_nota_fiscal (TNF_CODIGO, TNF_DESCRICAO) VALUES ('C','Copart');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15759', '7', '475', '/v3/manterNotaFiscalBeneficio', 'acao', 'iniciar', 1, 'S', 'S', null, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15760', '7', '475', '/v3/manterNotaFiscalBeneficio', 'acao', 'editar', 1, 'S', 'S', null, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15761', '7', '475', '/v3/manterNotaFiscalBeneficio', 'acao', 'salvar', 1, 'S', 'S', null, 'N', '2'); 

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15762', '7', '475', '/v3/manterNotaFiscalBeneficio', 'acao', 'excluir', 1, 'S', 'S', null, 'N', '2');
