-- DESENV-20144
DELETE FROM tb_ajuda WHERE ACR_CODIGO in ('16775', '16776');

DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO in ('16775', '16776');

DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO in ('16775', '16776');

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, ITM_CODIGO_PAI, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA)
VALUES ('277', '4', NULL, 'Download Cópia de Segurança', 1, 88);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16775', '1', '548', '/v3/listarArquivosDownloadHistorico', 'acao', 'iniciar', 1, 'S', 'S', '277', 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16776', '7', '548', '/v3/listarArquivosDownloadHistorico', 'acao', 'iniciar', 1, 'S', 'S', '277', 'N', '2');

