-- DESENV-16545
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16422', '7', '517', '/v3/processarLoteInfoSaldoDevedor', 'acao', 'processar', '1', 'S', 'S', NULL, 'S', '2');
