-- DESENV-18147
INSERT INTO tb_tipo_param_sist_consignante (tpc_codigo,TPC_DESCRICAO,TPC_DOMINIO,tpc_cse_altera,TPC_CSE_CONSULTA,TPC_VLR_DEFAULT,TPC_SUP_ALTERA,TPC_SUP_CONSULTA)
VALUES ('887','Tamanho Máximo de Arquivo Anexado ao Credenciamento (KB)','INT','N','N','200','N','N');

INSERT INTO tb_param_sist_consignante (tpc_codigo,cse_codigo,psi_vlr)
VALUES ('887','1','300');
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16634', '1', '528', '/v3/visualizarDashboardCredenciamento', 'acao', 'uploadArquivoCredenciamento', 1, 'S', 'S', NULL, 'N', '2');; 
    
INSERT INTO tb_tipo_arquivo (TAR_CODIGO,TAR_DESCRICAO,TAR_QTD_DIAS_LIMPEZA,TAR_UPLOAD_SUP,TAR_UPLOAD_CSE,TAR_UPLOAD_ORG,TAR_UPLOAD_CSA,TAR_UPLOAD_COR,TAR_NOTIFICACAO_UPLOAD)
VALUES ('62',' Arquivo de Anexo Credenciamento',0,'S','S','S','S','S','N');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16635','7','200','/v3/downloadArquivo','tipo','anexo_credenciamento',1,'S','S','N','2');
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16636','1','200','/v3/downloadArquivo','tipo','anexo_credenciamento',1,'S','S','N','2');   
        
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16637','7','528','/arquivos/upload_anexo.jsp','tipo','anexo_credenciamento',1,'S','S','N','2');    
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16638','1','528','/arquivos/upload_anexo.jsp','tipo','anexo_credenciamento',1,'S','S','N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16639','7','200','/v3/excluirArquivo','tipo','anexo_credenciamento',1,'S','S','N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16640','1','200','/v3/excluirArquivo','tipo','anexo_credenciamento',1,'S','S','N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16641','7','200','/v3/excluirArquivo','tipo','anexo_credenciamento_temp',1,'S','S','N','2');
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16642','1','200','/v3/excluirArquivo','tipo','anexo_credenciamento_temp',1,'S','S','N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16643','7','200','/v3/downloadArquivo','tipo','anexo_credenciamento_temp',1,'S','S','N','2');
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16644','1','200','/v3/downloadArquivo','tipo','anexo_credenciamento_temp',1,'S','S','N','2');
        
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16645','7','528','/arquivos/upload_anexo.jsp','tipo','anexo_credenciamento_temp',1,'S','S','N','2');   
    
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ACR_FIM_FLUXO,ACR_METODO_HTTP)
VALUES ('16646','1','528','/arquivos/upload_anexo.jsp','tipo','anexo_credenciamento_temp',1,'S','S','N','2');   