-- DESENV-9293
UPDATE tb_acesso_recurso SET PAP_CODIGO = '1', FUN_CODIGO = '162', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciar', ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = '86', ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '10188';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '1', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'editar',  ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '10174';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '1', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'excluir', ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'S', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12749';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '1', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'salvar',  ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'S', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12747';

UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '162', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciar', ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = '86', ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12009';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'editar',  ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12001';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'salvar',  ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'S', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12750';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '142', ACR_RECURSO = '/v3/manterGrupoConsignataria', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'excluir', ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'S', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '12752';

DELETE FROM tb_ajuda WHERE ACR_CODIGO IN ('12748', '10175', '12751', '12002');
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO IN ('12748', '10175', '12751', '12002');
DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO IN ('12748', '10175', '12751', '12002');
