CREATE TABLE `tb_comunicacao_org` (
  `CMN_CODIGO` char(32) NOT NULL,
  `ORG_CODIGO` char(32) NOT NULL,
  `CMO_DESTINATARIO` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`CMN_CODIGO`,`ORG_CODIGO`),
  KEY `R_778_FK` (`CMN_CODIGO`),
  KEY `R_779_FK` (`ORG_CODIGO`),
  CONSTRAINT `FK_TB_COMUN_R_778_TB_COMUN` FOREIGN KEY (`CMN_CODIGO`) REFERENCES `tb_comunicacao` (`cmn_codigo`),
  CONSTRAINT `FK_TB_COMUN_R_779_TB_ORGAO` FOREIGN KEY (`ORG_CODIGO`) REFERENCES `tb_orgao` (`org_codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 
