-- DESENV-16542
INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16423','1','146','/v3/listarHistoricoMargem',null,null,1,'N','S',null,'N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16424','3','146','/v3/listarHistoricoMargem',null,null,1,'N','S',null,'N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16425','7','146','/v3/listarHistoricoMargem',null,null,1,'N','S',null,'N','2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO,PAP_CODIGO,FUN_CODIGO,ACR_RECURSO,ACR_PARAMETRO,ACR_OPERACAO,ACR_ATIVO,ACR_BLOQUEIO,ACR_SESSAO,ITM_CODIGO,ACR_FIM_FLUXO,ACR_METODO_HTTP) 
VALUES ('16426','6','146','/v3/listarHistoricoMargem',null,null,1,'N','S',null,'N','2');

-- DESENV-16578
UPDATE tb_tipo_param_sist_consignante SET tpc_dominio = 'DATA' WHERE tpc_dominio = 'DATE';