//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 11:19:35 AM BRT 
//


package com.zetra.econsig.soap;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="convenio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codVerba" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="servicoCodigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orgaoCodigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="estabelecimentoCodigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxaDeJuros" type="{TaxaDeJuros}TaxaDeJuros" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cliente",
    "convenio",
    "usuario",
    "senha",
    "codVerba",
    "servicoCodigo",
    "orgaoCodigo",
    "estabelecimentoCodigo",
    "taxaDeJuros"
})
@XmlRootElement(name = "cadastrarTaxaDeJuros")
public class CadastrarTaxaDeJuros {

    @XmlElementRef(name = "cliente", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cliente;
    @XmlElementRef(name = "convenio", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> convenio;
    @XmlElement(required = true)
    protected String usuario;
    @XmlElement(required = true)
    protected String senha;
    @XmlElementRef(name = "codVerba", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> codVerba;
    @XmlElementRef(name = "servicoCodigo", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> servicoCodigo;
    protected String orgaoCodigo;
    protected String estabelecimentoCodigo;
    @XmlElement(required = true)
    protected List<TaxaDeJuros> taxaDeJuros;

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCliente(JAXBElement<String> value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the convenio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConvenio() {
        return convenio;
    }

    /**
     * Sets the value of the convenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConvenio(JAXBElement<String> value) {
        this.convenio = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the senha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenha() {
        return senha;
    }

    /**
     * Sets the value of the senha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenha(String value) {
        this.senha = value;
    }

    /**
     * Gets the value of the codVerba property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodVerba() {
        return codVerba;
    }

    /**
     * Sets the value of the codVerba property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodVerba(JAXBElement<String> value) {
        this.codVerba = value;
    }

    /**
     * Gets the value of the servicoCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getServicoCodigo() {
        return servicoCodigo;
    }

    /**
     * Sets the value of the servicoCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setServicoCodigo(JAXBElement<String> value) {
        this.servicoCodigo = value;
    }

    /**
     * Gets the value of the orgaoCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgaoCodigo() {
        return orgaoCodigo;
    }

    /**
     * Sets the value of the orgaoCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgaoCodigo(String value) {
        this.orgaoCodigo = value;
    }

    /**
     * Gets the value of the estabelecimentoCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstabelecimentoCodigo() {
        return estabelecimentoCodigo;
    }

    /**
     * Sets the value of the estabelecimentoCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstabelecimentoCodigo(String value) {
        this.estabelecimentoCodigo = value;
    }

    /**
     * Gets the value of the taxaDeJuros property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxaDeJuros property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxaDeJuros().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxaDeJuros }
     * 
     * 
     */
    public List<TaxaDeJuros> getTaxaDeJuros() {
        if (taxaDeJuros == null) {
            taxaDeJuros = new ArrayList<TaxaDeJuros>();
        }
        return this.taxaDeJuros;
    }

}
