//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 11:19:35 AM BRT 
//


package com.zetra.econsig.soap;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="convenio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="adeNumero" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="adeIdentificador" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codigoMotivoOperacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="obsMotivoOperacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cliente",
    "convenio",
    "usuario",
    "senha",
    "adeNumero",
    "adeIdentificador",
    "codigoMotivoOperacao",
    "obsMotivoOperacao",
    "periodo"
})
@XmlRootElement(name = "liquidarConsignacao")
public class LiquidarConsignacao {

    @XmlElementRef(name = "cliente", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cliente;
    @XmlElementRef(name = "convenio", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> convenio;
    @XmlElement(required = true)
    protected String usuario;
    @XmlElement(required = true)
    protected String senha;
    @XmlElementRef(name = "adeNumero", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> adeNumero;
    @XmlElementRef(name = "adeIdentificador", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> adeIdentificador;
    @XmlElementRef(name = "codigoMotivoOperacao", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> codigoMotivoOperacao;
    @XmlElementRef(name = "obsMotivoOperacao", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> obsMotivoOperacao;
    @XmlElementRef(name = "periodo", namespace = "HostaHostService", type = JAXBElement.class, required = false)
    protected JAXBElement<String> periodo;

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCliente(JAXBElement<String> value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the convenio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConvenio() {
        return convenio;
    }

    /**
     * Sets the value of the convenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConvenio(JAXBElement<String> value) {
        this.convenio = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the senha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenha() {
        return senha;
    }

    /**
     * Sets the value of the senha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenha(String value) {
        this.senha = value;
    }

    /**
     * Gets the value of the adeNumero property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getAdeNumero() {
        return adeNumero;
    }

    /**
     * Sets the value of the adeNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setAdeNumero(JAXBElement<Long> value) {
        this.adeNumero = value;
    }

    /**
     * Gets the value of the adeIdentificador property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAdeIdentificador() {
        return adeIdentificador;
    }

    /**
     * Sets the value of the adeIdentificador property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAdeIdentificador(JAXBElement<String> value) {
        this.adeIdentificador = value;
    }

    /**
     * Gets the value of the codigoMotivoOperacao property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodigoMotivoOperacao() {
        return codigoMotivoOperacao;
    }

    /**
     * Sets the value of the codigoMotivoOperacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodigoMotivoOperacao(JAXBElement<String> value) {
        this.codigoMotivoOperacao = value;
    }

    /**
     * Gets the value of the obsMotivoOperacao property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getObsMotivoOperacao() {
        return obsMotivoOperacao;
    }

    /**
     * Sets the value of the obsMotivoOperacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setObsMotivoOperacao(JAXBElement<String> value) {
        this.obsMotivoOperacao = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPeriodo(JAXBElement<String> value) {
        this.periodo = value;
    }

}
