//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 11:19:35 AM BRT 
//


package com.zetra.econsig.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Parcela complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parcela"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="dataDesconto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataRealizado" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="valorPrevisto" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="valorRealizado" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="observacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parcela", namespace = "Parcela", propOrder = {
    "numero",
    "dataDesconto",
    "dataRealizado",
    "valorPrevisto",
    "valorRealizado",
    "status",
    "observacao"
})
public class Parcela {

    protected int numero;
    @XmlElement(required = true)
    protected String dataDesconto;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataRealizado;
    protected double valorPrevisto;
    protected Double valorRealizado;
    @XmlElement(required = true)
    protected String status;
    protected String observacao;

    /**
     * Gets the value of the numero property.
     * 
     */
    public int getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     */
    public void setNumero(int value) {
        this.numero = value;
    }

    /**
     * Gets the value of the dataDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDesconto() {
        return dataDesconto;
    }

    /**
     * Sets the value of the dataDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDesconto(String value) {
        this.dataDesconto = value;
    }

    /**
     * Gets the value of the dataRealizado property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRealizado() {
        return dataRealizado;
    }

    /**
     * Sets the value of the dataRealizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRealizado(XMLGregorianCalendar value) {
        this.dataRealizado = value;
    }

    /**
     * Gets the value of the valorPrevisto property.
     * 
     */
    public double getValorPrevisto() {
        return valorPrevisto;
    }

    /**
     * Sets the value of the valorPrevisto property.
     * 
     */
    public void setValorPrevisto(double value) {
        this.valorPrevisto = value;
    }

    /**
     * Gets the value of the valorRealizado property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValorRealizado() {
        return valorRealizado;
    }

    /**
     * Sets the value of the valorRealizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValorRealizado(Double value) {
        this.valorRealizado = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacao() {
        return observacao;
    }

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacao(String value) {
        this.observacao = value;
    }

}
