-- DESENV-17767
INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) values ('2', '224');
INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) values ('4', '224');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16539', '2', '224', '/v3/declararMargem', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('16540', '4', '224', '/v3/declararMargem', 'acao', 'iniciar', 1, 'S', 'S', NULL, 'N', '2');