-- DESENV-17697

UPDATE tb_relatorio_filtro SET RFI_SEQUENCIA = RFI_SEQUENCIA + 1 WHERE REL_CODIGO = 'sintetico_mov_fin' AND RFI_SEQUENCIA >= 8;

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('sintetico_mov_fin', 'campo_margens', '1', '1', '1', '1', '1', '0', 8, NULL); 
