-- DESENV-12051
INSERT INTO tb_natureza_servico (NSE_CODIGO, NSE_DESCRICAO, NSE_TRANSFERIR_ADE, NSE_ORDEM_BENEFICIO, NSE_IMAGEM, NSE_CODIGO_PAI) 
VALUES ('10','SAÚDE', 'S', '0', NULL, NULL);

INSERT INTO tb_item_menu (ITM_CODIGO, MNU_CODIGO, ITM_CODIGO_PAI, ITM_DESCRICAO, ITM_ATIVO, ITM_SEQUENCIA, ITM_SEPARADOR, ITM_CENTRALIZADOR) 
VALUES ('221','5', NULL, 'Saúde', 1, 1, 'N', 'S');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15188', '6', '432', '/v3/fluxoPortal', 'nse_codigo', '10', '1', 'S', 'S', '221', 'N', '2');

UPDATE tb_natureza_servico SET NSE_CODIGO_PAI = '10' WHERE NSE_CODIGO IN ('4','9'); 

UPDATE tb_acesso_recurso SET ITM_CODIGO = NULL WHERE ACR_CODIGO IN ('14869','14975','14988','15018');
