-- DESENV-11165
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/editarMenu', ACR_PARAMETRO = 'acao' , ACR_OPERACAO = 'iniciar' WHERE ACR_CODIGO IN ('11784', '12531');
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/editarMenu', ACR_PARAMETRO = 'acao' , ACR_OPERACAO = 'listarItemMenu' WHERE ACR_CODIGO IN ('11785', '12532');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15684', '1', '227', '/v3/editarMenu', 'acao', 'salvarItemMenu', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('15685', '7', '227', '/v3/editarMenu', 'acao', 'salvarItemMenu', 1, 'S', 'S', NULL, 'N', '2');
