-- DESENV-18606
DELETE FROM tb_ajuda WHERE ACR_CODIGO = '16551';
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO = '16551';
DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO = '16551';
UPDATE tb_acesso_recurso SET PAP_CODIGO = NULL, FUN_CODIGO = NULL WHERE ACR_CODIGO = '16550';