-- DESENV-20685
UPDATE tb_relatorio_filtro SET RFI_SEQUENCIA = RFI_SEQUENCIA + 1 WHERE REL_CODIGO = 'regra_convenio' AND RFI_SEQUENCIA >= 1;

INSERT INTO tb_relatorio_filtro (REL_CODIGO, TFR_CODIGO, RFI_EXIBE_SUP, RFI_EXIBE_CSE, RFI_EXIBE_ORG, RFI_EXIBE_CSA, RFI_EXIBE_COR, RFI_EXIBE_SER, RFI_SEQUENCIA, RFI_PARAMETRO)
VALUES ('regra_convenio', 'campo_csa', '1', '1', '1', '1', '0', '0', 1, NULL);

