-- DESENV-12992
UPDATE tb_acesso_recurso SET ACR_RECURSO = '/v3/editarAnexosSolicitacao' WHERE PAP_CODIGO = '6' AND FUN_CODIGO = '405' AND ACR_RECURSO = '/v3/editarAnexosConsignacao';

DELETE FROM tb_ajuda WHERE ACR_CODIGO = '15259';
DELETE FROM tb_acesso_usuario WHERE ACR_CODIGO = '15259';
DELETE FROM tb_acesso_recurso WHERE ACR_CODIGO = '15259';

UPDATE tb_acesso_recurso SET ACR_OPERACAO = 'anexo_solicitacao' WHERE ACR_CODIGO = '14763';
UPDATE tb_acesso_recurso SET ACR_OPERACAO = 'comprovante_pag_saldo' WHERE ACR_CODIGO = '13902';
UPDATE tb_acesso_recurso SET ACR_OPERACAO = 'anexo_consignacao' WHERE ACR_CODIGO IN ('13677', '13678', '13679', '13680', '13681', '15320');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15343', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'ativar', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15344', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'bloquear', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15345', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'descrever', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15346', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'excluir', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15347', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'exibir', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15348', '6', '200', '/v3/editarAnexosConsignacao', 'acao', 'upload', 1, 'S', 'S', NULL, 'N', '2');

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP) 
VALUES ('15349', '6', '200', '/v3/downloadArquivo', 'tipo', 'anexo_consignacao', 1, 'S', 'S', NULL, 'N', '2');
