-- DESENV-8205

INSERT INTO tb_tipo_param_sist_consignante (TPC_CODIGO, GPS_CODIGO, TPC_DESCRICAO, TPC_DOMINIO, TPC_CSE_ALTERA, TPC_CSE_CONSULTA, TPC_SUP_ALTERA, TPC_SUP_CONSULTA, TPC_VLR_DEFAULT)
VALUES('597', NULL, 'Chave pública de configuração do Captcha avançado', 'ALFA', 'N', 'N', 'N', 'N', NULL); 

INSERT INTO tb_tipo_param_sist_consignante (TPC_CODIGO, GPS_CODIGO, TPC_DESCRICAO, TPC_DOMINIO, TPC_CSE_ALTERA, TPC_CSE_CONSULTA, TPC_SUP_ALTERA, TPC_SUP_CONSULTA, TPC_VLR_DEFAULT)
VALUES('598', NULL, 'Chave privada de configuração do Captcha avançado', 'ALFA', 'N', 'N', 'N', 'N', NULL); 

-- VALORES PARA AS CHAVES PÚBLICA E PRIVADA PARA TESTES
-- INSERT INTO tb_param_sist_consignante (TPC_CODIGO, CSE_CODIGO, PSI_VLR) VALUES ('597', '1', '6LfXfGQUAAAAANb2hB2Y1haKJdyvWhWV821VF_et');
-- INSERT INTO tb_param_sist_consignante (TPC_CODIGO, CSE_CODIGO, PSI_VLR) VALUES ('598', '1', '6LfXfGQUAAAAAGmtYrbS0wslb2pJL3MIXiJmthKT');
