-- DESENV-9088

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14899', '7', '417', '/v3/alterarCalculoBeneficio', 'acao', 'novoReajuste', 1, 'S', 'S', null, 'N', 2);

INSERT INTO tb_acesso_recurso (ACR_CODIGO, PAP_CODIGO, FUN_CODIGO, ACR_RECURSO, ACR_PARAMETRO, ACR_OPERACAO, ACR_ATIVO, ACR_BLOQUEIO, ACR_SESSAO, ITM_CODIGO, ACR_FIM_FLUXO, ACR_METODO_HTTP)
VALUES ('14900', '7', '417', '/v3/alterarCalculoBeneficio', 'acao', 'salvarReajuste', 1, 'S', 'S', null, 'N', 2);

UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '417', ACR_RECURSO = '/v3/alterarCalculoBeneficio', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'iniciarTabela', ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '14857';
UPDATE tb_acesso_recurso SET PAP_CODIGO = '7', FUN_CODIGO = '417', ACR_RECURSO = '/v3/alterarCalculoBeneficio', ACR_PARAMETRO = 'acao', ACR_OPERACAO = 'ativarTabela',  ACR_ATIVO = 1, ACR_BLOQUEIO = 'S', ACR_SESSAO = 'S', ITM_CODIGO = NULL, ACR_FIM_FLUXO = 'N', ACR_METODO_HTTP = '2' WHERE ACR_CODIGO = '14856';
