-- DESENV-6831

UPDATE tb_acesso_recurso SET FUN_CODIGO = '63' WHERE ACR_CODIGO = '12725';
UPDATE tb_acesso_recurso SET FUN_CODIGO = '63' WHERE ACR_CODIGO = '11052';
UPDATE tb_acesso_recurso SET FUN_CODIGO = '63' WHERE ACR_CODIGO = '11692';

INSERT INTO tb_funcao (FUN_CODIGO, GRF_CODIGO, FUN_DESCRICAO, FUN_PERMITE_BLOQUEIO, FUN_EXIGE_TMO, FUN_AUDITAVEL, FUN_RESTRITA_NCA, FUN_EXIGE_SEGUNDA_SENHA_CSE, FUN_EXIGE_SEGUNDA_SENHA_SUP, FUN_EXIGE_SEGUNDA_SENHA_ORG, FUN_EXIGE_SEGUNDA_SENHA_CSA, FUN_EXIGE_SEGUNDA_SENHA_COR)
VALUES ('63', '1', 'Solicitar Consignação', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N');

UPDATE tb_funcao SET FUN_DESCRICAO = 'Solicitar Consignação' WHERE FUN_CODIGO = '63';

INSERT INTO tb_papel_funcao (PAP_CODIGO, FUN_CODIGO) SELECT '6', '63' FROM tb_papel_funcao WHERE FUN_CODIGO = '79';

INSERT INTO tb_funcao_perfil_ser (SER_CODIGO, USU_CODIGO, FUN_CODIGO) SELECT SER_CODIGO, USU_CODIGO, '63' FROM tb_funcao_perfil_ser WHERE FUN_CODIGO = '79';
